### ISSUE TITLE
Explainability: Fairness and Bias Metrics (Phase 0)

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1001]
- #1006 
- #1007 
- #1008 

![64fbfeee-3ea1-4800-a566-8d11b9eee0ce-2](https://user-images.githubusercontent.com/4092230/231132421-5b0d9cdf-1601-4610-801a-8e771b5d401f.png)

- Updated mock to latest version [11th April]

**Comment by andrewballantyne** [comment]
Not going to be part of the next release -- we'll do more internal iterations on it before we release it.

**Comment by alexcreasy** [comment]
The tech preview UI for the TrustyAI phase0 April 12th demo is complete and available here: https://github.com/opendatahub-io/odh-dashboard/pull/1093

This will need more iterations: both to improve code quality and UX before releasing. Planning for this will begin after the April 12th demo is delivered.

**Comment by alexcreasy** [comment]
PR awaiting final review to close tracker and related issues: https://github.com/opendatahub-io/odh-dashboard/pull/1093
