### ISSUE TITLE
[Feature Request]: Project Sharing

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1010]
### Feature description

1. Enable project sharing at the user level.
    * Just allow for text entering of another user's name -- we may swing back with typeahead + smart searching, out of scope
    * We should investigate if we can server-side k8s grep for characters, if so we can limit it to 10 and do it... otherwise we will slam the network unneedlessly
1. Enable project sharing at the group (OpenShift groups) level.
    * Check to see if they can list the groups -- if so, provide a typeahead list of available groups -- if not, just allow for text entering
1. Provide 2 levels of sharing access:
    1. Admin - full edit access to all aspects of the project and the ability to view & edit permissions, i.e. sharing 
    1. Edit - full edit access to all aspects of the project, but no ability to view or edit permissions
1. Users that have access to a project via sharing should be able to view & edit shared projects from the projects list. 
1. For model serving, the list of deployed models is based on projects access. This needs to continue to function in the same way with project sharing. Example: if I have access to project 1 via sharing, I should see deployed models for project 1 in the model serving list from the left nav menu. 

Mocks: https://www.sketch.com/s/b073af35-46b7-46f0-afe0-5db079848ad9

### Anything else?

Impacted by the work done in #619

**Comment by kywalker-rh** [comment]
UX mock-ups here: https://www.sketch.com/s/b073af35-46b7-46f0-afe0-5db079848ad9

**Comment by andrewballantyne** [comment]
@lucferbux be sure to review the updated mocks for any shifting in design (I don't think there is at first glance).
