### ISSUE TITLE
[Docs]: Clean up our documentation for development & frontend

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1015]
We have fairly old and incomplete docs in our frontend folder.

We need to document how we can start up and run the various tests -- storybook, jest, etc. 

We should also add to the frontend docs the reasoning behind `optionalDependencies` (from https://github.com/opendatahub-io/odh-dashboard/pull/1004#discussion_r1137271965)

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2458
