### ISSUE TITLE
[Feature Request]: Readdress our needs for Model Serving Metrics

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1022]
### Feature description

Our previous implementation (#916) did not work out to desired goals we set out to have. We disabled it recently (#998), and now want to re-enable with the needed corrections.

Changes highlighted are:
- We need runtime metrics
- Different inference metrics

### Anything else?

Follow up on these issues from the partial feature branch PR:
- https://github.com/opendatahub-io/odh-dashboard/pull/1023#discussion_r1143641079
- https://github.com/opendatahub-io/odh-dashboard/pull/1023#discussion_r1143655562
- https://github.com/opendatahub-io/odh-dashboard/pull/1023#discussion_r1145881808

Things currently missing:
- Metric queries
- Tooltip improvements (Vince send me some DMs, let @andrewballantyne know if you need them)

**Comment by andrewballantyne** [comment]
This took a turn yesterday at the UX meeting. We are going to investigate OpenShift Console's Observe pages and see if there is changes we need to make to our Metric stack in the Dashboard.

**Comment by andrewballantyne** [comment]
Broken up into multiple tickets. See https://github.com/opendatahub-io/odh-dashboard/issues/1128 for other issues in this effort.

**Comment by shalberd** [comment]
> This took a turn yesterday at the UX meeting. We are going to investigate OpenShift Console's Observe pages and see if there is changes we need to make to our Metric stack in the Dashboard.

The Openshift Console Observe pages, in the per-namespace Developer pane as well as under Admin - Observe, are certainly very useful. What kinds of metrics do you want to observe and potentially display within ODH Dashboard instead? What is your Prometheus Data Source for the metrics?

**Comment by andrewballantyne** [comment]
> > This took a turn yesterday at the UX meeting. We are going to investigate OpenShift Console's Observe pages and see if there is changes we need to make to our Metric stack in the Dashboard.
> 
> The Openshift Console Observe pages, in the per-namespace Developer pane as well as under Admin - Observe, are certainly very useful. What kinds of metrics do you want to observe and potentially display within ODH Dashboard instead? What is your Prometheus Data Source for the metrics?

Ah so to catch up the ticket with what was decided / investigated and found out.

1. OpenShift Console uses graphana dashboard configs to build their Observe dashboards -- We don't really have a need for this today, might be technically useful going forward to lean into this, but it's not needed for our first pass
2. OpenShift Console & the Dashboard both use the same prometheus call points, so our fetching of our data is the same
3. We are going to rework the Metric effort to lean into producing a more direct approach using the same queries we were -- this is where this ticket got broken up and a new "tracker" (aka group) ticket was created to track the work and plan for it. The mocks for our goals are listed on the ticket https://github.com/opendatahub-io/odh-dashboard/issues/1130

Hopefully that added clarity. Let me know if you have any other questions.

**Comment by shalberd** [comment]
There is a prometheus call point for all namespaces, port 9092, and a prometheus call point for only the opendatahub namespace, port 9091.

I have written down what I think would be a less invasive way to get to metrics at 

https://github.com/opendatahub-io/odh-manifests/issues/752#issuecomment-1510760800

**Comment by andrewballantyne** [comment]
We use 9092 ([code](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/prometheusUtils.ts#L97-L108)) when dealing with things like PVC fill status data from Prometheus.

When querying Model Serving metrics, we go through a route that is created by the backend serving team ([code](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/prometheusUtils.ts#L110-L144)). This structure properly could use with cleaning up -- it was a semi-rush job on the previous Metrics effort that we ended up pulling out.

**Comment by shalberd** [comment]
Regarding 9092: That is very good, neat to see you went that way, directly using namespace-specific kube-state-metrics and kubelet (PVC) metrics.

https://cloud.redhat.com/blog/thanos-querier-versus-thanos-querier

I don't sent see where in the code you set the url parameter ?namespace=xxxxx, but since it works, that should be ok.

Regarding the route / haproxy metrics currently done from odh-model-monitoring port 443, yes, that is the approach with getting the routing / ingress metrics from central openshift monitoring via federation to an own prometheus.

https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/prometheusUtils.ts#L124

via a federation to an own prometheus instance (operator-based)

https://github.com/opendatahub-io/odh-manifests/search?q=odh-model-monitoring

@lucferbux 

For that (Router Metrics), you could ditch the own prometheus instance and instead use the approach described at [Router Metrics part of my comment](https://access.redhat.com/solutions/4998261) That would mean using the url `https://router-internal-default.openshift-ingress.svc.cluster.local:1936/metrics`

**Comment by andrewballantyne** [comment]
> Regarding 9092: That is very good, neat to see you went that way, directly using namespace-specific kube-state-metrics and kubelet (PVC) metrics.
> 
> https://cloud.redhat.com/blog/thanos-querier-versus-thanos-querier
> 
> I don't sent see where in the code you set the url parameter ?namespace=xxxxx, but since it works, that should be ok.

The backend is not intended to have business logic. It's intended to be a CORS work around and a proxy service. The business logic is on the client. Eg. https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/api/prometheus/pvcs.ts#L11

**Comment by shalberd** [comment]
> the backend is not intended to have business logic. It's intended to be a CORS work around and a proxy service.

Ah, there is is, the namespace query parameter, neat :-)
