### ISSUE TITLE
[Bug]: Model Serving - Unnecessary Pulling of Project Name when Editing Modal

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When editing a project's model serving model, you get a loading spinner for project, when clearly it's *in this project*.

Note: Model Serving from Global page doesn't need this functionality either -- you're already rendering the data in the Table cell, just reuse

Side note: When creating a model in the Project View -- the field is text only -- but editing it is a disabled field.

![Screenshot 2023-03-18 at 3 42 55 PM](https://user-images.githubusercontent.com/8126518/226134151-630e3617-fcad-4d8c-9584-c368605a0d9c.png)

Mid-loading state
![Screenshot 2023-03-18 at 3 43 17 PM](https://user-images.githubusercontent.com/8126518/226134152-39e5a8a5-f0f1-45d1-aec4-b2b483333d01.png)

### Expected Behavior

- Convert project from disabled text field to text only when editing
- Do not load / spinner when the data is already available in either the project or global contexts where it is open

Cover both Project view & Global Model Serving. The data will need to come from each context individually.

### Steps To Reproduce

Setup
1. Create a Project
2. Create a runtime
3. Create a model

Edit the model from the table row.

### Open Data Hub Version

```yml
Dashboard: v2.8.0
```

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-3985
