### ISSUE TITLE
[Feature Request]: Make Metrics Available on Runs/Experiments View

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1035]
### Feature description

When testing different models, hyper parameters, or any other changes in a data pipeline, it is often necessary to compare the results across multiple runs.  In the upstream Kubeflow Pipelines UI, they make the metrics available on the Experiments view to allow you to easily see the results of all of the runs:

![image](https://user-images.githubusercontent.com/1628206/226422330-52bd0bf8-c625-40a6-bf0c-983909c798f5.png)

**Comment by rimolive** [comment]
@strangiato Can you provide a screenshot with better resolution? This one is too small and it's loosing resolution when zomming in.

**Comment by strangiato** [comment]
![experiments](https://user-images.githubusercontent.com/1628206/226431451-696230d2-1eda-41b0-b981-c8407c902f36.png)

Hopefully this is better!

**Comment by strangiato** [comment]
Also, in case it is helpful, here is a very simple pipeline for generating metrics:
https://github.com/rh-intelligent-application-practice/kubeflow-examples/blob/main/pipelines/5_metrics_pipeline.py

**Comment by accorvin** [comment]
@strangiato this is definitely something we plan to include, but we're still very much in the design phase. Are there any specific metrics you think are most important to include?

**Comment by strangiato** [comment]
@accorvin, I would expect each pipeline to have their own requirements, which would be defined in the pipeline itself.  Metrics will be very dependent on what kind of model you are building, the use case/requirements, what the model is being optimized for, the optimization algorithm the data scientists chooses, etc.

Common metrics I would expect to see might include:
* accuracy score
* mse
* f1
* precision
* recall

Those are all metrics that are relevant to classification problems so when you get into different data science problems such as NLP, there are whole new sets of metrics that become relevant.  You could also have a totally custom metric defined for the specific use case as well.

The feature request here is to simply display the metrics that are defined in the pipeline (by the pipeline developer/data scientist) in a way that you can compare the results of multiple runs without having to open each run one by one.

**Comment by accorvin** [comment]
Thanks @strangiato! I've been thinking through what a user-friendly yet sufficiently generic mechanism for implementing this could be. I think the best idea I have is to implement a standard for storing a json (or similar file) with a well defined structure in some well defined location for each pipeline run. It would be something like key/value pairs or metric name/value or something like that, that the dashboard could then display. Thoughts?

**Comment by accorvin** [comment]
`mlflow.log_metric('my-metric', 9000)` <-- This seems like a really elegant way to provide this functionality.

@rimolive, @HumairAK, @gmfrasca, @gregsheremeta  do any of you know if the KFP community has any plans for providing this sort of functionality?

**Comment by dgutride** [comment]
Moving to closed - there is an epic tracking experiments requirements and implementation here:  https://issues.redhat.com/browse/RHOAIENG-2944
