### ISSUE TITLE
[Feature Request]: Fix the footer submit across all forms

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1042]
### Feature description

Currently, forms in the dashboard have mixed implementation and contain a lot of bugs and duct tape fixes. The goal of this issue is to make forms as reusable as possible through something like a custom hook, form library, some custom components... (to be discussed). In this new implementation we should be able to easily produce the following:
- dry running on submit for all k8 post requests
- reusable and generic state management for multiple types of states
    - basic field form elements
    - new/existing form elements
    - dropdown form elements
- validation 
- and more (we will need to go through each form and find what it needs so that it can be generalized and added to the generic implementation)

Once the new form is created, replace all the old forms with the new one

Create storybook tests to test the generic form, as well as each of its implementations

### Describe alternatives you've considered

This is to be discussed, but the form could all come from:
- a custom hook - ex) useForm()
- a custom component or set of components - ex) <ODHForm />, <ODHFormFooter /> ...
- a 3rd party form library (probably the best bet, however we will be reliant on the limitations of whatever form library we choose. This could get messy down the line if it doesn't meet our needs)

**Comment by christianvogt** [comment]
@Gkrumbach07 (cc @andrewballantyne ) has a form library like formik (which has a [PF wrapped](https://github.com/patternfly-labs/formik-pf)) been looked at?

**Comment by Gkrumbach07** [comment]
@christianvogt I dont think we have looked into third party solutions. I agree that we should use something like formik or react hook form to simplify the flow of our many forms instead of creating a purely custom one. But that formik wrapped one seems unmaintained so we may have to do the wrapping ourselves as to not rely on something that may become EOL.

**Comment by andrewballantyne** [comment]
FWIW, our form tech debt ticket: https://github.com/opendatahub-io/odh-dashboard/issues/1783

**Comment by adnankhan666** [comment]
Not migrating ~ labelled "stale"

**Comment by Gkrumbach07** [comment]
parent ticket was migrated
