### ISSUE TITLE
[Bug]: Unable to authenticate to odh-dashboard with Service Account

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Related to this issue:

https://github.com/opendatahub-io/odh-manifests/issues/757

If a Service Account is granted a narrow scope to get routes in the specific namespace that the opendatahub instance is deployed it will be unable to authenticate to with the OAuth Proxy instance. With the current --openshift-delegate-url arg the Service Account must have cluster level permissions to view all routes on the cluster.

When attempting to authenticated via a Bearer Token with a service account, the request is rejected with a 403 error message.

### Expected Behavior

Service Accounts should be able to authenticate via Bearer Token by only granting view permissions to the routes that the odh-dashboard is deployed to and not cluster level view permissions.

### Steps To Reproduce

1. Install ODH with a standard kfdef in a namespace called `opendatahub`
2. Create a test service account:
```
oc create sa test-connection
```
3. Grant permissions to the service account:
```
oc policy add-role-to-user view system:serviceaccount:opendatahub:test-connection
```
4. Verify SA has permissions to list service:
```
TOKEN=$(oc create token test-connection -n opendatahub)
oc login --token=${TOKEN}
oc get services odh-dashboard -n opendatahub
```
5.  Attempt to authenticate to OAuth
```
URL="https://$(oc get routes odh-dashboard -n opendatahub -o jsonpath='{.spec.host}' )"
curl --location --request GET $URL \
--header "Authorization: Bearer ${TOKEN}" -I
```

Request will return a 403 error message.

### Workaround (if any)

Grant the service account cluster level view permissions.

### Open Data Hub Version

```yml
1.4.2 standard kfdef
```

**Comment by shalberd** [comment]
Thank you, very enterprise-level work, nice job
