### ISSUE TITLE
[Feature Request]: Make storybook MSW mocks more controlled

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1049]
### Feature description

Right now, mocks are added to stories by setting a list of handlers in the story config where each mocked request follows
```tsx
 rest.get(
          'api/k8s/apis/serving.kserve.io/v1alpha1/namespaces/test-project/servingruntimes',
          (req, res, ctx) =>
            res(ctx.json(mockK8sResourceList([mockServingRuntimeK8sResource({...}), ...]))),
        ),
```
The request is to move the entire rest function into another helper function. This function would generate the url and properly call `get`, `post`, `delete`, or `put` depending on input. You should be able to call 
```tsx
const config = { ... }
mockK8Resource(K8_RESOURCE.SERVING_RUNTIME, KIND.GET, config)
```

### Describe alternatives you've considered

Alternatives would be to keep the current solution.

### Anything else?

For generating the url, we might have to copy the url generation code from the k8 sdk

**Comment by andrewballantyne** [comment]
@Gkrumbach07 Have you considered using `mockK8sResource(model, verb, etc)`? We should be able to use [the function in the SDK](https://github.com/openshift/dynamic-plugin-sdk/blob/c79a9a737c406ada0c52d46ae011ca8216960ffd/packages/lib-utils/src/k8s/k8s-utils.ts#L60) (likely we will need to copy it) to convert the model into a resource URL and prefix it with our stuff.

**Comment by Gkrumbach07** [comment]
make sure to handle
- generic URL
- kube URL

be able to override mocks for certain tests

**Comment by andrewballantyne** [comment]
We'll close this because we want to move away from MSW and Stories.
