### ISSUE TITLE
[Feature Request]: Change dashboard config mock on a per story level

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1051]
### Feature description

Currently there is no way to set the odh dashboard config from individual stories. We will have to add some params at the story level that get passed to the preview.js global handlers. We should be able to utilize storybook [context](https://storybook.js.org/docs/react/writing-stories/decorators#context-for-mocking) to define params per story and injetc them into the decorator. 

### Describe alternatives you've considered

Adding the context to each story so it can be configured at that level. This adds a lot of extra boilerplate that make writing stories more complex

**Comment by andrewballantyne** [comment]
We are moving to a jest testing environment and MSW is no longer a priority. Closing this as testing infra will be changing away from stories.
