### ISSUE TITLE
[Feature Request]: Preview BYON Display When Creating Instance

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1070]
See associated issue for more details: https://github.com/opendatahub-io/odh-dashboard/issues/375

**Comment by andrewballantyne** [comment]
@kywalker-rh let us talk about this issue on Monday. I think you meant this for another board. You modified our board maybe on accident?

Anything logged in ODH Dashboard gets added to our board for triage -- open & in done state is an invalid state for our board.
