### ISSUE TITLE
[Investigation] Determine the best way to store Custom Serving Runtimes

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1075]
## Feature description

For this feature, we will need to store and retrieve [Serving Runtime](https://kserve.github.io/website/0.8/modelserving/servingruntimes/) specs that customers might wanna add to deploy them in their projects.

### Tasks

- We need to know the best way to store a Custom Serving Runtime Object and retrieve it
- This object should allow parameters
- Some suggestions point at [Openshift Templates](https://docs.openshift.com/container-platform/4.9/openshift_images/using-templates.html)
- We need to figure out a way to sort this Custom Runtimes in an specific order to display them

**Comment by lucferbux** [comment]
Just opening this to reflect the final decision about how to implement this feature, the main suggestion for this would be:

1. Use Openshift Templates and have the type in an annotation field
2. Use odhDashboardConfig to track the Serving Runtime position

**Comment by lucferbux** [comment]
@andrewballantyne v1 will not include parametrize Custom Serving Runtimes, but I'm thinking about adding OpenShift templates as the blueprint for the Serving Runtimes, it won't add too much complexity if we leave the params empty and it's a great foundation for v2. What do you think?

**Comment by andrewballantyne** [comment]
Sounds great to me -- we chatted about this and I think it's best to just start with this, it solves some other concerns about creating runtimes in a general namespace and dealing with any reactive operator/controller that sees the objects being created.
