### ISSUE TITLE
Custom Serving Runtime Filter and Pagination

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1078]
## Feature description

Add filter and pagination functionality to the Custom Serving Runtimes table to make it easier to find and manage specific runtimes.

### Continuation of

- https://github.com/opendatahub-io/odh-dashboard/issues/1077

### Tasks

- Add filter to the table
- Add pagination

### Mocks

- https://www.sketch.com/s/5c26573b-fd37-4d54-a4f7-aab1cc17ff5d/a/y9grqEa

**Comment by DaoDaoNoCode** [comment]
I think based on the conversations in slack, we don't need filters and pagination anymore because of the drag-and-drop function. So this issue could be closed.
