### ISSUE TITLE
[Bug]: Custom notebook image fails to pull with registry port

### ISSUE THREAD

**Issue by davwhite** [opendatahub-io/odh-dashboard#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a custom notebook image hosted in the OCP internal registry, any attempt to spin up a session using this notebook causes imagePullBackoff. Basic troubleshooting points to parsing of the image name. It looks like anytime there is a ":<portnumber>" descriptor in the name, it gets parsed incorrectly. When there is no port number, like quay.io, it parses correctly.

### Expected Behavior

The custom image should spin up without errors regardless of the existence of port number in the name.

### Steps To Reproduce

1. Create a custom notebook image stored in the internal registry. (image stream)
2. Add this image to the custom notebooks in your ODH environment.
3. Launch a notebook with this new image.

### Open Data Hub Version

```yml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  creationTimestamp: '2023-03-26T12:29:23Z'
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
  generation: 2
  managedFields:
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:applications': {}
          'f:repos': {}
      manager: Mozilla
      operation: Update
      time: '2023-03-26T12:29:23Z'
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"kfdef-finalizer.kfdef.apps.kubeflow.org"': {}
        'f:status': {}
      manager: opendatahub-operator
      operation: Update
      time: '2023-03-26T12:29:23Z'
  name: opendatahub
  namespace: odh
  resourceVersion: '92958'
  uid: d9c111c7-e20d-4695-8a15-dd012ccc97e1
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.4.2'
status: {}
```

### Anything else

Originally entered in doc repo
https://github.com/opendatahub-io/opendatahub.io/issues/76

**Comment by jedemo** [comment]
@jkoehler-redhat - can we raise the priority of this item? It's a customer issue.

**Comment by andrewballantyne** [comment]
@jedemo I have raised the priority and put it into next sprint.

**Comment by jedemo** [comment]
Great, thanks
