### ISSUE TITLE
[Feature Request]: Support use of Service Mesh for routing

### ISSUE THREAD

**Issue by cam-garrison** [opendatahub-io/odh-dashboard#1087]
### Feature description

In order to enable service mesh for routing between ODH components, we need to make some changes to ODH-Dashboard.

- Create a feature flag to differentiate between when using service mesh as part of the ODH infrastructure and not.
- If using service mesh, create requisite service mesh annotations when creating notebook and data science project resources.
- If using service mesh, ensure that traffic goes through the mesh rather than openshift routes.

### Anything else?

PR incoming.

**Comment by Gkrumbach07** [comment]
cc @lucferbux can you add a specific feature label for this

**Comment by andrewballantyne** [comment]
Merged into the feature branch -- getting it into incubation... see the Tracker for more details.
