### ISSUE TITLE
[DS Projects]: When Model Serving is disabled -- Don't Fetch the Data

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1089]
### Feature description

During the Pipeline feature, it was exposed that when you disable the model serving feature, the details page spams the API looking for Inference Services & Serving Runtimes -- this is unnecessary.

Pipelines gets around this with it's own context provider that is conditionally mounted ([example](https://github.com/opendatahub-io/odh-dashboard/pull/1052#discussion_r1152442209)).

Two -- of the top of my head -- ideas I have are:

1. We parameterize the args into the hooks -- the new `useFetchState` hook can manage the "enablement" of these calls from there
2. We wrap the ProjectDetailsContext in a ModelServingProjectDetailsContextAdditions (or something like that) and it does its own hooks and supplies data to the ProjectDetailsContext (instead of being a provider) -- which then the ProjectDetailsContext consumes as empty if disabled or as actual data for the context. 
    eg
    ```
    if (enabled)
       <ModelServingProjectDetailsContextAdditions />
    else
      <ProjectDetailsContext />
    
    const ModelServingProjectDetailsContextAdditions = () => {
       // fetch hooks
       
       return (
          <ProjectDetailsContext inferenceServices={...} runtimes={...} />
       );
    }
    ```

I favour 2 more -- but 1 is easier.

### Anything else?

cc @lucferbux

**Comment by lucferbux** [comment]
@andrewballantyne @DaoDaoNoCode regarding #1179 I have a few mixed up questions about this:

Once we have Custom Model Servings and Pipelines, the project context would fetch requests from three different feature flags: `Model Serving`, `Model Serving Templates` and `Pipelines`. If we get to merge #1179 as it is, we would have two different ways to conditionally render this provider, one would be the wrapper for `Model Serving` and the other the conditional render of the provider of `Pipelines` inside `ProjectDetailContext`.

If find that slightly weird, why not use the same approach for those two features?

**Comment by andrewballantyne** [comment]
I responded on slack... but for posterity -- Pipelines is not the same as ModelServing + any of the existing functionality in Projects Details. Pipelines has a massive overhead as it is not k8s resources / api. Pipelines needs to walk its own path... since it's a context on its own, it can be above or below, dealers choice, I chose below as a child... but it doesn't really matter.
