### ISSUE TITLE
[Bug]: Create Model Server redirects to Data Science Project Screen

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When navigating to the `Model Serving` tab if I currently don't have a model server created it includes a button to `Create server`. 

![image](https://user-images.githubusercontent.com/1628206/230664442-9559d52e-c5c5-4793-a1d9-13a7924bd80c.png)

When clicking that button, the page navigates to the `Data Science Projects` page with no additional context or information available:

![image](https://user-images.githubusercontent.com/1628206/230664645-f12480fc-beb5-4f11-8d71-95c8ae4eca47.png)

There is no clear "next steps" a user needs to take or any feedback provided to the user as to what they need to do.  It is not clear that you must either create a project and then from that page create a model server or select a project and then create a model server.

There is no indication that a Model Server is a project scoped object and no indication that I need to create one in my project before I can server a model.

### Expected Behavior

Instead of redirecting the user to the Data Science Projects page, pop up a modal just like with the option to `Deploy model`.

### Steps To Reproduce

See current behavior

### What browsers are you seeing the problem on?

Chrome

### Open Data Hub Version

```yml
1.5.0
```

### Anything else

In all honestly the project / object scope workflow for the odh-dashboard makes very little sense to me.

Why can I create a `Deploy model` outside of the `Data Science Project` interface with a dropdown menu in the modal but I have to create the server under the Data Science Project menu?

![image](https://user-images.githubusercontent.com/1628206/230666602-740890a0-9317-48f7-80ba-78d351aacadb.png)

If a `Data Science Project` is a namespace/project proxy in the ODH/RHODS interface, why not fall back on the same navigation language as the OpenShift console.

Provide a drop down menu to select which "project" you are in.  

Allow the types of objects to be navigable items in the left panel:

- Workbenches
- Cluster Storage
- Data Connections
- Model Servers
- Models

If you really want to combine some of those things like Model servers and models on a single page that would still work since these pages aren't likely to be dense.

Each of these pages should only display the objects belonging to that specific project to clearly show the scope of those objects.

**Comment by lucferbux** [comment]
@vconzola @andrewballantyne 

This flow is intended but maybe is misleading to the user, we might wanna review the description to make it more clear?

**Comment by vconzola** [comment]
@lucferbux Looking at my mockups I realize that I never addressed the scenario of what to show under Model Serving when no models are deployed. Rather than offering a Create model server action in this empty state, I think we should simply inform the user that no deployed models exist and re-direct them to the Projects page where they can create a model server and deploy a model. I'll mock something up to address this scenario. I think part of the confusion results from the nav item being called "Model serving" rather than "Deployed models", but that was edicted from on high.

**Comment by lucferbux** [comment]
> @lucferbux Looking at my mockups I realize that I never addressed the scenario of what to show under Model Serving when no models are deployed. Rather than offering a Create model server action in this empty state, I think we should simply inform the user that no deployed models exist and re-direct them to the Projects page where they can create a model server and deploy a model. I'll mock something up to address this scenario. I think part of the confusion results from the nav item being called "Model serving" rather than "Deployed models", but that was edicted from on high.

Great thanks!

**Comment by vconzola** [comment]
@DaoDaoNoCode I think this is going to be addressed as part of bigger changes to Model serving to make it more consistent with Pipelines. Watch the recording of the 5/25 UX meeting to hear the details.

**Comment by manaswinidas** [comment]
I think this issue(or a part of it) is already addressed.
<img width="1091" alt="Screenshot 2023-06-28 at 11 54 39 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/e2d79a05-dff2-43fa-b811-9911e778bcd3">

**Comment by vconzola** [comment]
@manaswinidas @DaoDaoNoCode Sorry. I created a mockup for this empty state and then never put a link in the issue. It should look like this: https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/uuid/00D5CBEB-9D5F-4886-BCB4-ECE815B2C991

**Comment by lucferbux** [comment]
> @manaswinidas @DaoDaoNoCode Sorry. I created a mockup for this empty state and then never put a link in the issue. It should look like this: https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/uuid/00D5CBEB-9D5F-4886-BCB4-ECE815B2C991
> 
> @kaedward Please review the content for this empty state.

Ok, I'm gonna take this issue, I'm starting with it but I probably raise the pr next week.

**Comment by kaedward** [comment]
@vconzola I reviewed the empty state but didn't update here, whoops

**Comment by andrewballantyne** [comment]
Accidental merge -- PR is being reverted and ticket is reopened for the work to be reviewed.

**Comment by lucferbux** [comment]
> @manaswinidas @DaoDaoNoCode Sorry. I created a mockup for this empty state and then never put a link in the issue. It should look like this: https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/uuid/00D5CBEB-9D5F-4886-BCB4-ECE815B2C991
> 
> @kaedward Please review the content for this empty state.

For future reference, here you have the right text: https://github.com/opendatahub-io/odh-dashboard/pull/1796#issuecomment-1726433685
