### ISSUE TITLE
[Feature Request]: Provide Access to Yaml for Objects

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1097]
### Feature description

Every object a user can control in the dashboard should be editable as YAML in addition to the form view currently supported.

For example, if a user creates a "Model Server" or a "Workbench" in the UI, a user should ultimately be able to view/edit the object that the UI creates directly via YAML.

Here is a very basic mock up of how it might be incorporated into the existing UI for a Data Connector:

![image](https://user-images.githubusercontent.com/1628206/230985268-71a19456-1792-405a-a38b-98677259fcb0.png)

And what the YAML looks like for that object on the OCP console:

![image](https://user-images.githubusercontent.com/1628206/230985032-26da7826-c31c-4d14-96f2-dd80c0ece61a.png)

Why is this important?

* Everything being an object/yaml in k8s is a core foundational piece of why k8s is a popular orchestration platform.  Often times it does make sense to provide a great UI to edit and manage objects, but at the end of the day the YAML for the objects is the "Source of Truth".
* When troubleshooting an issue the first question is most often "Can you share the YAML?".  The Support channel of the ODH Slack is a great example of this where most troubleshooting threads ask for the YAML.
* One thing that OCP does great is providing a form based view to manage objects, but always exposing and making the YAML accessible.  This makes it easy for users to discover and better understand what the tool is actually doing and how changes you make through the form impact the actual YAML object.
* Customers are most often talking to Red Hat about RHODS because they are already familiar with k8s/OCP.  The fact that these users are likely already well versed in working with YAML means that providing access to the YAML through the UI can help to bridge what they know on the OCP side to better help them to leverage RHODS.
* When moving to higher level environments, often times users do not have any direct permissions to the cluster and all changes must be implemented through GitOps.  Generally this means that users must extract the YAML objects that they have created through the UI and re-implement them in a GitOps repo.

### Describe alternatives you've considered

Many of these objects can be found in the OpenShift Console but the fact that different components come from different operators make for a less than desirable experience.  On the OCP side you need to either know the name of the object Kind or the operator that provides the object in order to find it.

The Data Connector is a great example where you need to know that a Data Connector is actually a Secret and you need to know that the dashboard actually creates the secret name as <object-type>-<your-name> and is not simply the name you gave the data-connector.

Another option would be to simply redirect the user to the object in the OCP console with the `Edit YAML` button mocked up above.

**Comment by andrewballantyne** [comment]
@strangiato we have intentionally been avoiding YAML inclusion in our application as it is intended to be guided flows to working with k8s and the resources under the hood. The end-user (eg. data scientist) being separated by this flow is a foundational aspect of the ODH Dashboard and the flows we deliver -- OpenShift Console does not have this goal which is why they offer a YAML tab. I am not sure if this is a goal we are targeting for our use-cases.

cc @kywalker-rh / @jedemo Did you guys want to chime in here?

**Comment by kywalker-rh** [comment]
@strangiato Thanks for bringing this up, it had not occurred to me at all until you mentioned it. I'll need to do some thinking and talking about this with other team members, both to figure out if it fits with the larger vision for ODH, and also if it is something other users would find useful. As @andrewballantyne mentions above we've been specifically trying to make the ODH user experience different from OpenShift to be sure we are accounting for a large amount of users that aren't familiar with, nor care about, the underlying k8s infrastructure. As we're expanding the capabilities though, it is becoming clear we need to account for more types of users than we have in the past, so we are trying to decide how to do that.

That said, you've done a great job explaining the use-case you have, so I can envision there being a use for it, but I'm not sure exactly how prevalent that is, and if there will be some users that specifically DON'T want to see any YAML. More to come.

**Comment by andrewballantyne** [comment]
@strangiato I'm going to close this issue based on Kyle's reply. Please feel free to reply and discuss the scenario as you see fit. We can even reopen it if the conversation goes that direction.

But for the sake of bookkeeping on our board and objectives, I'm marking this issue closed.

**Comment by kywalker-rh** [comment]
@strangiato Looks like we're going to reopen this. After more discussion with additional people working in the field it seems there is more of a desire for this than we originally thought.

We're going to need to be very thoughtful with it, especially if we are going to let users edit the YAML (I'm sure you know there are things they can break fairly easily by editing the wrong field) so this won't get in right away, but I'm going to think about it along with another design task around more advanced features. The plan there is to design a way to allow users to do this while making it obvious it can break things (or maybe even implementing a way to undo if there are problems with edited code).

**Comment by shalberd** [comment]
Yes, for example, we do not add data science projects via GUI, we add them via gitops workflows, all yaml-based

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2964
