### ISSUE TITLE
Discrepancy of values in OdhDashboardConfig's feature flags

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Values of different feature flags in OdhDashboardConfig could vary depending on the file document, for example [docs](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/dashboard_config.md) have the default values set to `false`, but the default file deployed for [OdhDashboardConfig](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml) have different values turned to `true` while the default [value initialization](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/constants.ts#L40) when there's no odhdasboardconfig object has again all the values set to `false`.

We should have consistency across al these different files to ensure the dashboard works as we expect.

### Expected Behavior

All these files to have the same values.

### Steps To Reproduce

1. Check the files mentioned above
2. See that the values are different

**Comment by Gkrumbach07** [comment]
talking internally

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2522 to handle under feature flag rework epic.
