### ISSUE TITLE
[Feature Request]: Migrate storybook to version 7

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1107]
### Feature description

We are on storybook 6 and should bump the version to 7 as it is out of beta. There are some migration efforts we need to consider first: https://storybook.js.org/docs/react/migration-guide

When doing this migration, there are some optional migrations that we should also include:
- [CSF2 to CSF3](https://storybook.js.org/docs/react/migration-guide#csf2-to-csf3)

### Describe alternatives you've considered

remain on 6

**Comment by Gkrumbach07** [comment]
errors might be coming from the plugins used

**Comment by andrewballantyne** [comment]
@Gkrumbach07 is this not done?

**Comment by lucferbux** [comment]
@andrewballantyne @Gkrumbach07 Yes, this was part of the effort in https://github.com/opendatahub-io/odh-dashboard/pull/1314
