### ISSUE TITLE
[Feature Request]: `modelMetricNamespace` is a misnomer feature flag

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1109]
### Feature description

Model Metric Namespace is a flag we have to enable ODH for where to find the metric stack. This is the only flag we have of this kind.

We should treat it like an override (eg `overrideMetricsNamespace`). Where we are deployed should be the default for everything. 

We also need to look at disabling the feature. See #1108 for more ideas on that front.

### Describe alternatives you've considered

Maybe we keep the same flag name and just default it unless it exists in the OdhDashboardConfig?

**Comment by alexcreasy** [comment]
The modelMetricNamespace CRD field is being removed as part of the UWM migration. Metrics are now stored within the namespace of the model server to support multi-tenancy (amongst others), as such there is no longer a need to override the namespace metrics are stored. The field will be removed as part of #1854.
