### ISSUE TITLE
[Bug]: Error while creating a workbench with OpenVINO and Anaconda image 

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/8126518/231505672-6cb21e89-aa26-4038-a641-4603d7b694bd.png)

From the image error `n.from` is this line [here](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx#L83). We have some imageVersion that is not compatible with our known type ([code type](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/k8sTypes.ts#L129-L153)).

Best guess, without debugging, is the ImageStream that is behind OpenVINO doesn't fit our expected type structure. The tags don't have a `from`.

This code works for other OOTB images, but is looking to change to an alternative structure in https://github.com/opendatahub-io/odh-dashboard/pull/800. As it stands though, likely the issue is we are trying to do segment.io tracking stuff and got burned by data not being as pure as our type suggested ("from" was expected on every tag).

### Expected Behavior

For no error. It already submits fine, the segment.io crashes the thread after things are created but before we redirect.

### Steps To Reproduce

1. Add OpenVINO image via installing the Intel Openvino Toolkit Operator
2. Test adding it as a workbench

### Open Data Hub Version

```yml
Dashboard: v2.9.0
```

**Comment by lucferbux** [comment]
@andrewballantyne is this happening upstream? That's kind of weird, cause by default tracking should be disable upstream, we don't provide a key there so it shouldn't be firing the event.

**Comment by andrewballantyne** [comment]
@lucferbux the code executes and doesn't get sent -- it's a NPE, it happens because it's in the spawner footer trying to craft the object... the function it calls just doesn't send it anywhere.
