### ISSUE TITLE
[Feature Request]: Create ODH UX Team Group & Add them to the PR Template

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1119]
### Feature description

Currently in our [PR Template](https://raw.githubusercontent.com/opendatahub-io/odh-dashboard/main/.github/pull_request_template.md) we ask you to tag the UX team. How will anyone open source know who is on the UX team?

Using https://github.com/opendatahub-io/org-management, we should create a group (@LaVLaS is setting it up). Then we should update our template to reference this group name.

**Comment by LaVLaS** [comment]
We're still working on the PR template but just submit the PR to [org-management](https://github.com/opendatahub-io/org-management) to create the groups

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2524
