### ISSUE TITLE
[Feature Request]: Don't Mount AppRoutes when feature is off

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1122]
### Feature description

We need to hide the routes so our 404 page catches things when the feature is disabled.

Today: Projects Disable => Project Routes are mounted -- undesirable state for fetching data
Goal: Projects Disabled => No Project Routes => 404 Page if they try to get to it

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2525
