### ISSUE TITLE
Model Serving Performance Metrics

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1128]
We need to readdress our goals for Model Serving Metrics to be more inline with what we want from a UX / product point of view.

Tasks:
- https://github.com/opendatahub-io/odh-dashboard/issues/1022
- https://github.com/opendatahub-io/odh-dashboard/issues/1130
- https://github.com/opendatahub-io/odh-dashboard/issues/1131
- https://github.com/opendatahub-io/odh-dashboard/issues/1132
- https://github.com/opendatahub-io/odh-dashboard/issues/1405
- #1511
- #2090
- #2091
- #2092
- #2099

Dependent on:
-  #1854
- Signoff by UX

Target Branch
f/mserving-metrics

**Comment by gmarkley-VI** [comment]
@alexcreasy is the status on this correct?

**Comment by alexcreasy** [comment]
Update: a PR has been raised for UWM (https://github.com/opendatahub-io/odh-dashboard/issues/1854) it is awaiting review and unblocks development of any remaining tickets for Performance metrics.

**Comment by alexcreasy** [comment]
@gmarkley-VI I'll remove the hold text from the top of the ticket, we're no longer blocked.

**Comment by alexcreasy** [comment]
@gmarkley-VI Ahh presumably you mean the ODH Dashboard Planning Status. I've moved this back to `Dev in progress`.

**Comment by alexcreasy** [comment]
Update: no further progress to report, I believe the last open ticket is actually already implemented, I'll verify this tomorrow and report back. If so we'll just require UX sign off.

**Comment by alexcreasy** [comment]
I've raised a PR for the last remaining issue of this tracker, once this is merged it'll be ready for moving to incubation along with UWM and Explainability

**Comment by alexcreasy** [comment]
This feature is now complete and ready for incubation. This needs to be merged at the same time as UWM (also ready for incubation) and Explainability.

**Comment by alexcreasy** [comment]
Update: following a request from Vince we have two new issues that need to be completed before this tracker is ready for incubation.

**Comment by alexcreasy** [comment]
Update: I've added ticket: https://github.com/opendatahub-io/odh-dashboard/issues/2099 as a place holder to ensure metrics are compatible with kserve - this will require backend work before it can be undertaken. This would block release but not incubation.

**Comment by dgutride** [comment]
Migrated to https://issues.redhat.com/browse/RHOAIENG-242
