### ISSUE TITLE
Improve Chart Tooltips & Colours

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1131]
We want to make nicer tooltips to give the appropriate look and feel when there is a lot of data to view.

- Continuation of #1130 & #1022 
- Tooltip Changes
    - Make sure it's a straight fixed line, not point based
    - We want to show the x-value at the top of the graph
    - Multiple Lined Graphs: We want to legend items, the name line & the value
      **Example:**
      ![image](https://user-images.githubusercontent.com/8126518/232142790-3c804ff9-cced-4db2-8a61-a6b3f8705e26.png)
    - Single Lined Graphs: We want to just show the name of the line & the value
- Colour changes:
    - For the successful requests use green-400
    - For the failures use red-100
    - Distinguish them for colorblind users use different patterns in the shaded areas -- https://www.patternfly.org/v4/charts/patterns (use the first two PF offers)

**Comment by dgutride** [comment]
@alexcreasy  - believes it is done and just needs to verify that the work is complete - should be able to verify today (10/27/23)

**Comment by alexcreasy** [comment]
@dgutride - I had some cluster issues following the PSI outage, I've got most the way to rebuilding it, but unfortunately I've run out of time. This is on the list for Monday (10/30/23)

**Comment by alexcreasy** [comment]
All but one of the acceptance criteria in this ticket are already met. The only outstanding item is that the colours for success / failed requests are not correctly set to red / green. I'll start working on a fix for this right away.

<img width="1016" alt="preview-issue" src="https://github.com/opendatahub-io/odh-dashboard/assets/4092230/1cc2c99a-5a6a-4212-a89c-87aeb34e12e2">

**Comment by alexcreasy** [comment]
PR Raised for this issue here: https://github.com/opendatahub-io/odh-dashboard/pull/2030

**Comment by vconzola** [comment]
@alexcreasy I think this is probably OK to get us into incubation, but once we start seeing real data we might want to change how the data is presented. For example, this is supposed to be a stack chart. The hashing makes that less clear. Is that absolutely necessary for a11y?

**Comment by alexcreasy** [comment]
Paraphrasing our discussion on slack: I inherited this ticket and the requirements stated green / red colours with hashing for a11y. If that's not necessary I'm totally happy to change the implementation.

**Comment by alexcreasy** [comment]
Based on our slack discussion I've removed the shading.
