### ISSUE TITLE
Lack of support for npm v9

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Follow up of #1123  and #1033 we lack of support of npm v9 in our build CD, so we needed to revert our runtime back to npm v8.

We will need to revert it back to npm v9 once support is added.

### Expected Behavior

Our current image to be using Node 19 AND npm v9

**Comment by Gkrumbach07** [comment]
cc @lucferbux do we have the right deps downstream to do this upgrade?

**Comment by lucferbux** [comment]
We currently have a fix for downstream, we can unblock this for next sprint cc @LaVLaS @andrewballantyne

**Comment by lucferbux** [comment]
It seems that cachito has implemented lockfileversion v3, we'll test the support downstream to check if we are unblocked here.

**Comment by andrewballantyne** [comment]
@lucferbux let us make sure asap that this is fixable for this current release (end of next week). If it is not, let us wait a bit and not complicate the deliverables for this release and then have to revert it again.

**Comment by lucferbux** [comment]
Yes, already raised a PR and testing downstream, if that works we can merge it here too.
