### ISSUE TITLE
[Investigate]: Websockets - The What, The How, The When

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1138]
### Feature description

We are in relatively high need for moving away from our 30s normal poll (or 3s fast polling) interval to head over to websockets so we only get what we need when it changes.

This ticket is to investigate that effort, thoughts on how to implement it, and setup our tech debt effort around it.

**Comment by christianvogt** [comment]
An investigation into the areas of the code base that would benefit from conversion to web sockets has been documented here: https://github.com/opendatahub-io/odh-dashboard/issues/1762

**Comment by andrewballantyne** [comment]
Functionality is in `main` now -- we are not using it for anything.

Effort will be followed up by https://github.com/opendatahub-io/odh-dashboard/issues/1762

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1792
