### ISSUE TITLE
[Feature Request]: Setup GH Action For PRs

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1142]
### Feature description

We should look at setting up an action or two to help with the following flows (maybe more scenarios?):

1. When a PR references a ticket, and it's not going into `main` it should still link (not sure if we can do this easily)
2. When a PR merges into a feature branch -- the ticket is closed (this should be possible with actions)
3. ~When a ticket is associated to a pull request, it should move into `In Review` so it properly shows up on our board in the PR tab~

### Anything else?

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions

**Comment by alexcreasy** [comment]
act is a really useful utility for testing gh actions locally.

**Comment by DaoDaoNoCode** [comment]
Saw a comment https://github.com/orgs/community/discussions/13240#discussioncomment-5440154, maybe this is a promising way to automatically close the issue when PR is targeting the feature branch.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2523
