### ISSUE TITLE
Threshold violation alerting

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1158]
### Goal

Clearly display threshold violations to the user

### Dependency issue

* https://github.com/opendatahub-io/sig-ml-developer-experience/issues/29

### Itemized goals

* Create subtasks when mocks available

### Mocks

Mocks not yet available, ticket subject to rework on receipt.

**Comment by alexcreasy** [comment]
@vconzola @kywalker-rh this ticket was based on the original requirements doc Karl sent round - I've noticed we don't really have anything in the current set of mocks around this - is this something you're planning to add, or does the graph simply exceeding the threshold line serve this purpose?

**Comment by vconzola** [comment]
@alexcreasy yes, the text of the issue doesn't say anything about alerting users, so i consider just showing the graph exceeding the threshold satisfying this requirement. i kinds recall Rob or Karl saying something about changing the line color for values that exceed the threshold, but for me that's a nice to have if it's easy to do.

**Comment by alexcreasy** [comment]
@vconzola ok thanks for that, I'll close this issue in that case as the phase 1 requirement was already met at phase 0.
