### ISSUE TITLE
Deletion of metric registrations

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1162]
### Goal

The user should be able to delete previously defined metric registrations

### Dependency issue

* #1152
* #1269 
* https://github.com/opendatahub-io/sig-ml-developer-experience/issues/29

### Itemized goals

* On the bias metric configuration page, add a delete button to the table row actions kebab
* The delete button should get the user to confirm deletion using the standard flow, and then call the TrustyAI API to delete the bias configuration.

### Mocks
![78888c5a-a824-42eb-96b2-c4f77c89cd8a](https://github.com/opendatahub-io/odh-dashboard/assets/4092230/ff946af1-28e2-457f-9ada-6e30072cd6ad)

**Comment by alexcreasy** [comment]
@vconzola @kywalker-rh just FYI there's nothing specific around this flow in the mocks. Do we just go with a confirmation that requires the user to type the name of the metric to delete?

**Comment by vconzola** [comment]
Yes. That would be consistent with the rest of the UI. Also, we haven't typically been mocking up these types of flows, but I'm happy to do it if there are other ones like this you want to see mocks for.

**Comment by alexcreasy** [comment]
Thanks for that Vince, I don't think that needs a mockup to be honest, I just wanted to be sure you were on board with the "standard" flow we already have.
