### ISSUE TITLE
[Feature Request]: Utilities for Routing

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1169]
### Feature description

We currently route to everything on magic strings. I think we need to change this.

Just in projects we have:
- `/projects/*`
- `/projects/:namespace`
- `/projects/${namespace}`
- `/projects/${namespace}/spawner`
- `/projects/${namespace}/spawner/:workbenchName`
- `/projects/${namespace}/spawner/${notebook.metadata.name}`
- All of model serving routes
- All of pipeline routes

And we have all the global page routes too. 

Suggestion:
```
export const globNamespace = ':namespace';
export const globWorkbenchId = ':notebookName'; // TODO: should be workbenchName
//...etc

export const routeProjects = `/projects`;
export const globProjectsAll = `${routeProjects}/*`;
export const routeProjectsNamespace = (namespace: string) => `${routeProjects}/${namespace}`;
export const globProjectsNamespace = routeProjectsNamespace(globNamespace);
//...etc
export const routeProjectNamespaceSpawner = (namespace: string) => `${getNamespaceProjectRoute(namespace)}/spawner`;
//...etc
export const routeProjectNamespaceSpawnerEdit = (namespace: string, workbenchName: string) => `${getNamespaceProjectRoute(namespace)}/spawner/${workbenchName}`;
//...etc
```

* `route<Name>` - a navigation route
    * Can be a string or function -- function means it has dynamic values (which will be most of our paths)
* `glob<Name>` - a react-router path, specifies a path or path chunk for something we use to route with
    * Ideally we lean into the route functions as much as possible and supply dummy values -- maybe these are all constants so we can reuse?

This has a lot of refactor (eg. notebook => workbench nomenclature, project => namespace, etc) powers as well as removing all of the magic strings that if you miss an `s` on a pluralized route it won't work.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2455
