### ISSUE TITLE
Improvements for the Custom Runtimes feature

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1197]
### Goal

List of improvements and questions to enhance before the release

### Itemized goals

- [x] Permisioneless users cannot list templates and sort
- [x] Inference services are not filtered by serving runtimes
- [x] In Serving Runtime creation, **dry run** the creation of the `ServiceAccount`, `Rolebindings` and `Secrets` to avoid issues.
- [x] Serving Runtimes are ordered in the Creation Modal
- [x] Support tokens (Secrets) with the same name in different Serving Runtimes.
- [x] The “Serving runtime” column is missing from the model servers table.
- [x] Enable/disable serving runtime might take a while and UI is reflected before it's persisted
- [x] Change the logic of retrieving the template order
        - Right now if the attribute is not present in odhdashboard config, it will display an error message
        - We want to enable it
        - Display an error when dragging if we cannot update the order
- [x] Check which runtimes we’ll have as OOTB (and deploy them by default)
- [x] If you try to upload a servingruntime but you already have a piece of code, it won't override it
- [x] Delete references of servingruntimeConfig (https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/modelserving/servingruntimes-config.yaml)
- [x] Revamp the feature flag with the following constraints:
       - If Custom Model Serving is disable, only allow to display OOTB
- [x] If we don't have the `template-display-name` or `template-name`, display "Unknown Serving Runtime" in the edit field.

**Comment by lucferbux** [comment]
These are things we might wanna review in the feature freeze as enhancements.

**Comment by lucferbux** [comment]
Patching dashboard config doesn't throw any error, just tried `oc patch OdhDashboardConfig odh-dashboard-config --type='json' -p'[{ op: 'replace', path: '/spec/templateOrdersss', value: templateOrder }]'`

**Comment by andrewballantyne** [comment]
> Patching dashboard config doesn't throw any error, just tried `oc patch OdhDashboardConfig odh-dashboard-config --type='json' -p'[{ op: 'replace', path: '/spec/templateOrdersss', value: templateOrder }]'`

Have you tried this in code? I'm worried if the oc patch command has extra error handling to avoid it crashing for chaining cli commands.
