### ISSUE TITLE
Tests for Custom Serving Runtimes feature

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1198]
### Goal

Add coverage for the Custom Serving Runtime feature:

- https://github.com/opendatahub-io/odh-dashboard/issues/1327
- https://github.com/opendatahub-io/odh-dashboard/issues/1328
- https://github.com/opendatahub-io/odh-dashboard/issues/1329
- https://github.com/opendatahub-io/odh-dashboard/issues/1330
- https://github.com/opendatahub-io/odh-dashboard/issues/1334

**Comment by andrewballantyne** [comment]
Talked with Lucas -- going to close this. Each individual test is on our backlog, we can get to those as individual items and we don't need a grouping ticket for it. `feature/model-serving` + `quality` should be all you need.
