### ISSUE TITLE
[Feature Request]: Dashboard Config Solidification -- Pipelines + Custom Serving Runtimes

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1201]
### Feature description

We are in a bit of a pickle with the inclusion of code from both the Pipelines feature & the Custom Serving Runtimes feature.

- Today: We have one DashboardConfig pulled in the frontend, it is behind a ResourceWatcher (2min cache) -- this is fetched from the App component
- Pipelines: We have a need to inject a faux operator status into the resource to help with service account (to be dashboard operator) injection of operator status for the dependant operator
- ~Custom Serving Runtimes: Stores the template order of custom serving runtimes and needs a pretty snappy response from the server (cache is the problem)~ covered by https://github.com/opendatahub-io/odh-dashboard/pull/1294

What can we do here? We sorta need this faux status about operator status from the service account -- basic users do not have permissions to fetch this so it can't be done on the frontend. We need a snappy response from the server for the status of the template order -- but if it invalidates the cache, we spam looking at operators (instead of every 2 mins). Since it is a faux status, it's not actually in the k8s object -- maybe it should be?

Discussion is needed.

**Comment by andrewballantyne** [comment]
Seems the solution here is to move to a custom endpoint for now. The Dashboard Controller future code can fix this up to bring it officially into the status of the DashboardConfig.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2962
