### ISSUE TITLE
[Feature Request]: Change the way we store Enabled/Disabled State of Custom Runtimes

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1205]
### Feature description

We currently store the value of if a custom serving runtime template is enabled or disabled as an annotation of the resource.

This needs to change. Unfortunately the resource is a manifests resource of OOTB runtimes -- which means they are managed by the Operator on install and thus will reconcile their way out of any change we want to apply.

For this release, we'll work with `opendatahub.io/configurable=true` in ODH so the resource can be modified by our code without being reconciled by the Operator.

In the next release, we need to remove this dependency on changing the resource and remove that annotation. We should probably go to managing this via the ODHDashboardConfig like the template order.

~Do we store enabled states or disabled states 🤔 We may need to discuss the pros and cons for that.~

EDIT: I think we will want to store `disabled` states for ease of use (all runtimes are on by default when they are created) -- if we lack the config we can just show the OOTB ones.

**Comment by lucferbux** [comment]
I think the other way around, that we need to store `disabled` states, by default, all the new custom runtimes will be enabled, so we'll need two calls (one to create and one to add it to the enable list) storing disables it's just a call when an admin disables a resource.

**Comment by andrewballantyne** [comment]
That's a good point @lucferbux -- I'll update the ticket.

**Comment by andrewballantyne** [comment]
@lucferbux we missed this for this release -- this is not good. Let us start on this "immediately" and get it in for next release.

Upstream won't be able to use proper configs. Downstream can't maintain their items. This is not sustainable for long.

**Comment by lucferbux** [comment]
> @lucferbux we missed this for this release -- this is not good. Let us start on this "immediately" and get it in for next release.
> 
> Upstream won't be able to use proper configs. Downstream can't maintain their items. This is not sustainable for long.

Yes, this is one of the issues I intended to get for this sprint, however, I prioritized the ones I was working cause despite the fact this is bad for our dev flows, it doesn't affect the end user, the way is working now allows both upstream and downstream deployments to use OOTB the same way, the main downside is that we need to be working on several projects, and that's no ideal.

I will work on this asap.
