### ISSUE TITLE
[Feature Request]: Update DSP Server - Data Connections

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1214]
### Solution

* Mocks are listed in [Yan's comment](https://github.com/opendatahub-io/odh-dashboard/issues/1214#issuecomment-1672783455)
* Replace the Data Connection functionality with a direct "Object Connection" functionality
    * All fields are required & a name is no longer needed
    * Fields: `Access key`, `Secret key`, `endpoint`, `bucket`
* Allow for a prefill from a Data Connection for reuse of data they have already setup
    * This hopefully can be a fancy dropdown in PF, but explore what components might be useful in v4 of PF
    * Make sure you have a "hide" secret functionality so we don't expose the `Secret key` value
* DO NOT implement the typeahead feature for first pass

---

### Feature description

Today we allow the use of Data Connections in setting up of the Data Science Pipelines Server.

This actually is not a proper representation of what is happening. This may lead the user to think we are "associating" the Data Connection to their Pipeline Server. So they could assume changes to the Data Connection would be reflected here. This is not the case technically.

Suggested changes:
 - We change the UX so it does not say "use existing" data connection & we just provide 4 of the fields (key, secret, endpoint, bucket) directly, all required
 - We will create a secret by the static name `mlpipeline-minio-artifact`, and provide the same keys as we do today
     - We'll want to push the db-password secret (when applicable) into this secret too so that the server can use it all at once

This should separate the relationship between the Data Connection & the DSPA.

Side note: We may want to prefill the information from an existing Data Connection -- TBD, bringing it up at the UX Meeting this Thursday.

**Comment by andrewballantyne** [comment]
We do not have a concrete idea of how this will look. @kywalker-rh we can make them add it directly as a first pass -- but we should look at some way to say "prefill from existing" if someone wants to reuse the values they have already added.

**Comment by andrewballantyne** [comment]
@kywalker-rh I just flagged this as field-priority.

**Comment by andrewballantyne** [comment]
We are close to having this done by UX. 

WIP Mocks: https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/prototype/a/BE8AE158-C97F-46ED-A821-9E58C028B96D

**Comment by yannnz** [comment]
This is the latest design: [Update DSP Server mockup](https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/JAamzrb).   Need @kaedward to help on reviewing the content.

**Comment by kaedward** [comment]
@andrewballantyne I'm not sure I understand exactly what is happening during the "enable pipelines" process - is there any other information we can provide about what exactly "enable pipelines" means? This would be helpful for the empty state, as well. I'm imagining something along the lines of "enable pipelines for use on your system" or "for your account"... but I'm sure that's not accurate. :-)

**Comment by pnaik1** [comment]
@andrewballantyne , does bucket needs to a mandatory field  in the new implementation?

**Comment by andrewballantyne** [comment]
> @andrewballantyne , does bucket field needs to a mandatory field in the new implementation?

That's what the mocks say @pnaik1. Do note that it's not the same fields as we have in the Data Connection modal because this is very much targeted for DSPA creation.

@yannnz can you remove the typeahead functionality from your mocks? We discussed that in the UX Meeting doc file and it appears still in your [last comment](https://github.com/opendatahub-io/odh-dashboard/issues/1214#issuecomment-1672783455).

**Comment by andrewballantyne** [comment]
@pnaik1 I've updated the description to help detail out the solution more. Let me know if you're still unsure of anything.

**Comment by pnaik1** [comment]
@andrewballantyne thanks , this clarifies most of my doubts

**Comment by yannnz** [comment]
@andrewballantyne @pnaik1 I've removed the typeahead function in my mockup, you can refresh the same link to see it. There are also content updates based on Katie's suggestion.
