### ISSUE TITLE
[Feature Request]: Show more than 20 Pipeline Runs

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1223]
## Solution

Implement full API for:
- Pagination
- Filter
- Sort

In all three areas of Pipelines:
- Pipelines
- Triggered Run
- Scheduled Runs (Jobs)

Clean up sort for the Project Pipelines section -- but there is no sort or pagination there.

Details on changes can be found in the comment below: https://github.com/opendatahub-io/odh-dashboard/issues/1223#issuecomment-1654602539

Internal doc for [Pagination testing](https://docs.google.com/document/d/1HBmcQVLquqU-N3oD3jwQCZHghvWHvVa-Lr3CrIJjNS0/edit#heading=h.stkra0etg3rm).

---

### Feature description

Kubeflow API caps at 20 -- then pages. We should chain fetching that information until we have all the information.

All list pages will suffer from this problem -- Pipelines, Runs, Jobs.

**Comment by andrewballantyne** [comment]
The problem here more than just "why only 20" -- that's simply answered by setting a page limit.

The problem here that we need ux for is to figure out how we will fetch an indeterminate amount of data.

Things we need to consider:
 - Our filters are frontend queries only -- so if the data is not there, it's not filterable
 - The data can be an indeterminate amount, so "locking up the page to load everything" is going to be a bad idea
 - The [page component](https://www.patternfly.org/v4/components/pagination) from PF does support indeterminate state of whatever we want (including buttons to retrigger refresh or pull more it seems)
 - Whatever our pull data setting is, we will need to consider how we can refresh the latest... this particular list can have new ones pop in at the top regularly
 - Ideally whatever solution we come up with can be used to handle large amounts of values on any given page that needs to show "everything of one type"

@yannnz (cc @kywalker-rh)

**Comment by kywalker-rh** [comment]
@yannnz We should consider this at the same time as adding versions for Pipelines.

**Comment by gregsheremeta** [comment]
I hit this personally yesterday. I consider this a bug, not an RFE :slightly_smiling_face:

**Comment by andrewballantyne** [comment]
Major UX & UI rework needed.

We need to move to API instead of client-side efforts.

From the UX meeting:
> Update of Pipeline & Runs filter & sort
> Doc:  [API filter & sort tips research](https://docs.google.com/document/d/1HBmcQVLquqU-N3oD3jwQCZHghvWHvVa-Lr3CrIJjNS0/edit#heading=h.zedt38d24pp6) (internal only)
> Mockups:
> - [General rework](https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/0AGk9D0)
> - [Update the name and description of Job-runs under the Triggered runs tab](https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/v/Lx3Emd/a/DEnow9W)
> - [Filter Runs by Pipeline and Experiment (by IDs)](https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/nQJRQdl)

**Comment by roytman** [comment]
The 20 Runs or Pipelins limitation continues to exist. We can set the page size to 100, but only the latest 20 Runs/Pipelines are displayed. We have observed the same limitation with ODH 2.4.0

**Comment by andrewballantyne** [comment]
The solution is working through the final stages of other work and will be added to the incubation branch by the end of the week along with log improvements and Pipeline Versions.

Apologizes for the delay @roytman.

**Comment by roytman** [comment]
Thank you @andrewballantyne

**Comment by andrewballantyne** [comment]
Oh boy, terribly sorry about that. If you're using the v2 Operator you can use the Dev Flags (https://github.com/opendatahub-io/opendatahub-operator/wiki/3.-Using-Operator-in-Dev-Mode)

These will be in your DSC, and you point the manifests we use to deploy the Dashboard at our incubation branch -- which is the next release of ODH (should be soon). This uses the nightly built Dashboard image (which will only update when the pods rollout -- so it should be pretty stable and fixed).
```
    dashboard:
      devFlags:
        manifests:
          - contextDir: manifests
            sourcePath: ''
            uri: 'https://github.com/opendatahub-io/odh-dashboard/tarball/incubation'
      managementState: Managed
```

@roytman let me know if you need anything else. ODH will be releasing soon-ish.

**Comment by roytman** [comment]
@andrewballantyne, many, many thanks.

**Comment by roytman** [comment]
@andrewballantyne , the Pipeline and Run lists work magic; thanks a lot. 
However, we have a new issue. We frequently use the option to duplicate a Run. 
With this update, it stopped working as expected. Now, it creates a new RUN with the **default** input parameters.

Should I open a new issue?

**Comment by roytman** [comment]
It looks like an ODHv2 problem; I'll open an issue.

**Comment by DaoDaoNoCode** [comment]
@roytman Sorry, it's a known issue that's accidentally imported with the new feature of the pipeline version. It's already fixed and will be merged into the `main` branch tomorrow.
