### ISSUE TITLE
[Feature Request]: Better Support for Pipeline Server Issues

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1224]
### Feature description

When we have server issues, there is no way to know we are having them... resources in the background crash loop and in general don't behave up to standards... and the DSPA just keeps saying "Not ready" -- which is the same as the loading state.

I've asked the backend devs to work on better reporting of this. We should react to those changes when they are done.

**Comment by andrewballantyne** [comment]
[Talked with the backend folks](https://odh-io.slack.com/archives/C03DY3YT151/p1696440880844229) -- this looks ready to go. Let us get failed state testing in here (bad S3 connection data, and anything else we can think of -- look at what the DSPA takes and mess with it a bit to generate some issues). 

We have had this topic brought up a couple times recently and I think we can do better than our 5min timeout "please delete and try again" messaging.

**Comment by jgarciao** [comment]
@andrewballantyne in RHODS 1.34.0 the DataSciencePipelineApplication CR provides some conditions that can help verify the status of the pipeline server creation and warn you if there are problems connecting to object storage or the database 

![incorrect-database-password-dspa-conditions](https://github.com/opendatahub-io/odh-dashboard/assets/66894/4d3ce43f-b453-492b-8783-89d45a2c3425)

![incorrect-access-key-dspa-conditions](https://github.com/opendatahub-io/odh-dashboard/assets/66894/4b417df8-0114-487b-8a44-e918eb1a6382)

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2906
