### ISSUE TITLE
[Feature Request]: Custom Serving Runtimes -- Admins Should Have Access

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1225]
### Feature description

Custom Serving Runtimes uses the k8s pass through API -- this is a problem for basic "Admins".

We need close this gap about the settings page and the admins. We either need to grant them access to the dashboard namespace fully or stick the effort behind the service account (this is not ideal).

Today a basic user that is an Admin of our dashboard cannot view/modify the Custom Serving Runtimes.

**Comment by andrewballantyne** [comment]
cc @lucferbux

**Comment by lucferbux** [comment]
Ok, based on the conversation we had the other day, let me do a summary of the roadmap for this future:

**For this release**
We would create new custom endpoints in the backend, properly secured, to get all the logic that we currently have in the pass through API through the backend

**Near future**
We will deprecate the way admins in rhods work right now and migrate back the functionality to the pass-through API.

Is that right? @andrewballantyne

**Comment by andrewballantyne** [comment]
@lucferbux Erwan had an interesting response on the Jira -- which made me think that maybe we don't do a workaround. We should talk with UX and PM about this. Let me add it to the UX meeting this afternoon. Unfortunately I think you'll have to catch the recording as it's pretty late for you.

**Comment by lucferbux** [comment]
@andrewballantyne I'm not sure if I can get this before this feature freeze, found some blockers that slowed me down. Would it be fine to push it either tomorrow/earlier next week or should we move it to next sprint?

**Comment by andrewballantyne** [comment]
@lucferbux do your best with your working hours -- we can address tomorrow how far along you are.
