### ISSUE TITLE
[Bug]: When many users wait for their notebook to be scheduled, the dashboard gets overloaded

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the large scale test with an under-sized cluster, the Dashboard may overload the APIServer.
[Test result 1](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/664/pull-ci-openshift-psap-ci-artifacts-main-ods-notebooks-long/1638873673945321472/artifacts/notebooks-long/test/artifacts/003__plots/report_00_report:_error_report.html): 1741/2000 users succeeded
Most of the failures were due to the cluster being unable to start the notebooks.
But multiple failures are due to APIServer timeouts
[Test result 2](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/665/pull-ci-openshift-psap-ci-artifacts-main-ods-plot-notebooks/1643381974997405696/artifacts/plot-notebooks/test/artifacts/report_00_report:_error_report.html): 863/2000 users succeeded
Most of the failures were due to the cluster being unable to accommodate the notebooks.
But many of them are due to APIServer timeouts.

### Expected Behavior

- The dashboard does not overload the APIServer when Pods cannot be scheduled. We need to work on it together to better understand what's happening and how to prevent it
- The dashboard steps should be constant, as when the notebook nodes are [prepopulated](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/681/pull-ci-openshift-psap-ci-artifacts-main-ods-notebooks-long/1647845203073044480/artifacts/notebooks-long/test/artifacts/001__notebook_scale_test_dsg/001__test_run/002__plots/report_05_report:_user_execution_overview_files/fig_0.html):

### Steps To Reproduce

1. run the notebook scale test with [300 users and auto-scaling enabled](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/684/pull-ci-openshift-psap-ci-artifacts-main-ods-notebooks/1648304942877773824/artifacts/notebooks/test/artifacts/001__test_run/002__plots/report_00_report:_error_report.html), see that the Dashboard takes more and more time to be accessed

**Comment by lucferbux** [comment]
After some investigation, these are the two outcomes:

- Change `useFetchState` to dynamically  change the polling time (`refreshRate`) based on polling conditions to solve the polling flood
- Wait on [websocket implementation](https://github.com/opendatahub-io/odh-dashboard/issues/1138) to watch the notebook status  with websockets

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-825
