### ISSUE TITLE
[Bug]: Mount path for additional storage can only be /opt/app-root/src

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any additional PVC is mounted under `/opt/app-root/src`.
In fact, when you set the mount path to be `/data` on the dashboard, the storage is mounted under `/opt/app-root/src/data` in the notebook.
This is an issue when you need to mount specific resources under a different path.
For example, to train with Pytorch with lots of data/resources, you need a supplemental storage space mounted at  `/dev/shm` to increase shared memory. Right now it's feasible only by hacking the Notebook YAML through the OpenShift console.
Right now this is the only way to do serious PyTorch training.

### Expected Behavior

You should be able to mound a PVC anywhere in the container filesystem.

### Steps To Reproduce

Try to mount a volume, it will always be under `/opt/app-root/src`.

### Workaround (if any)

- Create the additional storage through the dashboard
- Mount it anywhere, e.g. /shm
- Stop the notebook
- With the OpenShift Console, or CLI, edit the corresponding Notebook YAML
- modify the mount point from /opt/app-root/src/shm to /dev/shm
- Restart the notebook. The new configuration is preserved and the volume is mounted where you wanted it

**Comment by shalberd** [comment]
Same could also be necessary for auto-injected ca-bundle placement (mount from a secret data section to a system-level linux location in the container) for custom CA trust at notebook container-level.

**Comment by davwhite** [comment]
Work around not working in workbench or notebook server. This is a problem for projects using Pytorch. I have potential customers using pytorch with GPUs.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1100
