### ISSUE TITLE
Patternfly (PF) Abstraction Layer

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1250]
## The What

Today we have a very strong stance of "If PF doesn't do it, they should before we do" and "If we run into a bug, we hack it, tell PF, and undo our hack when they release the fix".

This is no longer going to be the case. PF is taking the stance of limiting design changes to PF to support use-cases applications need. To that extent, it seems we will need an abstraction layer on our end to help expand on what PF is creating so that we don't need to duplicate it on our end or anything of that nature.

If at some point in the future, PF decides to adopt our change or include it in an extension, we have that abstraction layer that can be moved out and reused for other applications.

## The How

Technically how are we going to do this:
* These will be hosted in the folder: `frontend/src/components/pf-overrides`
* All components that are PF extended items, should be prefixed with Dashboard — eg `DashboardRadio` `DashboardTab` `DashboardTable` (yes, we should move and rename our table)
* CSS/SASS files are still faux pas — but they can be used inside this new dashboard concepts folder

## The Goals (of this ticket)

- [ ] Create a new folder in concepts
    - [ ] Add a README describing how this layer is important (note the [slack conversation](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1684340207245209?thread_ts=1684340203.238529&cid=C043A9D5DMW) for details on how we can populate the content of this README)
    - [ ] Investigate lint rules to help contain the effort (no CSS outside of it?)
    - [x] Update the existing Architectural design documentation (https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/architecture.md) to include this new folder
    - [ ] Components should get actual storybook stories for their use-cases / props as a means to document the use-case
- [ ] Move the `src/components/table` set of components including our generic `Table` component into the new folder
    - [ ] Rename the `Table` component to `DashboardTable` and apply the name change throughout the app

That should get us started down this path. Future goals will be to take the card expectations we brought to PF in https://github.com/orgs/patternfly/discussions/5486 to our new folder as well.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2407
