### ISSUE TITLE
[Bug]: Users with Edit permissions cannot create a model server runtime in a shared project

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Users with "Edit" permissions on a shared project are not able to create a serving runtime, like they can create other resources like workbenches, storage and data connections.

<img width="821" alt="Screenshot 2023-05-18 at 21 33 25" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/3cea4dda-2088-459c-8d3a-06476bbb2c84">

### Expected Behavior

Either one of:
- operation is performed successful
- user cannot click on "Configure server" button if the operation is actually not allowed

### Steps To Reproduce

1. Create a Data Science Project myprojectA with user A
2. grant "Edit" permissions on "myprojectA" to user B
3. check user B can access the DS project "myprojectA"
4. click "Configure server" button
5. insert the required information in the form
6. click "Configure" button

### Workaround (if any)

Grant user admin role

**Comment by lucferbux** [comment]
We agree on the following for this fix:

- Disable token authorization for users who doesn't have permission to edit
- Move the logic for creating the rolebinding based on the check

**Comment by bdattoma** [comment]
> * Move the logic for creating the rolebinding based on the check

hey @lucferbux, wanted to double check on this line
`Move the logic for creating the rolebinding based on the check`. What does it mean? Will the user be able to create the model server with this? Who will create the rolebinding?

**Comment by lucferbux** [comment]
> > * Move the logic for creating the rolebinding based on the check
> 
> hey @lucferbux, wanted to double check on this line `Move the logic for creating the rolebinding based on the check`. What does it mean? Will the user be able to create the model server with this? Who will create the rolebinding?

Yeah, I've changed the comment to make it more clear. We've just basically refactored the logic, since we were always creating the rolebinding, now  it checks first if the user can create it and if token auth is enabled.
