### ISSUE TITLE
[Feature Request]: Support for template parameters

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1260]
### Feature description

Right now we are using `templates` to manage Custom Serving Runtimes, but we are using the `objects` field to store the spec, but not the `parameters` functionality built in.

We need to add support, both from a UX and UI standpoint for managing parameters to control certain aspects such as resource limits, GPU and more.

**Comment by Gkrumbach07** [comment]
@vconzola Can you take a look at this and talk with @lucferbux for additional info

**Comment by lucferbux** [comment]
Based on [this conversation](https://redhat-internal.slack.com/archives/C05KDB2HFQQ/p1695659459584789) templates might be deprecated in the future, we need to consider wether adding parameters to templates or just use any other technology.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-558
