### ISSUE TITLE
[Feature Request]: Container Comparing Utility

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1263]
### Feature description

Note: This is for both Model Serving & Notebooks -- and really any place that would use PodContainers.

We have a Notebook Sizes to Notebook Container resources compare utility that is inline in the `useNotebookDeploymentSize`. This should probably be made more generic and have proper tests written against it.

Since container comparison is just K8s and not specific to Notebook. For instance, Model Serving needs to use this functionality too.

Sample coding idea:
```
// => sizes of resources
// => container to compare
// <= one of the sizes
  const size = sizes.find(
    (size) =>
      isCpuLimitEqual(size.resources.limits?.cpu, container.resources?.limits?.cpu) &&
      isMemoryLimitEqual(size.resources.limits?.memory, container.resources?.limits?.memory),
  );
```

Might be able to do a "test 1" container and size function too -- might be useful if the caller has specific logic they want to do or has complex sizes or something.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2963
