### ISSUE TITLE
[Bug]: Model Serving Promotion Doesn't use the Right Check Access

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We can't check access on `update` -- not every user will be able to do that; `edit` permission users for instance.

If they cannot get through the check access condition on `/namespaces/:namespace/1`, it errors out:

```
{"statusCode":403,"code":"403","error":"Forbidden","message":"You don't have the access to update the namespace"}
```

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/f1f21869-3ff3-45dd-9cb5-35825eb32b43)

### Expected Behavior

We shouldn't fail this check access check if they have access to operate within the project. Being able to at least "edit within" the project is the check we need to do.

We can do it off of list of the project -- but a better check might be to create some resource inside the project. We have to be careful not to try and check non k8s resources as if model serving is not installed we don't want to fail the check on the resource type not existing.

### Steps To Reproduce

We will need to figure out what the RH Developer Sandbox permissions are... mirror those for a project. Then we can test properly for RBAC validation.

### Open Data Hub Version

```yml
Dashboard: v2.9.1
```

**Comment by Gkrumbach07** [comment]
related: https://github.com/opendatahub-io/odh-dashboard/issues/1259

**Comment by lucferbux** [comment]
Closing this in favor of #1259
