### ISSUE TITLE
[Tracker] Custom Notebook (BYON) Improvements - Part 2

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1266]
### Description

Continuation of Part 1:
- https://github.com/opendatahub-io/odh-dashboard/issues/1254

General improvements to the Custom Notebooks Admin UI (part 2 is the "remaining items").

### Target Branch

TBD

### Requirements

> OOTB images in admin UI list of images, changing the display order, UI for entering software and packages
> Enable users to access/view image location URL after creating custom NB image
> Differentiate between provided by RH, partner, and custom - to be defined in UX.
> Behavior of table sorting & display order - to be defined in UX. 

### Itemized UX Issues

* https://github.com/opendatahub-io/sig-ml-developer-experience/issues/28

### Itemized Dev Issues

- https://github.com/opendatahub-io/odh-dashboard/issues/864
- https://github.com/opendatahub-io/odh-dashboard/issues/375

TBD for more.

### Related artifacts

UX Mocks: https://www.sketch.com/s/c8183f89-76f5-4a23-b885-a9e404a61414/a/7ywAQZp

**Comment by dgutride** [comment]
Closing tracker - will be covered by PM feature board when necessary.
