### ISSUE TITLE
Ability to configure available storage classes

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1270]
Support multiple storage classes for PVCs (Cluster Storages) in the Projects view.

**Mocks:** https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/g1rOAvJ

Using feature branch `f/storage-class`

# Dependencies

- UX: https://github.com/opendatahub-io/odh-dashboard/issues/1798
- Early adoption: https://github.com/opendatahub-io/odh-dashboard/issues/1701

## Foundational Work

- https://github.com/opendatahub-io/odh-dashboard/issues/1355
- https://github.com/opendatahub-io/odh-dashboard/issues/1362

## P0: Admins must be able to configure which storage classes should be available for users

> * Must be able to configure storage classes other than the OpenShift default.
> * Must be able to configure a 'default' storage for RHODS. This does not have to be the OpenShift default.
> * Must be able to configure the name of the storage class as it should appear for users if exposed in the end user UI. Note: per Guillaume's comment below, the end user UI should show the admin configured display name as well as the real name. 

- https://github.com/opendatahub-io/odh-dashboard/issues/1363
- https://github.com/opendatahub-io/odh-dashboard/issues/1364
- https://github.com/opendatahub-io/odh-dashboard/issues/1365
- https://github.com/opendatahub-io/odh-dashboard/issues/1366

##  P0: Users should be able to select from available storage classes based on admin config when creating workbenches or NB serving sessions

> * If only 1 storage class available, the UI should not present an option for users (since the one available will always be used).
> * If more than 1 available, the UI should start with default configured by admin, but users should be able to select any of the available options.

- https://github.com/opendatahub-io/odh-dashboard/issues/1367
- https://github.com/opendatahub-io/odh-dashboard/issues/1368

**Comment by shalberd** [comment]
For listing available storage classes, you might need more than Clusterrole Admin. There is a ClusterRole basic-user that can list users and storageclasses. Especially for showing which users already have access to the project in project sharing, that might be good as well. https://docs.openshift.com/container-platform/4.10/authentication/using-rbac.html

**Comment by andrewballantyne** [comment]
@shalberd as I understand it, all users can list storage classes (I tested this on my cluster with a basic user -- it was a while ago though). After listing, there is nothing else happening around storage class resources. We are not allowing creation, deletion or editing of the resource itself. We'll need to manage the metadata way from the storage class as this is a cluster resource that the admin probably shouldn't be marking up for our application use-case (a cluster could have multiple use-cases ongoing).

TBD if we use a CRD or some configmap setting / OdhDashboardConfig setting -- but we will need to store in an "enabled state", description and a display name for the end-user (data scientists). That'll be figured out part of this effort once @lucferbux starts flushing it out over the next week or two.

**Comment by shalberd** [comment]
>all users can list storage classes
depends on what you define as user. I checked on the Openshift Web GUI. Aside from the optional rolebindings at project-level to Admin, View, Edit, fortunately, the basic-user ClusterRole applies to all logged-in users by default.




The clusterrole basic-user

openshifthostname/k8s/cluster/clusterroles/basic-user can list storageclasses, which is nice.
![Bildschirmfoto 2023-06-11 um 20 47 35](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/018bbdd0-e53d-4dd8-bdc3-7e6b3e7b0b75)



Any authenticated / logged-in user is assigned clusterole basic-user, so it's cool.

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: basic-users
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:authenticated'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: basic-user
```

**Comment by andrewballantyne** [comment]
Another [good note](https://github.com/opendatahub-io/odh-dashboard/issues/1876#issuecomment-1739093145) about something we should support with Storage Classes when we do this feature.

**Comment by dgutride** [comment]
Migrated to jira:  https://issues.redhat.com/browse/RHOAIENG-332

**Comment by dgutride** [comment]
Moving to closed - future work will be tracked in Jira
