### ISSUE TITLE
[Tracker]: Data/Object Connections Rework

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1271]
### Description

Our Data Connections were a "needed at the time" situation. It has since gotten feedback. We would like to relook at the feature set and see what we can do to improve this.

### Target Branch

TBD

### Requirements

TBD

### Itemized UX Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1825

### Itemized Dev Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1602
* https://github.com/opendatahub-io/odh-dashboard/issues/1711
* https://github.com/opendatahub-io/odh-dashboard/issues/1763
* Test Connection Story

#### External Related Issues

* https://github.com/opendatahub-io/odh-model-controller/issues/61

**Comment by xianli123** [comment]
Hi @andrewballantyne. I have been researching the features related to data connection such as Pipelines, Runs, and Model deployment. I will try to rebuild a holistic view of it and then update the data connection. Once I have the deliverables, I will let you know.

**Comment by andrewballantyne** [comment]
Rolled into https://issues.redhat.com/browse/RHOAIENG-1811
