### ISSUE TITLE
[Feature Request]: Add Clone and Stop actions from the actions menu in Runs home page

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1282]
### Feature description

In order to stop or clone a Triggered run user must open the Run details page and click on Action button from the top-right of the page.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/918fbbf1-d18b-4df1-b95c-894144b2971c)

It could be useful to have the stop and clone actions in the Run home page directly, along with deletion option:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/f9ead849-1f40-4549-b606-0ee3210f1a7b)

### Anything else?

It should be considered that "Clone" action for runs which are triggered from schedule may not be fully meaningful: if you need you can clone the scheduled run instead. But it might be open to UX analysis :)

**Comment by Gkrumbach07** [comment]
@kywalker-rh cc

**Comment by kywalker-rh** [comment]
Agreed @bdattoma. Thanks for pointing it out.
@Gkrumbach07 and @andrewballantyne let me know if you need anything else from me to implement this idea.

**Comment by andrewballantyne** [comment]
Nope, that's great... thanks Kyle!
