### ISSUE TITLE
[Feature Request]: Multi select in Pipelines page

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1284]
### Feature description

It would be useful to add the option to delete multiple pipelines in bulk, like we can do with pipeline runs.

current: 
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/7457fe8a-7ee3-49f8-93b8-29b2885a1f9e)

multi select (pipeline runs):
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/fca6657f-b47a-4c87-b5c0-eefdb84c7142)

**Comment by Gkrumbach07** [comment]
@kywalker-rh cc

**Comment by andrewballantyne** [comment]
> I don't see any issues with adding this. I would expect it to work the same way as it does for Runs, but if you need more direction to implement it let me know, @andrewballantyne.

Runs are checkbox, Pipelines are expanded rows. I think we need to pick one or the other, or you need to come up with a design for this (maybe two initial columns?)

**Comment by kywalker-rh** [comment]
Okay, this is going to take some more thought to implement right. I'll add it as an issue for future UX work.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2904
