### ISSUE TITLE
[Feature Request]: Filter runs by pipeline when clicking on "View all runs" from a pipeline

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1285]
### Feature description

Currently, if you have multiple pipelines and you click on "View all runs" from the 3dots menu it will just redirect you to the "Runs" section. However, if the action "View all runs" is in the action list of a specific pipeline, I believe it makes sense to redirect the user to a filtered list of runs showing only those belonging to the specific pipeline.

GIF showing how it works today:

![view-all-runs](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/d2887acc-1098-4b62-b22b-aded167a595e)

### Describe alternatives you've considered

An alternative approach would be to move the "View all runs" outside the 3dots-menu of a single pipeline and move it in a common place for all the pipelines. e.g., next to "Import pipeline" button. Like this:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/7e648ca5-b206-476d-a5fc-89cc34cf2db2)

**Comment by andrewballantyne** [comment]
@kywalker-rh there are two UX issues with this...

1. We don't filter directly on a Pipeline -- it's by text name... thus you can technically match on "Test" and "Demo Test"
2. We don't share filters between Scheduled and Triggered runs -- so how do you think this should work when you navigate from the Pipeline page?

**Comment by kywalker-rh** [comment]
> We don't filter directly on a Pipeline -- it's by text name... thus you can technically match on "Test" and "Demo Test"

If we can add a filter for the pipeline itself that would obviously solve this, not sure the effort it would take to add that, though. In the meantime, I think filtering on something is better than nothing, so I'd be okay implementing it as a filter on name as an mvp.

> We don't share filters between Scheduled and Triggered runs -- so how do you think this should work when you navigate from the Pipeline page?

We should have a conversation about what it would look like to share the filters, I see that as having some usefulness larger than this too. I would put the filters above the tabs and allow users to click between them. That actually gives us a better view of Runs associated with a specific pipeline than what we have now.

That said, if I had to pick something to implement now, I would say we should take them to the scheduled run page and filter there.

**Comment by andrewballantyne** [comment]
Experiments are likely going to need to refactor a little about the way the data works on this page -- I'll keep it in mind about the sharing of filters when I design it. I agree we need a new UX layout from you @kywalker-rh if we are going to do it though.

There is no rush to do anything, let us do it right. If you want some hacked version for a short term, we can try -- but there is no logic here today to handle anything other than maybe injecting a "text search".

**Comment by yannnz** [comment]
We included this issue into the [Support pipeline versions issue](https://github.com/opendatahub-io/odh-dashboard/issues/1575). 

Based on the discussion with Humair, we will not be able to provide 
/ with 
/. We will have 
/ with 
/ instead.

**Comment by andrewballantyne** [comment]
Filtering on runs is not really supported by the backend. Versions will remove this functionality as well.

This functionality won't be iterated on and will be removed in Versions.

**Comment by bdattoma** [comment]
>  Versions will remove this functionality as well.

what functionality do you mean? 


If we don't want to / cannot implement this filtering mechanism, I'd still consider the alternative solution I proposed in the issue description `An alternative approach would be to move the "View all runs" outside the 3dots-menu of a single...` because IMO the menu at row level should provide actions on the specific item, not all of them. If we want to provide an action which embrace all the items (e.g., view all runs), it should be put at table-level, not at row-level. 

Of course this is my opinion, if UX is okay with how it is now, I won't insist more on it. @kywalker-rh @andrewballantyne

**Comment by kywalker-rh** [comment]
@bdattoma The original intent of the "View all runs" action was to view all the runs that are associated with a specific pipeline, so it wasn't implemented the way it was intended in the first place (because of the constraints @andrewballantyne mentioned). To me, having a "View all runs" button for the page doesn't have much value, since users can simply click on the Runs left-nav item. I don't know the implementation schedule for Versions, if its coming soon I say we just leave it as is and it will be removed then. If it will take a while longer we could simply remove the action from the kebab dropdown so users aren't confused by the action.
