### ISSUE TITLE
[Bug]: Confusing Start to Pipeline Runs

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you startup a Pipeline Run (run immediately) you get navigated to the Run Details page. For a brief moment as it loads, you see an error among other states of "loading".

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/fe7e7a31-3b09-4567-aed2-eb511c55eb08)

### Expected Behavior

Don't see an error -- loading indicators only.

### Steps To Reproduce

1. Have Pipelines installed
2. Have a Pipeline
3. Create a run for the Pipeline

Should happen for a brief moment while we fetch the exact resource in question.

### Open Data Hub Version

```yml
Dashboard: v2.10.0
```

**Comment by lucferbux** [comment]
@andrewballantyne Is there any situation in which you can bump into an error trying to retrieve the pipeline? or is it expected to have a spinner in all situations?
Asking cause I lack the context of this part of the feature, thanks in advance.

**Comment by andrewballantyne** [comment]
For posterity -- @lucferbux and I talked on Slack -- it can not find the data is the most obv error. There might be others, but I don't recall there being other break points for this page (purely from memory -- we'd need to look at the code to be sure)

**Comment by uidoyen** [comment]
@andrewballantyne @lucferbux What do you think of handling error by `usePipelineRunById` `error` here https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx#L46

**Comment by andrewballantyne** [comment]
We should talk on the PR about your implementation so the reference to the state of the code is present. I've replied as such.
