### ISSUE TITLE
[Feature Request]: Test Pipelines Projects

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1295]
### Feature description

These tests should have and use mocks.

Test the Pipelines section on the Projects page for:

* Import is disabled while server is not installed
* Import is disabled while server is loading/installing
* Import is enabled when server is installed
* Empty state is there when there are no Pipelines but server is installed

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
