### ISSUE TITLE
[Feature Request]: Test Global Pipelines

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1296]
### Feature description

These tests should have and use mocks.

Test the global pipelines: 

* No project state
* Project, but no Pipeline Server
* Project, Pipeline Server is loading + you can see the actions
* Removal of Pipeline Server modal opens and enables on proper value added
* View of Pipeline Server -- no action, just that it opens
* Project switch (other project doesn't have server setup & things disappear)
* Server Installed, content tests
    * Pipeline Empty State
    * Upload modal
    * Pipeline actions - delete (others can be ignored -- see 'anything else' section)
    * Pipeline Filters
    * Expand row
        * Empty state
        * Runs render
        * Runs cap at 5

### Anything else?

Can we test navigation cleanly?

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
