### ISSUE TITLE
[Feature Request]: Test Global Runs (setup)

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1297]
### Feature description

These tests should have and use mocks.

Test the global pipeline runs:

* No project state
* Project, but no Pipeline Server
* Project, Pipeline Server is loading
* Project switch (other project doesn't have server setup & things disappear)
* Server Installed, content tests
    * Tabs in empty state
    * Each tab test will be handled in other issues

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
