### ISSUE TITLE
[Feature Request]: Allow deletion of Pipeline Server from the Data Science Project view

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/odh-dashboard#1298]
### Feature description

In a _Data Science Project_ you can _Create a pipeline server_ but, once is created, you cannot delete it or view the server configuration (you have to go to the Data Science Pipelines section to do it). It would be nice to be able to manage the server from the Data Science Poject page, same as you can do it for models.

Also, once the server is started, there is no visual representation of the server being running and consuming cluster resources. It would be nice to inform users about it until a more sophisticated solution is developed (more info at [RHODS-8639](https://issues.redhat.com//browse/RHODS-8639))

**Comment by kywalker-rh** [comment]
There are a couple reasons:

1. Space, I don't want to add too many things to the already busy Projects page
2. The feedback was this action wouldn't be accessed very much (by the DS), so I prioritized the uploading of a pipeline on that page and pushed the server interaction to the Pipelines page.

I think we're again seeing a contrast between what an ML Ops Eng and a data scientist want to see. Being able to interact with and see if the server is running feels like something ML Ops wants to see, but not necessarily a data scientist. We will test with actual users soon, so I am hoping that will give us more insight into whether my assumption is correct, and allow us to make more informed decisions about which user we should be prioritizing.

**Comment by jstourac** [comment]
Hi guys, is this issue still relevant? At least in the upcoming {{RHOAI 2.5}}, I can click on the "three dot" button next to the "Import pipeline" button to view the pipeline server configuration and also to "Delete pipeline server" options, see:

![Screenshot from 2023-12-10 21-09-42](https://github.com/opendatahub-io/odh-dashboard/assets/12250881/cf11d602-057c-4ad4-8916-1c87dad94e06)
