### ISSUE TITLE
[Feature Request]: When creating a run, make pipeline input parameters more evident

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/odh-dashboard#1301]
### Conclusion / Objective

Make the title of the section `Pipeline run parameters` ([as noted by UX](https://github.com/opendatahub-io/odh-dashboard/issues/1301#issuecomment-1581240542))

### Feature description

When creating a pipeline run, there is a _Parameters_ field that shows the input parameters of the pipeline, but that’s not evident at first view (specially if you haven't created the pipeline)

I think _Pipeline input parameters_  or _Input parameters_ could be more evident. Also, they could be under the pipeline selector, not below _Run type_

![create-run-input-parameters](https://github.com/opendatahub-io/odh-dashboard/assets/66894/1972fd39-d969-4828-8fd7-4827377c74be)

**Comment by Gkrumbach07** [comment]
@kywalker-rh UX issue

**Comment by kywalker-rh** [comment]
@jgarciao I see your point, but we also have no idea how many parameters could be added on any given pipeline, so if there are 20 parameters the Run type section would end up being shown far down the page. We have a usability test scheduled soon, so we will see if this comes up as an issue there. If it does we'll think about solutions, if not, I propose we leave it as is.

**Comment by andrewballantyne** [comment]
> @jgarciao I see your point, but we also have no idea how many parameters could be added on any given pipeline, so if there are 20 parameters the Run type section would end up being shown far down the page. We have a usability test scheduled soon, so we will see if this comes up as an issue there. If it does we'll think about solutions, if not, I propose we leave it as is.

Not sure if this helps -- but I think Jorge is mentioning that we call them just "Parameters" -- would we not want to call them "Run Parameters" "Pipeline Parameters" "Input Parameters" etc to help indicate what kind of params they are... is it immediately clear? The context helps a lot (we are on the create run page) but they are somewhat disconnected from the Pipeline selection.

**Comment by kywalker-rh** [comment]
Okay, that makes sense, thanks for the further explanation @andrewballantyne.

@kaedward If I'm understanding this correctly adding a descriptor to the current field of Parameters in the run creation page would be helpful. Do you have a preference for one of Andrew's suggestions ("Run Parameters" "Pipeline Parameters" "Input Parameters"), or a suggestion of your own?

**Comment by kaedward** [comment]
@kywalker-rh I prefer "Pipeline input parameters", but if a user will already know that they're input parameters, we could drop "input" and just say "Pipeline parameters".

**Comment by kaedward** [comment]
I think having "pipeline" in there is important if we don't switch the placement of run type and parameter.

**Comment by kywalker-rh** [comment]
No objections from me, I don't think we need to make it especially short. Let's go with your suggestion "Pipeline input parameters" @kaedward

**Comment by manaswinidas** [comment]
I think this is taken care of. 
<img width="917" alt="Screenshot 2023-06-20 at 4 54 56 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/b61cb6e6-60b6-44da-8aa0-2a01e104fd6d">
