### ISSUE TITLE
[Bug]: Limit Issue with Project name + Resource name

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating OpenShift Routes, it has been determined that a max of 63 characters can be used between the project name & the route name which takes the form of `<resrouceName>-<projectName>.xyz.foo.com`.

If appending the project name and the resource name gives a route name with more than 63 characters the resource creation will fail. This is happening currently in:

- DS Pipelines servers -> When the project name is longer than 31 characters 
- Workbenches -> Notebook name plus project name is longer than 63 characters
- Model Serving -> Model Server Name (ServingRuntime) plus project name is longer than 63 characters

#### For Workbenches and Model Serving

We are waiting on https://github.com/opendatahub-io/odh-dashboard/issues/1820 to get a proper ux handler of this issue.

#### For pipelines

Pipeline server should have more flexibility in its name. 

Suggested fix is to simply take the current name of `ds-pipeline-pipelines-defintion` and shrink it to `ds-pipeline-dspa`. You do this by shrinking the DSPA's name to `dspa` (from `pipelines-definition`). The `ds-pipeline` prefix is backend and does not need to change.

### Steps To Reproduce

1. Create a project with 62 characters in the name (`DS Pipelines Project-ldap-user20` as found in automation)
2. Then attempt to create the Pipeline Server
3. Attempt to create a workbench
4. Attempt to create a model server

A route will never be created and the resources will never initialize. 

### Workaround (if any)

Have a shorter named project.

### Open Data Hub Version

```yml
Dashboard: v2.10.0
```

### Anything else

It should be noted you have to consider listing of DSPA CRs since we need to support upgrades. This will handle the use-case of GitOps deployed resources as well.

**Comment by shalberd** [comment]
an openshift route is `componentname-namespacename.apps.ocp4test.mydomain.com`

The 63 characters length limit is not for the whole openshift route, but for "string between the dots", in our case

ds-pipeline-`dspamame`-`namespacename`

We have no control over the prefix ds-pipeline apparently, but it really could be shorter, say dspi

from 11 to 4 characters.

Namespaces names can also be quite long, let's say

tst-opendatahub

already 15 characters

plus the name of the dspa CR metadata.name

https://access.redhat.com/solutions/3638581

do we have to have that route? What's it used for?

**Comment by andrewballantyne** [comment]
> do we have to have that route? What's it used for?

If you're referring to the DS Pipelines Route -- it's used for service communication to get the data behind DS Pipelines. We might be able to use internal service or something. But today it's an OpenShift Console Route.

**Comment by gregsheremeta** [comment]
any ETA on this? An ODH user hit this today.

**Comment by andrewballantyne** [comment]
Raised the priority, we were not looking at doing this as I expected it to be a rare case -- only QE hit it with long testing names

**Comment by strangiato** [comment]
This seems like an issue that isn't a Dashboard problem and should be something solved on the DSPO side.

> We have no control over the prefix ds-pipeline apparently, but it really could be shorter, say dspi

The dashboard does not, but that should be something that is updatable in the operator.  The pre-fix is coming from here:

https://github.com/opendatahub-io/data-science-pipelines-operator/blob/7f5f983f765a40801edf74c52bd637f5436e7be6/config/internal/apiserver/route.yaml.tmpl#L4

Updating the DSPA that the Dashboard generates to be something like dspa instead of pipeline-definition is probably a good quick fix but I don't think that fixes the underlying issue.

The root issue is that the host name in the route can't be longer than 63 characters.  The default behavior if you don't provide a host name is to create one using the format <route-name>-<namespace>.app* so if <route-name>-<namespace> is longer than 63 characters the route creation fails.

Removing the ds-pipeline prefix from the route name gives you some extra characters but once again doesn't resolve the issue.  It would still be possible to have a namespace route name combo that is too long and will fail.

The permanent fix is that DSPO needs to be aware of the route and namespace names and when they are longer than 63 characters it needs to manually set the host name to a truncated version of the route name/namespace combo.

> I expected it to be a rare case 

31 characters is certainly a long namespace name but not out of the ordinary, especially in orgs that run large multi-tenant clusters that have standard naming convention such as <org>-<team>-<project>-<environment> for namespaces.

**Comment by andrewballantyne** [comment]
@strangiato thanks for your comment. I was unaware that route names based off of other resources had flexibility to call themselves whatever they wanted. But I suppose that makes sense.

@HumairAK @gmfrasca @gregsheremeta Would the DSPO be able to handle the 63 character limit and craft a manual alternative to the host name?

**Comment by shalberd** [comment]
Why are you not using the internal service .svc, which has no such limitations? Why is it absolutely necessary to first go outside the cluster network boundary and then in again via route? Yes, you'd have to provide some kind: NetworkPolicy objects to define what is alllowed ingress from what pod and on which port from a data science project to the central dashboard namespace, but that is totally managable.

**Comment by andrewballantyne** [comment]
We call from the client browser @shalberd -- we pass this data also off to the Elyra Notebook -- which calls the svc as well.

Not sure we can use the svc as it's not directly part of a Pod efforts to make the call. The Dashboard might be able to look into it, but I'm not sure that works for Notebooks.

**Comment by shalberd** [comment]
A service is resolve via cluster DNS just like everything else, but yeah, I have no idea about your architecture currently :-) What component is making which calls for example

**Comment by andrewballantyne** [comment]
@shalberd Take a look at my (admittedly poor) representation of the Dashboard: 
https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/meta/arch-overview.png

All client code for any app (as far as I am aware), the stuff you see in your browser, is not running in a Pod; it's static JS, CSS, and HTML assets downloaded to the client and executed (outside of any k8s infrastructure). 

Now all the network traffic an app does can be proxied through a pod (we do that for all calls in the Dashboard to work around CORS issues, among a couple others) -- for instance, on-cluster we run the Prometheus (thanos) stuff through the service to talk to it instead of using the route because it has unique permission issues around their exposed route that prevents basic users from getting access (so really limits what we can do).

The new backend service calls (Pipelines being the first of two so far) are all done through the client determining the k8s Route obj of the service and using that as part of a simple proxy to the server (in the pod) to facilitate the call without aforementioned CORS issues. Could we change this to use internal services? Yes, I suspect we could -- it would take a little rework, but should be possible. Only concern is we are not the only callers to this endpoint.

Is the Notebook architecture going to be able to use the service? I have no idea, but today, we feed them our route to use as the endpoint for their calls. We can investigate this if there is real benefit here. cc @harshad16

**Comment by shalberd** [comment]
I found this about load-balancing of services (not haproxy-based routes), albeit only stackoverflow :-) https://serverfault.com/questions/1069274/how-openshift-service-loadbalance-between-pods Any input is welcome on the topic of calling routes vs services, i.e. from @gregsheremeta or @guimou

**Comment by lucferbux** [comment]
I've reworked this issue to make it broader, we currently have this issue for several resources, such as ds pipeline server, model server and workbenches.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-583
