### ISSUE TITLE
[Feature Request]: reduce number of serviceaccount names, define them in manifest yamls and use KfDef parameters

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1311]
### Feature description

Conceptually, what is the reason that individual notebooks / workbenches have individual service account names? 

Is RBAC so vastly different between different notebooks? 

Regarding e.g. Elyra, I see that RBAC is added to the dynamic service account name / notebook name. 
But could that not also be done using just a single serviceaccount name for all notebook images of the same kind of RBAC, in manifests? 

I guess having the dynamic aspect is mainly due to specific Elyra RBAC added to Elyra / pipeline-enabled notebooks, correct? 

Context for question: quite a lot additional work for either linking optional image pull secret to podspec (not a good idea conceptually) or serviceaccount name (variable, thus not possible to link via KfDef / manifests optional parameters (i.e. image pull secret name created by admins in openshift) of notebook. See https://github.com/opendatahub-io/odh-manifests/issues/833 

The alternative to many dynamically-created ServiceAccounts along with their rolebindings would be a worbench-notebook serviceaccount and a workbench-notebook-pipelines serviceaccount, statically defined in manifests of odh-dashboard along with its RBAC / rolebinding and programatically added by name during assembly of the notebook CR as a whole. 

That would also make linking optional image pull secrets wayy easier via KfDef parameters ... in my opinion, RBAC should be defined in static yamls in manifests and then used programatically / indirectly by referencing one of a few service account names with clear RBAC in the notebook spec serviceaccountname. I mean, even pipeline definition name is static / a const, as used in the elyra rolebinding, so that could also be put in manifests with a default value for that parameter ...

The same conceptual question probably applies to [model serving serviceaccounts](https://github.com/search?q=repo%3Aopendatahub-io%2Fodh-dashboard%20serviceaccountname&type=code) There, too, it seems, a lot of putting-together serviceaccounts and RBAC / rolebindings is done programatically just because of service account name equaling the servingruntimename. Currently, the serving runtime name is namespace-specific, model-server-${namespace}, so rolebinding name and service account name are, too. There is no reason to put the namespace name into the name of a rolebinding or serviceaccount, as both have their context in the namespace anyways. Could that not be done similar to odh-dashboard/manifests/base/model-serving-role.yaml and model-serving-rolebinding.yaml?

I mean, for application model serving serviceaccounts:

There, dynamic names of serviceaccounts and rolebindings are created it seems, this time containing the namespace. There, a rolebinding called `model-server-<namespace>-view` and a serviceaccount called `model-server-<namespace>-sa` are created. 

Question there, too, is: why not create the rolebinding and serviceaccount in manifests with a static name, e.g. model-serving-view and static serviceaccount name, e.g. model-serving-sa, and then only reference both rolebinding and serviceaccount name from code, making only the to-be-applied namespace dynamic in code? Does RBAC for model serving differ at all per namespace? If not, putting it in manifests is the much better solution in my view. 

@lucferbux 

Yes, the namespace / model serving namespace is only known to dashboard because namespaces are variable, but there is no conceptual reason for putting namespace as a part of rolebinding and serviceaccount names programatically if the RBAC content does not change. You could keep the RBAC definitions themselves in dashboard code for model serving, but keep the name of serviceaccount and rolebinding static. Rolebindings and ServiceAccounts are namespace-specific anyways.

That idea (reducing the number of service account names per namespace) does not apply to rolebinding for project sharing, as those are not service-account specific, correct? They have users and groups as subjects, I see. Great work on admin, edit, view there!

**Comment by Gkrumbach07** [comment]
cc @andrewballantyne

**Comment by shalberd** [comment]
a) Regarding notebooks: not an option to do this. According to @VaishnaviHire, notebook-controller relies on individual / unique per-workbench/notebook [serviceaccounts](https://github.com/opendatahub-io/kubeflow/blob/44b375c3ac396bacda6d1403a8cbf516cecb2286/components/odh-notebook-controller/controllers/notebook_oauth.go#L55) because they are used as oauth-clients and for correct setting of e.g. redirect-url and so on. 

[Openshift doc](https://docs.openshift.com/container-platform/4.13/authentication/using-service-accounts-as-oauth-client.html) reference as well.

I will submit a PR for applications (model mesh controller, dashboard, notebook controller, odh notebook controller ... ) using static serviceaccounts in the main opendatahub namespace as well as here for manifests. Mere changes to manifests with kustomize tweaks. Focsussing on that first.

For odh-dashboard notebooks, we will need to figure out a way to 
a) add image pull secret with dockerconfigjson credentials to a dynamic workbench namespace
b) link up that image pull secret by name with the dynamically-created serviceaccounts

That will be a PR for odh-dashboard.

**Comment by shalberd** [comment]
greater context: ODH on-premise / disconnected / airgapped
possible milestone: ODH v1.7.0

**Comment by shalberd** [comment]
closing as approach is clear
