### ISSUE TITLE
Model Serving Enhancements

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1312]
## Description

This issue is targeted to collect all the issues related to Model Serving, both `ModelMesh`, `KServe` and `Custom Serving Runtimes`.

## Target Branch

`main` 

### General UX Improvements

- https://github.com/opendatahub-io/odh-dashboard/issues/1604

### General UI Improvements

- https://github.com/opendatahub-io/odh-dashboard/issues/2228

### KServe UX Improvements

- https://github.com/opendatahub-io/odh-dashboard/issues/2178
- https://github.com/opendatahub-io/odh-dashboard/issues/2165
- https://github.com/opendatahub-io/odh-dashboard/issues/2168
- https://github.com/opendatahub-io/odh-dashboard/issues/2170

### KServe UI Improvements 

- https://github.com/opendatahub-io/odh-dashboard/issues/1776
- https://github.com/opendatahub-io/odh-dashboard/issues/2244
- https://github.com/opendatahub-io/odh-dashboard/issues/2177
- https://github.com/opendatahub-io/odh-dashboard/issues/2172
- https://github.com/opendatahub-io/odh-dashboard/issues/2143
- https://github.com/opendatahub-io/odh-dashboard/issues/2135
- https://github.com/opendatahub-io/odh-dashboard/issues/2137
- https://github.com/opendatahub-io/odh-dashboard/issues/2105
- https://github.com/opendatahub-io/odh-dashboard/issues/1727
- https://github.com/opendatahub-io/odh-dashboard/issues/1584
- https://github.com/opendatahub-io/odh-dashboard/issues/2051
- https://github.com/opendatahub-io/odh-dashboard/issues/2097
- https://github.com/opendatahub-io/odh-dashboard/issues/1980
- https://github.com/opendatahub-io/odh-dashboard/issues/2237
- https://github.com/opendatahub-io/odh-dashboard/issues/2187

### Improve Custom Serving Runtimes (templates)
- https://github.com/opendatahub-io/odh-dashboard/issues/1260
- https://github.com/opendatahub-io/odh-dashboard/issues/1190

### Routing
- https://github.com/opendatahub-io/odh-dashboard/issues/1149
- https://github.com/opendatahub-io/odh-dashboard/issues/1287

### GPU Support
- https://github.com/opendatahub-io/odh-dashboard/issues/1313

## Past improvements

- https://github.com/opendatahub-io/odh-dashboard/issues/1395
- https://github.com/opendatahub-io/odh-dashboard/issues/1320
- https://github.com/opendatahub-io/odh-dashboard/issues/1310
- https://github.com/opendatahub-io/odh-dashboard/issues/1216
- https://github.com/opendatahub-io/odh-dashboard/issues/1215
- https://github.com/opendatahub-io/odh-dashboard/issues/1173
- https://github.com/opendatahub-io/odh-dashboard/issues/1259
- https://github.com/opendatahub-io/odh-dashboard/issues/1357
- https://github.com/opendatahub-io/odh-dashboard/issues/1394
- https://github.com/opendatahub-io/odh-dashboard/issues/1320
- https://github.com/opendatahub-io/odh-dashboard/issues/1198
- https://github.com/opendatahub-io/odh-dashboard/issues/1261
- https://github.com/opendatahub-io/odh-dashboard/issues/1582
- https://github.com/opendatahub-io/odh-dashboard/issues/1605

**Comment by lucferbux** [comment]
We are gonna work on this for Model Serving v2, wait until we have https://github.com/opendatahub-io/odh-dashboard/issues/1810 in place

**Comment by lucferbux** [comment]
Moved kserve enhancements from #1810

**Comment by dgutride** [comment]
Migrated to jira:  https://issues.redhat.com/browse/RHOAIENG-330
