### ISSUE TITLE
[Feature Request]: Improve GPU detection in Model Serving

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1313]
### Feature description

Currently, no standardized logic detects if a Custom Serving Runtime supports GPU. In order to have minimal logic, we use  `opendatahub.io/template-enabled` just for admins to hide the GPU selector in their Custom Serving Runtimes but that's a minimal support for this logic.

We would want to support a better logic to handle the display for the GPU selector in given Custom Serving Runtimes.

**Comment by lucferbux** [comment]
@Xaenalt Based on the conversations we've had recently, I think we can close this right? I think there's no proper way to detect whether a model serving supports GPU or not right?

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-562
