### ISSUE TITLE
[Bug]: RoleBinding deletion API call fails when a user with Edit permission deletes the model server

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the scope of Project Sharing feature, a user B who got "Edit" permissions to project A owned by user A can delete the model server but it leaves a leftover in the cluster that is the rolebinding <modelserver-name>-view. 
This happens because user B does not have enough permissions to delete the rolebinding. The screenshot reports the set of API calls triggered by the deletion of the model server by user B

[UPDATE]

As we comment in the discussion bellow, we are going to check permission with `useAccessReview` and disable the deletion if the user doesn't have enough permissions.

### Expected Behavior

Either one of those:

- rolebinding gets deleted
- user B does not have the power of deleting a model server

### Steps To Reproduce

1. login RHODS Dashboard with basic user A
2. create a DS Project project A
3. share access to the project with basic user B, granting Edit permissions
4. create a model server in project A with user A
5. (optional) deploy a model (which user does not matter)
6. delete the model server with user B

**Comment by lucferbux** [comment]
@vconzola We have another issue with this, users with edit cannot delete model servings either, since they cannot delete the rolebinding resource, what should we do UX wise in this scenario?

**Comment by shalberd** [comment]
question is: should user B even have the power to delete a model server in a shared project / namespace? In terms of clusterrole edit at namespace-level:

The edit role permits modifying and creating common application resources but gives no access to **permissions**, limit ranges, or quotas that also correspond to the typical developer user.

i.e. permissions = roles, rolebindings, all that stuff

You can think of creating custom clusterroles maybe, e.g. edit-odh or something like that :-)

https://www.redhat.com/sysadmin/rbac-openshift-role

**Comment by andrewballantyne** [comment]
> @lucferbux I think maybe we should disable the model server Edit and Delete buttons (and possibly Create too) for users with only Edit permissions. That might solve all of the issues we're seeing in this area. So Edit users would be able to deploy models using model servers in namespaces for which they have Edit permissions, but only Admin users would be able to Create, Edit, Delete. Thoughts?

There may also just been a holistic look at what "Edit" means for us -- If I invite you to my project, should you really be able to run around deleting my stuff? I dunno... As Sven alluded to -- maybe we make our own Edit rule variants... 

I don't know if permissions were really chewed to the bone on the use-cases, it was just a means to grant Dashboard the ability to share projects -- and `admin` everything seemed kinda goofy. But there is a lot of small nuance here that we are missing. 

cc @jedemo @kywalker-rh @vconzola might want to spin that off for another conversation / issue.

For this issue, my opinion is to not allow create or delete.. but leave edit the way we are going now. This way they can edit the replica count, in case they want to "spin down" the server. My two cents...

**Comment by jedemo** [comment]
We discussed changing the terminology for 'edit' permissions because we already have some cases where editing is not allowed. I think maybe we change to 'Contributor' and clearly document what that enables. I'm ok restricting 'delete' to admins. 
@kywalker-rh

**Comment by lucferbux** [comment]
Thanks @jedemo that should cover this issue and future functionality that relies on roles or rolebindings. I'm gonna open another task to cover that refactor.

**Comment by lucferbux** [comment]
I've created https://github.com/opendatahub-io/odh-dashboard/issues/1335 just to track those changes.

**Comment by kywalker-rh** [comment]
Commenting here to say I am on board with changing the "Edit" type in the permissions section to "Contributor". For the rest it sounds like there will be more conversation.

**Comment by andrewballantyne** [comment]
Got to discuss this at the UX meeting last week. We are not going to do anything special here -- we are going to lean into access checks and disable deletion when it cannot complete.
