### ISSUE TITLE
[Bug]: If you delete a Pipeline, the run reference leads to a weird error page

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have an issue where when you delete the Pipeline to runs that are already created, navigating to the Runs list page you can see the Run and click on the Pipeline.

You see this error page:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/f32ef7a8-a185-4f16-8141-08218841b367)

It's not the best, I imagine we can improve this UX somehow.

### Expected Behavior

An improved experience when viewing a deleted Pipeline (from the run list)

[From Kyle](https://github.com/opendatahub-io/odh-dashboard/issues/1324#issuecomment-1573979423)... A UI that reflects:

> Pipeline not found
> To see more pipelines navigate to the pipelines page.
> [See all pipelines]

### Steps To Reproduce

1. Create a Pipeline
2. Create a Run for that Pipeline
3. Delete the Pipeline
4. View the Run on the Global Runs list page
5. Click on the Pipeline link

### Open Data Hub Version

```yml
Dashboard: v2.10.0
```

**Comment by andrewballantyne** [comment]
@kywalker-rh not sure if you have a preference on how we address this... the dropdown has values to "Create Run", that's not going to work out.

Suggestions on how we address this issue?

**Comment by jgarciao** [comment]
I saw this issue today too.  One option could be to remove the pipeline runs when the pipeline is deleted. The pipeline deletion dialog could warn users about it

**Comment by kywalker-rh** [comment]
If its possible to simply remove the link to the pipeline that no longer exists I think that's the simplest option. Does that break anything else? I think there is a use-case where someone could want to reference Runs for a Pipeline that was deleted, so if we can avoid that I'd like to.

**Comment by andrewballantyne** [comment]
> If its possible to simply remove the link to the pipeline that no longer exists I think that's the simplest option. Does that break anything else? I think there is a use-case where someone could want to reference Runs for a Pipeline that was deleted, so if we can avoid that I'd like to.

There could be a heavier option for sure about querying for the resource itself, so if I query for the Pipeline, get a 404 back, I'd know the resource is not there anymore and thus has been delated (reasonably sure that's the right and sane path to take).

But this is a performance hit to fetch every pipeline that is referenced in the Runs page (we could do this lazy like so it's by your number of items on your page). We'd need to be careful about how we store the data and how it is managed throughout the app -- We'd need to do this on both the Runs Triggered / Scheduled tables as well as the bottom drawer in the Run Details page.

**Comment by kywalker-rh** [comment]
Okay, sounds like we need a short term solution, and maybe time to think about a way to do it longer term that isn't so resource heavy. For short term can we create an empty state that says:

Pipeline not found
To see more pipelines navigate to the pipelines page.
[See all pipelines]

**Comment by andrewballantyne** [comment]
Sounds good, this will also help if you bookmark your Pipeline or have a tab open and it refetches and it is no longer there anymore (or if you try to manually type that id lol -- not likely a real use-case)
