### ISSUE TITLE
[Tech Debt]: Cleanup Image Regex

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1326]
### Feature description

We implemented a Image regex in #1249 and it's got little explanation. We use it `string.match(regexp)` and the result is manually `match[4]` -- this is nightmarish for the next dev to read into this. Looking at the complex regexp is nasty too...

Also, to tie it all off, the reg exp is duped in both back and frontend due to having no test runner in the backend and that's where the code usage is at.

Changes needed to clean this up:
* Wrap the usage of the reg expression in a function -- document through code
    * eg. `parseImageURL(imageString)` and put the constant inside inside this function
    * Return out of this function an object `{ fullURL: string; tag: string; host: string; ... }` Using `[1]`, `[4]` should only be used in this function and thus documented as you put into a variable... ideally don't have groups you don't care about, or put them all in the object -- ie, what is `[2]` and `[3]` in the match string?
* Add Jest on the backend + Test this function (we'll move it from the backend to the frontend with the code)
    * Delete tests in frontend (as they are copied/rewritten to use the function)
    * Delete copied regexp in frontend

**Comment by shalberd** [comment]
Here is Mr. airgapped / on-prem again :-)

What about typing in a specific image by digest, not by tag, in BYON? As of now, that is not possible, is it?

e.g. { fullURL: string; digest: string; imagestreamtagname: string; ... }  or so

https://github.com/opendatahub-io/odh-manifests/blob/v1.6/notebook-images/base/jupyter-datascience-notebook-imagestream.yaml#L24

`quay.io/opendatahub/workbench-images@sha256:af8da57b334a334475d9404ed42f7b535ca27ad7c9e0278d28b47b9e83002493`

tag for imagestream / dashboard GUI when selecting available notebook images to start. For the image above, I'd want that to appear as jupyter-datascience-ubi9-python-3.9-2023a-20230515 later on, being imagestream tag.name

![Bildschirmfoto 2023-06-03 um 07 17 58](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/859c8167-a576-4d2b-bfb6-649b3d792538)
![Bildschirmfoto 2023-06-03 um 07 18 10](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/dc7f8274-c79d-497d-be44-d504de16e849)


On the other hand, the whole BYON image import functionality only works with the internal docker registry probly anyways, so no need to also make this sha256 digest format compatible?

On import, is only an imagestream def created? If yes, that whole above idea is not necessary, unless someone absoiutely want to make sure to get an image by digest and not by tag.

**Comment by andrewballantyne** [comment]
Hey @shalberd -- love the engagement! I do believe we will be correct this in https://github.com/opendatahub-io/odh-dashboard/issues/1266 when we cycle through to clean up BYON based on other customer feedback.

Snippet from the WIP mocks:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/0e618ce4-f2cd-42dc-9e6c-370fcccef71c)

Things still need to be ironed out, but it should cover SHA references at that point.
