### ISSUE TITLE
[Feature Request]: Test Custom Serving Runtime Util Methods

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1327]
## Type of test
Unit Testing

## Description
Add coverage for utils method for Custom Serving Runtimes. Inputs for the unit tests should have mock data.

## Coverage
Test following logic:
- Get templates sorted by an array of names
- A common K8s resource is a Serving Runtime object
- Get a Serving Runtime object from an array of templates given the template name.

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
