### ISSUE TITLE
[Feature Request]: Test Model Serving Util Methods

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1328]
## Type of test
Unit Testing

## Description
Add coverage for util methods for Model Serving. Inputs for the unit tests should have mock data.

## Coverage
Test the following logic:
- Get `ServiceAccount` and `Rolebinding` resource names given a `Serving Runtime` name.
- Control that the user cannot have resource requests larger than resource limits.
- In `setUpTokenAuth` you only create a `Service Account` if you are in create mode (no existing secrets)
- In `setUpTokenAuth` create a `Role Binding` only if the option is enabled and the resource doesn't exist.
- In `createSecrets` you create all the given secrets.
- In `createSecrets` you create only new secrets and remove the ones that are not present anymore.

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
