### ISSUE TITLE
[Feature Request]: Test Custom Serving Runtime View

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1329]
## Type of test
Integration Testing

## Description
Add coverage for the Custom Serving Runtime table section. 

## Coverage
- There's an empty state if no `template` is provided.
- `OOTB` `templates` should display a `Clone` kebab action
- Regular `templates` should display `Edit` and `Delete` kebab action
- `Clone` and `Edit` actions should navigate to the Code Editor view.
- `Delete` should delete the template.
- Templates should be ordered based on the array of name given by `servingRuntimeTemplateOrder`

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
