### ISSUE TITLE
[Feature Request]: Test Custom Serving Runtime Creation/Edition

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1330]
## Type of test
Integration Testing

## Description
Add coverage for the Custom Serving Runtime Creation and Editing section. 

## Coverage
- View should change from `Creation` to `Editing` mode depending on the input prop.
- User should be able to upload a resource from a yaml
- The creation button should be disable if no code is present
- The creation button should be disable if there is no change in `Editing` mode
- Creation should fail if there's no name in the resource

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
