### ISSUE TITLE
[Bug]: PVC Size wrong when not explicitely specified on ODH Dashboard Config, pending PVC

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@DaoDaoNoCode 
The PVC Size Default in odh dashboard code is set to 20 in both backend and frontend code.

It should be taken from a default entry in odh dashboard config and not be set to a value explicitely in all sorts of places frontend and backend. There is always an auto-generated odh dashboard config, and pvc size is non-optional.

https://github.com/search?q=repo%3Aopendatahub-io%2Fodh-dashboard%20DEFAULT_PVC_SIZE&type=code

The error with number 20 leads to a PVC being pending forever, with event message saying "20 bytes is not a valid size"

Default should be set to 20Gi. 

This is only happening if no other value is speficied in OdhDashboardConfig odh-dashboard-config at notebook controller level. Also, I specified a storageclassname as there is no default storage class. That part worked well.

Good: Code for setting or changing the value via Settings - Cluster Settings - PVC Size and thereby setting pvcSize entry in odh dashboard config CR works correctly (the number is in there plus Gi postfix).

Since you set default PVC size in code, think about delivering that entry by default in delivered odh-dashboard-config and not relying on DEFAULT_PVC_SIZE anymore, unless that is necessary for local development.

That is, when auto-generating from dashboard code in case there is no odh dashboard config CR present yet.

i.e. 
notebookController
```
     notebookController: {
      enabled: true,
      pvcSize: 20Gi,
    },`
```
https://github.com/opendatahub-io/odh-dashboard/blob/73dc3ba5b1cc71fd852f0beeb8a85aa56ff438ce/backend/src/utils/constants.ts#L58

If you were to put it in here, you could remove it from backend and frontend code, having the default more centrally.

### Expected Behavior

PVC should bind with correct size and without errors even when no setting is specified at
notebookcontroller.pvcsize in odh dashboard config, as is the default.

**Comment by shalberd** [comment]
Yes, I think the same could be said for MIN_PVC_SIZE and MAX_PVS_SIZE. You do not seem to use them currently, but they do not have Gi postfix either.

**Comment by andrewballantyne** [comment]
> we have another issue with storageClassName not set when done from frontend code / Data science projects workbench creation perspective, should be easy to fix
> 
> [opendatahub-io/odh-manifests#840](https://github.com/opendatahub-io/odh-manifests/issues/840)

FWIW, this is unrelated. I'm sorry I'm being a broken record following you around tickets, but it's for posterity for the individual who picks up the issue.

**Comment by shalberd** [comment]
agreed, only loosely-connected in that it relates to storageclasses.

**Comment by shalberd** [comment]
this error only occurred in jupyter tile / backend as I tested without a set entry in OdhDashboardConfig
