### ISSUE TITLE
[Feature Request]: Test Custom Serving Runtime User Interaction

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1334]
## Type of test
  e2e Testing

## Description
Add coverage for a full interaction flow of the Custom Serving Runtime interaction

### Adding a new Custom Serving Runtime
1. As an admin user
2. Navigate to the Custom Serving Runtime section
3. Click in "Add a new Serving Runtime" button
4. Fill a new Serving Runtime and click the "Add" button
5. The page should navigate back to the Custom Serving Runtime List and a new Custom Serving Runtime should be added at the bottom of the list.

### Arranging and disabling Custom Serving Runtimes
1. As an admin user
2. Rearrange and disable some elements in the Custom Serving Runtime List
3. Create a new Project
4. Enable a Model Server
5. The list should only have the Serving Runtimes enabled
6. The list should have the elements sorted as the list

**Comment by dgutride** [comment]
Moving to closed in favor of new quality initiative work.
