### ISSUE TITLE
Create a documentation point for usage behind features

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1338]
### Feature description

Today we have some documentation on things like the [OdhDashboardConfig](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/dashboard_config.md), [general architecture of the Dashboard](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/architecture.md), and [BYON](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/byon.md) to name a few -- we should cover features we have in the dashboard and how their internal workings go on.

For instance, we do not describe how the Jupyter tile yields a certain flow or how self provisioner is needed for Data Science Projects. Custom Serving Runtimes and Data Science Pipelines are new features that also lack some information on usage.

We should have an introductory effort documented somewhere -- we can start with it in the Dashboard where the other doc items are.

**Comment by shalberd** [comment]
Recently, we had a pull request open for changes to the data science pipelines operator with regards to its requirements on Red Hat Openshift pipelines.

You could replace the Kubeflow screenshots at https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/README.md#using-the-graphical-ui with new screenshots and explanations from ODH dashboard pipelines.

**Comment by andrewballantyne** [comment]
> You could replace the Kubeflow screenshots at https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/README.md#using-the-graphical-ui with new screenshots and explanations from ODH dashboard pipelines.

@gmfrasca thoughts on this point? Do we want to include our new UI in your screenshots?
