### ISSUE TITLE
[Feature Request]: Rename kebab actions from "Clone" to "Duplicate"

### ISSUE THREAD

**Issue by vconzola** [opendatahub-io/odh-dashboard#1341]
### Feature description

Handle both scenarios:
- Model Serving (see below)
- Pipelines
    - Run page uses it for "naming" of the page -- x3: breadcrumb, page title, initial name of the run
    - Action from the Run Tables (kebab)
    - Action from the Run Details page (header options)

#### Model Serving Details

Under Serving Runtimes in the admin menu we have a kebab action for pre-installed runtimes called "Clone" that allows users to create a new runtime based on an existing runtime. We have a similar function in bias metrics configuration called "Duplicate". For consistency, these actions should have the same name. After discussion with content team, "Duplicate" is the preferred term. 

Note: No change to the actual behavior is required. It's just a text change in two places: the kebab menu action button and the title of the page that opens when the button is selected.

### Anything else?

<img width="1651" alt="Screen Shot 2023-06-06 at 1 50 51 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22823035/a9baea0a-0c10-4983-bcb8-72b6e88081ae">

**Comment by andrewballantyne** [comment]
@vconzola @kywalker-rh we use `Clone` in all things Pipeline Runs... should we rename that to Duplicate as well?

**Comment by andrewballantyne** [comment]
There are 6 references, 5 are Pipelines haha -- so we will need to update all of them. Should be easy.
