### ISSUE TITLE
[Feature Request]: Upgrade OAuth Proxy

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1345]
### Feature description

We should investigate upgrading our OAuth Proxy -- if others in the stack are using a later version than our current 4.8, we should consider aligning. There may be incompatibility if we go beyond what they are using, but a conversation should be had about upgrading with the wider ODH team.

**Comment by shalberd** [comment]
related to opendatahub-io/odh-manifests#760

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2450
