### ISSUE TITLE
[Feature Request]: Add "Edit Permissions" Kebab to Project Row

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1347]
### Feature description

A simple request for "Edit permissions" to be added to the dropdown for each row in the Project list view. 

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/2482dad6-ae40-44d1-a824-5aec1f41547b)

We will need to make sure they can edit the permissions (ie, the same check we have in Project Details).

**Comment by tarunsamanta2k20** [comment]
@andrewballantyne I'd like to look into this.

**Comment by Bingolast** [comment]
> @andrewballantyne I'd like to look into this.

heyyy i cant understand the issue can u explain it to me whats going on here i want to learn and want to have my first contribution can u help me

**Comment by andrewballantyne** [comment]
Hi @tarunsamanta2k20 and @Bingolast -- I'm happy to hear you both are interested in this issue and contributing. This issue is a bit on the edge of not being a good first issue -- but I labelled it as such as this is a good first issue that is also a feature. Might have been a bit over zealous of me to do so, so I apologize for the confusion. 

If you'd like to find easier issues, you can search our project for [good-first-issue label but also a bug](https://github.com/opendatahub-io/odh-dashboard/issues?q=is%3Aopen+label%3A%22good+first+issue%22+label%3A%22kind%2Fbug%22+).

---

Essentially in our application we have a set of Projects from OpenShift Console (that have `opendatahub.io/dashboard=true` label). Those get listed in the screenshot above.

Once you click on one of the projects, you should see a "Permissions" tab if you're an "`admin`" permission (see [K8s documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)) on the project. Thus you can modify the permissions to invite others into to collaborate on your project. If you're not an `admin` the tab should be hidden.

Essentially the request here is that tab is hidden inside the project and we want to help users navigate their way into the project and to that tab. 

- So you need to fire up the Dashboard in local dev environment
- You need to locate the code that shows the "Permissions" tab
- Understand `useCheckAccess` (how you ask K8s about the permissions of a user)
- And then render a kebab option only if they are `admin` (ie, look at the check to show the tab)
- The kebab option should just redirect to the tab on click

**Comment by tarunsamanta2k20** [comment]
@tiwariParth @Bingolast  Go ahead if you want to do it.
