### ISSUE TITLE
[Feature Request]: Report results of BYON URL validation in the modal

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1348]
### Feature description

Currently while importing a custom image from Dashboard, if the URL validation fails, the modal gets closed and user need to re-insert the data in a new Import session. That could impact user experience, especially if user inserted all the pkgs/software information.

Would it be possible to report the validation error in the form itself? Letting the user fixing the url format.

**Comment by andrewballantyne** [comment]
So this may be possible in time -- but it's not ideal today because the error is an async response from OpenShift. So we can "lock you in as we do it" but that's a whole UX flow in itself.

@DaoDaoNoCode you went through the testing scenarios and know more about this.
@vconzola is the designer on this and agreed to showing the error after the modal.

If this is possible, we would need a unique UX flow for this that sorta "sits and waits" -- may be a long wait. And then we'd need to support deletion of the image stream & tag if it is unsuccessful (which could also fail).

This may not be easily done nor do I expect a nice UX for this... but today the UX is "start over" -- so maybe there is room to improve. cc @kywalker-rh 

I'm inclined to close this as won't do -- but let us give it the shake it deserves to see if we want to invest in some other mechanism to give a better experience in the end.

**Comment by shalberd** [comment]
Hi, I agree with Andrew. You should validate the url in dashboard code before the imagestream yaml gets submitted to the openshift server. So as to not have dependencies on Openshift. Also, just tested this with the latest version of master: it is nice that source of a byon imagestream (tag.from.name) can also be in sha256 digest format  `myreposerver.com/myrepo/image@sha256s2929d91919`, cool thing. 

Now, whether the url is actually valid in the sense that it is externally correct and can be pointed to an image is up to the user.

**Comment by andrewballantyne** [comment]
Thanks for the input Sven, as well as the colloquial phrase haha. 

There is definitely limitations here for what we can do. Not sure there is an easy way to validate an image tag without sending it through the OpenShift infra. But we can try to validate the image structure BEFORE submit, as you mentioned - we are using regexp on the backend to split it apart. Might be worth investigating if we can do all that on the frontend and send the parts broken to the backend to have all the logic in once place 🤔 

This older area of the code is definitely unique and suffers a lot from our old (now deprecated) design of business logic in the backend.

**Comment by kywalker-rh** [comment]
I agree with the idea of making this experience slightly better, its not great that all the info you just entered could be deleted if you made a mistake in the url. If its especially difficult to validate the url, could we instead remember everything the user entered and allow them to go back to a pre-filled form if it fails? I could see that working as a link from a toast alert.

**Comment by andrewballantyne** [comment]
> I don't recall agreeing to the UX, because I didn't design it, but whatever.

@vconzola This is the conversation: [slack link](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1684178347040339?thread_ts=1684173221.066679&cid=C043A9D5DMW).

**Comment by vconzola** [comment]
OK. Thanks for reminding me - did not remember that conversation. I didn't do the original custom runtimes design, but I stand by the UX I recommended in Slack. Can we do that?

**Comment by andrewballantyne** [comment]
We have no real way to stop the modal -- we are creating the object -- if we want to wait some time for that resource to settle in the k8s system before closing the modal, that'll be a long time for the user.

We "hide" the image when it fails during that validation cycle as per the request of Vince in that slack thread.

So unless @kywalker-rh and/or @vconzola wants to lock up the modal (or something) to give the user a chance to "delete and recreate" the name... I think this is not a doable issue in the current infra of our backend (which uses OpenShift Console to have the resource to test it out).

**Comment by vconzola** [comment]
@andrewballantyne I'm not suggesting we hide the image in the notebook images table. I'm suggesting we hide invalid images from the end user when creating a workbench. Let me mock something up to show you what I'm talking about. I'm not doing a good job of describing it in words.

**Comment by bdattoma** [comment]
>  If its especially difficult to validate the url, could we instead remember everything the user entered and allow them to go back to a pre-filled form if it fails? I could see that working as a link from a toast alert.


as alternative to remember form value which can bring to another issue (i.e., I create a new runtime but the modal get auto-filled with older values, like it was happening with Data connections in the past), we could make the "Edit" action able to change the URL. I kind of remember there is an existing issue for it downstream. 

@andrewballantyne is the backend checking the image points to an existent and accessible domain? I thought it was just regex checking the URL. I inserted a fake URL but which met the expected regex and didn't get any issue in the dashboard. If you say it checks the accessibility of the URL, I didn't wait enough probably

**Comment by andrewballantyne** [comment]
@bdattoma it is my understand that it is validated by the image stream we create through the mechanisms of creating the tag in OpenShift Console. It's not done by our end. 

If you specified something that did not create an error but you knew to not be valid, my only question is what did you test with so I can test and repeat? I was fairly certain that's what was happening.

**Comment by shalberd** [comment]
Ah, so you look at the imagestream status-section?

![Bildschirmfoto 2023-06-14 um 21 00 44](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/eb4372f0-83b7-47a8-8f5d-c58d68103321)

**Comment by andrewballantyne** [comment]
@shalberd we already make use of the status message -- https://github.com/opendatahub-io/odh-dashboard/pull/1249

```
const getBYONImageErrorMessage = (imageStream: ImageStream) => {
  // there will be always only 1 tag in the spec for BYON images
  // status tags could be more than one
  const activeTag = imageStream.status?.tags?.find(
    (statusTag) => statusTag.tag === imageStream.spec.tags?.[0].name,
  );
  return activeTag?.conditions?.[0]?.message;
};
```

Looking back on this now, that seems somewhat odd logic. Maybe ImageStreams don't have conditions when they successfully find the source?

**Comment by shalberd** [comment]
Mmh,  yes, error relates to a string currently. Better would be, similar to the boolean isBYON, not looking at the message,
but a combination of type and status

https://docs.openshift.com/container-platform/4.10/rest_api/image_apis/imagestream-image-openshift-io-v1.html#status-tags-conditions

conditions?.[0]?.type        currently in OCP only  string "ImportSuccess"
conditions?.[0]?.status       i.e. for "ImportSuccess", there is a string here at status: Status of the condition, one of True, False, Unknown

**Comment by andrewballantyne** [comment]
@shalberd yes, that's the currently the only implemented logic. BYON is a bit of a patchwork of code. There definitely should be more logic around reading conditions... my best guess is @DaoDaoNoCode coded this originally when he found the conditions don't appear for successful image streams. We'll need to improve it.

**Comment by bdattoma** [comment]
was this solved in the last dev cycle of the custom notebook images? @andrewballantyne

**Comment by andrewballantyne** [comment]
@bdattoma no it was not.

**Comment by bdattoma** [comment]
> @bdattoma no it was not.

ok thanks. Are you planning on migrating this ticket to jira?

**Comment by andrewballantyne** [comment]
@bdattoma it is your issue, please feel free to migrate it.

**Comment by bdattoma** [comment]
I give it another try, and I'm not able to reproduce the issue anymore. If the URL has a wrong format, it complains inside the modal. If the URL actually doesn't exist, it complains after I submit the modal, but it keeps the data I've submitted

**Comment by dgutride** [comment]
Closing based on the last comment - @bdattoma  - please feel free to open in jira if this is a mistake.
