### ISSUE TITLE
[Feature Request]: Validate Serving Runtime when creating Custom Serving Runtime

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1353]
### Feature description

Currently we are validating the Serving Runtime once that we try to deploy it:

```javascript
export const isServingRuntimeKind = (obj: K8sResourceCommon): obj is ServingRuntimeKind =>
  obj.kind === 'ServingRuntime' &&
  obj.spec?.builtInAdapter !== undefined &&
  obj.spec?.containers !== undefined &&
  obj.spec?.supportedModelFormats !== undefined;
```

But this might be misleading as you can already select it, so when it fails it gives you a misleading creation message.

We should move this validation into the ServingRuntime creation flow.

**Comment by bdattoma** [comment]
since the number of mandatory fields for the validation is finite, could we report in the error message which are the invalid fields?

**Comment by lucferbux** [comment]
@Jooho @Xaenalt can we do a run down of the mndatory fields? I would love to hav your opinion/validation here to ensure we are casting a valid object!

**Comment by Jooho** [comment]
@lucferbux I took at this source and I think the 3 fields can be mndatory.
- container
- supportedModelFormats
- kind

`builtInAdapter` can be omitted when it is using a default puller like Watson runtime. @Xaenalt WDYT?

I agree with @bdattoma , it would be a good idea to show the error message when required fields are not specified.

**Comment by lucferbux** [comment]
Ok thanks, and yes, I'm gonna update that!

**Comment by lucferbux** [comment]
> I agree with @bdattoma , it would be a good idea to show the error message when required fields are not specified.

Yes, that's right, I'm gonna update the error message to reflect that one of the required fields is not present.

**Comment by Xaenalt** [comment]
Yeah, those fields should be the mandatory ones, I don't think we'd have a case where you could omit supportedModelFormats
