### ISSUE TITLE
[Feature Request]: Allow admin groups direct access to application items

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1355]
### Feature description

We need to get rid of our backend shim layer for all things Admin. Operator needs to take ownership: https://github.com/opendatahub-io/opendatahub-operator/issues/606

The dashboard today has a deprecated layer of business logic in the backend. This does a lot of help to get around permissions but that leads to a lot of problems. We need to bring this logic to the frontend and find a way to grant admins the permissions to do the role effectively -- directly.

Suggestions / topics to start talking:
* Create a role for all the permissions of mutating resources in the Dashboard project
* Admin groups setup in the admin section need to be granted access to that role (role bindings) -- on change of admin group, the role binding subjects needs to be updated
* On startup / upgrade -- we need to figure out how to apply this... perhaps on pod start, the service account applies the effort to existing admins
* Since this is per group(s) -- we should be fine for auto updates as the user list changes, but that should be tested
* Mutating the dashboard config outside of the Dashboard to add more groups / remove groups is unsupported and will not update until they mutate it again in the UI

**Comment by shalberd** [comment]
Could kubeflow profiles controller possibly help with that handling of RBAC and stuff?

**Comment by andrewballantyne** [comment]
@shalberd perhaps a poorly labeled ticket... Kubeflow has no direct impact and can't really help here. We currently rely on a lot of the backend Dashboard service account to do actions for the admin against resources in our Application Namespace. We should just properly grant them access, toss the backend logic to the frontend, and let the admin themselves do it directly.

We'll need to craft our own permissions based on our own needs. ImageStreams, OdhDashboardConfig, Custom Runtimes (Templates), etc... they all need to be controlled by the Admin directly through K8s as an admin of our application.

**Comment by lucferbux** [comment]
> Yep, agreed, I know the current approach and the efforts are very good indeed.
> 
> @LaVLaS @VaishnaviHire Mainly saying there could be kind of Profiles CRDs handled by a Kubeflow profiles controller (similar to how kubeflow notebook controller with some extensions (odh-notebook-controller) is already handling Notebook CRDs). My idea is more around: why not look at how kubeflow profiles controller upstream is handling RBAC on a namespace-level and in the medium term also include that downstream in ODH? I quote from upstream docs "[Internally, Kubeflow uses the Profile custom resource to control all policies, roles, and bindings involved, and to guarantee consistency](https://www.kubeflow.org/docs/components/multi-tenancy/design/). " Dashboard could then do assemble, update and so on of Profile CRs. That is a way bigger effort, though. https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/README.md

Yes, that's a great suggestion, I'm gonna ask @LaVLaS or perhaps @harshad16 about this, particullary this:

> On startup / upgrade -- we need to figure out how to apply this... perhaps on pod start, the service account applies the effort to existing admins

Fits perfectly the use case of a controller, in the future we'll end up developing our own controller so we can own this, but in the meantime, we can do a workaround in the frotnend or just use an approach similar to the kubeflow profiles controller. 
With our current setup, in an ideal world we would have:

- Role with all the permissions for a rhods admin
- A resource to list the groups added for rhods-admin/rhods-user
- A controller watching that resource and reconciling the state of the rolebindings based on changes

While thinking about this, I remembered that we have the rhods-user profile too... which in my opinion is even harder to implement right now, is there any conversation around that topic, I feel that the best thing to do is leverage the basic usage to k8s permissions now that projects are the main feature.

What are your thoughts on that @andrewballantyne @LaVLaS ?

**Comment by lucferbux** [comment]
Another thing that it might be worth mentioning is change the way we detect admins in the dashboard, we are currently using the isAdmin attribute, but we can simplify this if we follow a holistic approach to the hole admin thing, if being an admin means having admin permission in the odh operator's namespace, we can start using useAccessReview for this kind of checks.

**Comment by andrewballantyne** [comment]
`isAdmin` needs to speak for our UI elements that are not k8s driven. Seeing administrative pages when you're not an admin, despite having permissions, is a misnomer.

**Comment by lucferbux** [comment]
> `isAdmin` needs to speak for our UI elements that are not k8s driven. Seeing administrative pages when you're not an admin, despite having permissions, is a misnomer.

Mmmm ok, yes, that sounds fair. I would love to have a discussion with you later this week about this, I'm adding draft notes for this effort, there are a few details worth discussing and I think this should be a tracker issue, cause it can be easily split up in several efforts, I'm gonna try to have an overview for today so we can discuss it asap.

**Comment by harshad16** [comment]
> On startup / upgrade -- we need to figure out how to apply this... perhaps on pod start, the service account applies the >  effort to existing admins

I m not aware of the Kubeflow profile controller and whether it could help us with the following pattern.
Will investigate and provide the details.

**Comment by andrewballantyne** [comment]
It should be noted that permissions for users is quickly looking like it will be not a Dashboard thing. The Operator rework stuff is in motion now, and we need to investigate possibilities. 

- See https://github.com/opendatahub-io/odh-dashboard/issues/1475 for more information

**Comment by andrewballantyne** [comment]
I'll create something on the Platform team to look into owning permission controls. This ticket can be for cleaning up that effort after the fact to move the logic back to the frontend and use the Pass Through API.

**Comment by andrewballantyne** [comment]
For notification posterity, the issue on the Platform team: https://github.com/opendatahub-io/opendatahub-operator/issues/606

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1103
