### ISSUE TITLE
[Feature Request]: Add descriptions to ISV CRD attributes

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1360]
### Feature description

Right now the Resource Definition of the ISV objects that we use for the dashboard are not documented anywhere.

This can create confusion in collaborators that would want to contribute with their ISV definitions.

We need to either add description for the CRDs or create a documentation for better usage:

- [OdhApplication](https://github.com/red-hat-data-services/odh-deployer/blob/main/odh-dashboard/crds/odh-application-crd.yaml)
- [OdhDocument](https://github.com/red-hat-data-services/odh-deployer/blob/main/odh-dashboard/crds/odh-document-crd.yaml)
- [OdhQuickStart](https://github.com/red-hat-data-services/odh-deployer/blob/main/odh-dashboard/crds/odh-quick-start-crd.yaml)

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2960
