### ISSUE TITLE
Create Custom Resources to track Storage Classes metadata

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1362]
### Goal

Create Custom Resource to track all the Storage Class metadata such as description, name, enablement...

### Dependency issue

No dependencies

### Itemized goals

Create a Custom Resource for the dashboard that allows:

* Link the CR to an existing Storage Class
* Add Display Name
* Enablement of the resource
* Select if the resource is the default one
* Date of last modification

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/1363

### Mocks

- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/8VkRW3O

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1104
