### ISSUE TITLE
Storage Classes Table

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1364]
### Goal

Create a table to display the available Storage Classes with relevant information such as name, openshift name, enablemnt...

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1363
* https://github.com/opendatahub-io/odh-dashboard/issues/1363

### Itemized goals

* Render a table that displays all the Storage Classes in the Cluster
    * Make use of the generic table component
    * Design reasoning:
       * Display name, Openshift storage class and last modified fields must be sortable
       * We need to define the Openshift default storage class
*  Cells must display:
   * Display name
   * Openshift storage class
   * Enable
   * Default
   * Last modified
* Default logic:
   * Only enabled storage classes can be the default one
   * Ther should only be one default storage class at a time
   

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/1365
- https://github.com/opendatahub-io/odh-dashboard/issues/1366

### Mocks

- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/8VkRW3O
- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/27max8l
- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/MmeDl1a
- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/5nxl15L

**Comment by lucferbux** [comment]
<img width="246" alt="Screenshot 2023-06-12 at 15 26 12" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/e0dc46f2-faaa-4f6a-b9bc-73d0505f85ac">

I assume this is a label targeted only for the default Openshift storage class.

The other assumption is that if there's no default storage class it will default to the Openshift default one.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1106
