### ISSUE TITLE
Edit for Storage Class Table Row

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1366]
### Goal

Implement edit mode in each row for the Storage Class Table

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1364

### Itemized goals

- Add `edit` action in the kebab menu for the row
- Modal for editing mode:
   - Ability to edit display name
   - Ability to display description 

### Mocks

- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/5nxl15L
- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/bLrJAj4

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1108
