### ISSUE TITLE
Select Storage Classes in Workbench creation

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1367]
### Goal

Implement storage class selection in workbench creation

### Itemized goals

- Add customHook to fetch storage classes and CR
- Add the customHook to the Project Context
- Ability to select  available storages in workbenches
   - List all the available storage classes
   - Auto-select the default one
   - If only one storage class available, disable the dropdown

### Mocks

- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/EeqZzD2
- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/j4VakGz

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1109
