### ISSUE TITLE
Display storage class selected in Workbenches

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1368]
### Goal

Display the storage class selected for the workbenches deployed in a Project

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1367

### Itemized goals

- Get the storage class that was selected for the workbench
- Display the CR info about it
- Update the Workbench table to display the information

### Mocks

- https://www.sketch.com/s/f6fa37fc-0c25-49e3-8b24-ecaf981433a8/a/MmeRnqz

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1110
