### ISSUE TITLE
Add accelerator table

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1373]
### Goal

Create a table to list available accelerator devices including the device indicator, display name, descriptions, enablement, and last modified date

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1372

### Itemized goals

- Render the following columns: Device identifier, display name/description, ennoblement switch, date last modified, action button
- Columns (except for action column) must be sortable
- include help icons where present in the docs
- should include pagination
- ellipsis action button should include: edit, delete
- hook to fetch accelerator CRDs
- Display a label next to accelerator name for Nvidia GPU and HBU
- alert to notify if migrated gpu was generated (press X to go away or on save of profile ??)

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/1374
- https://github.com/opendatahub-io/odh-dashboard/issues/1375
- https://github.com/opendatahub-io/odh-dashboard/issues/1376
### Mocks

https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/P1R0eVL

**Comment by Gkrumbach07** [comment]
### UX Needed (not a blocking UX request)
@yannnz 

the mocks still show that the accelerator table in the admin panel should have labels for Nvidia GPUs and HBUs. However i recall a conversation where we said that we dont want to hard code a relationships between accelerator and display label. What are your thoughts on this. Pic for ref

![image](https://github.com/opendatahub-io/odh-dashboard/assets/12587674/2a1a7172-0a4c-40ee-8632-81e1f9927c23)

**Comment by yannnz** [comment]
@Gkrumbach07 @andrewballantyne Are we planning to support toleration? It can be an opportunity to add the Group feature to allow the admin naming the labels as I proposed before: https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/L4bvgpy . If the admin can customize group names, it will not require us to hard code the labels.  cc: @xianli123

**Comment by andrewballantyne** [comment]
> If the admin can customize group names, it will not require us to hard code the labels

There will be no hardcoding of anything in the UI now that we have Accelerator Profiles. Only hardcoded scenario is our migration script to move them into AcceleratorProfiles with Nvidia GPU.

As for "supporting versions of cards" -- I think we still need to figure out some stuff. See my [req comment](https://docs.google.com/document/d/1m1dFOdRnSF1BSt2dT8F9Nxd6YC1mOTS4vX05G9YSEds/edit?disco=AAAA8Md0-Ko) where I ask @Xaenalt what our options here are.

IMO though, groups in themselves can be part of this effort, we have the runway to do it right as we want it. I do imagine this is optional for the user though.

**Comment by yannnz** [comment]
@andrewballantyne @Gkrumbach07 Please help to review the design for Tolerations and Groups: https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/JAW7zxr

**Comment by xianli123** [comment]
@dpanshug Here is [the latest design](https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/prototype/86C650A6-010A-4C88-9510-7BCD2FA65540/a/86C650A6-010A-4C88-9510-7BCD2FA65540) of the Accelerator profiles table fyi.
