### ISSUE TITLE
Accelerator table filter and action bar

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1374]
### Goal

Be able to search and filter the accelerator table by its columns

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1373

### Itemized goals

- Columns to filter on:
   - name
   - identifier
- Add new device button (leave the action empty for now)

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/1376

### Mocks
https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/prototype/86C650A6-010A-4C88-9510-7BCD2FA65540/a/4EB7F6AF-D9FA-4418-B6D8-03AFCF9338A2

**Comment by Gkrumbach07** [comment]
@yannnz what filters do you want available to the user. Right now I have the list of:
- device name
- device identifier
- enablement
- last updated date

But do you also want:
- device description
- device category i.e: Nvidia, Habana

**Comment by yannnz** [comment]
Discussion happend on sketch: https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/P1R0eVL?annotation=afcde2c4-1058-45a4-9dac-74d06a404561

We might need to revisit once we restart this issue.

**Comment by yannnz** [comment]
Discussion happened in Sketch comments: https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/P1R0eVL?annotation=afcde2c4-1058-45a4-9dac-74d06a404561
