### ISSUE TITLE
Accelerator add/edit modal

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1375]
### Goal

Create a modal that allows admins to add new accelerator devices and edit them

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1373

### Itemized goals

- include the fields:
   - Device name (required)
   - Identifier (required)
   - description
   - enabled (default is false)
   - tolerations list (needs UX)
- be able to edit a device and all its fields (including tolerations)
- open edit mode from ellipsis action button on each row
- open add mode from button on top 

### Mocks

https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/AZnp2MY
https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/8VwQZo8

**Comment by Gkrumbach07** [comment]
### Needs UX
@yannnz

The create/edit modals for accelerators in the admin panel are missing the input for tolerations. The CRD allows for an array of tolerations, which are defined in [here](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml#L37-L54). Can you update the mocks to include a way to set and edit those tolerations

**Comment by Gkrumbach07** [comment]
I am going to start the dev on part of this as most of the UX is done besides groups and tolerations

**Comment by xianli123** [comment]
Hi @Gkrumbach07, this is [the final design](https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/prototype/3CD8C088-E132-4FD9-99CE-CE5560ACC440/a/3CD8C088-E132-4FD9-99CE-CE5560ACC440) of the **Toleration part** in the accelerator creation page. I will invite @kaedward to help us review the wording and optimize the text. 

Hi @kaedward , I left some comments on the mockups and tagged you. Please take a look and help us review the wording.

Thanks in advance @kaedward @Gkrumbach07!

**Comment by xianli123** [comment]
Hi @Gkrumbach07 I updated [the accelerator profiles table](https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/prototype/86C650A6-010A-4C88-9510-7BCD2FA65540/a/86C650A6-010A-4C88-9510-7BCD2FA65540) based on @yannnz 's designs. The main change is that we removed the Groups column because the group feature has been removed from the accelerator creation process.
