### ISSUE TITLE
Accelerator delete modal 

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1376]
### Goal

Create a accelerator delete modal with the ability to bulk delete and cascade delete compatible images

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1375

### Itemized goals

- Confirm deletion by typing the device name i.e. _A100_
- follow how other delete modals work
- use delete modal component that is made already

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/1375

### Mocks

- https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/prototype/86C650A6-010A-4C88-9510-7BCD2FA65540/a/ED714EF1-7AA1-4C9F-A7D2-63AF6372A804

**Comment by Gkrumbach07** [comment]
### UX Needed
@yannnz

This is for the delete modal for the accelerator admin panel. Is [bulk deleting](https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/vRLwOLe) still a desired function? If not, should the table still be checkboxes?

**Comment by yannnz** [comment]
@Gkrumbach07 If there are not many accelerators practically, we can remove the bulk deleting. And we will not need the checkboxes. I will update the design. cc: @xianli123

**Comment by xianli123** [comment]
Hi @yannnz @Gkrumbach07 Based on the discussion and requirements, I updated [the original design](https://www.sketch.com/s/d8550d2f-fae4-44fd-82df-9f400563d459/a/3oxP1aD) and removed the bulk deletion. Here is [the design link](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1601%3A89735&type=design&node-id=1601-89813&viewport=419%2C293%2C0.13&t=DAp8L6LDBPessy0Z-1&scaling=scale-down&starting-point-node-id=1601%3A92679&mode=design) for reference. Please take a look and leave your comments if you have any suggestions for the design. Thanks!
