### ISSUE TITLE
[Bug]: Install the Pipelines Operator message in GUI when in fact Red Hat Openshift Pipelines installed

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1379]
### Summary Solution

Added to help the assignee know where to go with the solution.

See the summary comment below -- https://github.com/opendatahub-io/odh-dashboard/issues/1379#issuecomment-1591566202

---

Original issue reported by Sven.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a message when clicking on the Data Science Pipelines section:

To use pipelines, first install the Red Hat OpenShift Pipelines Operator.

![Bildschirmfoto 2023-06-14 um 13 01 26](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/db6bade3-4d5c-4085-a773-a8ea151c65ed)

https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/dependencies/PipelinesDependencyMissing.tsx#L39

https://github.com/search?q=org%3Aopendatahub-io%20%22startup-pipeline-state%22&type=code

when clicking on the button, it leads to a namespace "startup-pipeline-state", without the Openshift pipelines operator.

**Neither Project startup-pipeline-space nor namespace startup-pipeline-state exist on the Cluster.**

Is the dependency check too much downstream / RHOSDS-specific?

![Bildschirmfoto 2023-06-14 um 13 03 15](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/e2dbc0ff-9eee-42d3-aaf1-e4515892f177)

However, the Openshift Pipelines operator is installed in openshift-operators as a global operator.

![Bildschirmfoto 2023-06-14 um 13 04 23](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/0c3dcbd9-618e-4b6f-af72-db78c37321bc)

Is the Red Hat Openshift Pipelines operator not supposed to be installed that way? I looked at https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main#pre-requisites

Openshift Pipelines operator 1.8.x was installed while dashboard pods running.

### Expected Behavior

No error message or more specific one

### Steps To Reproduce

master branch build of odh-dashboard
install odh with data-science-pipelines in kfdef
install Red Hat Openshift Pipelines operator in openshift-operators in mode "all namespaces".

### Open Data Hub Version

1.6.0
1.6.0 with master branch build of ODH Dashboard

### Anything else

data science project exists

```
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: mydsproject
  labels:
    kubernetes.io/metadata.name: mydsproject
    modelmesh-enabled: 'true'
    opendatahub.io/dashboard: 'true'
...
```

**Comment by shalberd** [comment]
![Bildschirmfoto 2023-06-14 um 15 07 35](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/6451f6d6-6b5c-4c3e-8bce-8950befb7089)

**Comment by shalberd** [comment]
The "go install the operator link" at https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/dependencies/PipelinesDependencyMissing.tsx#L39 should be changed, has a wrong namespace startup-pipeline-state instead of openshift-operators.

`${url}/operatorhub/ns/startup-pipeline-state?details-item=openshift-pipelines-operator-rh-redhat-operators-openshift-marketplace`

i.e. currently

`${url}/operatorhub/ns/<operatornamespace>?details-item=<operatorname>-<catalogsourcename>`

Also, in mirrored environments (on-prem, airgapped) there are often custom catalog sources

https://docs.openshift.com/container-platform/4.10/operators/admin/olm-restricted-networks.html#olm-creating-catalog-from-index_olm-restricted-networks

So for going to the details page of a certain operator, to install it or view the status, it is most likely always openshift-operators for the namespace and a custom catalogsource name is possible. One could get the catalogsources via openshift api (`oc get catalogsources -n openshift-marketplace`) and regex-match or starts-with match the correct one
 
![Bildschirmfoto 2023-06-14 um 17 11 08](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/2b74ba50-8a57-4345-a995-63d20413501a)

not sure if it's worth it, though, since the name can be anything.

i.e. in your case, the catalogsource name was

`rh-redhat-operators-openshift-marketplace`

and in our case, our cluster-admins named the catalogsource / mirrored index

`redhat-operator-index`

**Maybe including the link is not even necessary**, as not all admins of data science projects also have the right to view, lest even install or modify, operators in openshift-operators. A text might suffice, e.g.

The OpenShift Cluster must have OpenShift Pipelines 1.8 or higher installed. We recommend channel pipelines-1.8 on OCP 4.10 and pipelines-1.9 or pipelines-1.10 for OCP 4.11, 4.12 and 4.13. Instructions at https://docs.openshift.com/container-platform/4.12/cicd/pipelines/installing-pipelines.html#op-installing-pipelines-operator-in-web-console_installing-pipelines.
Ask your cluster-admin for install.

Taken from

https://github.com/opendatahub-io/data-science-pipelines-operator/tree/main#pre-requisites

**Comment by shalberd** [comment]
Also, regarding how the serviceaccount checks whether the operator is installed

https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/types.ts#L68

you'd also have to ensure somehow that the check works for the operator, regardless of which catalog source it was installed from.

**Comment by andrewballantyne** [comment]
Thanks @shalberd for the detailed breakdown.

Okay, I think the solution for this ticket probably should be:
1. [Backend] Merge the blankDashboardConfig right after it is pulled from the API -- all code should use our defaults baked in anyways (remove it from the get config call as it will be always merged now)
2. [Frontend] Update the URL used for redirect
    1. Try to use the "all projects" url; OperatorHub doesn't really work on namespaces per se, so no real reason to do that
    2. Change the search from trying to select the tile to doing a search (eg. `?keyword=red+hat+openshift+pipelines`)
4. [Frontend] Change the permission understanding for the install button on the dependency page
    1. Using check access, determine if they can create ClusterServiceVersions (CSVs) -- if they can't, they can't install the operator, hide the button away (this is done by `isAdmin` today, remove that logic)
    2. If we hide the button, we should provide text to lead them to contacting their admin (wording should be vetted by UX)

I think that'll get us to a nicer working effort so the operator can be used. Any objections to this solution @shalberd?

We have https://github.com/opendatahub-io/odh-dashboard/issues/1385 to chase down if we can detect the operator name better for the cluster-admin / CSV creator.

**Comment by shalberd** [comment]
Points 1 to 3 sound very good indeed. 

I added a way to detect the operator in a comment in #1385
