### ISSUE TITLE
[Feature Request]: make data connection for S3 model sources AWS-unspecific

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1381]
### Solution

Implementation details can be found in https://github.com/opendatahub-io/odh-dashboard/issues/1381#issuecomment-1607711576

---

### Feature description

Currently, at least the Workbench creation Data Connection GUI for model servers (to get model files from) is highly AWS S3 specific. I don't know whether that is intended, as models could also live in S3 compatible object storage on a company-internal server in a bucket, e.g. IBM Cloud Object Storage. 

Certificate trust is also an issue when, there are ways with trusted-ca-bundle configmap to get all trusted certs and use them as trusted when making https requests.

### Anything else?

![Bildschirmfoto 2023-06-14 um 14 34 59](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/7a6e7d76-b826-4d9c-812a-44e57c0a19db)

@Joohoo Unclear whether there is a connection with model-mesh as well, as dashboard is just the GUI side of things.

Pep Turró Mauri @codificat of Red Hat once created an issue for that, too, I think, not related to the GUI, but still

https://issues.redhat.com/browse/RHODS-8813

**Comment by DaoDaoNoCode** [comment]
cc @andrewballantyne

**Comment by andrewballantyne** [comment]
I think I found it.

UX ticket
- https://github.com/opendatahub-io/sig-ml-developer-experience/issues/6

We'll treat this ticket as our side of the effort to follow through with what we need to do to achieve that across the board with our data connections.

**Comment by andrewballantyne** [comment]
Technical background... @shalberd 

We did this originally in this design as a first stage for DS Projects. We used those keys at that name for injecting into Notebooks as it was a suggested naming structure. Technically we do not need to do that today I believe. We'll just need to understand the flows for the JupyterLab notebooks and how they use it before we make any stance. I'll try to bring this up at our Thursdays UX meeting. Might be able to get information on any internal workings that might be impacted by this change.

**Comment by andrewballantyne** [comment]
The solution here will be to:

* Reword all the Data Connection fields
    * `AWS_ACCESS_KEY_ID` => `Access key`
    * `AWS_SECRET_ACCESS_KEY` => `Secret key`
    * `AWS_S3_ENDPOINT` => `Endpoint`
    * `AWS_DEFAULT_REGION` => `Region`
    * `AWS_S3_BUCKET` => `Bucket`
* Remove the default values
    * Make `Endpoint` and `Region` required fields since they lose their defaults
* This should be done to the following areas:
    * Data Connections modals
    * Model Serving modals
    * Pipeline Server Create modal (will become partially obsolete with https://github.com/opendatahub-io/odh-dashboard/issues/1214)

The underlying values that get injected into the Notebook and are passed to Model Serving will remain the same (prefixed with AWS). This is something we cannot change at this time. This is purely a visual set of changes.

**Comment by andrewballantyne** [comment]
> @andrewballantyne @guimou There might not always be a region field required, at least not when using on-prem [IBM Cloud object storage](https://cloud.ibm.com/docs/cloud-object-storage/hmac?topic=cloud-object-storage-uhc-hmac-credentials-main), or a mini-solution like Ceph or Minio. Whether the region field makes a diffference at all when not actually needed I don't know, it does not look like it though in [existing code behind](https://github.com/andrewballantyne/odh-dashboard/blob/main/frontend/src/pages/projects/dataConnections/const.ts)

Good point -- let's not my region required -- I recall that being the case when using Minio now that you mention it.

**Comment by shalberd** [comment]
in pipelines, by design secrets are used to read access key id and access key from an Openshift secret, context [Elyra pipeline defs](https://github.com/opendatahub-io/odh-dashboard/pull/1419/files)

Here is model-serving, are the values put into the env var directly or via an Openshift secret? That is, is an Openshift secret created with the info from the fields?

**Comment by andrewballantyne** [comment]
> in pipelines, by design secrets are used to read access key id and access key from an Openshift secret, context [Elyra pipeline defs](https://github.com/opendatahub-io/odh-dashboard/pull/1419/files)

That's a different secret -- look at Create Pipeline Server Modal (the DSPA creation)

> Here is model-serving, are the values put into the env var directly or via an Openshift secret? That is, is an Openshift secret created with the info from the fields, especially access key id and access key, to be used later?

Data Connection values are the same throughout our UI forms (model serving or not) and should be updated at the same time (with the [solution I noted here](https://github.com/opendatahub-io/odh-dashboard/issues/1381#issuecomment-1607711576)). They all create a secret under the hood, something like `aws-connection-something`. This content will be not impacted by this change, as we are just improving the visual representation of making a data connection.

**Comment by jedemo** [comment]
Would like to raise the priority for this. Have received feedback on this from multiple sources.
