### ISSUE TITLE
Enhance validation and defaults of bias metric config form

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1383]
We need a few improvements to the bias metrics config form:
* The default value populated for the"violation threshold" field should be based on the user selected type of the bias metric config. Reference the defaultDelta values specified here: https://github.com/opendatahub-io/odh-dashboard/blob/694ada2446c53e48364f6c0f8e7020af79164435/frontend/src/pages/modelServing/screens/metrics/const.ts#L26-L71
* DIR threshold delta has an acceptable range of 1 >= x >= 0 - this needs to be validated (SPD does not have this constraint).
* Add tooltips to configure form

* Also when duplicating a bias metric config, the "Metric name" field should be prepopulated with "Copy of x" where x is the name of the config being duplicated.

--
* Tracker: #1127

**Comment by DaoDaoNoCode** [comment]
Do we also want to add tooltips and descriptions in this issue? They are all the enhancements for the configuration form. Or do you want to create a separate issue to trace that? @alexcreasy

**Comment by alexcreasy** [comment]
@DaoDaoNoCode Oh yeah, meant to put that in, updating now :)
