### ISSUE TITLE
[Investigate]: Determine how to best locate a dependant operator

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1385]
### Feature description

Today, we try to link out to the Red Hat OpenShift Pipelines Operator through a link.

`...?details-item=openshift-pipelines-operator-rh-redhat-operators-openshift-marketplace` ([code](https://github.com/opendatahub-io/odh-dashboard/blob/383bf278c748aaae99915093a2e83deee4c70bb0/frontend/src/pages/dependencies/PipelinesDependencyMissing.tsx#L39))

This assumes the catalog in which the operator sits, is called `redhat-operators-openshift-marketplace` -- but that's not always the case.

Can we search the catalog sources and determine how to properly find and link to the operator?

### Anything else?

This needs to have considerations for performance before we accept any solution. The solution may end up being we can't do this cleanly and cheaply enough.

**Comment by shalberd** [comment]
The operator serviceaccount has Clusterrole RBAC for get, list, watch ClusterServiceVersions and Subscriptions. So the operator could easily check the status-section of the subscription to determine if the operator is installed. 

https://github.com/opendatahub-io/odh-dashboard/issues/1379#issuecomment-1591511302

**Comment by andrewballantyne** [comment]
Reviewed by the Advisors, we feel this is good enough for now. If we additional need here, we can address those as they appear.

We'll keep the name search for now.
