### ISSUE TITLE
[Bug]: Image Error has Misleading Enabled State

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you put an registry & image path into the BYON custom images modal and it doesn't reference a valid tag it will eventually error out on the async nature of OpenShift validating the image. 

We then show the error on the list page and hide the image from the selection in creating a Notebook. However, the admin view it still looks enabled and may cause confusion.

### Expected Behavior

What we should do is, on render of the custom notebook table, we flip the toggle to disabled and then disable the toggle so they cannot re-enable it. The error should provide the context. 

This will give a better impression that it is not "enabled" with the error.

### Steps To Reproduce

1. Be an admin
2. Create a new custom notebook image with an invalid tag
3. Wait for the error to appear

### Open Data Hub Version

```yml
Dashboard: v2.11.0
```

**Comment by lugi0** [comment]
Tracking downstream in: https://issues.redhat.com/browse/RHODS-9384

**Comment by DaoDaoNoCode** [comment]
This issue will be fixed with the refactoring of Custom Notebook Phase 1 #1254

**Comment by manosnoam** [comment]
Verified on RHODS 2.4:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/6ff864e3-3d57-40e0-80f5-468889945561)
