### ISSUE TITLE
[Feature Request]: Remount Top-Level Route Components On Nav Click

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1389]
### Feature description

When you click on a navigation item, the effect does not remount the component because React Router does not sense any url change, React senses no component change, and thus no "refresh" power is given.

We have been asked by UX to allow a refresh on click of the navigation but I don't want to see this as a browser refresh.

I suspect what we'll have to do here is somehow implement a `<RouteComponent key={...} />` sorta of change. React uses `key` props as a means to keep lists performant. However, it can be used on a static component to force a drop and remount. 

We'll need to think on how to get this functionality in for only the top-level route components. Perhaps a custom `TopLevelRoute` component that encapsulates this functionality?

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2449
