### ISSUE TITLE
Add Backend REST API unit testing

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#139]
Currently we do not have Unit tests to test our backend API.  Using Fastify HTTP injection and jest we would like to add unit tests to verify our REST API.  Unit testing should test all the routes that we have in our REST API.   The following article details how to setup Fastify and Jest for REST API testing: https://jaywolfe.dev/blog/setup-a-fastify-app-with-jest-tests-the-right-way/

**Comment by andrewballantyne** [comment]
This will become obsolete the more we adopt #259 -- once it merges. I'm going to close this issue as I don't think the effort will be worth starting testing that won't last in the current architecture redesign.
