### ISSUE TITLE
[Feature Request]:  Switch to kubernets_secret option in place of user_credential option on elyrasecret

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/odh-dashboard#1415]
### Feature description

Currently, we are using the  [cos_auth_type: 'USER_CREDENTIALS'](`https://github.com/opendatahub-io/odh-dashboard/blob/736bf82719fdfc29547277d99247fae1f3d49fb2/frontend/src/concepts/pipelines/elyra/utils.ts#L61) which is allowing the creds to be uploaded as env var in the elyra export pipeline. In place of the USER_CREDENTIAL option , we would like to switch to `KUBERNETES_SECRET` type. so the export pipeline references kubernetes secret instead of simple env var,

### Describe alternatives you've considered

switch of the export functionality, which is not recommended as it is a feature.

**Comment by andrewballantyne** [comment]
Triaging this without the team as it is critical for the release at the end of the week. Spoke with @harshad16 about this and the solution looks good to me. Once we test it with the generated images from the PR, we can look at merging it.

**Comment by andrewballantyne** [comment]
> By the way, security-architecture-wise, what do you think about the discussion on whether putting env vars coming from secret values into the pipeline?

@shalberd are you considering the solution where we don't provide the Data Connection information as env vars to the Pod? 

We mount all our secrets the same way against the workbench 🤔

**Comment by shalberd** [comment]
> are you considering the solution where we don't provide the Data Connection information as env vars to the Pod

In airflow and its kubernetes pod operator ... no, not immediately, but medium-term, possibly yes. Do you have a CISO or someone in touch with infosec who could have a look at my comment? As mentioned, it is not an immediate issue, in fact, up to now, even Airflow passes secrets into pods via env vars only. But at Airflow, I think the discussion raises a valid point.
