### ISSUE TITLE
[Bug]: GPU Error shows up on Non-GPU Clusters

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="543" alt="image" src="https://github.com/opendatahub-io/odh-dashboard/assets/8126518/0721d081-ead6-4e17-9dee-450d666f6dc9">
<img width="506" alt="image" src="https://github.com/opendatahub-io/odh-dashboard/assets/8126518/c1f0116d-7759-4469-9aac-a19b2662aaaa">

On some clusters, we get an error on the Workbench page in relation to GPUs. This was reported on the Dev Sandbox as well as in another RHODS cluster. 

It's unclear what the actual cause is -- but it looks to be a 404 from the backend `/api/gpu` endpoint. Which means it likely is one of the many calls that happens on the backend that causes it to happen. The backend code is not safe from promise fails in k8s calls so it could just be a fail to fetch some details.

### Expected Behavior

Silently stop 404s and just say there is no GPUs on this cluster.

### Steps To Reproduce

Unknown.

### Open Data Hub Version

```yml
Dashboard: v2.11.0
```

### Anything else

This will be hard to reproduce -- best guess is it can't find the scale machines. 

Investigation of the GPU endpoint will be needed to see if there is some triggering factor. There are several calls that are unbounded and can throw into a non-existent catch which turns it into a thread breaking error.

**Comment by Gkrumbach07** [comment]
This issue is will no longer relevant as the `api/gpu` backend endpoint is deprecated in favor for accelerator profiles

tracker for accelerators merging into main:
- https://github.com/opendatahub-io/odh-dashboard/issues/1450

**Comment by Gkrumbach07** [comment]
This can be closed with the completion of:
- https://github.com/opendatahub-io/odh-dashboard/issues/1894
this issue will remove the deprecated gpu endpoint
