### ISSUE TITLE
[Bug]: Pipeline Runs - Handle references better

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We currently have functionality to find `results` in another task when viewing the sidebar of the selected run node. But this is under performing.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/27a6f2bd-63b0-4116-9982-08582c263a86)

### Expected Behavior

We need to be able to handle `parameters` in the task, and other concepts.

Tekton references are documented here: https://tekton.dev/docs/pipelines/variables/

References should appear as references in the Pipeline Details page.
References should appear as the value (if it exists -- if not, remains the reference) in the Pipeline Run Details page.

### Steps To Reproduce

1. Create a Pipeline in DSP that contains various references
2. Run the Pipeline

### Open Data Hub Version

```yml
v2.11.0
```

**Comment by alexcreasy** [comment]
I've been doing some research into the Tekton params and I _think_ we may not need any of the other concepts beyond `parameters` and tasks for this. @pnaik1 's solution could be easily cleaned up to address just this basic use case very effectively.

However, other things to address are whether we need to support additional syntax that the document seems to imply is possible, i.e. array style notation as well as dot notation e.g. `${params.foo}` v `${params["foo"]` and also whether we need to support index notation like `${params[1]}` amongst other notation.

I'd like to discuss this with @andrewballantyne on Monday to clarify how much needs to be done on this issue.
