### ISSUE TITLE
[Feature Request]: Create a generic odh modal component

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1428]
### Feature description

We need to create a generic odh model to wrap up the PF Modad component, cause we are aiming to add more functionality across all of our modals, such as accesibility and navigation like in the [Delete Modal](https://github.com/opendatahub-io/odh-dashboard/issues/1387).

There would be follow up issues to replace all the Modals in our dashboard with this generic component.

**Comment by xianli123** [comment]
Hi @lucferbux I am going through all issues related to Projects. Do you need UX design for any work on this issue?

**Comment by andrewballantyne** [comment]
@xianli123 no this is tech debt... no UX needed.

**Comment by xianli123** [comment]
@andrewballantyne Got it. Thanks!

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2402
