### ISSUE TITLE
[Feature Request]: Replace PF Modals outside DS Projects and Admin Panels

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1431]
### Feature description

Follow up of https://github.com/opendatahub-io/odh-dashboard/issues/1428
Continuation of https://github.com/opendatahub-io/odh-dashboard/issues/1429 and https://github.com/opendatahub-io/odh-dashboard/issues/1430

We have old implementations of PF Modal in several places of the dashboard outside DS Projects and Admin Section, replace these instances with the generic ODH Modal.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2399
