### ISSUE TITLE
Update all text items and field labels on Notebook images table

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1432]
### Goal

Make sure the text items and fields the same as the mock up listed as below

### Dependency issue

Tracker: https://github.com/opendatahub-io/odh-dashboard/issues/1254

### Itemized goals

- Change the nav item title
- Change the page description
- Use the generic table component
- Add a helper tooltip for the `Enable` field on the custom image table
- Change the expandable section UI to align with the design

### Aspects continued elsewhere

Update all text items and field labels on Notebook images modals (Import, Edit, Delete) - ticket TBD

### Mocks

![image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/dad5cac5-35b9-4348-b621-19d9e3c8a862)

**Comment by DaoDaoNoCode** [comment]
We will not add `To change the order...` in the description before we reach phase 2 because we will not implement the drag and drop feature in phase 1. cc @vconzola @kaedward Can we just set the description as `Manage your notebook images.` when we don't have drag and drop for now or do you think there are more descriptions we can add?

**Comment by vconzola** [comment]
@DaoDaoNoCode Yes, omitting the rest of the description, leaving "Manage your notebook images." is fine for phase 1.

**Comment by DaoDaoNoCode** [comment]
@vconzola Cool, thanks. BTW, what do we want to search in the filters? I think the `Name`, `Description`, and `Provider` should be enough, right?
