### ISSUE TITLE
Update all text items and field labels in modals

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1433]
### Goal

Make sure the text items and fields the same as the mock up listed as below

### Dependency issue

Tracker: https://github.com/opendatahub-io/odh-dashboard/issues/1254

### Itemized goals

- Modify the fields in the manage notebook images modal to align with the mockup (title, field label, empty state, helper text)
- Add a helper tooltip for `Image location` (the field label is `Repository` now, tooltip content TBD)
- Refactor the adding packages and adding software part. Now it's 2 icons instead of 3 icons with different user interactions design
- Use the generic delete modal to delete the custom notebook images

### Mocks

![image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/177b6111-b165-4041-9a38-494662b5838e)
![image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/1f4b4bd1-1437-4898-bf2b-b92499163c1c)
![image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/b978a95e-95dc-4a15-826d-5e33eba8d99f)

**Comment by manosnoam** [comment]
@DaoDaoNoCode Can you add the requirments as shown on the screenshots (text on the right side) ?
This can be used for verification purpose to describe the required tests. Thanks!

**Comment by DaoDaoNoCode** [comment]
@manosnoam Updated, please make sure you also refer to the description and test instructions in the PR because the implementation could be slightly different sometimes when we had the discussion in the development with the designers.

**Comment by manosnoam** [comment]
Thanks @DaoDaoNoCode  verified on release 2.4
