### ISSUE TITLE
Keep the enabled/disabled status after editing the custom notebook image

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1434]
### Goal

Make sure the status doesn't change after editing the notebook image

### Dependency issue

Tracker: #1254 

### Itemized goals

After editing an image, the 'enabled' state is automatically set to disable. Any edits should not change the state - if enabled prior to edits, it should remain enabled after edits and if disabled prior to edits, it should remain disabled after edits.

This is a bug and should be as simple as a one-line fix. Check [here](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/routes/api/images/imageUtils.ts#L371), the check is wrong, it should directly check the `body.visible` instead of `typeof body.visible` when updating the image stream.

### Mocks

No mocks

**Comment by manosnoam** [comment]
Verified on RHODS 2.4
