### ISSUE TITLE
Generate meaningful name for custom notebook image

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1435]
### Goal

Allow users to set a display name for the custom images they are importing and generate a meaningful k8s name

### Dependency issue

Tracker: #1254 

### Itemized goals

When adding custom images, the image stream names are not intuitive - eg. 'byon-xxxx'. This makes it hard to differentiate across custom images. Would like the name to be more intuitive and not include 'byon' prefix.

- Idea is to have an object (Kubernetes) name and display name for each custom NB image. The image stream would be "Custom: (Kubernetes name)".
- Users should be able to access the Kubernetes name from the custom NB images admin UI, so they can find it in the list of image streams.
- Kubernetes name must be unique (for custom NB images); display name does not need to be unique. Display name is what users will see in the UI for selecting images.
- When adding a URL for image location field, remove preceding and trailing white spaces.

### Mocks

No mocks

**Comment by shalberd** [comment]
@DaoDaoNoCode additionally, if not done so yet, a meaningful name should also be set for imagestream metadata.annotations `opendatahub.io/notebook-image-name`, like [here](https://github.com/opendatahub-io/odh-manifests/blob/master/notebook-images/base/jupyter-datascience-notebook-imagestream.yaml#L8C5-L8C39)

**Comment by lucferbux** [comment]
@shalberd We tend to use [this annotation](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/k8sTypes.ts#L39) for internal resources in the dashboard, both of them are to add descriptions and display names to render in the dashboard. I wasn't aware of that annotation in the notebook, so it's up to @DaoDaoNoCode to see which one fits best for our logic

**Comment by DaoDaoNoCode** [comment]
@shalberd Hmm, interesting, I didn't know we have this annotation before. I guess if we want to also show the OOTB images in the future, we should adopt the same annotations. So I agree that we should use `opendatahub.io/notebook-image-name` and `opendatahub.io/notebook-image-desc` for the display name and description. So the order of finding the display name could be `opendatahub.io/notebook-image-name || openshift.io/display-name || metadata.name`

**Comment by andrewballantyne** [comment]
@harshad16 do you have documentation behind [these annotations](https://github.com/opendatahub-io/odh-manifests/blob/b7e14215468f37988a8ab1fd02e209dfb5a95ed2/notebook-images/base/jupyter-datascience-notebook-imagestream.yaml#L7C1-L10)?

**Comment by harshad16** [comment]
We haven't clearly documented the annotation in the imagestream.
We will include it , tracker issue: https://github.com/opendatahub-io/notebooks/issues/138

**Comment by manosnoam** [comment]
Verified on RHODS 2.4:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/5409170f-5fb2-445c-9c92-60cba52b0484)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/7e730353-4916-4996-8676-ccabf8e982d9)
