### ISSUE TITLE
Update custom notebooks page to include OOTB images

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1438]
### Goal

Update custom notebooks page and table to include OOTB images

### Dependency issue

No dependencies

### Itemized goals

- update wording to be inclusive to OOTB images
- populate table with both custom notebook images and OOTB images
- OOTB images cannot be edited (kebab does not have edit option)

### Aspects continued elsewhere

- https://github.com/opendatahub-io/odh-dashboard/issues/1439

### Mocks

https://www.sketch.com/s/c8183f89-76f5-4a23-b885-a9e404a61414/a/aMV90OP

**Comment by dgutride** [comment]
Needs more investigation to see if this can be committed to or not.

**Comment by Gkrumbach07** [comment]
@dgutride there probably is some overarching epic or feature that should cover this. This was originally meant to be done with accelerators but we didnt have time. I am closing this as its probably a duplicate.
