### ISSUE TITLE
Map accelerators to custom notebook images

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1439]
### Goal

Be able to visualize and configure images accelerators mappings from the custom notebook images page and table

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1438
- https://github.com/opendatahub-io/odh-dashboard/issues/1371

### Itemized goals

- add supported accelerators column
- mapped accelerators are when a imagestream has the recommend accelerators annotation and that identiifer mathces one of the accelerator profiles
- images with accelerators mapped but no matching accelerators should show a button to add a accelerator. this navigates to the create accelerator page with identifier filled in and disabled. matching accelerators are added as labels and the button does not go away
- images that are OOTB with no mapped accelerators should show N/A
- images that are OOTB with mapped accelerators should show labels of the accelerator profiles with no button
- images without accelerators mapped should show the add button that is greyed out with a tooltip
- no dragable image list unless that is already implemented
- create/edit form should have a new section
   - section should allow you to add multiple identifiers
   - identifiers can be removed easily
   - dropdown identifiers from identifiers found in accelerators 
   - also allow to type your own

### Mocks

https://www.sketch.com/s/c8183f89-76f5-4a23-b885-a9e404a61414/a/aMV90OP

**Comment by Gkrumbach07** [comment]
### Needs UX
@yannnz

I believe this is where you last were working for the notebook image admin page 
 - https://github.com/opendatahub-io/odh-dashboard/issues/1802#issuecomment-1723722566 

This issue will be on hold until more solidified details on the use of group labels

**Comment by yannnz** [comment]
> ### Needs UX
> @yannnz
> 
> I believe this is where you last were working for the notebook image admin page
> 
> * [Habana (accelerator) UX design for admins #1802 (comment)](https://github.com/opendatahub-io/odh-dashboard/issues/1802#issuecomment-1723722566)
> 
> This issue will be on hold until more solidified details on the use of group labels

Yes that link is the latest one.

**Comment by Gkrumbach07** [comment]
latest https://www.sketch.com/s/c8183f89-76f5-4a23-b885-a9e404a61414/a/aMV90OP
