### ISSUE TITLE
Explainability Phase 1: Incubation refinements

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1447]
This ticket is intended to keep track of any small refinements to be made after Phase 1 work has started incubation.

- [ ] Better handling of edge case when feature flag is enabled but TrustyAI CRD is not available.
   -  This issue is captured here: https://github.com/opendatahub-io/odh-dashboard/issues/1996 
- [ ] Better UX around Project Settings tab when BiasMetrics feature flag disabled
  - Broken out into ticket: https://github.com/opendatahub-io/odh-dashboard/issues/2024 
- [ ] Error flow around CR fetch timeout
  - Broken out into ticket: https://github.com/opendatahub-io/odh-dashboard/issues/2023
- [ ] Add project name to the session storage key for the selected metrics chart
  - Broken out into ticket: https://github.com/opendatahub-io/odh-dashboard/issues/2022

**Comment by dgutride** [comment]
Let's take this issue and break remaining work out

**Comment by alexcreasy** [comment]
The action items all have their own ticket now, so I'm closing this one.
