### ISSUE TITLE
[Bug]:  OdhDashboardConfig  should have  API set to version: v1 not v1alpha

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/odh-dashboard#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not sure if it is intention, but https://github.com/opendatahub-io/odh-dashboard/blob/9da8645f6064c5820e3d2517010f56384668a423/manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml#L13 still uses v1alpha version when other CRDs have been on v1 since 9 months ago.

### Expected Behavior

update to v1

**Comment by manaswinidas** [comment]
cc @andrewballantyne

**Comment by andrewballantyne** [comment]
@zdtsw As is stands, this is not something we are doing right now. With the Operator rework things are going to be changing some and we need to support a different set of API than what we have today. Versioning this to v1 will just make us go to v2 very quickly.

**Comment by zdtsw** [comment]
> @zdtsw As is stands, this is not something we are doing right now. With the Operator rework things are going to be changing some and we need to support a different set of API than what we have today. Versioning this to v1 will just make us go to v2 very quickly.

Thanks @andrewballantyne 
As long as you don't see this as a bug and plan to uplift to v2 once re-design operator is ready, I am fine with v1alpha.

**Comment by andrewballantyne** [comment]
We will go to v1 once we figure out how the new landscape is working and manage the appropriate changes to match that structure.

**Comment by lucferbux** [comment]
@andrewballantyne should we close this issue by now? I think we don't need it to be open if we have the bump planned for the operator redesign.
