### ISSUE TITLE
[Feature Request]: Directly list all the runs when moving to Pipelines > Runs page

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1454]
### Feature description

As of now when user goes to Pipelines > Runs page of Dashoard they will likely switch between Scheduled and Triggered, based on their usage of the feature. 

I think it would give a smoother experience having all the runs listed as soon as user reaches the Runs page. Some options I could think of:
- merge scheduled and triggered runs in the same list and labeled in a way to be distinguished easily (filters would be great help) -> possible issue: handle different attributes in the same table
- move the scheduled run to a dedicated page

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIRFE-30
