### ISSUE TITLE
[Bug]: Deprecated dependencies in kubernetes/client-node

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently we are using the library `kubernetes/client-node:0.12.2` in our backend.
That version was released 3 years ago and contains several dependencies that are now deprecated.
We need to migrate the library to +1.0.0, as stated in the [version section](https://www.npmjs.com/package/@kubernetes/client-node?activeTab=versions).

This version contains a lot of breaking changes so we need to work on migration our codebase.

### Expected Behavior

Have libraries up to date.

**Comment by lucferbux** [comment]
Just a quick heads up, checking the current project, it seems that the current `1.xrc` branch is quite deprecated, and they are working on a [release soon](https://github.com/kubernetes-client/javascript/issues/1173), so I'm holding off to get the newest version with the fixes.

**Comment by lucferbux** [comment]
Moving this out of this sprint to focus on kserve.

**Comment by andrewballantyne** [comment]
See https://github.com/opendatahub-io/odh-dashboard/issues/2188 for the followup.
