### ISSUE TITLE
[KFNBC] UI - Add KFNB controller support to dashboard

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#148]
We need to be able to support KFNB controller by displaying a tile to the user and allowing them to do the following:

Requirements:

- [x] Add notebooks panel / tile to the ODH dashboard (only visible if notebooks CRD exists).
- [x] Create route to KFNB page.
- [x] Create initial page with UI from protoype / spawner
- [x] Create a [notebook object](https://github.com/samuelvl/odh-manifests/blob/25587f5bba7f4733ead45a2a423127dd9a4bb1f1/tests/resources/notebook-controller/notebooks/s2i-minimal-notebook.yaml#L1-L15) (only name and image). (API docs are missing)
- [x] Create the [corresponding route](https://github.com/samuelvl/odh-manifests/blob/25587f5bba7f4733ead45a2a423127dd9a4bb1f1/tests/resources/notebook-controller/notebooks/s2i-minimal-notebook.yaml#L17-L32) to expose the notebook pod.
- [x] Add screen that displays the UI for KFNBC similar to the spawner UI for juypter hub.
-- Images - Done (https://github.com/opendatahub-io/odh-dashboard/pull/254)
-- Sizes - In progress (https://github.com/opendatahub-io/odh-dashboard/pull/238)
-- GPUs (if applicable) - In progress https://github.com/opendatahub-io/odh-dashboard/issues/158 https://github.com/opendatahub-io/odh-dashboard/pull/264
-- Environment variables - Included in Notebook object
-- Secrets - In Progress (https://github.com/opendatahub-io/odh-dashboard/pull/256)
- [x] Add ability to start and stop the notebook based on mockup below.
- [x] Culling notebook support for current notebooks being added here https://github.com/opendatahub-io/odh-dashboard/issues/120 should also be supported for KFNBC.
- [ ] #273

Mockups for KFNBC: https://marvelapp.com/prototype/90ii3fd/screen/85876386

**Comment by samuelvl** [comment]
@maroroman @DaoDaoNoCode @dlabaj I have added a new item "Add admin section from jupyterhub spawner".

**Comment by samuelvl** [comment]
Closing this issue since the progress is tracked in this story -> https://github.com/opendatahub-io/odh-dashboard/issues/213
