### ISSUE TITLE
[Bug]: Partial Cluster Storage Sizes is Poorly Supported

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1480]
### Solution

- Implement dropdown for size option -- https://github.com/opendatahub-io/odh-dashboard/issues/1480#issuecomment-1689380585 for mocks
    - reflect value in number field in that unit
    - do not auto-convert value when unit changes
    - do not allow decimal values (whole numbers only in the unit of their choice)
- Apply this change to Workbench PVC & PVC Creation/Edit Modal

---

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Directly installing the Dashboard at the latest (eg. `odh-dashboard/main`)

### Version

v2.11.0

### Current Behavior

When creating a workbench, if you supply a partial value (1.5 for instance) K8s will convert that to Mi, instead of keeping the decimal Gi format. 

The UI renders the value fine for the visual representation on the table for cluster storages... but when you edit the cluster storage in question, we don't see that difference and treat the value as Gi -- which turns 1.5 gigs into 1536 gigs (instead of Mi)

### Expected Behavior

We support units (let K8s store it as it sees fit). Or we convert back by dividing by 1024.

UX should make the call that makes the most sense.

Alternatively (and less desired) we just stop partial values.

### Steps To Reproduce

1. create a DS Project
2. click "Create workbench" button
3. insert your workbench details
4. in the "Persistent Storage Size" field, insert a decimal value (e.g., 1.5)
5. Submit by clicking "Create workbench" button
6. check the cluster storage details in the table
7. wait until workbench gets "Running" state
8. edit the cluster storage in question

### Workaround (if any)

Use whole numbers

**Comment by andrewballantyne** [comment]
@kywalker-rh We need to discuss what the desired situation here is. Do we support units with a dropdown in the UI or should we convert everything back to Gi and deal with the slight imprecise nature of partial Gigabytes.

**Comment by xianli123** [comment]
@andrewballantyne I added a dropdown to select storage units as we discussed in the [Slack thread](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1692108500461999).  The screenshot below shows the dropdown. For more details, please refer to the [design mockups](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=746%3A3390&type=design&node-id=746-3869&viewport=385%2C418%2C0.07&t=P8dDGk1JaZXYRUNE-1&scaling=scale-down&starting-point-node-id=746%3A3391&mode=design). Thanks!

<img width="1073" alt="Screenshot 2023-08-23 at 14 50 22" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/c292699e-9b30-40f0-984a-e1c205d67a20">
