### ISSUE TITLE
RHODS Pipelines does not accurately display the number of runs. 

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1483]
A user created a pipeline that ran every minute. 
By the time I noticed, there were 
```
bash-4.4 ~ $ oc get pods | grep runsford | wc -l 
2292
```
completed pods. 

The pipeline is made up of 6 pods, so that's probably about 382 runs. 
And yet, in the UI, I see:

![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/cd5562df-e60d-42b5-82e8-154fbe271c9b)

I'd expect the UI to reflect the actual numbers, especially so that the cleanup can be done by the user.

**Comment by andrewballantyne** [comment]
I've moved the issue to clean things up, but it is a duplicate of https://github.com/opendatahub-io/odh-dashboard/issues/1223 so I'm closing it. We'll handle the solution on 1223.
