### ISSUE TITLE
[Bug]: Oauth Proxy failing on some installations

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Using an OpenDataHub main version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

When installing the dashboard through a default installation, when trying to access through oauth, we get this error:

<img width="1105" alt="Screenshot 2023-07-07 at 15 48 02" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/938079f0-09b5-4f2f-9641-a6bd6e55b083">

Looking at the oauth proxy's logs, we have this error message:

```log
2023/07/07 13:47:51 provider.go:587: Performing OAuth discovery against https://172.30.0.1/.well-known/oauth-authorization-server
2023/07/07 13:47:51 provider.go:627: 200 GET https://172.30.0.1/.well-known/oauth-authorization-server {
  "issuer": "https://oauth-openshift.apps.ods-qe-04.rhods.ccitredhat.com",
  "authorization_endpoint": "https://oauth-openshift.apps.ods-qe-04.rhods.ccitredhat.com/oauth/authorize",
  "token_endpoint": "https://oauth-openshift.apps.ods-qe-04.rhods.ccitredhat.com/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
2023/07/07 13:47:51 oauthproxy.go:656: error redeeming code (client:10.129.2.1:45526): got 400 from "https://oauth-openshift.apps.ods-qe-04.rhods.ccitredhat.com/oauth/token" {"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
2023/07/07 13:47:51 oauthproxy.go:445: ErrorPage 500 Internal Error Internal Error
```

### Expected Behavior

Log in successfully in the dashboard.

### Steps To Reproduce

1. Install the dashboard through its kfdef
2. Try to log in

**Comment by shalberd** [comment]
interesting, with which version of ose-oauth-proxy sidecar?

**Comment by lucferbux** [comment]
> interesting, with which version of ose-oauth-proxy sidecar?

It's on v4.8, I've tried to upload it to v4.10, but it's failing too, I'm checking if all the permissions are ok.

**Comment by lucferbux** [comment]
@VaishnaviHire @zdtsw I think this is related to the [secret generator](https://github.com/opendatahub-io/opendatahub-operator/tree/master/controllers/secretgenerator) I'm not able to reproduce it all the time but I've seen this happen a few times already, we might wanna take a look.

**Comment by lucferbux** [comment]
based on an internal conversation with @VaishnaviHire it seems that this is not related to any issue to our deployment, it might be some misconfiguration on clusters.
Closing this issue.

**Comment by andrewballantyne** [comment]
I think this is a related ODH slack thread. https://odh-io.slack.com/archives/C0330L52N22/p1689081494878929?thread_ts=1689076444.124509&cid=C0330L52N22

**Comment by asanzgom** [comment]
Reopening the issue as the bug is still reproducible on v2.4 RC2: 

https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1700135335630479?thread_ts=1700121604.676009&cid=C05NXTEHLGY

**Comment by andrewballantyne** [comment]
@asanzgom This issue should remain closed -- all conversations should be taken to https://github.com/opendatahub-io/opendatahub-operator/issues/712

This issue is more than likely unrelated to our repo -- but if it turns out we need to fix something, we can log something new and address that as-is. This issue was closed because it was not our repo.

Changing this from success close to not planned closed.
