### ISSUE TITLE
[Feature Request]: Add support for DataScienceCluster CR in dashboard.

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-dashboard#1491]
### Feature description

Related to #1475 

Currently dashboard uses KfDef CRs in the code base to enable `Application` CR. As we are moving away from KfDef CRDs, as part of migration , add support for the new operator CR [DataScienceCluster](https://github.com/opendatahub-io/opendatahub-operator/blob/feature-rearchitecture/config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml#L39-L73). 

### Describe alternatives you've considered

Possible Solutions

1. Update Dashboard code to watch for `DataScienceCluster` CR.
2.  Allow operator to update ODHApplication CR when a component is enabled/disabled

**Comment by andrewballantyne** [comment]
We will migrate away from the KfDefApplications and thus don't need to follow through with the CR reading.
