### ISSUE TITLE
[FeatureRequest] Add option to duplicate a Custom Serving Runtime different from OOTB

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1499]
As of now users can only duplicated Out-of-the-box serving runtime to create their own custom runtimes. However I think it could be useful to let users duplicating other Custom Serving Runtimes too.

**Comment by lucferbux** [comment]
@vconzola ok, so based on our conversation, it seems that we didn't add this to regular ones as we were focused on bringing that feature to OOTB serving runtimes, but there's no reason to not add it to regular ones.
@bdattoma we can work on that, it's a fair request.
