### ISSUE TITLE
[Bug]: Elyra Pipelines Lack Proper Task Names

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Directly installing the Dashboard at the latest (eg. `odh-dashboard/main`)

### Version

v2.12.0

### Current Behavior

When you create a Pipeline in Elyra, they don't use Tekton naming... they use metadata for task naming. Because of this, we don't render our items with the appropriate task names. 

Elyra:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/f69dea78-2ddd-4709-b467-238c255906bd)

Dashboards' DS Pipelines:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/24b74c73-730d-4781-88f9-f6ad9f12feb9)

### Expected Behavior

We need to read the metadata and convert the labels for our nodes over. 

### Steps To Reproduce

1. Launch an Elyra Notebook
2. Build any pipeline of any number of tasks
3. Launch DS Pipelines Dashboard UI and view the Pipeline/Run views

### Anything else

You'll have to investigate the yaml output, but it should be fairly easy to see when you can look at both ends... just search for the text.

**Comment by harshad16** [comment]
The SSL_CERT issue requires this key/value to be set
`PIPELINES_SSL_SA_CERTS=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

**Comment by erwangranger** [comment]
Can we re-open this? 
I just re-tested this with RHODS 1.31. 
I re-used the same pipeline example I had used in my original testing. 
(https://github.com/erwangranger/DS-Pipelines-Samples) 

In Elyra, It looks like this: 
![image](https://github.com/opendatahub-io/odh-dashboard/assets/32554862/1c80f31e-6804-48fd-821c-acc43b2c417e)

In RHODS it looks like this: 
![image](https://github.com/opendatahub-io/odh-dashboard/assets/32554862/081073e3-7d7a-421c-83a6-47ae1d2e5c3e)

While this is an improvement over "run-a-file" everywhere, it still is different enough that I can't tell which of the multiple "get" matches with the original tasks. 

FYI, @jedemo

**Comment by andrewballantyne** [comment]
Hey @erwangranger! Let's actually [create a new issue](https://github.com/opendatahub-io/odh-dashboard/issues/new/choose) -- the PR shows it "worked" to solve the situation but it seems to have not quite solved it for your use-case. We'll need more data to keep looking into this. Do you have a Pipeline Run we can upload on our side or some steps to get Elyra to recreate this effort?

I'd imagine there is more metadata we need to look at, but I hope Elyra doesn't convert the values on the fly as it creates the run to something we can't even pull back out. I'll tag @harshad16 on this too. 

FWIW and for posterity -- I suggest a new issue just because this is tied to a release already & it did solve _something_ in this area -- but seems to be not enough.
