### ISSUE TITLE
[Story]: Remove KF Watcher Crash on no KFDef Installed

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1508]
### Goal

Implement a softer requirement for KFDef CRD to be installed

### Dependency issue

No dependencies

### Itemized goals

* Today we crash on KFDef fetching for the Resource Watcher if the KFDef CRD is not installed
* We should silently fail and just say there are no KFDefs

### Aspects continued elsewhere

* Handle the logic behind KFDef usage -- Ticket TBD

### Mocks

No mocks

**Comment by manosnoam** [comment]
@andrewballantyne , can you please add reproduction steps to test this?

**Comment by andrewballantyne** [comment]
> @andrewballantyne , can you please add reproduction steps to test this?

@manosnoam Use the new operator & don't have a KfDef CRD installed on your cluster. Our old state would show an error in the `Enabled` page of the UI and not show the Jupyter tile.
