### ISSUE TITLE
[Bug]: If Workbench Update Fails -- Secret/Configmaps can be deleted

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Directly installing the Dashboard at the latest (eg. `odh-dashboard/main`)

### Version

v2.12.0

### Current Behavior

When you have a workbench that has secrets or configmaps associated to it... and then you edit it, remove one, and save -- if that save fails to update the workbench, the reference to the configmap or secret remains, but the resource is deleted leaving that broken reference.

This causes problems with starting the notebook. 

### Expected Behavior

Update the workbench BEFORE deleting any resources. We'll have to rework our footer logic on the Workbench Footer to not submit the requests to delete/update/create anything secret/configmap related until we can update the workbench.

If we fail an update -- it's more or less a noop
If we fail a create, we orphan the configmap/secret
If we fail a delete, we break the notebook with a reference that does not exist

### Steps To Reproduce

1. Start to create a Workbench
2. Add two secrets or configmaps (test both)
3. Submit the Workbench
4. Stop the Workbench (just reduces variables, this is not needed)
5. Edit the Workbench
6. Open a new tab and go to the OpenShift Console & locate the Notebook resource
    - Notice that there are two `envFrom` entires -- these are your configmaps/secrets
    - Edit the resource's template spec... modifying one of the resources values seems to work
    - Save the yaml in OpenShift Console
7. Return to the Dashboard UI still mid-edit of that Workbench
8. Remove one of the configmap/secrets
9. Update the workbench

You should see a conflict error if this was successfully reproduced. 

Go back to OpenShift Console and notice the following:
- Notebook resource still has two `envFrom` values
- OpenShift Console does not have both configmaps/secret resources anymore

We deleted a resource but it's still attached. Now the Notebook will not startup. 

### Workaround (if any)

Wait for the indeterminate amount of time for the workbench to settle before editing. Not a really good workaround.

**Comment by andrewballantyne** [comment]
I've updated the steps in the ticket description to be more specific.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-577
