### ISSUE TITLE
[Story]: Remove reliance on KfDefApplications OdhApplication CR field

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1510]
### Goal

~Implement support for DSC.status.installedComponents~ Depreciate `KfdefApplications` usage

### Dependency issue

- ~https://github.com/opendatahub-io/odh-dashboard/issues/1491~ no longer needed

### Itemized goals

* In the OdhApplication enablement flow it checks KFDefs for kfdefApplications -- this is deprecated
* ~Read the DSC and pull from the status.installedComponents (https://github.com/opendatahub-io/opendatahub-operator/pull/302#issuecomment-1631561998)~
    * ~We'll need to build a mapping on our side to convert from their naming to ours so we can migrate away from KfDefApplications to the status naming -- this can be gotten off the Operator install page~
* ~Create a new field in the OdhApplication CR to allow for components from the DSC~

### Mocks

No mocks

**Comment by lucferbux** [comment]
Just leaving this here to start a conversation.
I think we need to do a broader refactor of the OdhApplications enablement logic. Right now it's kind of confusing and it has led to several issues in the past, I think we need a cleaner solution at this point.

**Comment by andrewballantyne** [comment]
It's an interesting point. Not sure, is my short answer.

I imagine it has some logicality to group the CR with the Workbenches install... but the Jupyter `OdhApplication` has no value aside from being installed for our dashboard. It isn't even a real application, it's just a hint for a tile to show an internal route to get access to it. 

For other ISVs, or tied relationship resources (quick starts for Pipelines for instance) might have a lot of value being deployed from the other end (assuming we don't have any goals to "add them without installing them" as a means for self promo)... it's just Jupyter is unique in it's non-app app existence.

Let me think on this more. I'll look at what we do in the RHODS space as well to see if these OdhApplications have more value to keep this functionality. But I do like the concept of simplifying the Dashboard set of resources.

**Comment by strangiato** [comment]
+1 to @VaishnaviHire's idea.

The Dashboard reading what components are installed from the KFDef (or DSC) is a classic coupling problem.  The dashboard should not be dependent on the operator and should be able to be deployed without the operator.

It is ok if the operator has a way to set which components are enabled or disabled (e.g. ODHApplication objects included in the manifests for the other components) when deploying the dashboard.  It is ok for the dashboard to detect which components are installed directly from k8s (e.g. is the controller pod installed).  However, the dashboard should not mutate it's configuration based on a state reported by the operator.

**Comment by andrewballantyne** [comment]
> However, the dashboard should not mutate it's configuration based on a state reported by the operator.

This is not mutation, this is detection. Filtering based on K8s resources and their state is a common pattern I thought. 🤔 

I get the coupling issue for sure -- but it's native SPA functionality that was lifted up as a resource. Having that managed by another component seems a bit excessive. 

ISVs and QuickStarts for uninstalled components, I agree... those resources should just not exist (again, unless we have a self promo desire here) in with the Dashboard. Which is a heavy problem today in the RHODS space, given the wide variety of other resources we deploy as part of that system.

My 2 cents -- I still need to look at out use-cases we have for the OdhApplications before I can act on this issue.

**Comment by strangiato** [comment]
> This is not mutation, this is detection. Filtering based on K8s resources and their state is a common pattern I thought.

From my understanding the dashboard today is reading from the kdef to detect what components are installed and the pieces of the UI relevant to the installed components are either exposed or not.  Call it whatever you want but the functionality is changing based on the kfdef/operator.

Like I mentioned before, it would be totally appropriate for the dashboard to check what resources are available in k8s but it should be going to the source, not the operator.  In this case the source would be the the existence of the controller pods for the other components.

From the dashboard perspective, it should never even know the operator exists and there should be no guarantee that the operator doesn't decide to change the api schema in the future.  

The dashboard should also be able to function without the operator installed at all and all of the components should be able to be installed manually using something like `oc apply -k`.

**Comment by andrewballantyne** [comment]
Upon investigation ... we are no longer going to be using the `kfdefApplications` field. It will be deprecated with this change as will the code that uses it. Once the application stack moves to the new operator, the functionality will be gone -- to keep this functionality you'll want to add resources to the component it relies on and they will be deployed with that component.

The Dashboard will only hold onto the Jupyter tile as it's our "application".
