### ISSUE TITLE
[Bug]: Updating Host Details in Data Connection doesn't update host details in DSPA

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Directly installing the Dashboard at the latest (eg. `odh-dashboard/main`)

### Version

RHODS 1.29.0

### Current Behavior

When setting up a pipeline server in the dashboard, you are required to configure a data connection with the s3 endpoint, secret keys, and bucket.  When a DSPA object is created by the dashboard the AccessKey and SecretKey is loaded by the DSPA directly from the secret, but the dashboard hard codes the values for the bucket, host, port, and schema into the object.

As a user, since I entered this information into a data connection/secret when creating the object implies that the DSPA is consuming the secret directly and if I need to edit the connection details I should edit the data connection.  However, editing the data connection details and restart the pipeline-server pod does not do anything to the DSPA since it is hard coded into the DSPA.

The only way to edit the connection details is to delete the pipeline server and create it from scratch.

### Expected Behavior

The UI should reflect the reality of what is actually happening and users should be able to edit the connection information.

There are a couple of different ways this could probably be achieved...

DSPO could potentially add support for loading the connection details from a secret/data connection. An issue related to supporting that has been opened here:

https://github.com/opendatahub-io/data-science-pipelines-operator/issues/199

If a user were to update a data connection the pipeline-server pod would still need to be restarted in order to load that connection.  This may be something the dashboard would want to consider.

Another option would be to make it more clear what is happening when you setup a pipeline server.  Instead of implying that everything is loaded from the data connection directly, the UI could allow a user to select a data connection and automatically fill in the details for the things that are getting hard coded into the DSPA.

This would also require that the DSPA should be editable from the dashboard in case a user does need to update the host details or some other piece.

**Comment by andrewballantyne** [comment]
Hey @strangiato! I complete agree with your concern here. 

We logged:
- https://github.com/opendatahub-io/odh-dashboard/issues/1214

It wasn't flagged as field priority and was pushed down the priority. I just changed that. 

I'm going to close your issue. Please post any comments you feel you want on that issue to help with the direction. But effectively our current path is to drop the "data connection" relationship. We spoke with the DSPO folks and they didn't have a lot of flexibility on the rebinding of the Data Connection / Object Storage connection -- this was our plan and priorities shifted and this seemed to have slipped through the cracks. I'll get UX on it and we can look to get moving on this asap.
