### ISSUE TITLE
[Feature Request]: Validate User input for Data Science Pipelines Database Connections

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/odh-dashboard#1521]
### Feature description

In it's current implementation, Data Science Pipelines only supports Mysql-compliant databases.  This means that connection metadata (database name, username, and password) must conform to mysql specifications, and these have Regular Expressions associated with them (see related issue: opendatahub-io/data-science-pipelines-operator#207[1]).  Due to this stipulation, ODH Dashboard should also block users from providing invalid connection metadata

[1] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/207

### Describe alternatives you've considered

Alternatively we rely on DSPO/DSPA updating it's CRD to reject improper metadata, but this is fragile and adding UI validation would be an extra added layer of confidence that only proper metadata is allowed.

**Comment by dgutride** [comment]
Migrated to https://issues.redhat.com/browse/RHOAIRFE-19
