### ISSUE TITLE
[Feature Request]: Differentiate between model-server metrics and model metrics

### ISSUE THREAD

**Issue by RobGeada** [opendatahub-io/odh-dashboard#1524]
### Feature description

Right now,  the menu item for viewing model-server metrics and the menu item for viewing model metrics both share the same name: "View metrics":
![image](https://github.com/opendatahub-io/odh-dashboard/assets/20345051/161ff136-b168-42c9-9ef1-e1a987c7f6a7)
 
While I understand the difference it _what_ these metrics are for, users could perhaps think they are referring to the same things and be confused when they are sent to different pages. Could we differentiate these names, something like "View model-server metrics" and "View model metrics"?

**Comment by vconzola** [comment]
Yes, I was slacking with Rob and Berto about this. Seems like a one liner. Guessing you don't need a mockup?

**Comment by vconzola** [comment]
@andrewballantyne Yep, that's it. Berto brought up a few other concerns, but I want to investigate those with "real" users during our upcoming test before deciding if anything else needs to change.
