### ISSUE TITLE
[Bug]: Documentation link is broken

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

Right now, the link to documentation is broken upstream, probably due to the refactoring of the odh webpage.

<img width="402" alt="Screenshot 2023-07-18 at 16 02 21" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/72806d8d-2edc-47aa-9a16-7daaac432c45">

### Expected Behavior

Navigating to the right documentation page.

### Steps To Reproduce

1. Click the question mark icon in the nav bar
2. Click "Documentation"

### Workaround (if any)

Remove the `.html` extension from the url.

**Comment by shalberd** [comment]
when clicking on the documentation link, the url refers to https://opendatahub.io/docs.html, but it should be https://opendatahub.io/docs   

same for community link

needs to be https://opendatahub.io/community

**Comment by manaswinidas** [comment]
(Not related to migration to Gatsby)I realized the Jupyter Getting Started links led to a 404 page:
<img width="1290" alt="Screenshot 2023-07-28 at 12 54 53 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/1fb7a0b8-b837-4397-8260-b0cb90d200fd">

**Comment by shalberd** [comment]
@manaswinidas where or how do you get to the Jupyter getting started links from within dashboard GUI? Just out of interest.

I see them in code

https://github.com/search?q=repo%3Aopendatahub-io%2Fodh-dashboard+readthedocs&type=code

**Comment by manaswinidas** [comment]
You're right. I got to the 404 page after clicking on the `Getting started` link:
<img width="982" alt="Screenshot 2023-07-28 at 1 18 31 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/7dcad079-e332-45d5-84e8-8de98a2df9cc">

**Comment by manaswinidas** [comment]
This is the right getting-started link: https://jupyterhub.readthedocs.io/en/stable/tutorial/index.html#getting-started
Do we create a ticket?

**Comment by shalberd** [comment]
Let's see the others' opinion on that documentation part (odhApplication) of Dashboard first, especially with regards to [Jupyterhub](https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests/apps/jupyter).

**Comment by andrewballantyne** [comment]
Two things:
1. JupyterHub is going away (already well deprecated and should have been already removed -- we just have had other focuses) -- it is tracked in https://github.com/opendatahub-io/odh-dashboard/issues/534
2. We should probably always log issues for either code or content changes in the Dashboard; if it's not directly related to the effort in question, best to log something else. It'll help with tracing later (eg "was it an issue or part of some PR? How do I find it?" kind of questions).
