### ISSUE TITLE
[Bug]: No way to delete a Pipeline Server in DS Projects

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

I can create a Pipeline Server:

<img width="449" alt="Screenshot 2023-07-19 at 13 13 11" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/b8bb9fba-1f9e-43e6-9664-ac380f549c2b">

But I can't find any way to modify it or delete it after. 

But I should be able to delete, potentially to re-create it after? 

This is all I see:

<img width="692" alt="Screenshot 2023-07-19 at 13 13 24" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/1140c0bf-81af-45d2-9ada-e2b507883317">

This can be performed in the Pipeline section, but not in DS projects:

<img width="1419" alt="Screenshot 2023-07-19 at 13 17 06" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/d674ed94-d001-4147-9e8f-3be258bbb19b">

### Expected Behavior

Have the ability to delete a Pipeline Server

### Steps To Reproduce

1. Create a Pipeline Server
2. Try to delete it in DS Projects

**Comment by lucferbux** [comment]
@erwangranger I've moved the conversation of this topic upstream.

I think @kywalker-rh created some mockups for this, can you share them here please, I cannot render them.

**Comment by kywalker-rh** [comment]
Here's the design @lucferbux:

<img width="972" alt="Screenshot 2023-06-29 at 11 07 46 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/53235442/fe800121-3af6-4db2-96d2-af05b44663a6">

**Comment by andrewballantyne** [comment]
Not sure I'd have called this a bug -- it seems to be more of a feature request, but in the end, field-priority takes precedence anyways.

**Comment by lucferbux** [comment]
> Not sure I'd have called this a bug -- it seems to be more of a feature request, but in the end, field-priority takes precedence anyways.

Yeah, I should have converted this into a feature request, this was originally logged as an issue, but is more a feature request.
