### ISSUE TITLE
[Bug]: Pipelines "started at" and "finished at" dates look strange.

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.6.0

### Current Behavior

Creating a new Pipeline Run, the `Started at` and `Finished at` dates look wrong:

<img width="690" alt="Screenshot 2023-07-19 at 13 24 05" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/5cbee4fa-bf66-4913-8afa-02b3b6938281">

### Expected Behavior

Display the correct value for the dates

UX change: Render "N/A" instead of epoch value.

### Steps To Reproduce

1. Import a new pipelines
2. Create a new run
3. Check the dates

**Comment by DaoDaoNoCode** [comment]
I think this might not be a dashboard issue. It could be the issue in https://github.com/opendatahub-io/data-science-pipelines repo. I checked the network call and this is what we got from the pipeline server.

![Screenshot 2023-08-08 at 3 04 57 PM](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/2d5a7b96-667c-4150-a013-b53e4d5b7af8)

**Comment by lucferbux** [comment]
> I think this might not be a dashboard issue. It could be the issue in https://github.com/opendatahub-io/data-science-pipelines repo. I checked the network call and this is what we got from the pipeline server.
> 
> ![Screenshot 2023-08-08 at 3 04 57 PM](https://user-images.githubusercontent.com/37624318/259202864-2d5a7b96-667c-4150-a013-b53e4d5b7af8.png)

oh, that's quite handy, thanks @DaoDaoNoCode 

@HumairAK @gmfrasca @DharmitD FYI maybe you want to take a look at this

**Comment by andrewballantyne** [comment]
Epoch is a well known computer stance -- we can handle this and just so `N/A` -- it is weird that DS Pipelines (Kubeflow Pipelines) uses this value instead of some non-value -- but I guess they have a Date format and it is as much of a "0" number a date can be. @HumairAK is this improving in v2 of the API?

@yannnz Are we looking to just hide the field when it's "empty"? Or do you have a preferred `N/A` sorta rendering you prefer?

**Comment by yannnz** [comment]
I am trying to understand the issue here. Is it saying that we will not be able to display the correct `Scheduled at` value for all Runs? I think hide the field is better than `N/A`, if we would never be able to show the correct value. `N/A` can be used if sometimes it works, while other times it doesn't. WDYT?   

> Epoch is a well known computer stance -- we can handle this and just so `N/A` -- it is weird that DS Pipelines (Kubeflow Pipelines) uses this value instead of some non-value -- but I guess they have a Date format and it is as much of a "0" number a date can be. @HumairAK is this improving in v2 of the API?
> 
> @yannnz Are we looking to just hide the field when it's "empty"? Or do you have a preferred `N/A` sorta rendering you prefer?

**Comment by andrewballantyne** [comment]
@yannnz this is all data related... in some cases, the data is just not set. Epoch is equivalent to empty in a date format. So in the screenshot of the issue, it was created, not started, and then finished. Maybe something about the initialization of the Pipeline failed and it then never really got anywhere. While it's running, finished will be epoch.

So this is about transitory and unavailable data and how we want to show it. Hiding the fields are trivial -- we can do that, but they will just "pop" in when we have a value.

**Comment by yannnz** [comment]
> @yannnz this is all data related... in some cases, the data is just not set. Epoch is equivalent to empty in a date format. So in the screenshot of the issue, it was created, not started, and then finished. Maybe something about the initialization of the Pipeline failed and it then never really got anywhere. While it's running, finished will be epoch.
> 
> So this is about transitory and unavailable data and how we want to show it. Hiding the fields are trivial -- we can do that, but they will just "pop" in when we have a value.

Oh I see. So if it is for failed runs, then displaying N/A makes more sense. @andrewballantyne

**Comment by pnaik1** [comment]
> So this is about transitory and unavailable data and how we want to show it. Hiding the fields are trivial -- we can do that, but they will just "pop" in when we have a value.

@andrewballantyne , wanted to know little bit more , on what scenario the value pops up? is it when the runs are successfully completed?

**Comment by lucferbux** [comment]
> @yannnz this is all data related... in some cases, the data is just not set. Epoch is equivalent to empty in a date format. So in the screenshot of the issue, it was created, not started, and then finished. Maybe something about the initialization of the Pipeline failed and it then never really got anywhere. While it's running, finished will be epoch.
> 
> So this is about transitory and unavailable data and how we want to show it. Hiding the fields are trivial -- we can do that, but they will just "pop" in when we have a value.

@pnaik1 @andrewballantyne @yannnz Just to add more context here, I'm not sure if this is due to having an outdated pipeline controller (latest update was 3 weeks ago) or something wrong with my cluster, but I'm able to see this in successful pipelines, I'm attaching two screenshots, one with the run starting after triggering it and then another one after is successful and I navigate back to view and back again to the run:

1. Run just executed
<img width="2276" alt="Screenshot 2023-09-06 at 12 10 41" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/a12972f5-38ce-4989-8e43-32c446bcc3ed">



2. Run completed
<img width="2294" alt="Screenshot 2023-09-06 at 12 13 07" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/e8b482cf-2393-4ba2-bd10-6a576e02f085">

See that in case of Finished at it works just great, but not the other way around.

**Comment by HumairAK** [comment]
discussed this with @andrewballantyne in slack, posting the relevant bits here for persistence: 


> Purva: My question here is, when the scheduled at gets the exact value?

> Humair: I believe this should be set when it's a scheduled run, how was the run above created?

> Andrew: Ah interesting — yeah, scheduled runs have the scheduled at value … but that’s always the same as created at? 
what’s the value behind the scheduled_at property?

 > Humair: I believe created should be when the scheduled run was created, where as started should be the start of this scheduled run, so see if the next run differs (edited) 
 
 > Andrew: Nope, I looked at my last one … let me post a couple screenshots
```
No 9 in the execution:
  created_at: 2023-07-26T19:40:20Z
  scheduled_at: 2023-07-26T19:40:20Z
  finished_at: 2023-07-26T19:41:15Z
No 1 in the execution:
  created_at: 2023-07-26T19:32:29Z
  scheduled_at: 2023-07-26T19:32:20Z
  finished_at: 2023-07-26T19:33:23Z
The Job:
  created_at: 2023-07-26T19:31:20Z
  updated_at: 2023-09-06T19:34:14Z
```
> Andrew: This was flip coin fwiw

> Humair: based on the upstream code it looks like both timestamps will actually just going to be around the same time
>
> `created_at` is reported from the `PipelineRun` `creationTimeStamp` native k8s built in field
>
> `scheduled_at` is what the k8s controller will use to determine whether it is time to create the PipelineRun, I'm confused why they report this at all, hence why creationTimeStamp  might be a little late (so yes to cluster load part)
>
> I don't know why they show both, seems kinda pointless, my guess is that this was written to accommodate argo workflows engine and for the tekton implementation, this is not very meaningful
>
> I'd go with created_at and not include the scheduled_at field

**Comment by pnaik1** [comment]
double checking @yannnz @andrewballantyne,  so we are removing the started_at(Scheduled_at) all together ?

**Comment by yannnz** [comment]
My understanding from the latest conversion is removing the (Scheduled at), I remember Humair said that it is pointless to have both Created at and Scheduled at values. He suggested to only keep Created_at. 
https://odh-io.slack.com/archives/C03DY3YT151/p1694018948203919

**Comment by yannnz** [comment]
> double checking @yannnz @andrewballantyne, so we are removing the started_at(Scheduled_at) all together ?

My understanding from the latest conversion is removing the (Scheduled at), I remember Humair said that it is pointless to have both Created at and Scheduled at values. He suggested to only keep Created_at. 
https://odh-io.slack.com/archives/C03DY3YT151/p1694018948203919
