### ISSUE TITLE
[Bug]: Workbench not editable for a little while after it's stopped. 

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

If I stop my workbench, in order to edit it (say, change its size or its image), it lets me edit it, and then fails when I click the "update workbench" link:

<img width="1367" alt="Screenshot 2023-07-19 at 17 37 45" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/b7f6cacc-1aca-48f3-a9c6-a3280bbdc7d9">

If I wait and then try again, this time it saves my changes. 

### Expected Behavior

If I was not allowed to edit it yet, there should have been an indication it was the case. (greyed out edit button, warning symbol, etc...). 

### Steps To Reproduce

1. Create a workbench
2. Stop it
3. Try to edit it inmediately

**Comment by alexcreasy** [comment]
PR raised, awaiting review.
