### ISSUE TITLE
[Feature Request]: use error boundaries to provide details about the error to the enduser

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1554]
### Feature description

From the [react docs](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary):
> By default, if your application throws an error during rendering, React will remove its UI from the screen. To prevent this, you can wrap a part of your UI into an error boundary. An error boundary is a special component that lets you display some fallback UI instead of the part that crashed—for example, an error message.

The dashboard could benefit from error boundaries in at least two major areas:
- top level
- main content area

The error boundary should provide details of the error that would help the dev team reproduce the issue. The data should be made easily copiable to aid in the creation of a GitHub issue by the user.

### Anything else?

- OpenShift Console [error boundary implementations PR](https://github.com/openshift/console/pull/11607) (includes screenshots)
  - This implementation contains inline error boundaries. This may prove useful in some cases for the dashboard where individual components may want to guard against errors in their sub trees.
- Consoledot [error boundary components](https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ErrorBoundary)
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/dd6609cb-c482-4f33-b16e-25e20a9029b8)

**Comment by manosnoam** [comment]
@christianvogt Can you please add reproduction steps to test this on RHODS 1.31 ?
