### ISSUE TITLE
[Bug]: Cannot increase Persistent storage size using the keyboard

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/odh-dashboard#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

Downstream version - RHODS 1.30.RC3

### Current Behavior

Try to type `60` in `Persistent storage size`
![image](https://github.com/opendatahub-io/odh-dashboard/assets/687311/ae117c1a-6936-4ec9-9d2e-0065436137a6)

### Expected Behavior

60 in `Persistent storage size`

### Steps To Reproduce

Create a PV
Edit the PV

It is working while creating but not while editing

### Workaround (if any)

Hit - + buttons

### What browsers are you seeing the problem on?

Chrome

**Comment by andrewballantyne** [comment]
> I could not reproduce this issue. Could you provide more details? @diegolovison

@DaoDaoNoCode have you tried typing in the field? Up/Down arrows? Not sure what is expected here from PF... but if @diegolovison you could provide more reproduce steps, that'd be helpful.

**Comment by DaoDaoNoCode** [comment]
Yes, it works fine for me.

**Comment by diegolovison** [comment]
The problem is the following
![image](https://github.com/opendatahub-io/odh-dashboard/assets/687311/ecc94e9b-9c60-4822-8e37-ed2d7382f5cc)
Try to change to 35
The only way is
* Move cursor to the left
* Type 3
* Hit Delete in the keyboard
* Type 5
* Hit Delete in the keyboard

**Comment by DaoDaoNoCode** [comment]
@diegolovison You could just select `20` and enter `35`, right? I still didn't get what you mean.

https://github.com/opendatahub-io/odh-dashboard/assets/37624318/facec9dc-ec7e-4076-9c90-5455ddb2c7fa

**Comment by DaoDaoNoCode** [comment]
Chat with @diegolovison offline and reproduce the issue. Will take a look into it.

**Comment by manosnoam** [comment]
Bug still relevant in RHODS 1.33:

https://github.com/opendatahub-io/odh-dashboard/assets/9913945/4a554944-213a-4e6a-b851-92556ba9d25e

**Comment by diegolovison** [comment]
Not related with this issue
