### ISSUE TITLE
Connected workbench field in "Update cluster storage" modal is not reflecting the workbench

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/odh-dashboard#1566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

Downstream version - RHODS 1.30.RC3

### Current Behavior

Connected workbench field is "empty"

![image](https://github.com/opendatahub-io/odh-dashboard/assets/687311/373c134d-6712-44d4-90a7-b1679bf6b85b)

### Expected Behavior

The Connected workbench field should match the workbench name like in the data-grid

![image](https://github.com/opendatahub-io/odh-dashboard/assets/687311/0477d002-cd3b-4d7a-854d-f86e1d4894dd)

### Steps To Reproduce

Create a storage
Attached to a workbench
Edit the storage

### What browsers are you seeing the problem on?

Chrome

**Comment by manaswinidas** [comment]
We have wanted to do this for a while. This is a good feature request.

**Comment by DaoDaoNoCode** [comment]
@kywalker-rh It’s really interesting that the storage is not using the same design as the data connections. If you have a storage with a workbench connected, you will actually get 2 fields: `Existing connected workbenches` and `Connected workbench`, which is a lot confusing. if you want to connect the storage to another workbench, you will need to uncheck the current one and then select another one in the bottom select dropdown.
In data connection, on the other hand, we only have one field named `Connected workbench`, which you can check/uncheck everything.
I am wondering if should we refactor the storage modal to make it behave the same as the data connections modal.

![Screenshot 2023-09-20 at 1 46 42 PM](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/d176e6ec-2acb-42e5-8776-d1dc651cd342)
![Screenshot 2023-09-20 at 1 49 31 PM](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/fdbf63a2-3a11-4fe0-bb28-1ac7c8e2513f)

**Comment by kywalker-rh** [comment]
cc: @xianli123 for visibilty

**Comment by xianli123** [comment]
Hi @kywalker-rh @DaoDaoNoCode  I have devised a solution for this problem in another issue [#6247](https://issues.redhat.com/browse/RHODS-6247). We can remove the **Existing connected workbench** and show the selected connected workbench in the **Connected workbench** dropdown. I attached a screenshot below and this is [the whole design](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=875%3A40880&type=design&node-id=875-40939&viewport=342%2C395%2C0.08&t=5EDoQej1C0jXeTk9-1&scaling=scale-down&starting-point-node-id=875%3A40881&mode=design) for that issue. Does it make sense? @DaoDaoNoCode 

![image](https://github.com/opendatahub-io/odh-dashboard/assets/53931519/cfa0adbc-b311-4b06-a8ca-7f0447e61108)

**Comment by xianli123** [comment]
@DaoDaoNoCode Is there any new progress on this issue? lol

**Comment by xianli123** [comment]
@DaoDaoNoCode Sounds great. Thanks!

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1098
