### ISSUE TITLE
[KFNBC] Provide suitable error message for with inability of NB server to start

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#157]
The system must provide suitable error messages related to the inability to start NB server sessions and enable the user to recover and try again immediately

Mockup for this issue can be found here:

https://marvelapp.com/prototype/28dc5af6/screen/78116147

- [ ] Add UI to display the error to the user.
- [ ] Add UI backend code to get the status and the error.
- [ ] Integrate with KFNB controller.

**Comment by andrewballantyne** [comment]
Thought this was something else, apologizes for back and forth on the kind haha...

**Comment by andrewballantyne** [comment]
Should be covered by #351
