### ISSUE TITLE
[Tracker]: Support versions for pipelines

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1575]
### Description

We don't currently show Pipeline Versions in the Dashboard UI, only the first default version associated to a Pipeline. We would like to show all versions and have the proper selection throughout to support them.

### Target Branch

f/pipelines-enhancement

### Requirements

> P0: Ability to add new pipeline versions and access previous versions in the UI
> Can do runs against previous versions 

### Itemized UX Issues

TBD

##### Infrastructure:
* https://github.com/opendatahub-io/odh-dashboard/issues/2191

##### Global pipelines page:
* https://github.com/opendatahub-io/odh-dashboard/issues/2196
* https://github.com/opendatahub-io/odh-dashboard/issues/2199

##### Pipeline details page:
* https://github.com/opendatahub-io/odh-dashboard/issues/2197

##### Pipeline runs:
* https://github.com/opendatahub-io/odh-dashboard/issues/2194
* https://github.com/opendatahub-io/odh-dashboard/issues/2200

##### Components:
* https://github.com/opendatahub-io/odh-dashboard/issues/2192
* https://github.com/opendatahub-io/odh-dashboard/issues/2190
* https://github.com/opendatahub-io/odh-dashboard/issues/2204
* https://github.com/opendatahub-io/odh-dashboard/issues/2198

##### Other items:
* https://github.com/opendatahub-io/odh-dashboard/issues/2014
* https://github.com/opendatahub-io/odh-dashboard/issues/1961

### Related artifacts

- Mocks: https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/lRzqa1x
- API Docs: https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/

**Comment by andrewballantyne** [comment]
cc @yannnz @kywalker-rh

**Comment by yannnz** [comment]
The first point won't hold us up. It will only need to display very long names in UI.

**Comment by yannnz** [comment]
> @yannnz
> 
> (1) _might_ be possible, but that shouldn't hold us up right? What design hinders on the answer to this question?
> 
> (2) Is not possible based on Humair's findings. My opinion is we just scratch that one out fully -- no filtering on Pipelines at all; only Pipeline Versions (which is very unfortunate for our UI).

The first point won't hold us up. It will only need to display very long names in UI.

**Comment by yannnz** [comment]
@andrewballantyne  @uidoyen  I have two more questions when I was preparing the demo for Thursday's  UX review meeting. It is specific for the `Pipeline dropdown` and `Pipeline version dropdown`. Will we have the same issue as what we have on table list to load all pipeline options and version options all in once when the list is long? I think we will, so I added a solution for it. The demo only shows the dropdown for `Create a run modal`.  But if this case effects all Pipeline/Pipeline version dropdowns, we can apply the same approach: https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/L495k0L

[Demo recording](https://drive.google.com/file/d/1BWSNkDW5FBvudySMmArNi4n9kLUZYRP0/view?usp=sharing) (24min27s)
Question 1: 15:45
Question 2: 17:00

**Comment by yannnz** [comment]
The Pipeline & Pipeline version dropdown are updated. Please help to review the design :[Pipeline & Pipeline version dropdown](https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/y95Z0bz) @andrewballantyne @kywalker-rh

**Comment by andrewballantyne** [comment]
@yannnz are you completely done your first pass of Versions or are we still looking for more? I'm wondering if I should log you a UX issue to finalize the effort here or if the latest mocks (https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/p/52D4BC1C-F002-4775-9C69-7E82C519E931/canvas) are good to go? I'd like to break down the UI stories soon too.

cc @kywalker-rh @dgutride

**Comment by yannnz** [comment]
> @yannnz are you completely done your first pass of Versions or are we still looking for more? I'm wondering if I should log you a UX issue to finalize the effort here or if the latest mocks (https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/p/52D4BC1C-F002-4775-9C69-7E82C519E931/canvas) are good to go? I'd like to break down the UI stories soon too.
> 
> cc @kywalker-rh @dgutride

@andrewballantyne The latest mockup is good to go from my side.

**Comment by yannnz** [comment]
@andrewballantyne I am taking back my words. One last thing I forgot to check is the delete action. I am proposing to have the bulk action to the pipeline and pipeline version data lists, and change the Delete pipeline button to Delete depends on what are selected. 
<img width="931" alt="Screenshot 2023-10-12 at 12 20 18" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/d0b8a5a4-d847-4160-bd4a-eb82ec38d92e">
<img width="894" alt="Screenshot 2023-10-12 at 12 20 28" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/866428aa-6ab8-4c3a-82d6-31c0066ecb66">

**Comment by andrewballantyne** [comment]
@yannnz @kywalker-rh and I talked about it on slack... we will keep the delete the same effort all around and use the toolbar kebab "delete selected" functionality. Bulk delete is bulk delete. We may need additional wording around deleting a Pipeline as all Versions will go with it (99% certain I asked the backend team of this and got that answer)

**Comment by yannnz** [comment]
> @yannnz @kywalker-rh and I talked about it on slack... we will keep the delete the same effort all around and use the toolbar kebab "delete selected" functionality. Bulk delete is bulk delete. We may need additional wording around deleting a Pipeline as all Versions will go with it (99% certain I asked the backend team of this and got that answer)

@kaedward  Could you help on the content of the delete modal? I tagged you in the sketch file.

**Comment by yannnz** [comment]
This is the latest design link for implementation: https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/lRzqa1x

@kaedward There were several design updates after your latest review and needs your help. I @ you in those updates.

**Comment by dgutride** [comment]
Replaced by:  https://issues.redhat.com/browse/RHOAIENG-262

**Comment by dgutride** [comment]
Moving to closed. . .
