### ISSUE TITLE
Add popovers to Model Server Modal

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1580]
### Feature description

We need to add several popovers to the Model Server Modal fields:

- Number of model server replicas to deploy:
- Model server size
- Number of GPUs

### Mockups

https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/ZVnwmoZ

**Comment by DaoDaoNoCode** [comment]
@vconzola Can you check the design here? I think we had a conversation before that we should use popover instead of tooltip here and use clicking instead of hovering for those help icons.

**Comment by vconzola** [comment]
@DaoDaoNoCode You're correct - these should be popovers, not tooltips. Designer fail. 😞 But can you hold off on this one for a bit? Jeff wanted Chris Tyler from docs to weigh in on the popover text, and I'm waiting to hear back from him.

**Comment by lucferbux** [comment]
Removing this from this sprint, we can get this once the development is completed

**Comment by lucferbux** [comment]
@vconzola @kaedward we might wanna revisit the gpu/accelerators popovers, since we are now using accelerators, so maybe we might wanna change the label a little bit
