### ISSUE TITLE
Change option name for disabling Jupyter Spawner from OdhDashboardConfig CR

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1588]
In order to block users from spawning jupyter notebooks from the Jupyter spawner (i.e., `Dashboard > Enabled page > Jupyter tile > Launch`) we can disable the notebookController option in the OdhDashboardConfig CR:

```
  notebookController:
    enabled: false
```
Users can still use workbenches (create new one, launch existing one, etc), as I think it's expected. But if I'm not wrong, the workbenches use the notebook controller too, so maybe we could change the name of the option in the CR to avoid confusion.

What do you think?

**Comment by andrewballantyne** [comment]
Was working my way through the issues I moved from `opendatahub-io/opendatahub-community` repo (a generic logging spot).

Although I agree with Sven and Berto here, this is not likely something we will handle or change at this time.

We will need to rework our flags in general. We are also undergoing some rework with the new operator -- our config needs to get updated to support more component-separation model which may impact our configurations. TBD really, but doing this change is going to impact existing installations and it's going to just be a headache of moving things around while we are nearing a state of changing the dashboard config anyways (which is part of why it's still `v1alpha1`)

Related issues: 
- https://github.com/opendatahub-io/odh-dashboard/issues/1108
- https://github.com/opendatahub-io/odh-dashboard/issues/1475

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1159
