### ISSUE TITLE
[Bug]: If workbench name is just numbers, it never starts. 

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1589]
### ODH Component

ODH Dashboard

### Current Behavior

I created a workbench called "1234". This workbench never fully starts. 

<img width="1318" alt="image" src="https://github.com/opendatahub-io/opendatahub-community/assets/32554862/f1328cef-9d45-4239-9618-dfc18cb987a4">

<img width="896" alt="image" src="https://github.com/opendatahub-io/opendatahub-community/assets/32554862/79ac76ca-a018-4786-8d5d-f86b99220aea">

<img width="1350" alt="image" src="https://github.com/opendatahub-io/opendatahub-community/assets/32554862/baa4da36-7e43-4f84-a860-ab1cd6655173">

### Expected Behavior

either don't let me create a numeric-only workbench name, or make sure it can boot up successfully. 

### Steps To Reproduce

1. create a workbench called "1234"
2. wait for it to start fully. 

### Workaround (if any)

delete and recreate with another name that includes letters. 

### Open Data Hub Version

```yml
RHODS 1.29
```

**Comment by andrewballantyne** [comment]
Right, it might be a "I'm playing around with this" kind of scenario -- but if you get into it, it looks bad for us. This is as simple as forcing the first character to be a letter. [K8s has documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names) on this and if this was one resource, it would have stopped before it was created. We get hung up on the notebook-controller doing a lot of magic for us.

**Comment by uidoyen** [comment]
@andrewballantyne @lucferbux Does this naming convention applies only for `Workbenches` name or  for others too like `DSP name`, `Create Run`, `Cluster storage`?

**Comment by ldimaggi** [comment]
FYI - if a user does create a workbench where the name starts with a number, that workbench cannot be edited (and corrected) - it must be deleted.

**Comment by lucferbux** [comment]
> @andrewballantyne @lucferbux Does this naming convention applies only for `Workbenches` name or for others too like `DSP name`, `Create Run name`, `Cluster storage name`?

This is related to workbenches, cause we prepend some values, other resources will fail since k8s resources won't allow to get just numbers.

**Comment by jbyrne-redhat** [comment]
> @jbyrne-redhat There is a laundry list of regexp and technical things we can talk about -- but maybe that's not needed.
> 
> I'd say `starts with a letter` instead of includes. I think that'll be more accurate.

ACK - thanks, @andrewballantyne.
