### ISSUE TITLE
[Bug]: access notebook server button should behave like a link

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

The `Access notebook server` button on the `Notebook server control panel` page doesn't give direct access to the server URL for the user to be able to copy it or open the link in a new browser tab. The button isn't rendered as a link in the page but rather an action.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/1ccce1c8-8eba-4112-9405-cd2cc6c5b706)

### Expected Behavior

Expect all actions that perform navigation to be rendered as links to take advantage of build in browser behavior and accessibility.

### Steps To Reproduce

1. Create a notebook server
2. navigate to the notebook control panel page `/notebookController`
3. ctrl+click on the `Access notebook server` button
4. Expected: a new window / tab to open
5. Observed: content is loaded in the current tab
6. Similarly, right click and attempt to "copy link address"
7. Observed: no option to copy link address since the button has no href.

### Workaround (if any)

1. Duplicate the tab
2. Click the `access notebook server` button

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by andrewballantyne** [comment]
JupyterHub design... 😞 We can look to improving it to be more a11y. 

cc @kywalker-rh this is outside of everyone's SME ... you're up 🙂

**Comment by kywalker-rh** [comment]
Not sure there's much for UX to do here. Makes sense to me that we would simply change the current button to a link. I think it is mostly a transparent change, unless I am missing something.

**Comment by andrewballantyne** [comment]
> Not sure there's much for UX to do here. Makes sense to me that we would simply change the current button to a link. I think it is mostly a transparent change, unless I am missing something.

Okay, not sure if we want to talk about the futures of this page on this issue -- but that makes sense to me. It was designed this way because of JupyterHub some 10 months ago lol.

**Comment by bdattoma** [comment]
@christianvogt @andrewballantyne @kywalker-rh following the same reasoning, should also these buttons have a link attached? 
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/d5738059-af10-48fd-a8f4-23c6212b3a25)
