### ISSUE TITLE
[Feature Request]: Update Shared memory size for notebook

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/odh-dashboard#1593]
### Feature description

Jupyter notebooks deployed by RHODS have the shared memory (/dev/shm) set to 64 MB. There doesn't appear to be any way to change this default. This creates issues with Pytorch running multiple workers on GPU-enabled nodes. Multiple workers significantly speed up training tasks, but a 64Mb limit forces the user to disable multiple workers. The increase in performance can be an order of magnitude faster and utilizes GPUs more optimally.

Include volumeMount to update this shared memory size, based on the notebook node  availability.

### Describe alternatives you've considered

Tried to implement this via notebook-controller itself to directly update the statefulset of the notebook.
However, that approach causes long-running notebook to restart.

### Anything else?

Pre-existing issue on notebook side: https://github.com/opendatahub-io/kubeflow/issues/111

**Comment by andrewballantyne** [comment]
@harshad16 can you fill out the title?

**Comment by harshad16** [comment]
updated it, somehow missed it earlier.
