### ISSUE TITLE
[Bug]: Page not found after installing OpenShift Pipelines

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

ODH 1.8

### Current Behavior

After installing ODH without OpenShift Pipelines the Pipelines page shows an error recommending installing OpenShift Pipelines on the following page:

https://<dashboard-route>/dependency-missing/pipelines

If you navigate back to the OpenShift console to install Pipelines without closing the Dashboard page, install pipelines, and switch back to the dashboard tab, the page updates to a "We can't find this page message".

### Expected Behavior

Redirect to the /pipelines page

### Steps To Reproduce

1. Install ODH without install pipelines
2. Navigate to the pipelines warning page in the dashboard
3. In a new tab, navigate to the OCP Console and install OpenShift Pipelines
4. Switch back to the tab that the dashboard is already open to the pipeline warning page

**Comment by manaswinidas** [comment]
I think we logged this issue already. https://github.com/opendatahub-io/odh-dashboard/issues/1547 Please confirm whether it's the same. @strangiato

**Comment by strangiato** [comment]
Yup, that is the same issue. My apologies for the duplicate.
