### ISSUE TITLE
[Feature Request]: Object Storage Browser for DS projects as part of Dashboard UI

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1602]
### Feature description

I am aware of this existing [issue](https://github.com/opendatahub-io/odh-dashboard/issues/9), but I'd like to start fresh and explain the current rationale. 

The Dashboard UI should include an Object Storage browser, which could in turn use Data Connection details to allow the end-user to either view (render) or download files stored in Object Storage. 
This should also apply to the Data Connection used by the pipeline server in a project. 

## rationale
* A lot of the people who have started working with DS pipelines have quickly realized that having access to the pipeline artifacts (both the logs, but also any kind of actual output files) is key to figuring out why things fail, or accessing critical output artifacts. However, in the current state, it is quite difficult to do so unless you are both very experienced with Object Storage AND have the right credentials for the right bucket. 

* Currently, when creating the data connection, it's extremely easy to make mistakes, and there is no quick way to validate that everything works as expected. Having an Object Storage browser would help in confirming that everything was properly entered. 

* When deploying models in a model server, the user has to enter various details and path "blind", in the sense that there is no "browse" button that lets you navigate and choose the right path. 

## requirements

* browse: navigate through the storage, view the bucket, its content, the various paths, etc...
* view: for some file type (.log, .html, .py, .jpeg, etc...) be able to see their content directly in the browser
* download: be able to select and download files and/or folders 
* linking: be able to create a "rhods-link" that opens the browser based on a combination of DSProject+DataConnection+Bucket+path , so that we can for example send the user to the right folder for the artifacts of a specific pipeline run. 
* Delete? (I am not sure if this is desirable or not).. Deleting runs in the Dashboard UI does not delete anything in Object Storage, so we might want to also give the user the ability to delete content in the browser. 

### Describe alternatives you've considered

* doing nothing
Object Storage can be confusing, and assuming people understand it well and can code around it is not a sound approach. 

* using the "default" web ui
this would be highly dependent on the type of Object Storage in use. 
it would also not confirm that data was entered accurately, since you'd be redirected to the UI which would then ask you to authenticate. And you may or may not have the right credentials handy.

**Comment by andrewballantyne** [comment]
cc @jedemo

**Comment by andrewballantyne** [comment]
Linked this to our other S3 "verify connection" tracker. I imagine they'll follow the same lifecycle.

**Comment by Xaenalt** [comment]
Recently came up in an escalated ticket that someone was specifying an incorrect path, which I suspect could have been avoided if they had such browser functionality

**Comment by dgutride** [comment]
Moved to https://issues.redhat.com/browse/RHOAIRFE-17
