### ISSUE TITLE
Auto-expand deployed models column when a model is deployed

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1605]
### Goal

Auto expand deployed models column in model serving table when a new model is deployed for an specific model server

### Dependency issue

No dependencies

### Itemized goals

- Focus the deployed models tab when a model is deployed
- Focus only the tab for the given model server row

### Mocks

- https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/j4raLEG

**Comment by DaoDaoNoCode** [comment]
Follow-up fix in #1777, this PR is merged and the issue is fully fixed. Closing it now.
