### ISSUE TITLE
[Bug]: Misplaced divider in the Global Pipelines page

### ISSUE THREAD

**Issue by manaswinidas** [opendatahub-io/odh-dashboard#1606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.13.0

### Current Behavior

There's a divider between the header and the Pipelines table on the Global Pipelines page. This is present on other pages too, but there are navigation tabs in place. We don't have any navigation tabs here.
<img width="987" alt="Screenshot 2023-07-27 at 6 50 26 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/cc55d3c9-0dc2-4776-8641-fa6e816e3555">

### Expected Behavior

Since we don't have any navigation tabs on this page, we can remove the Divider just like what we have on the Projects page.

### Steps To Reproduce

1. Go to the Pipelines page by clicking on the same in the left Navigation bar.

**Comment by lucferbux** [comment]
Good catch!

**Comment by kywalker-rh** [comment]
I don't think this really needs UX at this point. The line/divider should be removed to match other pages. It should not have been included in the original designs.
