### ISSUE TITLE
[Bug]: event log empty for new notebook that is failing to start

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

Maybe some relation to https://github.com/opendatahub-io/odh-dashboard/issues/579

My notebook server is not starting and the UI did not display any error message or event logs as to why. Dropping back to the console was the only way to understand that the dev cluster had a resource issue.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/ec3f7c79-5861-4d51-9230-70b746798806)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/70ff2669-26f6-4f95-8453-b48e0e348300)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/4c75efa2-0778-4d6a-9fb4-22418eb93e94)
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/df6af6ce-6145-44b6-a2f2-c00dff4bf430)

### Expected Behavior

Event log and / or pod status should be presented to the user to understand why it's not starting.

### Steps To Reproduce

Using a new dev cluster which has limited resources apparently.

1. create a new project
2. create a new workbench and use a large size. Consider adding a new `notebookSizes` entry to the `OdhDashboardConfig` if your notebook server still starts.
3. Observe the pod not starting.
4. Check the dashboard UI by clicking on `Starting...` and viewing the event log

### Workaround (if any)

none in the dashboard

### What browsers are you seeing the problem on?

Chrome

**Comment by christianvogt** [comment]
The `Notebook` instance has no `notebooks.kubeflow.org/last-activity` annotation and therefore the UI assumes it hasn't started.

Here's what the UI should show:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/4535dbf6-9324-4416-8cc7-ca5e8aeda11e)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/37a8aeac-181f-4c96-97d4-d2444ac69d98)

**Comment by lucferbux** [comment]
I think https://github.com/opendatahub-io/odh-dashboard/issues/793 is also related to this one right?

**Comment by christianvogt** [comment]
@lucferbux unfortunately https://github.com/opendatahub-io/odh-dashboard/issues/793 will require additional changes because the error occurs on the StatefulSet before a pod is created. I tested a fix for this issue and it had no affect on https://github.com/opendatahub-io/odh-dashboard/issues/793
