### ISSUE TITLE
[Feature Request]: GH Action for downstream releases

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1612]
### Feature description

In an effort to improve our current release flow, we want to adapt this [GH to Jira Script](https://github.com/HumairAK/gh-to-jira) and add it as a Github Action to automate the creation of a Jira Tracker issue for a release to add this information to Errata.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2540
