### ISSUE TITLE
[Bug]: Tooltip with Openshift resource information for Custom Serving Runtime is misleading

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.30

### Current Behavior

When going hover the "Question Mark" icon on a Custom Serving Runtime, it shows a tooltip saying that we can find the resource in OCP by searching among `ServingRuntime` resources. 
However, `Custom Serving Runtime`s are stored as OpenShift `Template`: the ServingRuntime CR instance will be created only after a model server get created and the name will correspond to the model server's instead of the Serving Runtime name.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/220709c8-c59e-4c6e-ab67-511bfcb14ad0)

### Expected Behavior

the tooltip reports the OpenShift template resource information: 
- resource name: template-xxxxx
- resource type: Template

### Steps To Reproduce

1. Log in to Dashboard with a Dashboard Admin user
2. go to `Settings > Serving runtimes`
3. find a Custom Serving Runtime if present, otherwise create one
4. go hove the "Question Mark" icon
5. try searching the OpenShift resource by using the information in the tooltip message

### What browsers are you seeing the problem on?

Chrome

**Comment by lucferbux** [comment]
Oh wow, I don't know how we missed this, thanks @bdattoma we'll triage this later but this should be a great "good first issue"

**Comment by Gkrumbach07** [comment]
may have conflicts with: https://github.com/opendatahub-io/odh-dashboard/issues/1476
