### ISSUE TITLE
[Feature Request]: remove OdhApplication file and update getting started doc links in OdhQuickStarts

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#1616]
### Feature description

Related to term and usage of Jupyterhub in Dashboard

https://github.com/opendatahub-io/odh-dashboard/issues/534

The content itself in the OdhQuickstart documentation (not the getting started links) has been improved recently, i.e. no more references to installing something via npm and conda and so on for the most part, good on odh-manifests and here

https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests/apps/jupyter

https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard/apps/jupyter

**Exept** in jupyterhub app

https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/apps/jupyter/jupyterhub-app.yaml

there is talk of npm and all that.

But, the jupyter tile will be removed at some point anyways, so then, the following OdhApplication file jupyterhub-app.yaml can be removed in the process and shall not be linked to from anywhere anymore in Dashboard, which is done via #534 

In all files remaining, there is still a getting started link to jupyterhub docs, which seems wrong.

@MelissaFlinn Can you replace the `getStartedLink` in all remaining ODHQuickstarts with 

https://opendatahub.io/docs/ 

or https://opendatahub.io/docs/getting-started-with-open-data-hub/#creating-a-project-workbench_get-started

instead of the very Jupyterhub specific link

and change the `getStartedMarkDown` to something more in line with the content of https://opendatahub.io/docs/getting-started-with-open-data-hub/#launching-jupyter-and-starting-a-notebook-server_get-started

i.e. at https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/apps/jupyter/create-jupyter-notebook-quickstart.yaml

please? Describing 

https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests/apps/jupyter

At any files except jupyterhub-app.yaml basically, since @DaoDaoNoCode already removes that file in a separate PR :-)

There are for example currently instructions like " Locate the **Jupyter** card on the **Enabled applications** page".
As discussed with @lucferbux, that point of entry for a getting started, the jupyter card, can stay for now.

**Comment by shalberd** [comment]
@MelissaFlinn awesome, thank you very much for taking this up. Also for in general being active in the area of documentation, regardless whether upstream or downstream. That is why I pinged you, nice.

**Comment by MelissaFlinn** [comment]
Hi @shalberd 
Thank you for your kind words :)

I have these follow-up questions for you:

1. In a couple of the yaml files under:
https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard/apps/jupyter
a)  **appName** is set to **jupyterhub**
Should I change **appName** to **jupyter** ?
b)  icon is 'images/jupyterhub.svg`
Should we point to a different image file?

2. For the updated `create-jupyter-notebook-quickstart.yaml`, which notebook image should the user select when the user creates a workbench? (There are several options that use Python 3.x)

3. Regarding your comment above: “even file yaml file names are kind of not right”, please explain how you’d like them to change.

**Comment by shalberd** [comment]
>a) appName is set to jupyterhub
Should I change appName to jupyter ?
b) icon is 'images/jupyterhub.svg`
Should we point to a different image file?

Yes to both, similar to what was already the idea in https://github.com/opendatahub-io/odh-dashboard/pull/1211/files#diff-078b714eaaee3abced3381a15f9765a14f95d77238075d1f70fe5f90d38abab7R11

Adding [jupyter.svg as an image from all the images](https://github.com/opendatahub-io/odh-dashboard/tree/main/frontend/src/images) available seems sensible, espeically when compared to the old jupyterhub. Yes, there is the possiblity to also work with R Studio and Visual Studio Code spawned via Kubeflow Notebook controller in odh-manifests overlays, but for the getting started, since it is about jupyter, instantiated via Kubeflow notebooks, this is good for naming and images.
