### ISSUE TITLE
[Bug]: unable to start notebook server due to duplicate values in StatefulSet

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.8.0

### Current Behavior

May be related to https://github.com/opendatahub-io/odh-dashboard/pull/1594

Starting a new notebook server generates a StatefulSet that errors out:
```
create Pod jupyter-nb-clusteradminuser1-0 in StatefulSet jupyter-nb-clusteradminuser1 failed error: Pod "jupyter-nb-clusteradminuser1-0" is invalid: [spec.volumes[4].name: Duplicate value: "shm", spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/dev/shm": must be unique]
```

### Expected Behavior

Notebook server should start successfully without error.

### Steps To Reproduce

1. Go to `Applications -> Enabled`
2. Select `Launch Application` from the `Jupyter` tile.
3. Select a notebook image and click `Start server`
4. Observe the server never starts.
5. Jump into the OpenShift Console and search for the generated `StatefulSet`. This can be done through the `Administrator` perspective or the topology view.
6. View the events for this StatefulSet and observe the error.

_Note that the dashboard UI doesn't show the error due to another outstanding bug._

### Workaround (if any)

Manually by editing the `Notebook` resource via CLI or OpenShift console:
- Edit the `Notebook` resource that was created
- Remove all entries related to `shm`. These are the duplicate entries that show up in the StatefulSet:
```
            - name: shm
              mountPath: /dev/shm
```
```
        - name: shm
          emptyDir:
            medium: Memory
```
- Remove the `kubeflow-resource-stopped` annotation.

### What browsers are you seeing the problem on?

Chrome

**Comment by harshad16** [comment]
This is caused, as the feature to include the volumeMount `shm`:
- Earlier was included in notebook-controller: v1.7.0-1, which was later removed in v1.7.0-2
and moved to odh-dashboard.


So the latest version of odh-dashboard, would function well with notebook-controller v1.7.0-1
which was the case of this issue.

With this PR: https://github.com/opendatahub-io/odh-manifests/pull/900
odh-manifests master will have the right fix.
