### ISSUE TITLE
refactor frontend source to adhere to architecture guidelines

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1620]
### Goal

Refactor frontend source to adhere to architecture guidelines

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/pull/1573

### Itemized goals

The [architecture guidelines](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/architecture.md#coding-structure) set out to define the folder structure for the front end. These guidelines govern the import direction of code in order to define distinct layers.

New linting rules have been created to identify code which imports modules from restricted locations. See [lint results log](https://gist.github.com/christianvogt/33b140b777cd2e0bbbadd822c1b2bec6).

At a high level, there are 5 primary folders with defined code separation guidelines:
- api
- components
- concepts
- pages
- utilities

### Mocks

No mocks

**Comment by lucferbux** [comment]
@christianvogt Do you think we might need to convert this into a tracker and break down efforts?

**Comment by christianvogt** [comment]
tracked by https://issues.redhat.com/browse/RHOAIENG-2411
