### ISSUE TITLE
Edit Model server modal enhancements

### ISSUE THREAD

**Issue by manaswinidas** [opendatahub-io/odh-dashboard#1626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.13.0

### Current Behavior

When you click `Edit model server`, the `Add model server` button shows `Add` enabled with the field values intact. This is what I see after clicking on `Edit model server`
<img width="867" alt="Screenshot 2023-08-01 at 7 23 41 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/c438ea55-c4dc-4e95-b4c5-10ba61ea6c4c">

### Expected Behavior

The `Add model server` should be changed to `Edit model server` and the button should be changed to `Update`, The `Update` button should only be enabled when one or more fields are updated in the modal(consistent with the other modals)

### Steps To Reproduce

1. Go to `Models and Model servers` in DS projects
2. Click on the `Edit model server` button from the Kebab menu(You may have to add a model server and deploy model if you haven't done that already, so that you can "edit" it)

**Comment by lucferbux** [comment]
@manaswinidas wow great catch, not sure what has happened here that we've missed this one!

**Comment by lucferbux** [comment]
@manaswinidas I'm gonna add this one to the enhancement tracker I have for model serving, let me change this to a story.
