### ISSUE TITLE
[Feature Request]: Allow users to change the generated resource name for workbenches and other components

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1627]
### Feature description

When creating any of the components in a DS Projects, users don't have the option to change the automatically generated resource name. While, it is availble when creating a DS Project. 

In order to keep consistency, we could add the same option to the rest of the components (where technically feasible). This was raised in an internal slack thread.

### Describe alternatives you've considered

remove the option from DS Project creation form (maybe not ideal)

### Anything else?

- UX to be onboarded
- originally raised internally by @xianli123 :)

**Comment by xianli123** [comment]
@bdattoma Looks good. I will come up with a design for this feature.

**Comment by xianli123** [comment]
Hi @bdattoma I created a design for this issue. Here is [the design link](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=348%3A9183&type=design&node-id=354-25459&viewport=309%2C60%2C0.06&t=IV5mvzvr5ouYe7SZ-1&scaling=scale-down-width&starting-point-node-id=354%3A25459&mode=design) for your reference. To sum up the design:

- Added a new field named **Resource name** in the workbench creation page.
- Added 2 help texts to make users better understand the naming rules. 

Please take a look and feel free to let me know if there are any concerns. Thanks!

**Comment by xianli123** [comment]
Hi @bdattoma I found that you added the **_`other components`_** in the title. Could you please elaborate on what components will show the resource name during the creation process? I can provide some designs for these parts if needed.

**Comment by kywalker-rh** [comment]
@xianli123 We should look at a way to be able to hide the "resource name" section universally as well. Some ideas to make it less prominent: use an expandable section, either controlled by the expandable caret, or a button next to or near the Name field

**Comment by xianli123** [comment]
Hi @kywalker-rh An expandable section might be better than an icon next to the Name field. I used a clickable expandable link to show the resource name as shown in the screenshot below.
<img width="690" alt="Screenshot 2023-09-26 at 17 17 13" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/a280cb94-6517-4657-acde-9f7b078d8fae">

In addition, I put a question mark next to the link. The tooltip goes that: `Resource names are what your resources are labeled in Openshift and not editable after creation. It reuses Name by default and automatically converts Name to a valid resource name.`  What do you think?
<img width="707" alt="Screenshot 2023-09-26 at 17 22 11" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/bbf1de35-ca5a-4308-90ac-22aad74c1dfb">

**Comment by kywalker-rh** [comment]
I think this looks good to me!

@andrewballantyne you had some thoughts around not wanting to use the caret, but after seeing this I'm not sure I understood your reasoning for it, can you elaborate here?

@xianli123 Two minor points, first, I think the "Resource name" label and field should be indented to make it clear there is a hierarchy, and second, we should get @kaedward to look at the text for the tooltip.

**Comment by andrewballantyne** [comment]
My point was I saw no value in wasting the vertical space on something only "power users" (for lack of a better term) will want to use. Having it as an inline "Display Name Action" allowed it to be more "extra" and less in your face.

This has to be singularly applied to all modals, pages, and flows that support Display Name changes with a backing K8s name. On the Workbench page, you have the space, on a Create Data Connection or Create Cluster Storage modal, it really didn't need to take up valuable vertical real estate... but that is my two cents -- PF may disagree with me too, so don't take me on my opinion. I just didn't want it to be always "there" taking up space.

**Comment by kaedward** [comment]
@kywalker-rh @xianli123 Looks like we already have a tooltip for this purpose: 

"Resource names are what your resources are labeled in OpenShift.
Resource names are not editable after creation."

Although I like the idea of combining these two statements into one sentence - how about this? 

"The resource name is used to identify your resource in OpenShift, and is not editable after creation."

**Comment by xianli123** [comment]
Thanks! @kywalker-rh @kaedward. 

> Looks like we already have a tooltip for this purpose
Yes. There is a tooltip in the current UI. Combining them makes more sense. I will update the design based on your suggestions!

**Comment by xianli123** [comment]
@andrewballantyne @kywalker-rh If we don't want it to always take up space, we could get rid of the expandable link. I checked the PF and found a component named **_[Form group with additional label info](https://www.patternfly.org/components/forms/form#form-group-with-additional-label-info)_**. We might change the additional label to a checkbox toggle as shown below. 
<img width="712" alt="Screenshot 2023-09-27 at 11 02 10" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/e2f87345-0223-4dc3-9e5f-fca0867b7d1f">


After marking the checkbox, the **_Resource name_** will appear. But I am not sure if PF can support this kind of change. I conveyed this idea to the PF team and am waiting for their reply. What do you think of this idea? 
<img width="778" alt="Screenshot 2023-09-27 at 11 02 34" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/3e7f9369-a081-4062-9db0-4bf30a1c774a">

**Comment by andrewballantyne** [comment]
@xianli123 (cc @kywalker-rh) The top right hand corner is not supported by PF as far as I can see in their docs, but to the right of the input field is valid space we can put something.

This is what I had in my head (obv without polish):

Start at:
![Screenshot 2023-09-27 at 9 33 49 AM](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/ead664d5-a673-474b-a312-6570efa7cc6b)

Clicking on the link does this:
![Screenshot 2023-09-27 at 9 33 55 AM](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/42bd891f-140e-47fc-8487-66cea974b802)

**Comment by xianli123** [comment]
@andrewballantyne I have noticed[ this component](https://www.patternfly.org/components/forms/form/design-guidelines#validation-with-test-button) that you proposed. However, I initially thought that the link action should only have an impact on the front field. So I gave it up. If we all agree with using this component, we can use it. What do you think? @kywalker-rh

**Comment by andrewballantyne** [comment]
@xianli123 PF is often times a composable set of items, so usually whatever you see in the docs we can do. Your linked example you used is the design guidelines, not the component itself; but I imagine they'd never recommend a non PF component in their designs.

**Comment by xianli123** [comment]
Yes @andrewballantyne. I understood. 

One more thing I want to share is that the PF team thinks we can change the additional label to the checkbox toggle. So the [approach](https://github.com/opendatahub-io/odh-dashboard/issues/1627#issuecomment-1736601833) I first shared should be possible. A PF engineer helped to build [this sandbox](https://codesandbox.io/s/festive-firefly-pf4k69?file=/index.tsx) to demo it. The video below is a demo of that. 

https://github.com/opendatahub-io/odh-dashboard/assets/53931519/ef32e49d-f876-447e-9cf6-df7f01db5008

Using a link button next to the Name field is a good approach to trigger the **Resource name**. In addition, using a checkbox toggle to show/hide the **Resource name** is also a feasible way. Which one do you prefer? What are your thoughts about these 2 approaches? @kywalker-rh 
<img width="833" alt="Screenshot 2023-09-28 at 10 07 12" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/1ed222b9-55b1-4632-bc53-7979e5c62c32">

**Comment by kywalker-rh** [comment]
@xianli123 In this use-case I prefer the toggle. The one thing I want to be sure is that this can work for other use-cases where there might be more complicated "Advanced" settings). I think it could, but just want to explore what that would look like too, to make sure we're designing something that allows us to be more consistent.

**Comment by xianli123** [comment]
@kywalker-rh If there is a hidden Advanced part, we can use the **[Field Groups](https://www.patternfly.org/components/forms/form/#field-groups)** component. We can put the advanced settings into a field group. When the checkbox are marked, the **_Advanced settings_** part will appear as a separate section. Does it make sense?
<img width="688" alt="Screenshot 2023-10-08 at 14 56 37" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/e7dca7a1-a93a-4a7d-8413-50b7acb469a7">

**Comment by xianli123** [comment]
I created a template about how to show/hide the resource name or other components. Please take a look at [the design](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1334%3A31100&type=design&node-id=1334-35808&viewport=642%2C570%2C0.17&t=0WZlbQ8nJk6mYqyJ-1&scaling=scale-down-width&starting-point-node-id=1334%3A35808&mode=design). This template will work for most situations where users show/hide resource names or advanced settings. If there is any special case, I can modify the design to suit that.

**Comment by kywalker-rh** [comment]
This looks great @xianli123! I think this works perfectly for the name and for the advanced settings in the future. I'm completely on board, let's implement this everywhere 😄

**Comment by xianli123** [comment]
@kywalker-rh Thanks for reviewing it. Let's go ahead.

**Comment by andrewballantyne** [comment]
@uidoyen and I talked about implementation of this functionality in with his current PR. I've gone ahead and moved it forward to in progress as he works on his PR.

**Comment by xianli123** [comment]
@andrewballantyne Sounds good. If there are any questions during the implementation process, please feel free to let me know.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1161
