### ISSUE TITLE
[BYON] API authentication

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-dashboard#164]
ODH Dashboard part responsible for BYON should be available to authenticated users only. This seems to be supported for frontend, though we need to ensure the backend REST API endpoints are available to authenticated users only as well. Since the API is open to the internet, anybody can initiate an import potentially adding malicious or phishing (same name as other already available images) images... This should be mitigated.

/cc @LaVLaS @dlabaj

**Comment by tumido** [comment]
This should address 

https://github.com/opendatahub-io/odh-dashboard/blob/46cb6852ea4740d6176372f86297ba08208f2490/backend/src/routes/api/notebook/notebooksUtils.ts#L130

https://github.com/opendatahub-io/odh-dashboard/blob/46cb6852ea4740d6176372f86297ba08208f2490/backend/src/types.ts#L249

**Comment by andrewballantyne** [comment]
It's an admin-only route now and thus should not have issues with authentication anymore.
