### ISSUE TITLE
Pipeline Enhancements

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1651]
### Description

Misc improvements to Pipelines to help close the gap in functionality from v1 release.

### Target Branch

`f/pipelines-enhancement`

### Requirements

N/A - We are just trying to add various items to improve the state of things.

### Itemized UX Issues

N/A - UX will be done per issue

### Itemized Dev Issues

- https://github.com/opendatahub-io/odh-dashboard/issues/1247
- https://github.com/opendatahub-io/odh-dashboard/issues/1425
- https://github.com/opendatahub-io/odh-dashboard/issues/1516
- https://github.com/opendatahub-io/odh-dashboard/issues/1242
- https://github.com/opendatahub-io/odh-dashboard/issues/1791
- https://github.com/opendatahub-io/odh-dashboard/issues/1243
- https://github.com/opendatahub-io/odh-dashboard/issues/1223

### Dependent on
- https://github.com/opendatahub-io/odh-dashboard/issues/1746

**Comment by dgutride** [comment]
Replaced by: https://issues.redhat.com/browse/RHOAIENG-260
