### ISSUE TITLE
[Bug]: It is possible to start the Pipeline Server without pipelineruns.tekton.dev CRD

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/odh-dashboard#1673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

Downstream version - RHODS 1.31.RC3

### Current Behavior

The pipeline run is in an invalid state
![image (15)](https://github.com/opendatahub-io/odh-dashboard/assets/687311/421eb82a-dd0e-45cc-a4c8-0c4fac6de6b2)

### Expected Behavior

Double-check if pipelineruns.tekton.dev CRD is present before enabling `Create a pipeline server` button in UI.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/687311/193c04db-a7cf-48a0-9e2f-62305642194b)

### Steps To Reproduce

Install OpenShift Pipeline Operator
Wait for the pod to be with `status.phase` equals Running
```
"oc get pods -n openshift-operators -l name=openshift-pipelines-operator -o json",
"openshift-pipelines-operator",
"Running",
```
Create the project, start the Pipeline Server and Run the Pipeline

I found this issue with an automation test via UI

### Workaround (if any)

Wait for
```
oc get crd pipelineruns.tekton.dev
NAME                      CREATED AT
pipelineruns.tekton.dev   2023-08-11T17:18:55Z
```

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1212
