### ISSUE TITLE
[Feature Request]: Update deploy-python-model quickstart

### ISSUE THREAD

**Issue by MelissaFlinn** [opendatahub-io/odh-dashboard#1674]
### Feature description

Update the deploy-python-model quickstart (manifests/apps/jupyter/deploy-python-model-quickstart.yaml) to demonstrate how to deploy a model with model serving (rather than with Flask).

### Anything else?

follow-up from feedback posted in this PR: https://github.com/opendatahub-io/odh-dashboard/pull/1636

**Comment by shalberd** [comment]
cool, thank you. Yes, good to keep this separate

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2957 - please add updates to this if necessary
