### ISSUE TITLE
[Bug]: OVMS Model Serving Runtime /dev/shm default might be low

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1685]
### ODH Component

Model Serving

### Current Behavior

when using the OOTB model serving in RHODS 1.30, the ovms container inside of the modelmesh pod gets auto-assigned a value for /dev/shm. 

In other runtimes (Triton) this has sometimes been shown to be too little. Yet, it seems there are no way to change that size, other than creating a new version of the OVMS runtime. 

### Expected Behavior

be able to specify the size for /dev/shm for the model runtime container. 

### Steps To Reproduce

1. exec into the ovms container
2. run ` mount | grep shm`
3. observe: 
```
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c14,c47",size=65536k)
```

ideally, this value would be higher. 65 MB is not much.

### Workaround (if any)

duplicate the OVMS runtime and add a volume and volume mount to specify a different size. 
Similar to the changes made in this commit:
https://github.com/opendatahub-io-contrib/ai-on-openshift/commit/bc6346c70226c1abab2de30a80dfa9f199ced41d

### Open Data Hub Version

```yml
RHODS 1.30
```

### Anything else

I am not sure what triggers this bug, since it was discovered by someone else using another runtime and their own models. 
I am pretty sure we would have seen the same sort of bug if the runtime was OVMS. 
We should try to investigate/reproduce in OVMS. 

I did capture one screenshot from the issue, in case this helps. 

<img width="672" alt="image" src="https://github.com/opendatahub-io/opendatahub-community/assets/32554862/adeb2727-1cd1-4521-bb9a-6d6fa8168a75">

**Comment by andrewballantyne** [comment]
Related to https://github.com/opendatahub-io/odh-dashboard/issues/1593

**Comment by shalberd** [comment]
Yes, have a look at what was implemented for notebook CRs at https://github.com/opendatahub-io/odh-dashboard/pull/1594/files

**Comment by DaoDaoNoCode** [comment]
cc @harshad16 Do you have any information on this issue?

**Comment by DaoDaoNoCode** [comment]
Ah, my bad, misread the issue, sorry for the disturbing. @harshad16

**Comment by harshad16** [comment]
Just got the opportunity to take a look at the issue.
seems like a lot of other folks have already pointed to the direction, we can solve this.
Perhaps, mounting the `/dev/shm` with empty dir could be a solution for this as well.
Reference: https://github.com/opendatahub-io/odh-dashboard/pull/1594/files

**Comment by lucferbux** [comment]
Just to add more info, we can detaill the volume mount size just like @erwangranger deatiled here https://github.com/opendatahub-io-contrib/ai-on-openshift/commit/bc6346c70226c1abab2de30a80dfa9f199ced41d.
Checking @harshad16 solution, we can either go with a non UX solution, just adding the volume mount on ServingRuntime creation, btw @DaoDaoNoCode just to avoid confusion, we are talking Serving Runtime creation (Model Server setup) not Custom Serving Runtime (Templates).
If we would like the user to control the limit, it would require some UX work, my guess is that another field in size limits for shm would be enough, but it's too specific to be something users need to set up every time.
@DaoDaoNoCode You can reach me out if you have any questions.

**Comment by shalberd** [comment]
@harshad16 @erwangranger interesting twist compared to notebooks to r[estrict the shared memory size not just by the total requests.memory.limit of the container, but also by sizeLimit](https://access.redhat.com/solutions/4417201) of shm. One side note on that I noticed: the feature called * Promote Local storage capacity isolation feature to GA [#111513](https://github.com/openshift/kubernetes/pull/111513) has only been out of tech preview since 4.12.0.

**Comment by lugi0** [comment]
Can confirm the new Volume and VolumeMount values show up correctly in the ServingRuntime yaml; after deploying a model and going into the ovms container I can also see the updated value through `mount`.
```
sh-4.4$ mount | grep shm
tmpfs on /dev/shm type tmpfs (rw,relatime,seclabel,size=2097152k)
```
Size is as specified in the YAML at 2Gi
