### ISSUE TITLE
[Bug]: Confirm which Object Storage providers are supported

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1686]
### ODH Component

None

### Current Behavior

ODH/RHODS can leverage Object Storage via the concept of Data Connections. 

These can be used in Workbenches, and for Model Serving. 
An Object Storage connection is also required to enable DS Pipelines. 

Currently, this has only been test with AWS S3 storage. 

It would be interesting to test with other, common, Object Storage providers to confirm that they too can be supported. 

The main Object Storage providers we should target are:
* AWS S3
* Ceph Object Store
* Azure Blob Storage
* Google Cloud Storage

### Expected Behavior

I'd expect all of them to work, or, for the documentation to list which ones are supported, in case they don't all work. 

### Anything else

Entered as "bug" because that was the only choice I had, although I don't consider it a bug.

**Comment by andrewballantyne** [comment]
We should document this in the UI maybe? -- that's on UX (and maybe PM) to decide. Or product documentation; we can start in our markdown files -- https://github.com/opendatahub-io/odh-dashboard/issues/1611 -- eventually moving to RHODS official document -- cc @chtyler?

@jedemo @kywalker-rh thoughts on this front? Do we want to get into showcasing potential use-cases of the Data Connections in the UI?

**Comment by strangiato** [comment]
I would add Minio to the list as well.

We have obviously already tested it and use it with demos, but good to make sure it makes it into the documentation as well.

**Comment by kywalker-rh** [comment]
While having a list in the UI could be helpful, given that the list could change without our knowledge (some things could break, other things could be added) its probably best for this to be in the official documentation. Allowing users to get to the official documentation is the best option here, but I know we also can't deep link a doc at the moment.

**Comment by manaswinidas** [comment]
Please contact QE to figure out what's the current support.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2755
