### ISSUE TITLE
[Bug]: Replace "Connected worbenches" with singular form

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.31

### Current Behavior

the Cluster storage and Data connections tables (and related Edit forms) report the text "Connected workbenches", but both the resource type are allowed to be connected to maximum one workbench per time. In fact, the plural form is not always reported. 

_Examples of places using the plural form_
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/b8a15b4e-51e3-4ea5-a046-ccfb04cda0c0)
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/a9a19f2b-85d1-4430-b8ba-1c289438ac49)

_Examples of places using the singular form_
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/baa2a941-5708-4826-8bf5-e35cdbb3f814)

### Expected Behavior

"Conneted Workbench" used everywhere for both PVs and DCs

### Steps To Reproduce

1. create a workbench `work1`
2. create a new PV `storage1`(from dashboard UI)
3. craete a new DC `conn1` (from dashboard UI)
4. check the columns names in PV and DC table
5. edit the storage1 to connect it to `work1`
6. go once again to edit form of the storage and check the section title where the connected workbench is listed

Repeat the process for the data connection `conn1`

**Comment by andrewballantyne** [comment]
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/09b97535-5445-4f70-83d0-23fc5e5efef9)

You can connect a single Data Connection to multiple Workbenches. You cannot have multiple Data Connections assigned to the same Workbench (as they are injected as env variables and thus would stomp over each other). We'll look to document this more in https://github.com/opendatahub-io/odh-dashboard/issues/1611

@bdattoma let me know if I misunderstood your request
