### ISSUE TITLE
[Bug]: After updating the config map in the workbench the pods are not restarted

### ISSUE THREAD

**Issue by diegolovison** [opendatahub-io/odh-dashboard#1699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.31

### Current Behavior

After updating the config map in the workbench the pods are not restarted

### Expected Behavior

After updating the config map in the workbench the pods are restarted

### Steps To Reproduce

Create workbench adding environment variable
Double check the value in a notebook
Change the environment variable
The workbench is not restarted and the notebook won't see the changes

### Workaround (if any)

Manually restart

**Comment by jgarciao** [comment]
Maybe, instead of restarting the workbench automatically, the dashboard could show message warning that changes won't be applied until the workbench is restarted by user

**Comment by jbyrne-redhat** [comment]
@diegolovison @jgarciao Does the following release note text sound OK?

### Workbench does not restart after configuration update

If you update a workbench configuration (for example, by changing an environment variable value) the workbench does not autotamtically restart and you do not see the changes.

**Workaround:** 
Manually restart the workbench.

**Comment by alexcreasy** [comment]
@andrewballantyne is this something we can fix from the dashboard side?

**Comment by alexcreasy** [comment]
@harshad16 is there a way to restart the notebook pods through the notebook controller?

**Comment by harshad16** [comment]
Let's opt to the annotation method,
will get the right annotation to you soon, once we have worked on this.
for restarting pods directly via notebook controller.

Opened an issue on our end for this: https://github.com/opendatahub-io/kubeflow/issues/165
will get this soon.

**Comment by harshad16** [comment]
This feature could now be implemented in odh-dashboard.
Now, with the latest feature,  using the annotation, notebook pods can be restarted.
`notebooks.opendatahub.io/notebook-restart=true`
please set the above annotation to Notebook CR metadata, for restarting the pod.
The feature, would restart the pod and remove the annotation. 
This is available from Notebook-controller version: https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-4

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1210
