### ISSUE TITLE
Add ability to process markdown/rdoc and display as documentation/tutorials

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#17]
We should restructure the dashboard to include internal documentation.  A user with no JS knowledge should be able to create a document that is parsed and adds documentation to a the navbar menu and a set of well formatted documentation.  That documentation, links specific to the ODH installation, and may also include code or notebooks.

![Screenshot from 2020-08-31 13-07-31](https://user-images.githubusercontent.com/1448375/91746701-fc5a1e00-eb8a-11ea-8757-988150245369.png)

**Comment by andrewballantyne** [comment]
Assuming quickstarts covers this now... going to close. It is an old issue.
