### ISSUE TITLE
[Feature Request]: Support a default-less StorageClass cluster in DS Projects

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1701]
### Feature description

Today we have support for Jupyter to set a `spec.notebookController.storageClassName` that allows them, if set, to override and configure the Jupyter Notebooks with PVCs containing that particular storage class value.

@shalberd has [made a request](https://github.com/opendatahub-io/opendatahub-community/issues/56#issuecomment-1688274106) for an early adoption of Storage Classes in DS Projects. We have been trying to prep for it for a while now but it seems unlikely to be done in a timely manner.

Sven's scenario is one of no default storage class on the OpenShift Cluster.

Upon talking with Sven, we have agreed to do the following on construction of new PVCs (does not apply to edit path):
- List all storage classes (all users should have access RBAC wise)
- Look for a default storage class
    - if one is found, do nothing (continue with the flow today)
    - If one is not found, read the `spec.notebookController.storageClassName` value
        - if set & in the list, use it on the name on the PVC
        - if not set, do nothing (continue with the flow today)
        - if set & not in the list, print an error to the dev console `console.error(...)` and do nothing else (continue with the flow today)

Implementation is up for debate, but I imagine all the logic will be found in the `createPVC` function. We'll have it updated to take in the DashboardConfig & it will use Promises to fetch the storage class information and do the business logic.

This design is intended to be low footprint and to allow for us to adopt the future storage class feature as a whole and improve everything across the board.

### Describe alternatives you've considered

Wait for Storage Classes -- which doesn't have a timeline, best to go forward with something small for an easy win.

### Anything else?

@shalberd has agreed to take a shot at doing this work. So I'll be DM'ing him about steps to get into the `incubation` branch.

**Comment by andrewballantyne** [comment]
I'll be assigned to this for now until we figure that out.

**Comment by shalberd** [comment]
commenting ... maybe that helps :-)

**Comment by shalberd** [comment]
regarding looking for a default storageclass, at least with oc get, it seems easy. The name column has (default) in case the default annotation is present. In future work, maybe once could make use of that to quickly get the default storageclass, if any. If I were using bash scripting, I'd just parse that or get that default one, if present, with oc get storageclasses -o jsonpath='{range .items[*].metadata}{.....

![Bildschirmfoto 2023-08-24 um 21 30 58](https://github.com/opendatahub-io/odh-dashboard/assets/21118431/e2bf9a1b-3426-4ae6-a4dc-7afc90e5ba22)

**Comment by andrewballantyne** [comment]
So when you go to do the code logic, have a look at how we do any gets for other resources:

```typescript
export const getProjects = (withLabel?: string): Promise<ProjectKind[]> =>
  k8sListResource<ProjectKind>({ // you'll likely need to create a StorageClassKind
    model: ProjectModel, // the models are pretty simple (see below)
    queryOptions: {} // you probably don't need any query options as you're not looking to get by name or namespace or label
  }).then((listResource) => listResource.items);

// The project model -- see `/frontend/src/api/models/...`
export const ProjectModel: K8sModelCommon = {
  apiVersion: 'v1',
  apiGroup: 'project.openshift.io',
  kind: 'Project',
  plural: 'projects',
};
```

**Comment by andrewballantyne** [comment]
This will need multiple iterations and we track all incubating items via trackers now. See https://github.com/opendatahub-io/odh-dashboard/issues/1919

**Comment by shalberd** [comment]
@andrewballantyne yes LOL turns out I forgot to also add my logic to the Storage Section - Add New Storage

in addition to what I implemented here for New Workbench and creation of PVC along with a notebook.

See https://github.com/opendatahub-io/odh-dashboard/pull/2503/files#r1489215627 and

https://github.com/opendatahub-io/odh-dashboard/pull/2503/files#r1489362341

**Comment by andrewballantyne** [comment]
haha, thanks @shalberd -- @alexcreasy is working to get your work in as you saw. I've got a lot of juggling of other things, so I'll leave you two discuss any questions and what have you -- Alex or you can let me know if things get stalled and needs my attention -- otherwise I'll come back through when it is all set and address getting it into `main`.
