### ISSUE TITLE
[Bug]: CRDs violate Openshift type guidelines for boolean parameters

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.14.1

### Current Behavior

Currently we use a fair amount of booleans in our CRD to manage resource enablement and feature flags. This however is against Openshift API conventions. See [docs](https://github.com/openshift/enhancements/blob/master/dev-guide/api-conventions.md#do-not-use-boolean-fields) for more info on the guideline 

### Expected Behavior

All of our CRDs boolean parameters should be replaced with somme TBD enum value instead

### Steps To Reproduce

1. look at [Openshift guidelines](url)
2. look at CRDs
3. notice violation

### Workaround (if any)

Not a blocking issue at all, but is in clear violation of guidlines

### What browsers are you seeing the problem on?

Chrome

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1209
