### ISSUE TITLE
[Investigation]: Can the Dashboard use gRPC?

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1712]
### Feature description

What would be the effort to try and support gRPC?

Some resources
* https://grpc.io/blog/state-of-grpc-web/
* https://learn.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-7.0
* https://github.com/grpc/grpc-web

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2956
