### ISSUE TITLE
[Bug]: Elyra rbac already exists error

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.31

### Current Behavior

Spawner shows an error Error creating workbench, rolebindings.rbac.authorization.k8s.io "elyra-pipelines-notebook-name" already exists.
![](https://issues.redhat.com/secure/attachment/13024561/13024561_Screenshot+from+2023-08-25+10-15-36.png)

### Expected Behavior

Workbench is created without error

### Steps To Reproduce

1. Create a DS Project
2. Create a Pipeline Server
3. Create Notebook
4. Delete Notebook
5. Create Notebook with the same name

### Workaround (if any)

None

**Comment by andrewballantyne** [comment]
To the dev who picks this up: This should be able to be handled through `Owner` references in the K8s object. Investigate that as part of the solution.

**Comment by manosnoam** [comment]
The described steps to reproduce works, and the same workbench name can be created.
Note however that after deleting the workbench, it's persistent volume claim still exists, and thus when the users trt to create workbench with the same name, they need to create a new pvc, or use the one created before:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/dd9eaa82-7acb-4b00-b302-08607dba379c)
