### ISSUE TITLE
Unable to duplicate a serving runtime

### ISSUE THREAD

**Issue by vconzola** [opendatahub-io/odh-dashboard#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

main

### Current Behavior

Duplicating a pre-installed serving runtime either doesn't work, or the UX is poor, or both. There are several issues:

- When the duplicate modal is opened the title is "Add model server". It should be "Duplicate model server"
- The Add button (probably should be Create) is disabled with no explanation or guidance for the user

### Expected Behavior

We have the proper labels for duplicating OOTB Serving Runtimes

### Steps To Reproduce

1. Go to Custom Serving Runtimes
2. Duplicate an OOTB Serving Runtime

<img width="1427" alt="Screenshot 2023-09-06 at 15 32 34" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/52c4b0cb-08d2-44a9-b504-89a78696706e">

**Comment by andrewballantyne** [comment]
I moved this from the UX meeting -- this may need some additional information, due to the lack of a template. Triage team will figure that out.

**Comment by lucferbux** [comment]
> * I'm guessing that I need to either change the display-name or the name (or both) in the YAML file. When I change only the display-name the Add button is enabled, but when I click it I get an error saying the serving runtime already exists. When I change the name in the metadata I get a 403 error, which is meaningless to me. So, I'm stuck.
Mmmmm funny that you mention, we tried to fix this [here](https://github.com/opendatahub-io/odh-dashboard/commit/4d0bce286a02f1465161eeac232238f15d26fb70) basically adding a `-copy` suffix. But I didn't realize that this is just a one-shot workaround, since next time you try to duplicate it will fail, that's probably what's happening to you.
As @andrewballantyne noted, we need to improve this with parameters in the near future, but in the meantime not sure what's the best approach here
cc @vconzola

**Comment by vconzola** [comment]
@lucferbux I don't know how far out parameters are, but as an interim solution would it be possible to display a required field above the YAML where the user must enter a new name and/or display name (not sure if both need to be changed) for the duplicate? These values could then be "inserted" into the YAML when the modal is submitted. Is that possible?

**Comment by lucferbux** [comment]
Yes, we have https://github.com/opendatahub-io/odh-dashboard/issues/1260, which is part of https://github.com/opendatahub-io/odh-dashboard/issues/1312

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-552
