### ISSUE TITLE
[Bug]: Improve Logging for Starting / Completed Pods

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

f/pipeline-enhancements

### Current Behavior

Improve the starting effort -- it showcases an error in the log view as the pod is just initializing. 

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/bd8b911f-c08d-4dad-8551-c0ded3fc6b15)

Improve the ending state -- no need to keep denoting refreshing
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/e0bc3d63-9e66-47cd-ad0d-c7597dc19d80)

### Expected Behavior

Detect the state of the container -- if it is initializing, showcase that. If it's finished, disable all the on-going refresh efforts and visual support

Should support passing this "incomplete" container state knowledge off to the downloaded filename (https://github.com/opendatahub-io/odh-dashboard/pull/1724#discussion_r1311909409)

### Steps To Reproduce

1. Create a Pipeline Run
2. Select a node immediately and go to future containers / nodes as needed

**Comment by andrewballantyne** [comment]
For how we currently look at pods starting for Notebooks, we have [this code](https://github.com/opendatahub-io/odh-dashboard/blob/970fc27ecc0a7afb361a9b79a46a35597d837d92/frontend/src/pages/projects/notebook/service.ts#L6), ideally reuse this code if it's helpful.

**Comment by manaswinidas** [comment]
@yih-wang can you point me to the mocks/messages we should be showing for the above states(just making sure I didn't miss anything)? One I remember is this: https://github.com/opendatahub-io/odh-dashboard/pull/1724#issuecomment-1702233216

**Comment by yih-wang** [comment]
@manaswinidas I created this [lifecycle status summary](https://www.figma.com/proto/rJjOtl3nxpW6BAcl0MZr4y/Pipeline-log-viewer?page-id=62%3A1895&type=design&node-id=624-2327&viewport=344%2C-2019%2C0.11&t=3XnKD7cO6bo81JQW-1&scaling=min-zoom&starting-point-node-id=624%3A2327&show-proto-sidebar=1&mode=design) at some moment and I cannot remember where I shared them. I think case 2 and case 4, even case 7 in the mock are related to the current issue you are working on.

@andrewballantyne I found there are questions I'm not sure about in [Case 7](https://www.figma.com/proto/rJjOtl3nxpW6BAcl0MZr4y/Pipeline-log-viewer?page-id=62%3A1895&type=design&node-id=459-2392&viewport=-374%2C-9934%2C0.5&t=KNTzMQ3PunCKasTX-1&scaling=min-zoom&starting-point-node-id=624%3A2327&show-proto-sidebar=1&mode=design). Can you take a look and leave your insights? Thanks!

**Comment by dgutride** [comment]
Replaced by https://issues.redhat.com/browse/RHOAIENG-256 - moving to closed
