### ISSUE TITLE
[Feature Request]: Terminology for Pipeline Logs

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1736]
### Feature description

Follow up on https://github.com/opendatahub-io/odh-dashboard/issues/1247

`Containers` is our UI focus right now. 
`Steps` is Tekton's run state.

Should we look to talk more about steps and less about pure log containers. We may want to look at improving log-based naming? We talk about pods in errors because K8s talks about it. We could look to try and not show errors flat footed -- but it may be difficult.

**Comment by andrewballantyne** [comment]
cc @yih-wang

**Comment by andrewballantyne** [comment]
Let us change anywhere `Containers` is display in the Pipeline Logs view and turn it to `Steps`.

cc @yih-wang

**Comment by yih-wang** [comment]
@andrewballantyne When I updated the terminology for the group title within the Step dropdown, this question occurred to me - is it true that we decided not to show the init containers in the Containers (currently named Steps) dropdown?

**Comment by andrewballantyne** [comment]
Yeah, unless you know of a value add to show init containers, I see no reason to add them. @yih-wang These are Pipeline Logs, not Pod investigation screens... I think we should probably stick to the singular goal. If we want more pod information, perhaps we rollout another tab for that.

**Comment by yih-wang** [comment]
Thanks for the clarification @andrewballantyne. That makes sense. I just updated the dropdown example inside the `Step` dropdown to align with the decision.

I've made the change from 'Containers' to 'Steps' in the final design link (the one provided in #1247 ). Is there a specific place or document where I should note this change apart from the design itself?

**Comment by andrewballantyne** [comment]
> Thanks for the clarification @andrewballantyne. That makes sense. I just updated the dropdown example inside the `Step` dropdown to align with the decision.
> 
> I've made the change from 'Containers' to 'Steps' in the final design link (the one provided in #1247 ). Is there a specific place where I should note this change apart from the design itself?

@yih-wang here will be fine. We can use this ticket to adjust the text.
