### ISSUE TITLE
[Bug]:  Cannot create a WorkBench which name starts with a number

### ISSUE THREAD

**Issue by FedeAlonso** [opendatahub-io/odh-dashboard#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.32.0

### Current Behavior

A user can not create a Workbench if the name starts with a number (eg: '123_workbench_name')

### Expected Behavior

Users should be notified if they try to create a Workbench which does not comply with the regex '[a-z]([-a-z0-9]*[a-z0-9])?' 

### Steps To Reproduce

1. Get into a project ('Data Science Projects' -> <selected_project>)
2. Click on 'Create workbench'
3. Fill the fields using a numeric prefix: e.g:
- Name: '123_name'
- Description: empty
- Cluster Storage Name : '123_cs_name'
- Cluster Storage Description: empty
- Use a Data Connection: Checked
- Data connection Name: '123_dc_name' 
- Data connection Access Key: '123_dc_ak'  
- Data connection Secret Key: '123_dc_sk'
- Data connection endpoint: '123_dc_ep'  
- Data connection region: '123_dc_r'  
- Data connection bucket: '123_dc_b'  
4. Click on 'Create workbench'

The new workbench will be stuck on 'Starting...' status

### Workaround (if any)

As @tarun has find:
It appears that the k8s/OpenShift API limitation. Please note that services must adhere to the following rule:
Use a name that meet the following rule: 
a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')" for field "metadata.name".

**Comment by shalberd** [comment]
well, metadata.name != metatata.labels names. Label names (key-values) must not start with numbers, that is correct.

I think this current handling has more do to with the fact that label value for label key: app

i.e.

```
metadata:
  name: workbench-test-4
  labels:
    app: workbench-test-4
```

was done to be the the same as metadata.name to keep them in line.

And for that, the [restriction applies](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set): label value: unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),

valid label value:

    must be 63 characters or less (can be empty),
    unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),
    could contain dashes (-), underscores (_), dots (.), and alphanumerics between.

I can create a project, namespace, pod, statefulset, that only has ASCII numbers at start and letters and - in it just fine, regardless of the order. But ... that only applies to metadata.name, not for the labels

By the way: metadata.annotations, i.e. description or whatever, can contain non-ASCII characters like ü, ä, and so on, but that is currently not supported by odh dashboard.

```
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: 123-tst-sven
  labels:
    kubernetes.io/metadata.name: 123-tst-sven
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
```

**Comment by pnaik1** [comment]
similiar to this issue [1589](https://github.com/opendatahub-io/odh-dashboard/issues/1589)

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1208
