### ISSUE TITLE
[Feature Request]: Add caikit/tgis as a OOTB Custom Serving Runtime

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1744]
### Feature description

Based on the effort of https://github.com/opendatahub-io/caikit-tgis-serving/pull/49, we would need `caikit` as an OOTB Custom Serving Runtime for users to manage.

### Describe alternatives you've considered

Users can already add caikit as a Custom Serving Runtime, but we would need to ship it as an Out Of The Box resource.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1268 - moving to closed
