### ISSUE TITLE
[Bug]: ExitHandler steps are not showing in Dashboard

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/odh-dashboard#1751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

Any dashboard version that includes Data Science Pipelines

### Current Behavior

For every pipeline with ExitHandlers, the pipeline graph does not show that step. For this pipeline code example below:

`@dsl.pipeline(
    name='exit-handler)
def download_and_print(url: str = 'gs://ml-pipeline-playground/shakespeare1.txt'):

    exit_task = echo_op('exit!')

    with dsl.ExitHandler(exit_task):
      ......`

A component variable named `echo_op` is handled by the `with dsl.ExitHandler` line. After the code translation to the pipeline YAML, it shows the following:

`    finally:
    - name: echo
      taskSpec:
        steps:
        - name: main`

### Expected Behavior

Below is what is expected to show. In this pipeline, the `onExit - Echo` step is the ExitHandler

![Screenshot from 2023-09-05 14-30-58](https://github.com/opendatahub-io/odh-dashboard/assets/813430/a6576472-c250-4091-94b6-10bf7b20cb94)

**Comment by andrewballantyne** [comment]
@dpanshug read up on Finally Tasks (eg Exit Handlers) in the Tekton documentation: https://tekton.dev/docs/pipelines/pipelines/#adding-finally-to-the-pipeline

**Comment by dpanshug** [comment]
@rimolive can you pls provide pipeline yaml to reproduce it?

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-574
