### ISSUE TITLE
[Bug]: When trying to display model info, all models info is displayed

### ISSUE THREAD

**Issue by FedeAlonso** [opendatahub-io/odh-dashboard#1756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.32.0

### Current Behavior

When a User clicks on the number which represents the number of quantity of model which are deployed in a model server (in the project view), if the user has more than one model servers, the info of all deployed models (even in different servers) will be displayed.
The same happens if any of those servers has the Tokens enabled. All of them will open at the same time, showing the alert 'Tokens Disabled' in the servers which has the tokens disabled.

![Peek 2023-09-06 10-22](https://github.com/opendatahub-io/odh-dashboard/assets/31654558/78b268cc-975b-4fce-9c39-da3ad0de6d7d)

### Expected Behavior

Clicking in one model info should show just the info of the model clicked.
Same should happen with the tokens.

### Steps To Reproduce

1. login (as an admin) and go to "Data Science Projects" -> "Create new project". Fill the name of the project.
2. Inside the project config, go down to "Models and model servers"
3. Create one model server without Token
4. Create one model server with token
5. If the user clicks on the "1" displayed in the Tokens column (in the "Models and model servers" grid) all token info of both mode servers will be displayed
6. If the user clicks on one of the zeroes displayed on the "Deployed models" column (in the "Models and model servers" grid) , it will display the message "No deployed models" in both servers. 
7. If we have deployed a model in one (or both) of the servers, then the info of the model will be displayed (e.g.: the endpoint) instead of the  "No deployed models" message

### Workaround (if any)

No need, it's an UX bug which does not block any info or data, but it's a little bit unintuitive.

### What browsers are you seeing the problem on?

Chrome

**Comment by vconzola** [comment]
FWIW, this is a regression. The UI used to handle the row expansion properly.

**Comment by lucferbux** [comment]
Ah yes, this is totally a regression, I should have realized that cause we had this issue initially, add a fix by having the state inside the component and reverted back here https://github.com/opendatahub-io/odh-dashboard/pull/1646 
@DaoDaoNoCode curious why we moved the state up in the component, was it related with the scroll behaviour?

**Comment by DaoDaoNoCode** [comment]
@lucferbux It's because we want to expand the `Deployed models` tab when the user deploys a new model to indicate the changes in the model numbers. Refer to the code here https://github.com/opendatahub-io/odh-dashboard/pull/1646/files#diff-bc437fc442f3702adee24b7c009181e5fc76d0c6156bbe770c852f326088e1c2R93. That's why we lift it up. I can look into a solution here after this ticket is triaged.

**Comment by lucferbux** [comment]
> @lucferbux It's because we want to expand the `Deployed models` tab when the user deploys a new model to indicate the changes in the model numbers. Refer to the code here https://github.com/opendatahub-io/odh-dashboard/pull/1646/files#diff-bc437fc442f3702adee24b7c009181e5fc76d0c6156bbe770c852f326088e1c2R93. That's why we lift it up. I can look into a solution here after this ticket is triaged.

Okk, that makes sense, perfect, we can check a solution after triage!
