### ISSUE TITLE
[Bug]: UX: jupyter notebook server creation - may be confusing when user press ESC btn

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/odh-dashboard#1757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.32RC6

### Current Behavior

When creating the Jupyter notebook server from the Jupyter spawner (Applications -> Enabled -> Jupyter)  there is a modal window showed to user with the progress bar. Once the server is ready and running the user can choose from two buttons in the Web UI - open in new tab and open in current tab. Although, in case that user has the Jupyter tab already opened from previous session, or simply just because user wants, it can also intuitively click the escape button on the keyboard. In such case the modal window disappears and no running jupyter server is actually available for the user at this point.

It's required to click on one of the buttons mentioned above so that the Web UI is updated to the state where it shows the jupyter notebook server is running.

### Expected Behavior

Jupyter server should be prepared and running even after pressing the ESC button as the modal window text mentioned. Or there should be some info that if this modal window is closed without choosing one of the options below, the running instance will be killed.

The UI view in the background of the modal window should be updated accordingly too in case that ESC button is pressed and modal window is closed.

### Steps To Reproduce

1. Go to RHODS -> applications -> enabled -> launch Jupyter application
2. Choose any of the images and click on Start server button, see [jupyter-notebook-start-1.png](https://issues.redhat.com/secure/attachment/13028378/13028378_jupyter-notebook-start-1.png)
3. Wait till the server is created, see [jupyter-notebook-start-2.png](https://issues.redhat.com/secure/attachment/13028377/13028377_jupyter-notebook-start-2.png)
4. Instead of clicking on any of the available buttons, simply press ESC on your keyboard
5. You can see that you're back on your [jupyter-notebook-start-1.png](https://issues.redhat.com/secure/attachment/13028378/13028378_jupyter-notebook-start-1.png) screen and no server is running instead of seeing the expected [jupyter-notebook-start-3.png](https://issues.redhat.com/secure/attachment/13028379/13028379_jupyter-notebook-start-3.png) screen with some Jupyter notebook server running and available

### What browsers are you seeing the problem on?

Chrome

### Anything else

Checked only in Chrome not in any other browser.

This issue was created per discussion from this Jira https://issues.redhat.com/browse/RHODS-11648.

**Comment by DaoDaoNoCode** [comment]
@kywalker-rh @andrewballantyne The Jupyter tile has a weird flow, we should look at this.

**Comment by dgutride** [comment]
Tracking in jira now - reopened original issue.  https://issues.redhat.com/browse/RHOAIENG-2447
