### ISSUE TITLE
[Bug]: Error duplicating OOTB Custom Serving Runtimes several Times

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

main

### Current Behavior

Follow up of #1680 

When creating a new cloned OOTB Custom Serving Runtime, we added this logic:

metadata.name -> ${metadata.name}-copy

If the `metadata.name` is not changed, it work the first time (there's no other Custom Serving Runtime with that name), we might need to indicate the user that **they need to change both Display Name and `metadata.name`**

As per @vconzola comment:

- I'm guessing that I need to either change the display-name or the name (or both) in the YAML file. When I change only the display-name the Add button is enabled, but when I click it I get an error saying the serving runtime already exists. When I change the name in the metadata I get a 403 error, which is meaningless to me. So, I'm stuck.

### Expected Behavior

Users are aware that they need to change Display Name and `metadata.name`

### Steps To Reproduce

1. Go to Custom Serving Runtimes
2. Duplicate an OOTB Serving Runtime
3. Submit that Serving Runtime without changing any value
4. Duplicate again the Serving Runtime
5. Check that it will fail due to duplicate names

<img width="497" alt="Screenshot 2023-09-06 at 15 23 54" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/9d5cbd6c-077a-417c-9dba-836bfbff5042">

### Workaround (if any)

Just changin the `metadata.name` is enough.

**Comment by lucferbux** [comment]
@vconzola I was trying to replicate your comment, but it's not giving me a 403 once I change the `metadata.name`, can you try that again an share the steps?

**Comment by DaoDaoNoCode** [comment]
@vconzola @lucferbux We will need to together and discuss the next step.

**Comment by christianvogt** [comment]
Kubernetes does support name generation by setting the `generateName` field. So if we set `generateName: something-copy-` instead of `name: something-copy` it would result in a name of `something-copy-h487z` for example.

Unfortunately you cannot try this out today because we currently have custom validation that requires a name or otherwise results in an error:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/b78883b4-89b1-4f77-ba90-9d5a37a77f79)

We could generate the YAML as follows with the `generateName` property and a comment to guide the user if they want to specify a specific resource name:
```
  # <explain the result of generateName along with instructions on how to specify the name directly> 
  generateName: ovms-copy-
  #name: ovms-copy
```

**Comment by bredamc** [comment]
@lucferbux If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by bredamc** [comment]
@andrewballantyne If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by bredamc** [comment]
@andrewballantyne Suggested text -- let me know what you think:

"
[ODH-DASHBOARD-1758](https://github.com/opendatahub-io/odh-dashboard/issues/1758) - Error duplicating OOTB custom serving runtimes several times

If you duplicate a model-serving runtime several times, the duplication fails with the Serving runtime name "<name>" already exists error message.
"

**Comment by andrewballantyne** [comment]
@bredamc That works, thanks!

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1207
