### ISSUE TITLE
[Story]: The UX of Data Connections Is Rough -- Endpoint Missing

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

v2.13.0

### Current Behavior

In https://github.com/opendatahub-io/odh-dashboard/issues/1381 we removed the AWS specifics... but it seems to have increased the barrier to entry.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/32057340-4360-4d54-9447-1daacd49052f)

If you just want to use the AWS defaults we had, you now have to know about the endpoint value. There has been some feedback ([internal slack](https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1694026608710769)) about an expectation that if there is no value provided, we would assume it was S3. Overriding should still remain easy.

### Expected Behavior

EDIT: Change of plans -- simplified direction was added by Guillaume on slack:

- endpoint should be blank and optional with only a tool tip showing the format if someone wants to override.
- region can have a placeholder/default set at `us-east-1`.
- If there is nothing entered in both fields, we set the region to us-east-1 and the endpoint to `https://s3.us-east-1.amazonaws.com/`
-  If there is nothing entered in endpoint but there is something for region, we set the region to what was entered and the endpoint to `https://s3.region.amazonaws.com/`
- If there is an endpoint entered but no region, we set the region to `us-east-1` and the endpoint to what was entered.
- If there are entries in both fields, we set the values to exactly what was entered.

### Steps To Reproduce

1. Navigate to a DS Project (or create one)
2. Create a Data Connection

### Workaround (if any)

Know the endpoint.

**Comment by andrewballantyne** [comment]
@manaswinidas can you make sure you add the info icon too with the popover? As [Kun noted in these mocks](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1173%3A66160&type=design&node-id=1173-66792&viewport=435%2C420%2C0.09&t=FrdO4rrvKScokAA7-1&scaling=scale-down&starting-point-node-id=1173%3A66161). We'll likely need @kaedward to do a once over on the wording.

**Comment by kaedward** [comment]
@andrewballantyne The popover content? The mocks won't load for me, can you add an image here?

**Comment by andrewballantyne** [comment]
@kaedward I think the tooltip is going to wait -- there is still future discussion going on how to make it more meaningful to the user. I suspect your wording skills may not be needed just yet. ([internal slack thread](https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1694616029472549?thread_ts=1694026608.710769&cid=C03UGJY6Z1A))

**Comment by andrewballantyne** [comment]
@xianli123 I have updated the description => Expected Behavior to be what Guillaume mentioned in slack. Only question is what is the tooltip for the endpoint? Do we want one first pass? Maybe something like: 
```
Format: https://s3.REGION.amazonaws.com 
Example: https://s3.us-east-1.amazonaws.com
```

cc @manaswinidas as you already are aware, just keeping you in the loop

**Comment by andrewballantyne** [comment]
Removing 1.33 label -- may add it back if we can squeak it in before the end of the week.

**Comment by xianli123** [comment]
@andrewballantyne Thanks! I shared the latest design in the [internal slack thread](https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1694616029472549?thread_ts=1694026608.710769&cid=C03UGJY6Z1A) and wait for feedback. When I get the final decision, I can update the design asap.

**Comment by andrewballantyne** [comment]
@manaswinidas I have removed you from this issue -- let UX figure out a solution. We may swing through with something small but let us not rush it.

**Comment by xianli123** [comment]
Here is [the new design link](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1354%3A78568&type=design&node-id=1354-84277&viewport=352%2C180%2C0.06&t=mNMNnUn1zqI3fpyY-1&scaling=contain&starting-point-node-id=1354%3A84277&mode=design) of this issue. The main updates are listed below:

- The creation step is divided into 2 steps. Firstly, users need to select the type including "AWS S3" and "S3-compatible".Secondly, they can fill out the form.
- The provider info has been removed from the table. It isn't useful after the data connection is created.

If there are any comments or new requirements, please ping me here!

**Comment by andrewballantyne** [comment]
We'll want to break this in parts, where things like "test connection" can be done separately.

**Comment by xianli123** [comment]
@andrewballantyne Do you have any thoughts about breaking it down?

**Comment by andrewballantyne** [comment]
@xianli123 We will break it up as we approach the work. Nothing needs to happen now, does it?

**Comment by xianli123** [comment]
@andrewballantyne Yes.

**Comment by andrewballantyne** [comment]
Migrated... https://issues.redhat.com/browse/RHOAIENG-1812

**Comment by andrewballantyne** [comment]
Took the UX effort as it was noted in https://github.com/opendatahub-io/odh-dashboard/issues/1763#issuecomment-1776718662 to https://issues.redhat.com/browse/RHOAIUX-20
