### ISSUE TITLE
[Bug]: Usage data collection  is getting reset after RHODS upgrade

### ISSUE THREAD

**Issue by tarukumar** [opendatahub-io/odh-dashboard#1767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Current Behavior

The usage data collection setting is getting reset after the upgrade

### Expected Behavior

Usage data collection seeting should not reset

### Steps To Reproduce

1. Launch RHODS dashboard
2. go to Settings->Cluster setting -> uncheck the `Allow collection of usage data` under Usage data collection
3. Save Changes
4. Upgrade the cluster to latest build

RHODS-11791(Downstream issue)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else

There was old issue that seemed to have been misplaced and I couldn't locate it yesterday in jira. That's why I decided to open a new one.

**Comment by bredamc** [comment]
@DaoDaoNoCode If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by bredamc** [comment]
@andrewballantyne If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by andrewballantyne** [comment]
@bredamc I'm not quite sure how this happens... I have not seen this issue myself, so I'm unsure what to put as a release note.

I think there is something funky happening here... I don't think this is as clear cut as the bug states it is.

There appears to be [a release note](https://issues.redhat.com/browse/RHODS-11791?focusedId=22995869&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22995869) in the Jira when it was first logged. Maybe go with that?

**Comment by bredamc** [comment]
Thanks @andrewballantyne  -- this issue was actually already documented in 1.33 as RHODS-11791, so I've just updated that section to add a link to this Git issue.

**Comment by jgarciao** [comment]
This is still happening when upgrading OpenShift AI 2.4 > 2.5rc2

**Comment by andrewballantyne** [comment]
@jgarciao This seems very odd... We need to figure out what's happening here, because an "upgrade" shouldn't touch any of this unless some other component is over-reaching. I need to see what the setting state is in and ask for more output before and after an upgrade. This field can't just be "reset" without someone intentionally doing something 😕

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1205
