### ISSUE TITLE
[Bug]: RHODS UX inconsistencies across projects/pipelines/serving

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1774]
### ODH Component

ODH Dashboard

### Current Behavior

* DS Project:
 
![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/393b09c5-6d30-4155-8e29-6d9e1f8a453a)

* Pipelines:

![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/34d4c3b4-43f9-4917-8b2b-720cd70e3143)

* Model Serving:

![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/73fd6f2e-7c3f-47d4-8b62-d5377e85a155)

Differences:
* In "pipelines", the project is a drop-down, and you cannot list all the pipelines from all the projects at once. 
* In "model serving", you see all servers from all projects. Project is a column, but there is no drop down for it. Only way to only see models for a single project is to use the search feature. 
*  In DS project, there is no drop down, but all projects are listed. 
 

### Expected Behavior

Ideally, the User Interfaces would provide navigation mechanisms that are similar no matter which of these screens you are in. Further to this, if a user select a specific project, they should stay within the same project until told otherwise. 

Currently, there are many navigation paths where you "lose" the selected project and have to re-select it all over again. 

### Open Data Hub Version

```yml
Tested in RHODS 1.32. (I don't know which ODH that is).
```

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1206
