### ISSUE TITLE
[Feature Request]: Use openly available Oauth Proxy image

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1779]
### Feature description

In relation to: https://github.com/opendatahub-io/opendatahub-community/issues/100

[Oauth Proxy Image](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/kustomization.yaml#L29) uses the image from registry.redhat.io, which requires authentication, and is thus not freely accessible anonymously. We should look for open alternatives to this image and update it accordingly.

### Describe alternatives you've considered

Users can access registering to Red Hat

**Comment by shalberd** [comment]
so community Openshift Users (OKD) not also have access to registry.redhat.io via the Openshift Cluster?

**Comment by lucferbux** [comment]
@shalberd mmm that's interesting, I wasn't aware of the `Red Hat Developer Program`, I'm gonna add that to the conversation  in https://github.com/opendatahub-io/opendatahub-community/issues/100 cause it's an interesting point.

**Comment by lucferbux** [comment]
@zdtsw @VaishnaviHire Is this something the operator will take over or are we expecting all the components to manage these resources? (talking about the oauth proxy)

**Comment by zdtsw** [comment]
i thought we are moving towards the SSO solution, or?

**Comment by shalberd** [comment]
@zdtsw interesting .. so for example Red Hat Single Sign On / Keycloak, for example? I was under the impression that ODH Notebook controller would need tweaks for that, i.e. ServiceMesh / Istio, but I might be wrong.

**Comment by shalberd** [comment]
it seems the ose-oauth-proxy image is only available via authenticated access to registry.redhat.io.

https://github.com/opendatahub-io/opendatahub-community/issues/100#issuecomment-1717753512

**Comment by lucferbux** [comment]
> i thought we are moving towards the SSO solution, or?
Yes, that would be ideal, I might close this issue in favor of that if we can sync about it.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2910 - Please close the new jira issue if this is no longer valid.
