### ISSUE TITLE
[Bug]: Tooltip for Started Run status

### ISSUE THREAD

**Issue by dpanshug** [opendatahub-io/odh-dashboard#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

[odh-dashboard](https://github.com/opendatahub-io/odh-dashboard) main branch

### Current Behavior

The tooltip for Run status "Started" is not there.

![Screenshot from 2023-09-13 16-31-43](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/d300ab13-0561-4d37-9f7c-6a68ecdd4697)

![Screenshot from 2023-09-13 16-29-20](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/de5de4c6-8d4e-40d0-9026-b56e073ffe03)

### Expected Behavior

Status icon under Pipelines run table should mention "Started" as a tooltip.

### Steps To Reproduce

1. Create a pipeline server and import a Pipeline.
2. Create pipeline run.
3. Redirect quickly to Runs tab and click on Triggered tab.
4. Under table for Pipeline run you can see the Run created and it's status.
5. Hover over the Icon  ![image](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/b5dae205-5b45-4f9a-a183-80d708f92ca8)
6. No tooltip is visible.

### What browsers are you seeing the problem on?

Chrome

**Comment by lucferbux** [comment]
@kaedward maybe you want to take a look at this

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1203
