### ISSUE TITLE
[Feature Request]: Revamp manifest folder for future releases

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1787]
### Feature description

In the near future, we are gonna deprecate [odh-manifests](https://github.com/opendatahub-io/odh-manifests) in favor of our manifest folder for releases. We have several issues to review before that:

- Get the correct tag for each release in the [kustomization file](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/kustomization.yaml#L27)
- Current releases are based of `incubation`. We should adapt our flow to figure out how to always add the correct manifest files (either an overlay, pointing the operator to `incubation`...)
- Files that we only support downstream are now placed in **odh-manifests** downstream, we need to figure out were to place them in the future.

**Comment by andrewballantyne** [comment]
On your first point...

> Get the correct tag for each release in the [kustomization file](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/kustomization.yaml#L27)

We may want to look at a PR to change the value just before we cut the release tag. The release process will need to be thought through on this one.

**Comment by lucferbux** [comment]
> We may want to look at a PR to change the value just before we cut the release tag. The release process will need to be thought through on this one.

Yes, that's something I had in mind, for the sake of traceability we would want to have a PR just like we have now in odh-manifest, we need to take a close look at this flow.

**Comment by andrewballantyne** [comment]
We have ODH side of things figured out. `main` stays on the latest stable main release & `vX.YY.Z` release tagged image. `incubation` uses the `nightly` build and when we release it includes the `vX.YY.Z-incubation` build.

For RHODS we will continue using the `odh-manifests` downstream and we will need to sync those each release.

We should be good to go on this front and closing this issue until we find something we'll need to address in the flow.
