### ISSUE TITLE
[KFNBC] User name check against dedicated-admins membership does not match against Google auth user with username@domain.com

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#179]
**Describe the bug**
When logging into the cluster via Google Authentication, the user is created with `<ORG USERNAME>@<Google Apps Org Domain>` as their ocp username.  When the full username is added to the `dedicated-admins` groups the Dashboard won't enable settings due to it finding the user use `<ORG USERNAME>` without the domain

I am not sure if this is restricted to Google as the Identity Provider

**Steps To Reproduce**
1. Add an OCP identity provider with [Google](https://docs.openshift.com/container-platform/4.9/authentication/identity_providers/configuring-google-identity-provider.html#configuring-google-identity-provider) for authentication
3. Add the Google user to the `dedicated-admins` group
5. Login to the ODH Dashboard and see that admin `Settings` are not visible in the UI
6. Check the OCP users to confirm that they do exists `oc get users <ORG USERNAME>@<Google Apps Org Domain>`

**Expected behavior**
The `dedicated-admins` user membership check works based on the actual OCP user name that is created 

**Workaround (if any)**
Add the shortname for the user to the `dedicated-admins` group

**Open Data Hub Version**
BYON notebook build

**Dashboard Version**
v1.0.11

**OpenShift Version**
Version #: 4.10 
Provider: OpenShift Dedicated

**Additional context**

**Comment by lucferbux** [comment]
Ok, after testing it with @samuelvl we realized that oauth proxy is stripping the  domain from the username in the `X-Forwarded-User` header.
The approach we would be using from now on would be getting the `X-Forwarded-Access-Token` header, try to fetch the user and then get name of the object.

**Comment by lugi0** [comment]
@lucferbux @samuelvl was this fix included in the 1.15 live build? I've just noticed that our testing with special usernames fails on the user `ldap-special@`; the user is able to login and access the spawner page, however in the RHODS dashboard upper right the `@` is stripped away from the username, I feel this issue and mine are one and the same.

**Comment by samuelvl** [comment]
@lugi0 I'm afraid it's not included yet. Commits that were included in RHODS live build are https://github.com/red-hat-data-services/odh-dashboard/commits/main

I will create a new live build between today and tomorrow that include latest changes, I'll let you know when it is ready

**Comment by lugi0** [comment]
@samuelvl could you also provide us with a list of fixes that are included in the live build, so that we can validate them?
The list of commits could work, but a list of issues would be even better IMHO
