### ISSUE TITLE
[Tracker]: General Global UX Improvements

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1797]
### Description

General items we want to improve so we can holistically improve the experience of the Dashboard.

### Target Branch

f/global-ux-improvements

### Requirements

Improve generically -- no backing requirements

### Itemized UX Issues

* Data Connections rework -- Ticket TBD
* https://github.com/opendatahub-io/odh-dashboard/issues/1856

### Itemized Dev Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/427
* https://github.com/opendatahub-io/odh-dashboard/issues/839
* https://github.com/opendatahub-io/odh-dashboard/issues/1824
* https://github.com/opendatahub-io/odh-dashboard/issues/2195

**Comment by dgutride** [comment]
Will be driven by PM when necessary.
