### ISSUE TITLE
Explore allowing an administrator to enable/disable ODH components from UI

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#18]
With access to the `kfdef` file, we could allow authorized users to update the installed components of Open Data Hub.  This would require authentication through "Login with OpenShift" and verify they have access.  You could allow users to customize kfdef fields with a forms wizard.

Requirements:
- Allow users to Login with OpenShift
- Allow components to be correctly:
  - installed
  - updated
  - uninstalled

![Screenshot from 2020-08-31 13-31-19](https://user-images.githubusercontent.com/1448375/91748639-4a245580-eb8e-11ea-9739-c8c233bb7baf.png)

![Screenshot from 2020-08-31 13-31-23](https://user-images.githubusercontent.com/1448375/91748635-485a9200-eb8e-11ea-9f8e-de0660e25031.png)

![Screenshot from 2020-08-31 13-30-58](https://user-images.githubusercontent.com/1448375/91748608-3c6ed000-eb8e-11ea-870a-343ea9c9114c.png)

**Comment by jkoehler-redhat** [comment]
@andrewballantyne, not on the roadmap as of yet.  We could re-evaluate.

**Comment by andrewballantyne** [comment]
Not sure this is valid anymore -- at least not with any degree of priority. We are adding more and more items to the Dashboard to control things in the YAML -- especially for admins, so it is possible we could add a configuration for components. But we now have CRDs for Applications that can help with that to some degree.

This has not had motion for 2 years. I'm going to close it to clean up our backlog. We can continue to improve things as time goes on.
