### ISSUE TITLE
Habana (accelerator) UX design for admins

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1802]
- Currently there is no requirements doc for what features Admins will need to enable Habana support, so the best reference is the existing requirements doc. This also may not need its own issue, but I wanted to create it so we have somewhere to track it if needed. Existing doc: https://docs.google.com/document/d/10HOrkt-Vm4Ir_FAggyAttFipiG-L2eZX1wTZLJtLp-c/edit?usp=sharing

**Comment by yannnz** [comment]
We prioritized the issue for this sprint. Here are the UX effort needed to iterate the design:  
1. Update the create accelerator profile page to include the tolerations. 
2. Remove the bulk delete feature for accelerators. 
3. Need more discussion about the grouping feature, which allows the admin to create group names for the labels then we don't hardcode them. The designs relevant to this include: Grouping feature on Accelerator profile setting page,  and Labels on both accelerator profile table list and  Notebook image setting page. https://github.com/opendatahub-io/odh-dashboard/issues/1373#issuecomment-1763734088

cc @kywalker-rh @xianli123

**Comment by yannnz** [comment]
The final design link for Notebook image setting page: [Notebook image setting page](https://www.sketch.com/s/c8183f89-76f5-4a23-b885-a9e404a61414/a/aMV90OPl) 

@kaedward Please help to review the content. 

cc: @andrewballantyne @Gkrumbach07

**Comment by xianli123** [comment]
I updated the designs of accelerator profiles. It includes the accelerator home page and creation page. All the designs are shared in the original issue #1375. Please take a look at that issue and designs. Thanks!

**Comment by kaedward** [comment]
@yannnz just added some content suggestions. Looking good! :-)

**Comment by dgutride** [comment]
UX work is complete - all remaining work is captured in dev issues - moving to closed (please reopen with a comment if this is incorrect).
