### ISSUE TITLE
[Tracker] Model Registry

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1804]
### Description

Incorporate a model registry into the RHODS MLOps workflow, offering a centralized repository for storing and managing models, their versions, and associated metadata. This enhancement bridges the divide between model experimentation and production processes, streamlining user collaboration, facilitating integration with model serving and deployment, and optimizing the overall efficiency of the MLOps workflow.

### Target Branch

TBD

### Requirements

[Requirements doc #1](https://docs.google.com/document/d/1mRUQ9C5Br7T3bA49H503HTq0J7F4WKySdxaWpTX-i8k/edit) (will covert over to here later)
[Requirements doc #2](https://docs.google.com/document/d/1XT0PxVp78VEyeMXKkF5qrP-fdgN4V_G9UxH2a1OpPY8/edit#heading=h.vk5ku8fmql4y)
[Proposal doc](https://docs.google.com/document/d/1G-pjdGaS2kLELsB5kYk_D4AmH-fTfnCnJOhJ8xENjx0/edit#heading=h.ds8q4xtkmu64)
[Piroritized user stories](https://docs.google.com/document/d/13Q9CT0Qx6HUxumisyWQRkvcJpVB2peKC86fs7ZXw1vQ/edit#heading=h.439yc0mcih2e)

### Itemized UX Issues

- https://github.com/opendatahub-io/sig-ml-developer-experience/issues/17
- https://github.com/opendatahub-io/odh-dashboard/issues/1806
- https://github.com/opendatahub-io/odh-dashboard/issues/1805
- https://github.com/opendatahub-io/odh-dashboard/issues/1807
- https://github.com/opendatahub-io/odh-dashboard/issues/2130
- https://github.com/opendatahub-io/odh-dashboard/issues/1808

### Itemized Dev Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1920

#### API

From the Model Registry team:

> With the OpenAPI merged on main branch, [here a "permalink"](https://github.com/opendatahub-io/model-registry/blob/main/api/openapi/model-registry.yaml) to the OpenAPI file, and [here a "permahyperlink"](https://editor.swagger.io/?url=https://raw.githubusercontent.com/opendatahub-io/model-registry/main/api/openapi/model-registry.yaml) for displaying it on a swagger.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-571
