### ISSUE TITLE
[UX]: Designs for model registration workflow

### ISSUE THREAD

**Issue by simrandhaliw** [opendatahub-io/odh-dashboard#1807]
**WHAT**
 Create UX mockups for model registration workflow.

**HOW**
- Explore design options and create UX mockups for them.
- Review the designs with stakeholders including the UX team and CCS.

**DONE**
- Design artifact that includes information about design iterations, feedback, final or latest designs, etc.
- UX team, content, and stakeholder review and acceptance.

**Guidelines**
The following steps should be adhered to:
- The final, proposed design ideas must align with PatternFly design components.
- When sharing final design details, include links to PF components used in designs, and describe component behavior in the context of the use case. Also, include the final microcopy if needed.

**Comment by yih-wang** [comment]
Final mockup 1: https://docs.google.com/document/d/1fouVoKhfg-LhHy7Vdigsqm8_HjARfatkIMU8GxIXXtQ/edit#bookmark=id.xqvg9wm1s10k

**Comment by kywalker-rh** [comment]
Copied to issue: https://issues.redhat.com/browse/RHOAIUX-14
