### ISSUE TITLE
[UX]: Model serving v2 - enhancements

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1809]
### Description

This is to track the UX changes related to Tracker issues #1810 and #1312.

### Related Issues

#1810 and #1312

**Comment by vconzola** [comment]
Refer to topic discussions here: https://docs.google.com/document/d/1izyc2sjMYcIcxLpY1MlMnpXUN_Xx1i7zw7GEH5Be4Zo/edit?usp=sharing

**Comment by vconzola** [comment]
UX issues are being tracked in other places in JIRA.
