### ISSUE TITLE
[Tracker]: Model Serving v2 - KServe Support

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1810]
## Description

We'd like to support the ability to host KServe Model Serving servers... this differs from Model Mesh (our current structure).

## Target Branch

`f/model-serving`

## Requirements

* [Model serving phase 2 requirements](https://docs.google.com/document/d/1TXLEyzpYX6inMHOlaUW8VbMxMvQ5Y9TEzHM87G9_1Yk/edit?usp=sharing) (I'm gonna update the requirements later today)

1. Model serving runtimes
   * P0: OOTB support Caikit/TGIS
   * P0: (depending on feasibility): NVidia Triton Inference Server
   * P0: Control that some Model Serving Runtimes can only be enabled in kserve

2. Support options for KServe and/or ModelMesh (support KServe - 1 model per pod or modelmesh - multiple models per pod) 

   * P0: RHODS admins should be able to configure whether they want to use KServe (single model serving + additional functionality), ModelMesh, or both
   * P0: Users should be able to select kserve or modelmesh on project creation
      * Only one can be enabled per project
   * P0: Users should be able to deploy in the global view to both kserve and modelmesh  

## Itemized UX Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1809

### General configuration

* https://github.com/opendatahub-io/odh-dashboard/issues/1939
* https://github.com/opendatahub-io/odh-dashboard/issues/1946
* https://github.com/opendatahub-io/odh-dashboard/issues/1975

### Custom Serving Runtimes

* https://github.com/opendatahub-io/odh-dashboard/issues/1912
* https://github.com/opendatahub-io/odh-dashboard/issues/1911
* https://github.com/opendatahub-io/odh-dashboard/issues/1940
* https://github.com/opendatahub-io/odh-dashboard/issues/1973
* https://github.com/opendatahub-io/odh-dashboard/issues/1989

### Admin Settings

* https://github.com/opendatahub-io/odh-dashboard/issues/1913

### Projects

* https://github.com/opendatahub-io/odh-dashboard/issues/1941
* https://github.com/opendatahub-io/odh-dashboard/issues/1944
* https://github.com/opendatahub-io/odh-dashboard/issues/1942
* https://github.com/opendatahub-io/odh-dashboard/issues/1945
* https://github.com/opendatahub-io/odh-dashboard/issues/1943
* https://github.com/opendatahub-io/odh-dashboard/issues/1947
* https://github.com/opendatahub-io/odh-dashboard/issues/1995

### Global View

* https://github.com/opendatahub-io/odh-dashboard/issues/1948

### Enhancements

* https://github.com/opendatahub-io/odh-dashboard/issues/1579
* https://github.com/opendatahub-io/odh-dashboard/issues/1581
* https://github.com/opendatahub-io/odh-dashboard/issues/1583
* https://github.com/opendatahub-io/odh-dashboard/issues/1626
* https://github.com/opendatahub-io/odh-dashboard/issues/1353
* https://github.com/opendatahub-io/odh-dashboard/issues/1998
* https://github.com/opendatahub-io/odh-dashboard/issues/2050 

---

### Incubation work

* Unit testing coverage
* Integration testing coverage
* https://github.com/opendatahub-io/odh-dashboard/issues/1995
* https://github.com/opendatahub-io/odh-dashboard/issues/1994
* https://github.com/opendatahub-io/odh-dashboard/issues/1956
* https://github.com/opendatahub-io/odh-dashboard/issues/2053
* https://github.com/opendatahub-io/odh-dashboard/issues/2049
* https://github.com/opendatahub-io/odh-dashboard/issues/2058
* https://github.com/opendatahub-io/odh-dashboard/issues/2059
* https://github.com/opendatahub-io/odh-dashboard/issues/2048
* https://github.com/opendatahub-io/odh-dashboard/issues/2079

### Incubation Enhancements (can be done post-MVP)
* https://github.com/opendatahub-io/odh-dashboard/issues/2105
* https://github.com/opendatahub-io/odh-dashboard/issues/1580 
* https://github.com/opendatahub-io/odh-dashboard/issues/1727
* https://github.com/opendatahub-io/odh-dashboard/issues/1584
* https://github.com/opendatahub-io/odh-dashboard/issues/2047
* https://github.com/opendatahub-io/odh-dashboard/issues/2052
* https://github.com/opendatahub-io/odh-dashboard/issues/2051
* https://github.com/opendatahub-io/odh-dashboard/issues/2097
* https://github.com/opendatahub-io/odh-dashboard/issues/1980
* https://github.com/opendatahub-io/odh-dashboard/issues/2132
* https://github.com/opendatahub-io/odh-dashboard/issues/2134

## Related artifacts

* [Serving runtimes settings mockups](https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/p/B2327543-5B01-4CF8-8BEB-AB3294F9B2C8/canvas)
* [Cluster settings mockups](https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/p/FF910014-D6AF-4040-8343-5FBA0E9D8921/canvas)
* [Model Serving Project mockups](https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/p/7639AE0A-CD1D-4173-B63C-4BFB01613FD6/canvas)
* [Model Serving v2 Open Discussion](https://docs.google.com/document/d/1izyc2sjMYcIcxLpY1MlMnpXUN_Xx1i7zw7GEH5Be4Zo/edit)
* [Model Serving Controller Requirements](https://github.com/opendatahub-io/kserve/issues/92)

**Comment by andrewballantyne** [comment]
cc @lucferbux please adjust this tracker to fit what we want for v2 -- I imagine some of the issues might come from: https://github.com/opendatahub-io/odh-dashboard/issues/1312

**Comment by lucferbux** [comment]
Yes, that's right, I would say all the issues for 1312 can go to v2, that old tracker was just a filler until we waited for v2, let me rework this.

**Comment by lucferbux** [comment]
[UPDATE] We are gonna keep #1323 we have some issues there that can be fixed after **kserve** is implemented, moving only the tasks that are related to kserve development

**Comment by gmarkley-VI** [comment]
Is this still on UX? Can you please update the status on this? @lucferbux @vconzola

**Comment by vconzola** [comment]
@gmarkley-VI This is a Tracker. It looks like it has a Tracker State of "UX investigation", whatever that means. I have first pass designs that were reviewed at last Thursday's UX meeting, but the UX will likely be iterated on for quite a while. This should not prevent dev work from getting started. I'm not sure when we declare Tracker issues to be "off" UX?

**Comment by andrewballantyne** [comment]
I moved this into progress -- Lucas and Juntao are working on it.

**Comment by lucferbux** [comment]
Moving the enhancements to #1313
