### ISSUE TITLE
[Tracker]: Edge Deployments

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1812]
### Description

Investigate Edge deployments

### Target Branch

[`f/edge`](https://github.com/opendatahub-io/odh-dashboard/tree/f/edge)

### Requirements

- User provides location for Model stored in S3 or Git
- Kickoff the pipeline to build -> test -> push model in immutable container

### Itemized UX Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1811

### Itemized Dev Issues
**Foundation**
* https://github.com/opendatahub-io/odh-dashboard/issues/1933
* https://github.com/opendatahub-io/odh-dashboard/issues/2061
* https://github.com/opendatahub-io/odh-dashboard/issues/2251
* https://github.com/opendatahub-io/odh-dashboard/issues/2247

**Model Registry page**
* https://github.com/opendatahub-io/odh-dashboard/issues/2062
* https://github.com/opendatahub-io/odh-dashboard/issues/2064

**ML Ops Pipelines page**
* https://github.com/opendatahub-io/odh-dashboard/issues/2248
* https://github.com/opendatahub-io/odh-dashboard/issues/2250

**Comment by Gkrumbach07** [comment]
migrated issue tracked in jira 
ref: https://issues.redhat.com/browse/RHOAIENG-216?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel
/close
