### ISSUE TITLE
Future improvements for Pipeline run log viewer

### ISSUE THREAD

**Issue by yih-wang** [opendatahub-io/odh-dashboard#1814]
Use this issue to record some features that haven't been implemented for the first pass for future reference:
1. After implementing the initial version, assess whether to mask the original notification (log content) retrieved from the server after the log ends.
2. Provide links for users to access/download the logs of completed pods. Such logs should be stored in object storage (e.g. S3).

The following features are what OpenShift is supporting that could be potentially included in our console in the future:
1. Keep one version of the previous log in case of a crash loop for reference and troubleshooting purpose
2. Find/search feature
3. Support for viewing raw log. This will open a new tab in the browser to show the whole history of the log.
4. Enhance the functionality to include support for a full-screen log viewer (expand functionality).
5. Monitoring stale logs and providing a notification with a Refresh button.

**Comment by yih-wang** [comment]
Some further clarifications:

> 1. After implementing the initial version, assess whether to mask the original notification (log content) retrieved from the server after the log ends.

We were uncertain about the information that the server would return to the log viewer once the log had completed. Now according to the screenshots in #2159 , is it true that the server doesn't return any specific message at the end of the log? If so, I think we could ignore this requirement since the status in the toolbar could totally convey the message that the log is completed.

> Provide links for users to access/download the logs of completed pods. Such logs should be stored in object storage (e.g. S3).

This has been brought up during the larger team review. The discussion is about the pod could only be kept for a period of time after it's completed, while it would be nice if users could still download these logs from S3 after the pod is not there.

**Comment by yih-wang** [comment]
> The following features are what OpenShift is supporting that could be potentially included in our console in the future:
> 
> 1. Keep one version of the previous log in case of a crash loop for reference and troubleshooting purpose

Regarding this point, you can refer to the toolbar in this [doc](https://docs.google.com/document/d/1AWimZpAodgOyr_6rNlafXncaNPYIiOi9r2ln23WwbmM/edit#heading=h.6ty1ztg6r47j). There is a [current log/previous log] dropdown next to the container selection, which allow users to view one previous version.

**Comment by yih-wang** [comment]
> 5. Monitoring stale logs and providing a notification with a Refresh button.

I have accidentally seen this alert when using OpenShift pod logs. But I don't actually know when it will show up and how to reproduce it.

**Comment by andrewballantyne** [comment]
@yih-wang When you complete this effort, can you post a message either on the [Tracker](https://github.com/opendatahub-io/odh-dashboard/issues/1746) or here and tag @alexcreasy & I? We'll need to create follow up issues that likely won't be done now.

cc @DaoDaoNoCode 

Such as going to S3 -- that's not supported today in anyway, and we need to investigate that path and if Pipelines gives us that metadata. Which may need v2 (unsure).

**Comment by yih-wang** [comment]
@andrewballantyne What is the timeline for these improvements? If it's not on an urgent schedule, I anticipate beginning work on this in mid-December at the earliest, as my current focus is primarily on Model Registry designs.

**Comment by andrewballantyne** [comment]
Based on roadmaps and what not -- I think we are looking to try and wrap everything up mid January. Sooner the better though.

**Comment by yih-wang** [comment]
@andrewballantyne I'll try to complete this within this sprint.

**Comment by manaswinidas** [comment]
Hi @yih-wang, I'm good with the second approach too but have a few concerns. 
1. I'm a bit concerned about the download icon with the dropdown. I'm afraid that the down arrow(that signifies the dropdown) may look like another option altogether(similar to all the inline actions in the toolbar). Currently, we have a kebab menu for small screens(less than 576 px). Is it okay if we go ahead with this kebab menu? Also, we need to have some space beside download to make way for the downloading spinner that appears just after we click on a download item or download button(as per https://github.com/opendatahub-io/odh-dashboard/pull/2034#issuecomment-1788653279)
This is how it looks like now(based on https://github.com/opendatahub-io/odh-dashboard/pull/2034#discussion_r1383003323)
<img width="208" alt="Screenshot 2023-12-04 at 4 59 58 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/b9328095-591e-4e0c-ae9b-1e2fb6163b60">

2. We currently have a "Step" text item beside the container dropdown. Are we getting rid of that altogether? Or does it stay for anything more than 576 px? This is a screenshot of the current design for your reference.

<img width="188" alt="Screenshot 2023-12-04 at 5 10 17 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/dc56d1d7-9602-4259-8d79-58d454c8606c">

**Comment by yih-wang** [comment]
Hi @andrewballantyne @manaswinidas, I have finalized the design for the new layout of the toolbar. This new design accommodates our current components and offers flexibility for future features. Here is a demo of what a standard-size toolbar looks like.

https://github.com/opendatahub-io/odh-dashboard/assets/23331885/35ffbfe4-042e-4b9c-8f41-aaec81b548c1



And here is what a compact version looks like
<img width="820" alt="image" src="https://github.com/opendatahub-io/odh-dashboard/assets/23331885/2efa2d20-bf56-4564-b594-22616f41b392">

I'd like to hear your feedback on this. And I could also share this in the UX meeting on Thursday if you think this solution is doable from your perspective.
