### ISSUE TITLE
It is not clear from UI why PVs mounted on root cannot be attached to other workbenches

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1815]
## Solution

Follow UX Designs: https://github.com/opendatahub-io/odh-dashboard/issues/1815#issuecomment-1757043595

* Implement a disabled Delete kebab option with tooltip
* Add the context under the field in the Edit Cluster Storage Modal

See UX for more details.

---

PV which are mounted to root folder of a workbench cannot neither be deleted or change connected workbench (until the workbench doesn't get deleted).

However, a user may not know why certain PV cannot be fully edited or deleted. A PV mounted to root doesn't even show the connected workbench in the Edit modal:

In addition, when creating a workbench, the root PVs are not displayed among the existent PV, but may not be not clear to users why.

 

I think we need to change a bit the UI to show sth like:

the connected workbench while editing the root PV and make the connected workbench immutable.
show the delete action in the 3-dots menu but disable it or enable it but prompting a warning message saying that PV cannot be deleted 
when creating a workbench with an Existent PV, the UI should show all the PV and disable the selection for the ones which are used as root for other workbenches
these are just example, UX team could think other solutions

Jira issue: https://issues.redhat.com/browse/RHODS-6247

**Comment by xianli123** [comment]
[**UX work is done**] The design has been reviewed in the Jira task [#6247](https://issues.redhat.com/browse/RHODS-6247) and [the design](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?type=design&node-id=925-51008&t=NgcUY4kNjkiFszLz-1&scaling=scale-down&page-id=875%3A40880&starting-point-node-id=875%3A40881&mode=design) was finished. Wait for the dev team to implement.

**Comment by dgutride** [comment]
Already migrated - https://issues.redhat.com/browse/RHOAIENG-1140
