### ISSUE TITLE
[Tracker]: DS Project Enhancements

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1816]
### Description

Misc improvements to the DS Projects view

### Target Branch

TBD

### Requirements

TBD

### Itemized UX Issues

* [**UX Work Done**] https://github.com/opendatahub-io/odh-dashboard/issues/1815
* https://github.com/opendatahub-io/odh-dashboard/issues/1817
* https://github.com/opendatahub-io/odh-dashboard/issues/1818
* [**UX Work Done**] https://github.com/opendatahub-io/odh-dashboard/issues/1820
* [**UX Work Done**] https://github.com/opendatahub-io/odh-dashboard/issues/1566
* [**UX Work Done**] https://github.com/opendatahub-io/odh-dashboard/issues/1520
* [**UX Work Done**] https://github.com/opendatahub-io/odh-dashboard/issues/1627
* https://github.com/opendatahub-io/odh-dashboard/issues/1271
    * https://github.com/opendatahub-io/odh-dashboard/issues/1825
    * https://github.com/opendatahub-io/odh-model-controller/issues/61
    * https://github.com/opendatahub-io/odh-dashboard/issues/1763
    * https://github.com/opendatahub-io/odh-dashboard/issues/1711
* https://github.com/opendatahub-io/odh-dashboard/issues/1917
* https://github.com/opendatahub-io/odh-dashboard/issues/1706

### Itemized Dev Issues

TBD

**Comment by dgutride** [comment]
Will be captured by feature work by PM in new board.
