### ISSUE TITLE
Overriding the starting Home Directory: is it rude?

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1817]
When using a Custom Notebook Image. 

In previous versions, when the user would log into the terminal, their location would be their home directory as defined in the image, i.e. /home/jovyan. 

Now, in recent versions, when the user logs into the image's Terminal, they land in /opt/app-root/src/. 

Upon investigation, in the YAML for the notebook pod, the following statement appears

This workingDir statement apparently overrides the defaults of the customer image. 

Jira issue: https://issues.redhat.com/browse/RHODS-6349

**Comment by dgutride** [comment]
Already in Jira from before:  https://github.com/opendatahub-io/odh-dashboard/issues/1817
