### ISSUE TITLE
Workbench fails to start when using long titles for both project and workbench

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1820]
It looks like when the sum of characters of project title plus workbench title is higher than 62 characters, the workbenches fail to start because k8s is not able to create the route

Need to think on some UX how we best expose this unilaterally to the user in a way they can opt out of it and we figure out it under the hood.

Sounds like we will cap it at 31 characters for Project K8s name and Workbench K8s name – the visible label will be open-ended as it is today.

**Comment by xianli123** [comment]
[**UX work is done**]The design has been reviewed by the dev team and completed in Q3. Here is[ the final design](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=348%3A9183&type=design&node-id=348-11314&viewport=1005%2C310%2C0.3&t=6i6qqTqMd7GQg7qt-1&scaling=scale-down-width&starting-point-node-id=348%3A11314&mode=design). If we want to show/hide the resource name, we can use [the solution](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1334%3A31100&type=design&node-id=1334-35808&viewport=642%2C570%2C0.17&t=0WZlbQ8nJk6mYqyJ-1&scaling=scale-down-width&starting-point-node-id=1334%3A35808) for the issue #1627.
