### ISSUE TITLE
[Tracker]: Prompt tuning for foundation models

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1821]
### Description

TBD

### Target Branch

TBD

### Requirements

[Draft] https://docs.google.com/document/d/1BcNb-kXlHMvCjL7RWjckGgjiSGAG1H2dAzZJjWoH9kg/edit

### Itemized UX Issues

TBD

### Itemized Dev Issues

TBD

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-568
