### ISSUE TITLE
Add a way for Users to add self-signed certificates for data connections

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1825]
Users need a way to add self-signed certificates as supported so they can use internal S3 storage instead of only public S3 storage.

See related Eng spike: https://github.com/opendatahub-io/odh-model-controller/issues/61

This may be an admin setting, but it may also be a step in the data connection creation modal. We should understand and explore all options based on our understanding of Data Scientist, ML Ops Engineers, and Admin users.

**Comment by xianli123** [comment]
I just got back from my time-off and will continue to keep an eye on this.

**Comment by kywalker-rh** [comment]
Copied to issue: https://issues.redhat.com/browse/RHOAIUX-10
