### ISSUE TITLE
[Feature Request]: Update the name in `package.json` files

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1827]
### Feature description

We had an old name `open data science`, which made the acronym `ods` instead of `odh` at first. If you check the `package.json` file in the [root folder](https://github.com/opendatahub-io/odh-dashboard/blob/main/package.json#L2) and the [backend folder](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/package.json#L2), you will find it's still called `ods-dashboard(-backend)` there. However, the [frontend](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/package.json#L2) seems to be updated to `odh-dashboard-frontend` already.

We might want to make the name consistent in the whole project. Maybe consider update the root to `odh-dashboard` and the backend to `odh-dashboard-backend`.

**Comment by andrewballantyne** [comment]
Details for what to change are below.

Root package.json:
- Change `name` to `odh-dashboard`
- Remove `description` field
- Change `version` to `2.0.0`
- Change `license` to `Apache-2.0`
- Remove `author` field

Frontend package.json
- Change `version` to `2.0.0`
- Change `license` to `Apache-2.0`
- Remove `author` field

Backend package.json
- Change `name` to `odh-dashboard-backend`
- Change `version` to `2.0.0`
- Change `license` to `Apache-2.0`
- Remove `author` field

**Comment by dgutride** [comment]
Moved to:  https://issues.redhat.com/browse/RHOAIENG-2539
