### ISSUE TITLE
[Feature Request]: Support multiple IDPs in the Impersonate User feature

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1831]
### Feature description

Filing this issue after an offline discussion with @andrewballantyne. Impersonating users fails when different IDPs are installed in the cluster. While it works fine on engineers' side where always the same IDP is being used.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/f518d82a-5dd6-444f-842e-7f518b6bf53a)

### Anything else?

Error from node server:
```
end ] [13:16:51.111] INFO (236113): Impersonating user error
[dev:backend ]     reqId: "req-7l"
[dev:backend ]     res: {
[dev:backend ]       "statusCode": 403
[dev:backend ]     }
[dev:backend ]     err: {
[dev:backend ]       "type": "ForbiddenError",
[dev:backend ]       "message": "Impersonating user error",
[dev:backend ]       "stack":
[dev:backend ]           ForbiddenError: Impersonating user error
[dev:backend ]               at createCustomError (/home/bdattoma/Documents/Projects/utils-projects/dev_odh_dashboards/odh-dashboard/backend/src/utils/requestUtils.ts:8:28)
[dev:backend ]               at /home/bdattoma/Documents/Projects/utils-projects/dev_odh_dashboards/odh-dashboard/backend/src/routes/api/dev-impersonate/index.ts:74:34
[dev:backend ]               at processTicksAndRejections (node:internal/process/task_queues:95:5)
[dev:backend ]       "code": 403,
[dev:backend ]       "explicitInternalServerError": false,
[dev:backend ]       "error": "Error impersonating user",
[dev:backend ]       "status": 403,
[dev:backend ]       "statusCode": 403,
[dev:backend ]       "expose": true
```

**Comment by andrewballantyne** [comment]
@bdattoma let us sync on testing this scenario -- I didn't get a rely from you today about bringing the cluster back up. I'll tag you on slack as well.

**Comment by lucferbux** [comment]
@bdattoma I was able to create a new user an impersonate it in my cluster, let me know if you want us to take a deeper look in your cluster in case there's an edge case we are not contemplating.

<img width="484" alt="Screenshot 2023-09-21 at 13 27 56" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/1e988f37-7611-49f4-a459-f2d2ec73b2f7">
<img width="636" alt="Screenshot 2023-09-21 at 13 19 13" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/d672e8ed-fc22-4bd5-bc64-f3b710705edc">

**Comment by andrewballantyne** [comment]
Feature works fine... we tested it on his cluster and it was a problem with the `.env.local` file. Wrong instance of the file was being used.
