### ISSUE TITLE
[UX]: Ability for admins to configure NB container sizes

### ISSUE THREAD

**Issue by ralombar** [opendatahub-io/odh-dashboard#1832]
### Description

As an admin, I need to be able to configure custom sizes for NB server sessions, so I can ensure effective usage of cluster resources.

This story is to provide an admin UI ability to configure custom NB sizes in addition to the OOTB NB sizes.

### Goals

- Ability to define custom sizes aside from standard S, M, L, XL.
- Ability to configure which sizes are available for selection in the "spawner" UI. For example, the admin might only want to surface one or two custom sizes. If there is only one size option, the selection should not be visible to users. For example, if I define a single custom size, and that's the only option available to users, there shouldn't be a user input item to select the size.

### Expected Output

- Figma mockup 

### Related Issues

- https://issues.redhat.com/browse/RHODS-3625 
- https://github.com/opendatahub-io/odh-dashboard/issues/1514

### Figma mockup link (in progress)
https://www.figma.com/file/mw31oL8KLB9mvv7AOBTuY1/Admin-UI-configure-container-sizes?type=design&node-id=0%3A1&mode=design&t=WhBbXt6K24rEZ1F6-1 

### Completed artifacts

TBD

**Comment by ralombar** [comment]
Added https://github.com/opendatahub-io/odh-dashboard/issues/1514 to ticket 1832, as this ticket 1832, is now including deployment size from Model Serving in Figma mocks.

**Comment by ralombar** [comment]
Hii @kaedward would you mind having a look and review my mockup related to this ticket please when you get the chance? https://www.figma.com/file/iySvXThLOzuv8mtxD4JfNu/Admin-UI-Configure-container-sizes---Red-Hat?type=design&node-id=255%3A482&mode=design&t=KEvRrVpQy4DdWoAk-1

**Comment by kaedward** [comment]
@ralombar Done! LMK if I missed anything you wanted feedback on, or when I should take another look :-)

**Comment by ralombar** [comment]
@kaedward Thank you so much, very much appreciated. :) You should have edit access now too if required.

**Comment by ralombar** [comment]
Hi @andrewballantyne @guimou @erwangranger, I was hoping that you could take a look at this mockup and leave any feedback you may have.

The Figma mock up is in the ticket description or here: https://www.figma.com/file/mw31oL8KLB9mvv7AOBTuY1/Admin-UI-configure-container-sizes?type=design&node-id=0%3A1&mode=design&t=sih4H5qN0FW1wlDf-1 

I also have a recording for this mockup here: https://drive.google.com/file/d/1gs8M6Im7FS1xsnyK-R1-DDiJtcT48lnm/view?usp=sharing

Thank you 

cc @kywalker-rh

**Comment by kywalker-rh** [comment]
Copied to issue: https://issues.redhat.com/browse/RHOAIUX-6
