### ISSUE TITLE
[Tech Debt]: use barrel files to expose component apis and hide internal code

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#1833]
### Feature description

We should adopt a method that allows us to selectively expose component APIs for use across the repo.

Today the app has full access to import any module from the components dir. There is also no clear structure to this directory.

Proposal is to adopt the same pattern defined here:
https://github.com/openshift/hac-infra#folder-structure-design

- Update architecture document with folder structure guidelines
- Refactor component to conform to folder structure guidelines
- Create linter rules to enforce importing only from component barrel files (index.ts)
- Refactor component imports to conform

**Comment by lucferbux** [comment]
We already have barrel files for some parts of the project, such as `api`, I like the structure attached in the description, it could be beneficial for the rest of the project.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2538
