### ISSUE TITLE
[Tracker]: Service Mesh

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1838]
### Description

Adding the ability to use Service Mesh with the dashboard

### Target Branch

`f/ossm`

### Requirements

P0 Traffic should be rerouted when Service Mesh is enabled

### Itemized UX Issues

None

### Itemized Dev Issues

- https://github.com/opendatahub-io/odh-dashboard/issues/1087
- https://github.com/opendatahub-io/odh-dashboard/issues/2060
- https://github.com/opendatahub-io/odh-dashboard/issues/1935
- https://github.com/opendatahub-io/odh-dashboard/issues/1954
- https://github.com/opendatahub-io/odh-dashboard/issues/1958
- https://github.com/opendatahub-io/odh-dashboard/issues/1914
- https://github.com/opendatahub-io/odh-dashboard/issues/2208
- Handle DSCI States & Manage Area (merge main into your branch to get this feature) -- Ticket TBD

**Comment by andrewballantyne** [comment]
Needs a follow up to clean up some things and to test our way though the issue.

**Comment by dgutride** [comment]
This is now being tracked in jira - closing in favor of that.  https://issues.redhat.com/browse/RHOAIENG-372
