### ISSUE TITLE
[UX]: Support data visualization of Runs' components

### ISSUE THREAD

**Issue by yannnz** [opendatahub-io/odh-dashboard#1844]
### Description

In Pipeline phase 2, we will support more info and tabs for Run component right side drawer. Those info include: Input/Output artifacts under Input/Output tab, tags include Data visualization,Events, ML metadata. 

Reference to requirement 4 of this doc:
[Pipeline phase 2](https://docs.google.com/document/d/1p49-opf5P3cLKdfIZlONJD_IVPPe6eg7x4tfY8A7NvU/edit)

### Goals

1. Research on what types of the data does the data scientist need, what are the usage of them and connections between the data.
2.  Design the information layout, data visualization and interactions based on the research to meet user needs.
3. Review of design within stakeholders. Iteration based on feedbacks.

### Expected Output

Design mockups that are reviewed and implementable.

**Comment by cshinn** [comment]
Recreated as https://issues.redhat.com/browse/RHOAIUX-12
