### ISSUE TITLE
[Tracker]: Remove JH Dependencies

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1845]
Blocked by v2 Operator not cleaning up files on upgrade. Which means the JH resources stay around and still pop up. Can't merge this to incubation just yet. [Internal Slack Thread](https://redhat-internal.slack.com/archives/C064Z5S84F3/p1701119760417019).

---

### Description

Remove old dependencies of jupyterhub in Notebook controller.

### Target Branch

`f/notebook-controller`

### Requirements

- P0 Remove all the dependencies of Jupyterhub
- Revamp docs to remove references to Jupyterhub

### Itemized UX Issues

None

### Itemized Dev Issues

- https://github.com/opendatahub-io/odh-dashboard/issues/534
- https://github.com/opendatahub-io/odh-dashboard/issues/1616
- https://github.com/opendatahub-io/odh-dashboard/issues/844
- https://github.com/opendatahub-io/odh-dashboard/issues/712

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-572
