### ISSUE TITLE
[UX]: Improve the hierarchy relationship of Experiences, Runs and Pipelines 

### ISSUE THREAD

**Issue by yannnz** [opendatahub-io/odh-dashboard#1847]
### Description

In the current design, we've organized the structure of Experiments, Runs and Pipelines as follow: Pipeline serve as the highest-level navigation, with Pipelines and Runs nested under it. Experiments are accessible as a tab under Runs. However, based on insights gathered from competitive research and user interviews of Model registry continuous discovery, it's prudent to revisit the hierarchy of these three items for further consideration.  

The redesign also needs to consider adding metrics under experiment, compare runs and the problem we have to fetch Runs/Pipeline versions

### Goals

Research

- Some user interview from model registry continuous discovery can be used to help this issue.
- Competitive research such as Google vertex AI and MLflow
- Review from persona user flow and discussion with BU

Design
Design exploration  of the hierarchy relationship between Experiments, Runs and Pipelines based on the research.

### Expected Output

A redesign of the connection and arrangement between Experiments, Runs and Pipelines based on the insights gathered the research and discussions with BU & Eng team. 

### Completed artifacts

Persona and user flows of MLOps pipeline with DS pipeline as part of it. 
https://miro.com/app/board/uXjVMr919V0=/?moveToWidget=3458764562590434191&cot=14

**Comment by cshinn** [comment]
Recreated as https://issues.redhat.com/browse/RHOAIUX-11
