### ISSUE TITLE
[Investigation]: Stop Run Action -- Need Confirmation?

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1848]
### Feature description

We need to determine if the stop action needs a modal for confirmation. We have one for the Workbench -- but it can be muted "indefinitely" without re-enablement... we may need a settings page so they can control these things.

**Comment by diegolovison** [comment]
Yes. Everywhere
Pipelines also has the Stop action https://github.com/opendatahub-io/odh-dashboard/issues/1282

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2902
