### ISSUE TITLE
[Feature Request]: Report the status of Custer Storage re-size process in UI

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1852]
### Feature description

When the cluster storage is getting increased in size, the user does not know the status of the storage. A specific scenario where this could be seen like a UX gap is when the corresponding workbench is stopped:

![pv-status](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/8e72c737-a176-4d1b-9a8f-a3a01e6e491c)

Steps:
1. create a workbench with a pv storage of size _n_ Gib
2. wait until the workbench is Running
3. stop the workbench
4. edit the pv storage size from UI from _n_ to _m_ (_m_ > _n_)
5. what's the status of the re-size process?
6. go back to Edit storage modal: the input box for the size can still be changed (ok) and user can even lower the requested size to _n_ < _z_ < _m_ (Even though the UI says the size can only be increased)
7. go to OCP console and check the status of the corresponding PVC object: it reports that the risezing process is waiting for a pod (i.e., workbench) to start. We could trigger this and show in the UI

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-29
