### ISSUE TITLE
[Tech Debt]: Update dev testing docs

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1853]
### Type

Dev Efficiency (eg. CI improvements, issue templates, etc)

### Source

main

### Description

Our README has outdated testing scripts defined. Update those scripts to align with what we have for testing in our [contribution guidelines](https://github.com/opendatahub-io/odh-dashboard/blob/main/CONTRIBUTING.md#debugging-and-testing). Keep it concise and don't provide too much explanation as we already have a link to the contribution guidelines for more info in that section of the readme. 

### Why?

The README is the first docs a dev will see and having commands that are out of date in this area can cause confusion.

### Anything else?

may need to follow up for any new docs created from this that use testing scripts: https://github.com/opendatahub-io/odh-dashboard/pull/1851/files#diff-6a10aca6fb48bf9b93079bd5b76607312628c0519fca4aebfdea98fc93a99e8e

**Comment by andrewballantyne** [comment]
Solution:

- Make the contributing file link out to the details in the docs folder as needed
- We shouldn't duplicate the content
- Verify the link is using local file paths and not direct URL paths

**Comment by Gkrumbach07** [comment]
already tracked in another effort now.
