### ISSUE TITLE
[Tracker]: Migrate metrics to UWM

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#1854]
### Description

The backend metrics stack is moving to UWM, we need to migrate the prometheus calls in the dashboard to fetch these from UWM for both performance and bias metrics. This will also allow users who do not have the `cluster-admin` role to view the metrics.

### Target Branch

f/mserving-metrics

### Requirements

* P0: Performance metrics should be fetched from UWM.
* P0: Performance metrics should be viewable by a project admin, without `cluster-admin` role.
* P0: Bias metrics should be fetched from UWM.
* P0: Bias metrics should be viewable by a project admin, without `cluster-admin` role.

### Itemized UX Issues

N/A

### Itemized Dev Issues

* #1780
* #1855
* #1916
* #1109

**Comment by alexcreasy** [comment]
- We're currently blocked due to `haproxy` metric queries not working on UWM - these are used for performance metrics on the dashboard.
- I've raised a WIP PR for the dashboard that demonstrates TrustyAI bias metrics working along with model server performanmce metrics, however the model performance metrics don't work due to the above issue.
- Vedant is currently working on a solution for the missing metrics that involves using native modelmesh queries - I'm awaiting an estimate of how long this solution will take, I'll update when I have that info.

**Comment by alexcreasy** [comment]
Update: We're no longer blocked waiting for the modelmesh updates for our metric queries. I've finalised a single PR that closes all issues of this tracker[1] - it is now awaiting review before merging to the feature branch.

* [1] https://github.com/opendatahub-io/odh-dashboard/pull/1891

**Comment by alexcreasy** [comment]
Update: The fix is still awaiting review. I'm working with @pnaik1 & @ppadti to get their clusters up to speed so they can perform the code review before this is merged.

**Comment by alexcreasy** [comment]
All issues are complete and this tracker is ready to be moved to incubation when Explainability phase 1 and Performance metrics are moved over.

**Comment by dgutride** [comment]
Moving remainder incubation tracking to jira:  https://issues.redhat.com/browse/RHOAIENG-241

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1785
