### ISSUE TITLE
[UX]: Investigate Onboarding & Guided Help

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1856]
### Description

> Not all users were familiar with all functionalities on a project page (e.g. pipelines, model serving, etc.). Add information icons next to each section title of a project page.  A quick start guide would also be encouraged for new users to increase familiarity easily.

User studies showed that we need to help the user understand more about the features we have.

**Comment by cshinn** [comment]
Recreated as https://issues.redhat.com/browse/RHOAIUX-9
