### ISSUE TITLE
[Feature Request]: Cleanup Empty State Text

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1857]
### Feature description

On each of our sections in the Projects view, we have a subtext that is redundant.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/9009f9ec-4457-49f5-a795-2b1d9c0b6930)

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1784
