### ISSUE TITLE
[Tracker]: Live Notifications

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1859]
### Description

We would like some way to manage live notifications in the application. The use-case would be to find out when a resource has failed.

Example:
> If any part of a created run were to fail, users would like to receive a notification of message of some kind indicating so.

### Target Branch

TBD

### Requirements

TBD

### Itemized UX Issues

TBD

### Itemized Dev Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1584

**Comment by dgutride** [comment]
Covered by other work already in jira - moving to closed.
