### ISSUE TITLE
Add CI test to require that every input and clickable element has a unique id attribute

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#186]
**Is your feature request related to a problem? Please describe.**
To support automated testing of the Dashboard UI, there should be a test to required that every input and clickable element has an `id` attribute to ensure that it is easy to find using xpath.  

**Describe the solution you'd like**
This `id` attribute name or header should be "static" and unique so that the name does not change each release can be search with relative precision when the same element appears multiple times in the page

**Describe alternatives you've considered**
CI test would be best so it could be run against every PR

**Additional context**
N/A

**Comment by andrewballantyne** [comment]
I think this is going to be duplicated by other efforts -- but I'll add it to the milestone for now and look to clean them up together after the backlog has been trimmed.

**Comment by andrewballantyne** [comment]
IDs will be added as needed when we write our tests. This does not need to be a stand alone issue.
