### ISSUE TITLE
[Bug]: Accelerators dropdown not showing in a cluster with GPU

### ISSUE THREAD

**Issue by FedeAlonso** [opendatahub-io/odh-dashboard#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.33.0

### Current Behavior

Accelerators dropdown is not shown in the different forms where it should be (Jupyter Tile, Model Serving and Workbench)

### Expected Behavior

Accelerators dropdown should be displayed in place of the old GPU dropdown

### Steps To Reproduce

1. In an OSD cluster deployed with GPU, and installed the Habana RHODS version.
2. Create a Project inside RHODS
3. Go to that project and click on 'Create Workbench'
4. There is no 'Accelerators' dropdown (neither a GPU one) in the Create Workbench form

### What browsers are you seeing the problem on?

Chrome

### Anything else

Profiles (https://github.com/rh-aiservices-bu/accelerator-profiles-testing/blob/main/manifests/acc_profiles.yaml) can be exported and then the dropdown will be displayed. But the issue is that the NVidia GPUs from the cluster, are not being detected.
After troubleshooting with @lucferbux he has found that the "configured" attribute used [here](https://github.com/opendatahub-io/odh-dashboard/blob/f/accelerator-support/backend/src/utils/resourceUtils.ts#L694) and set [here](https://github.com/opendatahub-io/odh-dashboard/blob/f/accelerator-support/backend/src/routes/api/accelerators/acceleratorUtils.ts#L51) was not present on my cluster.

**Comment by andrewballantyne** [comment]
@Gkrumbach07 do we detect on fresh install?

**Comment by Gkrumbach07** [comment]
that detection is calling simply `oc get nodes` in the backend. So the issue you are seeing is the case where you have no profiles set but have configured gpus in the cluster, which should create the _fake_ profile.

Can you verify that this text is not in the logs for the dashboard `error occurred when listing cluster nodes`

and that `oc get nodes -o yaml` shows that you have an `nvidia.com/gpu` in the resource>

**Comment by Gkrumbach07** [comment]
@andrewballantyne we only will create the migrated accelerator on a restart of the dashboard. there was a problem in the detection (?? vs || error) which prevented the migrated gpu from being created
