### ISSUE TITLE
[Feature Request]: Allow edit PV size with +/- keys from keyboard

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1867]
### Feature description

When the user is in the Edit Cluster Storage modal, they can edit the PV size by either clicking on +/- buttons in the UI or inserting a numeric value from keyboard. 
Probably, we could give a more complete experience by allowing using the +/- keys from the  keyboard as third option.

**Comment by christianvogt** [comment]
@bdattoma the arrow keys `↑` and `↓` also work to control the number input. Is that sufficient for your request?

Since we use PatternFly for our components, we would need to put through a request to their component library to support this change to ensure that we are consistent with other PatternFly based applications.

**Comment by christianvogt** [comment]
I've consulted with the PF team and it's not something they will support because the arrow keys already provide this functionality.

Note that the underlying implementation of the number input comes from the browser itself which supports arrow keys by default but not `+` or `-`.

**Comment by bdattoma** [comment]
> I've consulted with the PF team and it's not something they will support because the arrow keys already provide this functionality.
> 
> Note that the underlying implementation of the number input comes from the browser itself which supports arrow keys by default but not `+` or `-`.
> 
> Closing on the basis that we do not want to implement custom logic on top of PF that would be inconsistent and that the arrow keys provide similar functionality.

okay @christianvogt thanks!
