### ISSUE TITLE
[Operator V2] Access to DS Projects fails if DS Pipelines are disabled from DSC

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1870]
**Describe the bug**
When trying to access a Data Science Project using a non-cluster-admin user, we get a permission error related to pipelines-definition, which prevents us to use DS Projects UI

**To Reproduce**
1. Install Operator V2
2. Enable Dashboard and disable DS Pipelines in the DataScienceCluster object
3. Log In Dashboard UI with a user who has no cluster admin permissions
4. create a DS Project from Dashboard UI
5. Access the DS Project from Dashboard UI
6. See error

**Expected behavior**
No errors, user can use the DS Project UI page

**Screenshots**
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/88311595/1a519e03-ba89-4ff2-b42d-767e4a1b8d2d)

**Additional context**

- OpenShift Pipelines 1.11.1 operator is installed 
- DSC has dashboard,kserve and workbenches enabled only
- enabling datasciencepipelines solves the issue

**Comment by andrewballantyne** [comment]
I imagine this has a reliance on https://github.com/opendatahub-io/opendatahub-operator/issues/588 in some way. We could probably handle the error for this ticket by just not failing like this... but to get it right we need to rework our feature flags & rely on the DSC information.

**Comment by bdattoma** [comment]
>but to get it right we need to rework our feature flags & rely on the DSC information.

makes sense to me. However, is there still a value in having the additional feature flags in the OdhDashboardConfig CR? If yes, then the dashboard should rely on the combination of both

**Comment by andrewballantyne** [comment]
@bdattoma that's being debated... but yes, that's our current plan.

**Comment by andrewballantyne** [comment]
> @harshad16 If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

@bredamc This is a known issue for v2 operator, I don't think it applies to the v1 operator for 1.34. Aimed to be fixed in 1.35

**Comment by bredamc** [comment]
Thanks @andrewballantyne. We already mention the V2 Operator in the "Limited Availability features" section of the 1.33 Release Notes, so I wondered if we should include this issue. Fine with me to exclude it in 1.34 :)

**Comment by andrewballantyne** [comment]
> Thanks @andrewballantyne. We already mention the V2 Operator in the "Limited Availability features" section of the 1.33 Release Notes, so I wondered if we should include this issue. Fine with me to exclude it in 1.34 :)

@bredamc I don't fully know the rules of LA, so I'll follow your lead on what we want to report.

**Comment by bredamc** [comment]
@andrewballantyne We can include this issue in the self-managed version of the 1.34 Release Notes.

Here is some suggested text, please advise if we need to change it. If a workaround is available, please specify.

"
[ODH-DASHBOARD-1870](https://github.com/opendatahub-io/odh-dashboard/issues/1870) - Access to projects fails if pipelines are disabled from cluster

Red Hat OpenShift Data Science Operator V2 only: If pipelines are disabled in the DataScienceCluster object, users who are not cluster admins cannot access projects that they created. Red Hat OpenShift Data Science Operator V2 is a Limited Availability feature.
"

**Comment by andrewballantyne** [comment]
@bredamc so we need to address this two ways:

1. The workaround here is to disable DS Pipelines feature flag `OdhDashboardConfig` => `spec.dashboardConfig.disablePipelines = true`
2. I don't believe this has anything to do with permissions, I think this is just the lack of the backend component being available

So something like:

> [ODH-DASHBOARD-1870](https://github.com/opendatahub-io/odh-dashboard/issues/1870) - Access to projects fails if pipelines are disabled from cluster
> 
> Red Hat OpenShift Data Science Operator V2 only: If pipelines are disabled in the DataScienceCluster object, users cannot access projects that they created. Red Hat OpenShift Data Science Operator V2 is a Limited Availability feature.
>
> Workaround: Disable the pipelines UI in the OdhDashboardConfig (`.spec.dashboardConfig.disablePipelines = true`)

**Comment by bredamc** [comment]
@andrewballantyne Thank you for the workaround -- is the following text correct?

"
Complete the following steps as a user with `cluster-admin` permissions:

. Log in to your cluster using the `oc` client.
. Enter the following command to update the `OdhDashboardConfig` Custom Resource Definition (CRD) in the `redhat-ods-applications` application namespace:
+
----
$ oc patch OdhDashboardConfig odh-dashboard-config -n redhat-ods-applications --type=merge -p '{"spec": {"dashboardConfig": {"disablePipelines": true}}}'
----
"

**Comment by andrewballantyne** [comment]
@bredamc Small correction... it's a "CR" they are modifying, not a "CRD". The CRDs are definitions, "blueprints"; in this case it already supports the ability to disable. The CRs are resources, these are data.

The patch command should work.

**Comment by bredamc** [comment]
Great -- thanks, Andrew!

**Comment by manosnoam** [comment]
Verified scenario on RHODS 2.4:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/61218ae1-8d88-41b4-8cd3-81ac145d377b)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/a95192b4-12a8-4426-bce6-e09934eb6457)
