### ISSUE TITLE
Dashboard shows sections related to disabled components

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#1871]
**Describe the bug**
Once the dashboard is enabled, it will always show all of its subsections, i.e. it will also show sections related to (possibly) disabled components that won't work

**To Reproduce**
1. Install ODH 2.0
2. Enable dashboard
3. Go to dashboard route
4. Notice sections related to disabled components, i.e. Model Serving or Data Science Pipelines

**Expected behavior**
The dashboard should only show sections that are related to enabled components, so IMHO

- Applications > Enabled (Jupyter tile, see opendatahub-io/opendatahub-operator#365) when Workbenches is enabled
- Data Science Projects only when one of mmserving,datasciencepipelines or workbenches is enabled
- Data Science Pipelines only when datasciencepipelines is enabled
- Model Serving only when mmserving is enabled

**Screenshots**
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/d2ce6669-ec1e-4ec7-b2d5-366dfd429468)
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/282c2a89-bf7a-40ce-a0ac-ef2bfe3d1985)

**Additional context**

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2958
