### ISSUE TITLE
[Tracker]: Support Plugins & Breaking Up the Dashboard

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1873]
### Description

We want to use the SDK to break up the dashboard into plugins that can be installed at runtime.

### Target Branch

TBD

### Requirements

Conceptually:

* Operator probably needs to support installing of plugins (??)
* We need a "base app" concept
    * Base App "Chrome"
    * AppContext
    * ProjectContext (almost everything is inside a project)
        * Create project (??)
    * ?? 
* Support slices in some fashion - TBD

Tasked efforts:

* Create "chrome" base app - supports loading plugins
* Extension support
    * Navigation
        * User navigation
        * Admin navigation
    * User dropdown items
    * "Waffle icon" items
    * "Link Provider" - I would like to link to another plugin
    * Plugins can just manage their own extensions as needed
* Create plugins for each feature - TBD if we bundle as single multi-feature plugin or if we runtime load all feature plugins
* Reshape code folders into "plugins" vs "core"
* Review features (to be plugins) for items that need to change to support
    * Sharing a route to share a context
* Provide docs to showcase what we support in the base (utilities) / extensions

Needs clarification:

- Does PM roadmap need the ability to change slices adhoc?
- What are our options?
    - No code for "features" - aka Bundle at dashboard build time for the needed slices (includes as many "feature plugins" as needed)
    - All code is present, but off by default / no support - aka Feature flags

### Itemized UX Issues

- Investigate project creation changes (??)

### Itemized Dev Issues

TBD

**Comment by strangiato** [comment]
Have you considered going down the [OpenShift Console Plugin](https://cloud.redhat.com/blog/developing-an-openshift-dynamic-console-plugin-1) route?

**Comment by andrewballantyne** [comment]
@strangiato I asked this question once of @jedemo and I didn't really get traction on being an OpenShift Console plugin. Seemed more guided flows in our app was more desired. I thought it would be a neat idea to make our own perspective and supply guided flows via that.

**Comment by christianvogt** [comment]
@strangiato OpenShift Console was the initiator of the [dynamic-plugin-sdk](https://github.com/openshift/dynamic-plugin-sdk) library which we plan to use to support this ticket.
