### ISSUE TITLE
[Tracker]: DS Pipeline Experiments

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1874]
On HOLD: We are investigating the best delivery model for Experiments. Having the raw value of Experiments doesn't bring a lot of holistic value. We are investigate more data and metrics that we can display with Experiments before we consider this a ready-to-go feature.

---

### Description

Data Science Pipelines uses a concept called Experiments. These cut across Pipelines and Runs.

We need a way to display and configure Experiments. As well as get the artifacts under an experiment.

### Target Branch

f/pipeline-experiments

### Requirements

[WIP]
* Support the ability to create/delete/list Experiments
* Support the ability to see artifacts associated with Experiments

### Itemized UX Issues

* Support Experiment Artifacts

### Itemized Dev Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1115
* TBD supporting artifacts

**Comment by dgutride** [comment]
Should this be closed in favor of pipelines phase 2?  https://github.com/opendatahub-io/odh-dashboard/issues/1813 - it is not listed on the slide for priorities any longer.  @andrewballantyne

**Comment by andrewballantyne** [comment]
@dgutride it has existing effort tied to it... which may or may not be able to built on. I'd like to not close it if we don't have to.
