### ISSUE TITLE
[Bug]: Layout issues in Notebook server pages

### ISSUE THREAD

**Issue by manaswinidas** [opendatahub-io/odh-dashboard#1881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

main

### Current Behavior

Loading area is different for `Start Notebook Server` and `Logging out` pages.
<img width="1021" alt="Screenshot 2023-09-29 at 12 09 50 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/30961aa6-239d-4ae6-96af-f68bf594e4f2">
<img width="1043" alt="Screenshot 2023-09-29 at 12 12 16 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/d2b98b24-1586-4631-a2f8-300b7a56a116">

In `Administration` tab, the content doesn't appear in full screen.

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/c25143cb-3aa4-4030-a602-ab651dd66a58

### Expected Behavior

The Loading area should be uniform on both pages.

The Administration tab content should appear on full screen.

### Steps To Reproduce

1. Go to `Applications` -> `Enabled` -> `Launch application` and try starting a notebook server.
2. Once you are on the JupyterLab page, click on `File` -> `Log out` and go to the `Logging out` screen
3. Check the Administration tab and check the layout issues.

### What browsers are you seeing the problem on?

Chrome

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1202
