### ISSUE TITLE
[Feature Request]: Update the title and submit button wording in all the add/edit modals

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1882]
### Feature description

Currently, there are a lot of inconsistencies in the Add/Edit modals across the dashboard. Many resources are reusing the same modal component for adding or editing, however, some of the wording is not updated and they don't follow the same pattern. Here are the findings:
- Data science projects
  - [ ] Project modal
    - Add
      - title: Create data science project
      - button: Create
    - Edit
      - title: Edit data science project
      - button: Update
  - [ ] Storage modal
    - Add
      - title: Add storage
      - button: Add storage (see the inconsistency here, it's not `Add`)
    - Edit
      - title: Update cluster storage (see the inconsistency here too, it's not `Edit cluster storage`, or it's not `Update storage` to align with the `Add storage`)
      - button: Update
   - [ ] Data connections modal
     - Add
       - title: Add data connection
       - button: Add data connection
     - Edit
       - title: Edit data connection
       - button: Update data connection
   - [ ] Pipeline server modal
     - Add
       - title: Configure pipeline server
       - button: Configure
     - No edit
   - [ ] Import pipeline modal
     - Add
       - title: Import pipeline
       - button: Import pipeline
     - No edit
   - [ ] Model server modal
     - Add
       - title: Add model server
       - button: Add
     - Edit (There is a [ticket](https://github.com/opendatahub-io/odh-dashboard/issues/1626) to fix this already and a [PR](https://github.com/opendatahub-io/odh-dashboard/pull/1878) up)
       - title: ~Add model server~ Edit model server
       - button: ~Add~ Update
   - [ ] Deploy model modal
     - Add
       - title: Deploy model
       - button: Deploy
     - Edit
       - title: Deploy model
       - button: Deploy
- Data science pipelines
  - [ ] Experiment modal
    - Add
      - title: Create experiment
      - button: Create experiment
    - No edit
- Model serving
  - [ ] Bias configuration modal
    - Add
      - title: Configure bias metric
      - button: Configure
    - Edit
      - title: Configure bias metric
      - button: Configure
- Custom notebook images (on feature branch `f/byon` and `incubation` branch, not `main`)
   - [ ] Custom images modal
     - Add
       - title: Import notebook image
       - button: Import
     - Edit
       - title: Update notebook image
       - button: Update

Above are all the modals that need consistency across the dashboard AFAIK.
NOTE: Consider the solution together with this issue #1428

**Comment by andrewballantyne** [comment]
Related to:

- https://github.com/opendatahub-io/odh-dashboard/issues/1897

**Comment by kywalker-rh** [comment]
@kaedward is in the middle of doing this now so assigning this issue to her.

**Comment by andrewballantyne** [comment]
Bumped it into In Progress as you noted she was working on it.
