### ISSUE TITLE
[Bug]: Add descriptions to accelerator profile CRD

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.15.0

### Current Behavior

The accelerator profile crd does not have descriptions for the schema. It should include this to make it easier for cluster admins to decipher what each param is used for. This is important now because the feature requires manual creation of these profiles. The admin UI (Habana part 2) will remove the need to manually interact with these crds

### Expected Behavior

To have descriptions for each param in the crd

### Steps To Reproduce

1. go to openshift console
2. create a crd in the editor
3. the side panel should have descriptions of each param in the spec

### Workaround (if any)

none

### What browsers are you seeing the problem on?

Chrome

**Comment by andrewballantyne** [comment]
FWIW, this is an OpenShift Console standard ([docs](https://github.com/openshift/enhancements/blob/master/dev-guide/api-conventions.md#write-user-readable-documentation-in-godoc))

**Comment by dgutride** [comment]
Assigned to Gage since he already opened a PR for this and pulled into the sprint since it's being actively reviewed.

**Comment by manosnoam** [comment]
Verified on RHODS 2.4:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/ce6005b4-7ee9-4f60-8f44-9954bdc8d7c6)
