### ISSUE TITLE
[Investigation]: Delete Modals, need confirmation?

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1897]
### Feature description

We should look at if deleting mid-project and related external resources need a confirmation.

Project should always have confirmation as it's taking several resources with it.

Maybe:
- If you delete 1 resource -- no confirmation
- If you delete >1 resource -- confirmation & explaining what resources

Erwan had a much more comprehensive list in the comments -- https://github.com/opendatahub-io/odh-dashboard/issues/1897#issuecomment-1745471322

**Comment by andrewballantyne** [comment]
@kaedward We have talked about this before about the structure of our Delete modals. This can be that change. I put my thoughts in the description.

cc @erwangranger (brought this up at a UX meeting and I don't think we addressed it then)

**Comment by andrewballantyne** [comment]
Related to:

- https://github.com/opendatahub-io/odh-dashboard/issues/1882

**Comment by erwangranger** [comment]
Some thoughts from me (thank @andrewballantyne for always thinking of me). 

If I was making the rules, I'd say they should be:
* never ever delete anything on a single click. Always have a **at least** a second click. 
* differentiate between what can easily be re-created, and what cannot. Deleting the wrong PVC by mistake can be a traumatic and irrecoverable loss of data. Deleting a workbench by mistake can usually be re-created in a few minutes. 
* For critical stuff, DO make me type a confirmation, and ideally that confirmation is descriptive of which item I'm deleting. 

So, for example: 
* "You are about to delete **project** xyz and everything contained in it. To confirm that is what you want to do, please type `xyz` in the box below and press "confirm". 
* "You are about to delete 72 models from this model server. Here is the list: ...... To confirm , please type `delete these 72 models` in the box below and click "confirm". 
* "You are about to delete a pipelinerun. To confirm the deletion of pipelinerun "ad-hoc-2023-10-03", click confirm".

**Comment by manaswinidas** [comment]
## UX context

@kywalker-rh

**Comment by kywalker-rh** [comment]
@kaedward Let's talk about this in the context of the content review you are doing. This isn't necessarily a content only issue, but I think its the right place to start.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2396 - moving to closed, we can move out of eng to ux or duplicate if we need to.
