### ISSUE TITLE
[Feature Request]: "Sticky" Project on Project List View

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1898]
### Feature description

I have experienced and seen some flows of users navigating away and returning to DS Projects view. We show the list page every time as if you see it for the first time.

In the DS Pipelines feature, we implemented a "sticky" project so when you navigated away from DS Projects to Pipelines, or between the Pipelines pages (Pipelines & Runs), it "kept" the project focus.

When you go from any of these pages back to DS Projects, it could be on page 4... could be the 2nd item (if you have multiple projects) ... it seems we should promote this concept and place some concept of a top-level project. Maybe as simple as a "pinned" Project or something... call it "last viewed" or something 🤔 Needs UX.

**Comment by andrewballantyne** [comment]
Related to:

- https://github.com/opendatahub-io/odh-dashboard/issues/1882

**Comment by manaswinidas** [comment]
## UX context

Can UX investigate this for the best way for keeping Project Context as we navigate the App? Our recommendation is to Promote it at the top.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2753
