### ISSUE TITLE
[Feature Request]: PF5 dark theme

### ISSUE THREAD

**Issue by dpanshug** [opendatahub-io/odh-dashboard#1905]
### Feature description

Incorporate the newly introduced dark theme from PF5 into our dashboard. Consider adding a toggle button to the header, allowing users to switch seamlessly between the light and dark themes (UX can guide more).

For more details, please refer to the Dark Theme Handbook: https://www.patternfly.org/developer-resources/dark-theme-handbook."

Dependent on https://github.com/opendatahub-io/odh-dashboard/issues/1694

### Anything else?

Things to consider:
- Icons for ISVs, Look at OpenShift console OperatorHub for how they did it
- How are we going to allow the users to modify this?
- Look at CSS to see what we are doing to set colors

**Comment by DaoDaoNoCode** [comment]
Note: When implementing the dark theme, we need to make sure the logo/icon in all of the ISV cards looks good on the dark background.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2405
