### ISSUE TITLE
[Tracker]: Distributed Workloads

### ISSUE THREAD

**Issue by kywalker-rh** [opendatahub-io/odh-dashboard#1906]
### Description

This will track all the work for distributed workloads, starting with the UX discovery and designs.

### Target Branch

TBD

### Requirements

- https://docs.google.com/document/d/1kdsF_186pM-_OOkTpbn0fAQE7KNJzmI5dzEGhOyibng/edit?usp=sharing

### Itemized UX Issues

- https://github.com/opendatahub-io/odh-dashboard/issues/1918 
- https://github.com/opendatahub-io/odh-dashboard/issues/1976
- https://github.com/opendatahub-io/odh-dashboard/issues/2257
- https://github.com/opendatahub-io/odh-dashboard/issues/2258

### Itemized Dev Issues

TBD

**Comment by dgutride** [comment]
Replaced by:  https://issues.redhat.com/browse/RHOAIENG-274
