### ISSUE TITLE
[Bug]: Page titles slightly inconsistent in text and case wrt other pages and menu titles

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1907]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.33

### Current Behavior

not a functional bug.

- sometimes menu title corresponds to the page title (e.g, Serving runtimes), sometimes it's slightly different (e.g., Notebook image**s**  -> Notebook image settings, or User management -> User and group settings)
- most of the settings pages have `settings` in the page title, but Serving runtimes one doesn't
- some pages keep the text case consistent between menu title and page title (e.g., Serving runtimes) and some others don't (e.g., Cluster **s**ettings -> Cluster **S**ettings, or Model **S**erving -> Model **s**erving) 

Some screenshots
![cluster-settings](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/297b72e7-1687-42f2-9e6f-d7c4a1b41c41)
![model-serving](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/0ef0d6d7-47cb-4c07-b94e-82ed088adc11)
![notebook-images](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/2158a0dd-0115-4964-b086-6de5991aa983)
![serving-runtimes](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/36f98abc-91b6-4a76-aa68-7e11296fc0c2)

### Expected Behavior

I would expect more consistency in title styles among the Dashboard pages

See UX direction on solution: https://github.com/opendatahub-io/odh-dashboard/issues/1907#issuecomment-1751350900

### Steps To Reproduce

1. go to RHODS Dashboard
2. check the differences between page titles and menu titles
3. check the differences between page titles of different pages.

### Anything else

I'm not assuming what should be the right styles/cases

**Comment by andrewballantyne** [comment]
Good inconsistency catch!

@kaedward I think this is fully a question about how we want wording. Do Navigation items now follow sentence case? Do we need to rundown of what we would expect Navigation => Page Titles to really be equal? I thought yes, but it seems we have inconsistencies.

**Comment by kaedward** [comment]
@andrewballantyne @bdattoma This is a great catch! Yes, page titles should match the title case navigation items. The capitalization issue is most likely my fault and a result of my deep-rooted hatred of title case. I actually need to double check on whether or not the nested navigation items should also be title case... I'll update tomorrow!
 
![Screenshot 2023-10-05 at 4 50 52 PM](https://github.com/opendatahub-io/odh-dashboard/assets/94569315/9780174e-3ce8-462f-8d54-6be129345f00)

**Comment by kaedward** [comment]
Update: The nested navigation items and their corresponding page titles are correct in the screenshots above - sentence case. @andrewballantyne @bdattoma

**Comment by bdattoma** [comment]
> Update: The nested navigation items and their corresponding page titles are correct in the screenshots above - sentence case. @andrewballantyne @bdattoma

okay, so `Cluster Settings` should become `Cluster settings`, right?

**Comment by kaedward** [comment]
> okay, so `Cluster Settings` should become `Cluster settings`, right?

@bdattoma yep!

**Comment by jstourac** [comment]
Just for the reference - current inconsistency with regards the `Model Serving` and `Deployed models` title is being handled by #2105.
