### ISSUE TITLE
[Story]: Add admin section to control model serving platforms

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1913]
### Goal

Add a new admin section to enable/disable kserve and model serving

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1939

### Itemized goals

* Add logic to allow users to create projects with kserve (`disableKServe: boolean`)
* Add logic to allow users to create projects with modelmesh (`disableModelMesh: boolean`)
* Add a new section in **cluster settings**
* Add checkbox to enable/disable different platforms
* Based on https://github.com/opendatahub-io/odh-dashboard/issues/1946 disable one of the checkbox if the platform is not enabled
* Add a warning if none of the checkbox are selected

### Aspects continued elsewhere

* https://github.com/opendatahub-io/odh-dashboard/issues/1973
* https://github.com/opendatahub-io/odh-dashboard/issues/1994

### Mocks

* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/ZVgZkRx
* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/4oE7lpo
* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/Eej0Yvg
* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/VEzYvLg

**Comment by lucferbux** [comment]
@vconzola I think there were some issues up in the air for the admin section right?

**Comment by vconzola** [comment]
@lucferbux I think there were, but based on our conversation earlier today, are we good? I'll update the mocks to match what we talked about.

**Comment by lucferbux** [comment]
> @lucferbux I think there were, but based on our conversation earlier today, are we good? I'll update the mocks to match what we talked about.

@vconzola  I'm only missing one more thing, are we gonna disable an option if we detect the platform is not enabled in the cluster? Meaning that if kserve is not installed, I assume we would want to greyed out that to the user right? Or we let that until it fails in the project creation?
