### ISSUE TITLE
[Bug]: Serving Runtime resource name displayed in UI does not correspond to actual name

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1915]
### ODH Component

ODH Dashboard

### Current Behavior

when hovering on the QuestionMark icon of a Custom Serving Runtime, it shows a resource-name which does not correspond to the resource name of the corresponding OpenShift Template object.

In RHODS Dashboard:
![runtime-ui](https://github.com/opendatahub-io/opendatahub-community/assets/88311595/965cf214-60e2-467d-a7b8-a891d0eef099)

Actual Template:
![image](https://github.com/opendatahub-io/opendatahub-community/assets/88311595/5ec114b2-c65f-4039-a206-d720b05d5b6f)

The `name: ovms-ods-ci` that you can see in the Template screenshot doesn't seem to be actually used as resource name anywhere. Even when creating a model server using that Serving Runtime, the ServingRuntime CR gets the name we insert in the model server creation modal.

### Expected Behavior

resource name should match an existing openshift object in a way to let user easily search for the object. 
In alternative, we could show the "Template" name and "runtime" name.

### Steps To Reproduce

1. add a custom Serving Runtime from RHODS Dashboard > Settings > Serving runtimes
2. move the mouse on the QuestionMark icon next to the newly added runtime _-> a tooltip opens_
3. check the resource-name which is reported in the tooltip
4. search the corresponding Template object `oc get templates -n <applications_namespace>` --> don't match point 3

**Comment by lucferbux** [comment]
Already done in https://github.com/opendatahub-io/odh-dashboard/pull/1772
