### ISSUE TITLE
Enable ODH Dashboard Admin & User groups

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#192]
**Is your feature request related to a problem? Please describe.**
In order to support administrative features in the dashboard, we should enable support for authenticated admin and users groups for the Dashboard

**Describe the solution you'd like**
Enable default admin & user groups for the dashboard

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewballantyne** [comment]
Would this effort be part of the KFNBC? @LaVLaS @DaoDaoNoCode @lucferbux 

I see https://github.com/opendatahub-io/odh-dashboard/pull/270 which looks like this overlaps with it in some fashion

**Comment by lucferbux** [comment]
@andrewballantyne oh ok, i didn't see the message here, I've updated it, it would be super nice if you can review it, it's ready to be merged, thanks for all the work.
