### ISSUE TITLE
[Bug]: Default-less Storage Class Value is not Specific

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

f/storage-class feature

### Current Behavior

From: https://github.com/opendatahub-io/odh-dashboard/pull/1740#discussion_r1348688416

When you have a default-less Storage Class case on your cluster, the current logic for `f/storage-class` is to string `includes` and not absolute match.

`standard` DashboardConfig value will catch `standard-csi`. This is not likely super ideal.

### Expected Behavior

Make absolute match for aligning to the DashboardConfig 

### Steps To Reproduce

1. Have an env without a default storage class
2. Update your DashboardConfig to use `notebookController.storageClassName` and specify a partial value of an existing storage class
3. Create a Workbench with a new PVC
4. View the PVC to see the storage class it referenced is not explicitly named the same in DashboardConfig

### Workaround (if any)

You can guarantee with a `.includes` if you could name your other storage classes so the full value is not included in another storage class name. That way, when explicitly defined as a whole storage class name you will get just that. Partial matches is user error.

**Comment by andrewballantyne** [comment]
cc @shalberd you are not required to fix this, thank you for your contributions so far. Just an FYI on this is related to your code.

**Comment by shalberd** [comment]
will fix it, no problem, yep

I could and actually shall do full string compare, ie. something like string.equals
```
const storageClassDashBoardConfigVsCluster = storageClasses.filter((storageclass) =>
    storageclass.metadata.name === configStorageClassName,
```

**Comment by andrewballantyne** [comment]
This has merged into the feature branch, closing this issue.
