### ISSUE TITLE
[Tracker]: Model Serving Quality Metrics

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1923]
### Description

TBD

### Target Branch

TBD

### Requirements

[Requirements doc](https://docs.google.com/document/d/1TXLEyzpYX6inMHOlaUW8VbMxMvQ5Y9TEzHM87G9_1Yk/edit) (will be converted to text later)  - Model serving phase 2 requirements

### Itemized UX Issues

TBD

### Itemized Dev Issues

TBD

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-570
