### ISSUE TITLE
[Bug]: Safari Favicon Missing

### ISSUE THREAD

**Issue by dimakis** [opendatahub-io/odh-dashboard#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

2.2.0

### Current Behavior

When loading the dashboard in safari the RHODS favicon doesn't load

### Expected Behavior

RHODS favicon in browser tab

### Steps To Reproduce

1. Install rhods v2.2.0
2. open DS dashboard using safari

### What browsers are you seeing the problem on?

Safari

**Comment by lucferbux** [comment]
Yes, this is kind of weird, we get the logo at build time, we should take a look what's happening in safari

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1200
