### ISSUE TITLE
[Bug]: Custom serving runtime creation error message makes no sense

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

main

### Current Behavior

When you try to create/duplicate a custom serving runtime and the error happens, the error message is very hard to read and you don't know what happened. (For example, it's `Request failed with status code 422` here)

<img width="1715" alt="Screenshot 2023-10-06 at 2 47 45 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/af14ce49-d2f6-44c3-871f-8a0f1361f1be">

### Expected Behavior

The error message is meaningful and explains why the creation/edit cannot succeed.

### Steps To Reproduce

1. Go to custom serving runtime settings
2. Duplicate any serving runtime
3. When duplicating, change the kind from `ServingRuntime` to `ServingRuntimeee` (Give it an error kind)
4. Click add, and you will see the error message

### Workaround (if any)

Carefully check the YAML code and find out the reason.

**Comment by lucferbux** [comment]
Good catch, we can either fix this in kserve or add it into the model server enhancements tracker

**Comment by bredamc** [comment]
@lucferbux If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by bredamc** [comment]
@andrewballantyne If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by bredamc** [comment]
Suggested text -- let me know what you think:

"
When you try to create or edit a custom serving runtime and an error occurs, the error message does not indicate the cause of the error. 

Example error message: `Request failed with status code 422`

**Workaround:** Carefully check the YAML code to identify the reason for the error.
"

**Comment by andrewballantyne** [comment]
@bredamc that RN looks good... not sure we have much better guidance at this point. This is just a fix we need to do.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1199
