### ISSUE TITLE
Add feature flag for enabling telemetry in the Dashboard

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#193]
**Is your feature request related to a problem? Please describe.**
Telemetry is enabled downstream but should be disabled by default for ODH Dashboard deployments

**Describe the solution you'd like**
Add a feature flag to enabled/disable telemetry

**Describe alternatives you've considered**
Add an optional build flag that can be toggled to include it in the image

**Additional context**
N/A

**Comment by andrewballantyne** [comment]
Does https://github.com/opendatahub-io/odh-dashboard/issues/285 not mean we have this already implemented?

@LaVLaS can this be closed?

**Comment by andrewballantyne** [comment]
I'm going to close this as I think #285 will be covering the fact that it's behind a feature flag.
