### ISSUE TITLE
[Tech debt]: Upgrade deprecated components with Patternfly 5

### ISSUE THREAD

**Issue by dpanshug** [opendatahub-io/odh-dashboard#1931]
### Feature description

In Patternfly 5, some components are deprecated such as `Select`, `Dropdown`, and `ApplicationLauncher`. Upgrade those with new implementation https://www.patternfly.org/get-started/upgrade#upgrade-deprecated-components

Depends on https://github.com/opendatahub-io/odh-dashboard/issues/1694

**Comment by andrewballantyne** [comment]
Can be merged into https://issues.redhat.com/browse/RHOAIENG-421 -- it's a separate issue though, recommend we move it and link the two Jiras together.

**Comment by dgutride** [comment]
Moved to jira:  https://issues.redhat.com/browse/RHOAIENG-2404
