### ISSUE TITLE
[Feature Request]: Disable "Edit project" action from the menu for users without Admin permissions

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1932]
### Feature description

When users with Edit access to a DS project tries to edit the project details, they get correctly a permission error:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/28974e5c-7b5e-46cd-a9a2-abe3ce992088)

However, I think it would be better not showing the Edit project menu when the user cannot actually edit the project. Similar to what is done for "Edit permissions" action which is available for project admin only

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1163
