### ISSUE TITLE
[Feature Request]: Potential enhancement. Discover new GPUs when added post operator installation

### ISSUE THREAD

**Issue by FedeAlonso** [opendatahub-io/odh-dashboard#1938]
### Feature description

Potential enhancement: 
Prior to the Accelerators feature, adding a new GPU was plug and play (used the node feature discovery).
Now the experience is not so straightforward, and involves the user to do some extra steps.

### Describe alternatives you've considered

Now there are some steps documented so the user can add new GPUs

**Comment by lucferbux** [comment]
Ok, I'm gonna expand the discussion here @Gkrumbach07 @andrewballantyne this might be an issue, not sure if only related to how QE cluster works. @FedeAlonso has had the same problem several times and debugging it it always ended up being the same:

1. Cluster is created
2. RHODS is deployed
3. Somehow the GPU installation is settled after the dashboard is up and running
4. So the migration is already performed and no accelerators are added

Is quite easy to trigger it again, just doing the following:

1. Delete the migration configmap
2. Delete the dashboard replicaset to trigger new pods

Not sure if this is gonna be a problem, or if we wanna change the logic (check once in a while if the gpu accelerator profile exists and if not, check if gpu is present to recreate it), but the current logic might bump into a race condition. Again, I'm not aware if that could happen in customer clusters.

**Comment by lucferbux** [comment]
cc @andrewballantyne

**Comment by andrewballantyne** [comment]
@Gkrumbach07 What was our decision here for the v2 effort? I think we decided on the UI being the source of truth and not needing to do this... thoughts?

**Comment by Gkrumbach07** [comment]
> What was our decision here for the v2 effort? I think we decided on the UI being the source of truth and not needing to do this... thoughts?

We have an [issue](https://github.com/opendatahub-io/odh-dashboard/issues/1893) tracking this being handled in UI which should prevent this race condition many people encounter. The issue will make it so that gpu migration will happen anytime in the lifecycle of the dashboard, not once on upgrade.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-15
