### ISSUE TITLE
[Story]: Create dashboard configuration to control kserve and modelmesh

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1939]
### Goal

Create a new dashboard configuration to enable kserve, modelmesh or both for project creation

### Dependency issue

No dependencies

#### On new cluster (fresh dashboard config)

1. Kserve will be enabled by default
2. Modelmesh will be disabled by default

#### On upgrade (dashboard config already deployed)

1. Kserve will be disabled
2. Modelmesh will be enabled

### Aspects continued elsewhere

* https://github.com/opendatahub-io/odh-dashboard/issues/1912
* https://github.com/opendatahub-io/odh-dashboard/issues/1975

### Mocks

No mocks

**Comment by lucferbux** [comment]
@andrewballantyne @christianvogt This is the first issue I want to discuss about the architectural design, I understand this would be something we own in our dashboard config, do you have any idea in mind, i was thinking a new section in the manifest with an array that can contain both, either values or none

**Comment by andrewballantyne** [comment]
If you want to make a new section, that's fine... I'd recommend just building more on the state of our awful named feature flags as they are today lol. We have to refactor everything anyways, so it's unlikely you'll nail the future state here.

I don't see other issues talking about it, but this is the way I think we can manage installed vs upgraded clusters:
- Upgrade => Check OdhDashboardConfig for `KServe` or `ModelMesh` feature flags, if neither, merge `KServe` off, `ModelMesh` on
- Install => OdhDashboardConfig's default is `KServe` on, `ModelMesh` off

**Comment by lucferbux** [comment]
> Upgrade => Check OdhDashboardConfig for KServe or ModelMesh feature flags, if neither, merge KServe off, ModelMesh on
Install => OdhDashboardConfig's default is KServe on, ModelMesh off

@andrewballantyne Great, that's what I had in mind, thanks for the feedback here.

My only concern with the feature flags is the current conversation we have with the nested dependencies, since we already have `disableModelServing` to disablement, and this should be something more in the line of enablement, I'm more than open to include two new flags called `Kserve` and `ModelMesh` (withouth the disable cause it's a different enablement) and get the flow that you mentioned here.

Let me know what you think and I can update the issue, thanks a lot.
