### ISSUE TITLE
Use feature flags as to enabled/disabled features in the UI

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#194]
**Is your feature request related to a problem? Please describe.**
For any features that are not default or core features of the Dashboard, we should support a feature flag to toggle them on/off when the dashboard is run

**Describe the solution you'd like**
Add feature flags for OPTIONAL features of the dashboard

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewballantyne** [comment]
Is there anything not currently covered in the ODHDashboardConfig? @DaoDaoNoCode @dlabaj

**Comment by andrewballantyne** [comment]
I'm marking this done as this is standard procedure. @LaVLaS if you feel this still needs to cover something, feel free to reopen.
