### ISSUE TITLE
[Story]: Adapt logic for model serving creation in new projects

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1941]
### Goal

Adapt the logic of how we display model serving technology in new projects

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1939

### Itemized goals

* Add logic to detect the project is not currently set up with any model serving technology
   * If the project lacks the `modelmesh-enabled: ...` annotation it will present an empty view (see the following options)
* If both modelmesh and kserve are enabled, display the page to select the technology https://github.com/opendatahub-io/odh-dashboard/issues/1944
* If only kserve is enabled display the kserve project view
* If only modelmesh is enabled, display de modelmesh project view 

### Aspects continued elsewhere

* https://github.com/opendatahub-io/odh-dashboard/issues/1942

### Mocks

* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/mPM4ngw
* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/elb3Oq0
* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/g1b3Dnq

**Comment by lucferbux** [comment]
There are a few edge cases that I would want to cover:

1. If we ended up having detection of the serving platforms and one of them is failing, do we show a message error?
2. If somehow the cluster ends up with no serving platform selected, what's the fallback? (i assume kserve)
3. If kserve is the only one selected but the controller is failing, I assume we'll show an error message right?


cc @andrewballantyne @christianvogt @vconzola

**Comment by andrewballantyne** [comment]
no1 & no3 We are not hunting down controller state... get everything from the DSC's `.status`, such as conditions and the reason. We can either get from it via the k8s pass-through API (if https://github.com/opendatahub-io/opendatahub-operator/issues/588 is done -- unlikely for this work) or we use a shim layer on the Node Server and get it through the Service Account.

no2 can favour KServe as a fallback until we decide how best to handle both being turned off -- naturally fall back on an error if it's not installed. We have a "model serving" flag, and we are adding "model mesh" and "kserve" flags... so it's a bit of a mess. We need to clean this up but this should be on your work to do so.

**Comment by DaoDaoNoCode** [comment]
Most of the functionality in this ticket is done in #2012, we just need #1943 to be done to apply the label `modelmesh-enabled: 'false'` to the project and we could close this ticket.

**Comment by DaoDaoNoCode** [comment]
After checking, I think we can actually safely close this ticket with #2012, all the logic could be addressed when the deploy KServe model feature is finished.
