### ISSUE TITLE
[Story]: Empty State platform selection

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1944]
### Goal

Create a view to select the model serving platform

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1941

### Itemized goals

* Add the card for single model serving platform
* Add the card for multi model serving platform
* Add a warning label to tell the user that there's no way to revert the selection **once a model is deployed**
* This page will appear when the project lacks the `modelmesh-enabled: ...` annotation
* When selecting an option, we will navigate to the empty screen of either kserve and modelmesh
* If the user reloads the page or goes back, it will present again the selection 
 

### Mocks

* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/mPM4ngw

**Comment by andrewballantyne** [comment]
I think the easiest way to do this until we worry about resets is just set the `modelmesh-enabled` flag to true or false based on their selection. No label is "choice time" (assuming feature flags back that up)

When we support the switching inside a project... we just ignore the label all together when there is no ServingRuntime objects in the project.

**Comment by lucferbux** [comment]
@andrewballantyne Yes, that makes total sense.
