### ISSUE TITLE
[Story]: Add logic to detect if kserve or modelmesh are installed

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1946]
### Goal

Add a logic to detect if both kserve and modelmesh are installed in the cluster

### Dependency issue

No dependencies

### Itemized goals

* Add a custom logic to detect if kserve is installed in the cluster
* Add a custom logic to detect if modelmesh is installed in the cluster

This issue is dependant of https://github.com/opendatahub-io/odh-dashboard/issues/1979

### Mocks

No mocks

**Comment by lucferbux** [comment]
@danielezonca @Xaenalt @andrewballantyne @christianvogt This is one of the technical challenges we've been discussing in the docs, is there a way to figure out if either kserve or modelmesh are installed outside of the CRDs? We need to detect each of them.

**Comment by andrewballantyne** [comment]
DSC will have the values. https://github.com/opendatahub-io/opendatahub-operator/issues/588 -- this is not likely to be done in time, so we will make a shim layer in our backend to get the Service Account to pull them. The `.status` of components installed will have your answer.

**Comment by lucferbux** [comment]
Ok, so we can have a layer for this release to check the status of the controller, and add a follow up to refactor it with the DSC values.
