### ISSUE TITLE
[Story]: Adapt Global View Table to Kserve

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1948]
### Goal

Adapt global view to support kserve deployed models

### Dependency issue

No dependencies

### Itemized goals

* Add a new column in the Global View Table to display the Serving Runtime platform
* The way to detect that is by some annotations in the InferenceService `serving.kserve.io/deploymentMode: ModelMesh`
* Add logic to display the proper modal when editing a new model (Kserve/modelmesh)

### Mocks

* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/j4MLjez

**Comment by andrewballantyne** [comment]
This is a two step process imo... not sure if we want both in the same ticket, but here are my thoughts.

1. Adapting the table to support both types should be fairly straight forward
    - Edit on each row shouldn't be a problem either, as it's an if/else sorta situation
    - Showing a label or column should be fairly easy given knowledge of the project it comes from
    - Delete will need to adapt, worse case scenario two flows
2. Deploy is a little weird from this page as project selection will change the rest of the modal... but I imagine that's not too crazy either
    - We need to support Model Mesh server deploys... perhaps this is the biggest annoyance of them all as we never got to it from the other issue
    - We shouldn't have a problem deploying a model from KServe or Model Mesh as we just expand the modal on project selection

We can work through the nit and grit @lucferbux

**Comment by lucferbux** [comment]
Yes, I should have mentioned that this is just a placeholder, I was thinking about splitting the different goals once we are sure what we want for this screen. n1 is quite clear, I envisioned something similar, and we can work through n2 to get the requirements.

**Comment by lucferbux** [comment]
@christianvogt since you got this, the only blocker here is that when editing, we are blocked by https://github.com/opendatahub-io/odh-dashboard/issues/1943, you can just add the logic there and we can later add it when working on 1943.

**Comment by christianvogt** [comment]
Yes @lucferbux. My plan was to stub out the condition and mark as `TODO`.

**Comment by lucferbux** [comment]
@christianvogt I'm sorry, @vconzola has updated the mocks with the inclusion of the label `Multi-model serving enabled` and `Single-model serving enabled` could you add that too please?
