### ISSUE TITLE
Fix accelerator crd version and migrated gpu name

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.16

### Current Behavior

Currently in the Accelerator profile crd is in version v1alpha and needs to be in v1.

We use the name Nvidia for our migrated gpu but Nvidia recommends using full caps NVIDIA when using its name. This needs to be changed for our migrated gpu.

### Expected Behavior

Switch to v1
Change names to use NVIDIA

### Steps To Reproduce

have the dashboard migrate accelerators and check the crd that is added.

### Workaround (if any)

Not a breaking change, no workaround needed

### What browsers are you seeing the problem on?

Chrome

**Comment by andrewballantyne** [comment]
This was demo feedback. This was not needing to be a blocker, but was felt it had value to be fixed for the release it's initially part of. We should address future demo feedback with an issue first and let it be triaged by the team. Incubation needs to prevent these items in the future. We'll continue to work through improving the process to avoid post release issues like this. May need earlier demos to the wider team to illicit feedback. 

cc @dgutride @gmarkley-VI 

PR is mered, closing issue.
