### ISSUE TITLE
OSSM: Consolidate Service Mesh related notebook patches

### ISSUE THREAD

**Issue by cam-garrison** [opendatahub-io/odh-dashboard#1954]
These seem all very related, we may want to look at cleaning that up in the future to make it one "set of patches" rather than 3 separate ones. Just for code cleanness.

_Originally posted by @andrewballantyne in https://github.com/opendatahub-io/odh-dashboard/pull/1088#discussion_r1346172057_
            

Currently, we have 3 separate functions that return patches for the 2 annotations and 1 label that need to be patched in the notebook object to enable/disable service mesh. For code cleanness, these three patches should be returned in one function call.

**Comment by dgutride** [comment]
Associated PR was merged - moving to closed (please add a comment if this was incorrect).
