### ISSUE TITLE
OSSM: General Improvements

### ISSUE THREAD

**Issue by cam-garrison** [opendatahub-io/odh-dashboard#1958]
Creating this issue to encompass several pieces of review + suggestions from the original PR #1088 which were not included in the PR.

              I suggest adding the same comment as we have present in the frontend code.
```suggestion
/**
 * Feature flags are required in the config -- but upgrades can be mixed and omission of the property
 * usually ends up being enabled. This will prevent that as a general utility.
 */
export const featureFlagEnabled = (disabledSettingState?: boolean): boolean =>
  disabledSettingState === false;

```

_Originally posted by @christianvogt in https://github.com/opendatahub-io/odh-dashboard/pull/1088#discussion_r1346121202_

```suggestion
          ? getRoute(notebookName, projectName).then((route) => route.spec.host)
```

_Originally posted by @christianvogt in https://github.com/opendatahub-io/odh-dashboard/pull/1088#discussion_r1346128212_
            
              Should we fall back to retrieving the host through the route?
By enabling the flag without service mesh, we'll get an invalid url.
```suggestion
    if (enableServiceMesh) {
      host = await getServiceMeshGwHost(fastify, namespace).catch((e) => {
        fastify.log.warn(`Failed getting service mesh route ${notebookName}: ${e.message}`);
        return undefined;
      });
    }
    if (!host) {
      const route = await getRoute(fastify, namespace, notebookName).catch((e) => {
        fastify.log.warn(`Failed getting route ${notebookName}: ${e.message}`);
        return undefined;
      });
      host = route?.spec.host;
    }
```

_Originally posted by @christianvogt in https://github.com/opendatahub-io/odh-dashboard/pull/1088#discussion_r1346092436_

**Comment by andrewballantyne** [comment]
PR closed
