### ISSUE TITLE
[Bug]: Admin users can list all of the project but fail to perform any actions

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.34

### Current Behavior

A RHODS Admin user who doesn't have cluster admin privileges can see the list of all the DS Projects owned by other users.  If they try opening any of the projects, they'll get a error message due to lack of permissions on the project. 

In addition, UI allows them to click on buttons to start workbenches (although they don't have permissions) but it doesn't get updated with any new status or error message. Refresh would show the workbenches in their current status which didn't actually change (as expected).

GIF showing the scenario:
![rhodsadmin](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/42643a5d-c88a-46f9-95c4-5c4013bfa7fd)

### Expected Behavior

2 options I could think of:
1. Users (including rhods admins) should list only the project they can actually open
2. RHODS admins can list all of the projects, but actions are disabled if they don't have access to those projects
..

### Steps To Reproduce

1. create 2 DS Project using 2 different users
2. log in Dashboard using a Dashboard Admin user (no cluster-admin, different from users at step 1)
3. go to Data Science Project page
4. check the list of projects
5. try accessing one of the projects

**Comment by bdattoma** [comment]
@andrewballantyne

two points:
1. I remember there were different discussions around the ODH/RHODS Admin users in the Dashboard, however I'm not sure if the behavior reported here was desired or expected to happen bcos of the design.
2. regardless point 1, I feel like user experience can be smoother in this scenario.

Wdyt?

**Comment by andrewballantyne** [comment]
@bdattoma can your admin list projects in OpenShift Console? What actions can they do there?

**Comment by bdattoma** [comment]
@andrewballantyne yes they can, but I thought it was something happening bcos of the dashboard giving too much permissions. But I found that we have an issue on our testing environments.

Sorry for the incovenience!
