### ISSUE TITLE
[Bug]: "Install Pipelines Operator" link shows two versions to choose, instead of one

### ISSUE THREAD

**Issue by manosnoam** [opendatahub-io/odh-dashboard#1971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.34

### Current Behavior

When data science pipeline operator is missing, user can press the button to install operator:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/524e8661-d1ab-45a9-bc0d-a6bc7b9431e4)

However, the link takes the user to Openshift OperatorHub, where it lists two versions to install:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/b610f8ac-70c2-4fa1-a3f2-a17b06fb360e)

This confuses the user, to which operator version is required: 

- Version 1.12.0: https://console-openshift-console.apps.ods-qe-08.rhods.ccitredhat.com/operatorhub/ns/openshift-operators?keyword=red+hat+openshift+pipelines&details-item=openshift-pipelines-operator-rh-redhat-operators-openshift-marketplace 

Or

- Version 1.10.4: https://console-openshift-console.apps.ods-qe-08.rhods.ccitredhat.com/operatorhub/ns/openshift-operators?keyword=red+hat+openshift+pipelines&details-item=openshift-pipelines-operator-rh-rhods-catalog-dev-openshift-marketplace

### Expected Behavior

It should list only one operator to install.

### Steps To Reproduce

Go to Data Science Pipelines in Dashboard - before the Pipeline operator is installed.

**Comment by andrewballantyne** [comment]
Talked with DevOps and QE for RHODS and they are intentionally including a duplicate catalog... I'm closing this issue as not an issue.
