### ISSUE TITLE
[Tech Debt]: Add `no-unnecessary-condition` lint rule

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#1977]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Description

We have some unnecessary if statements or optional chaining in the codebase that needs to be cleaned up. Applying [this rule](https://typescript-eslint.io/rules/no-unnecessary-condition/) helps reduce that.

Enable strict mode for TypeScript so this can work.

### Why?

It helps organize the code better and write the types more carefully.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-511
