### ISSUE TITLE
[Story]: Support pulling DSC Status

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1979]
### Goal

We need DSC status to determine the state of installed components.

### Dependency issue

No dependencies

### Itemized goals

* Create a utility in the backend to use the service account
* Create a get endpoint to expose the data on demand

### Aspects continued elsewhere

* Doing it via the k8s pass through won't be possible until the operator issue is resolved: https://github.com/opendatahub-io/opendatahub-operator/issues/588

### Mocks

No mocks

**Comment by lucferbux** [comment]
Oh, I wasn't aware of the passthrough issue, nice to know, thanks @andrewballantyne
