### ISSUE TITLE
[Story]: Add test coverage for kserve migration

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1980]
### Goal

Add jest to the backend and test the migration of kserve

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1975

### Itemized goals

* Add Jest to the backend -> **Update** Already in main and the branch, no need to be done.
* Add unit testing coverage

### Mocks

No mocks

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-555
