### ISSUE TITLE
[Feature Request]: Image description is not immediately clear

### ISSUE THREAD

**Issue by RHRolun** [opendatahub-io/odh-dashboard#1987]
### Feature description

When choosing a notebook, it's not immediately clear what it contains or what its purpose is.
After selecting an image there is the "View package information", although that one is not immediately obvious either.
It would be great if the user could get information about the package as they are browsing it, or immediately after selecting it.

### Describe alternatives you've considered

We already have an on-hover modal for the "Version selection", a similar one could be used for the "Image selection" to immediately display relevant information.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/113337503/9e189861-f33b-4403-b14e-ae6ad5fc5424)

Alternatively, a description could be placed flat under the version as soon as a combination is selected, replacing the "View package information" button.

**Comment by lucferbux** [comment]
## UX Context

@xianli123  Is there any better way to provide descriptions for users to get access to?

**Comment by xianli123** [comment]
Hi @lucferbux Sorry for the late reply. I've seen this kind of design. It seems a good way to show the advanced info by the tooltip as shown in the description. But for the requirement in this issue, let me think about how to make advanced information more visible at first glance. I will get back to you asap.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-12
