### ISSUE TITLE
[Feature Request]: Improved scalability of the notebook server UI

### ISSUE THREAD

**Issue by RHRolun** [opendatahub-io/odh-dashboard#1988]
### Feature description

The notebook server UI can get quite messy as custom notebooks are added:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/113337503/ce991f38-e30e-415e-b62f-0ea49f909d53)

It would be great if the UI could scale better so it doesn't become as cluttered.

### Describe alternatives you've considered

We already have a scalable UI for selecting custom notebooks when creating a workbench, the same could be applied for when starting a notebook server. Maybe with the added ability to search in the dropdown so the user does not need to scroll through all the images.

**Comment by shalberd** [comment]
yeah, this is the "old" Jupyter tile. Well, personally, aside from some playing around with that view by ODH Admins, I see Data Science projects and its view of Notebook images (imagestream name and tag based) as much more relevant. I'd venture to say: just use a data science project, can be one for Admins as well, and let go of that Jupyter tile ;-)

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-11
