### ISSUE TITLE
[Story]: Add new OVMS OOTB template

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1989]
### Goal

Implement new ovms image and deprecate the GPU one

### Dependency issue

No dependencies

### Itemized goals

* Figure out how to remove the gpu OOTB for already deployed servers (it appears it should be done by the operator automatically)
* Change the image from the OVMS template based on the [latest template](https://quay.io/repository/opendatahub/openvino_model_server?tab=history) 
* Remove the gpu limitation from the OVMS template

### Mocks

No mocks

**Comment by lucferbux** [comment]
cc @zdtsw @VaishnaviHire based on conversations, it seems that `ovms-gpu-ootb.yaml` will be removed in already deployed installations on an upgrade path, is that right? If so we can get this and then check the upgrade path if it's working

**Comment by zdtsw** [comment]
> cc @zdtsw @VaishnaviHire based on conversations, it seems that `ovms-gpu-ootb.yaml` will be removed in already deployed installations on an upgrade path, is that right? If so we can get this and then check the upgrade path if it's working

i think the easy way is to build a new local image, use a base catalog which still has the ovms-gpu-ootb.yaml included. and test the upgrade if the old instance gets cleaned up after upgrade.
in theory, i see this as a general case: when an old resource is removed from manifests, it should be auto removed after operator reconcile. 

but i am not sure, how  it will be if it's from v1 to v2(as if someone created ovms-gpu-ootb by  operator v1 then upgrade to operator v2, will that be cleaned up or hanging in the cluster)
