### ISSUE TITLE
[Bug]: ovms-gpu-ootb is missing recommended accelerator annotation

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.16.0

### Current Behavior

the OOTB gpu model serving template is missing the recommended accelerators annotation for `nvidia.com/gpu` so the label does not show up when selecting a NVIDIA GPU.

Notes: The OOTB GPU enabled model serving template is missing the annotation `'opendatahub.io/recommended-accelerators': '["nvidia.com/gpu"]'` which makes the "Recommended serving runtime" label not show up in the "Add model server" modal's Serving Runtime dropdown options.

### Expected Behavior

for the label to show up when selecting the NVIDIA GPU

### Steps To Reproduce

1. open model server create modal
2. select the gpu model server
3. accelerators with identifier = `nvidia.com/gpu` wont have a recommended label next to it

### Workaround (if any)

not a breaking bug, but you can manually add the label when making a copy of the template model server

**Comment by bredamc** [comment]
@Gkrumbach07 If you would like to include this issue in the 1.34 Release Notes, please provide the text for the "Known issues" section.

**Comment by Gkrumbach07** [comment]
@bredamc here is something

The OOTB GPU enabled model serving template is missing the annotation `opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'` which makes the "Recommended serving runtime" label not show up in the "Add model server" modal's Serving Runtime dropdown options, when it should be there.

**Comment by bredamc** [comment]
@andrewballantyne Do you still want to include this bug in the Known issues section of the 1.34 Release Notes?

If so, is the following text ok?

"
[ODH-DASHBOARD-1991](https://github.com/opendatahub-io/odh-dashboard/issues/1991) - ovms-gpu-ootb is missing recommended accelerator annotation

When you add a model server to your project, the Serving runtime list does not show the "Recommended serving runtime" label for the NVIDIA GPU.

Workaround
    Make a copy of the model-server template and manually add the label.
"

**Comment by andrewballantyne** [comment]
@bredamc Yup that works... it's unfortunate but should be fixed in 1.36 when we release KServe
