### ISSUE TITLE
[Tracker]: Notify users of new features that are available

### ISSUE THREAD

**Issue by xianli123** [opendatahub-io/odh-dashboard#1993]
### Description

Openshift AI is a complex platform that will continue to release new features. In order to avoid users missing out on some important new features, we want to have a design that would help users quickly notice that new features are available. The design will be applied to the whole dashboard.

### Target Branch

TBD

### Requirements

This needs the UX designer to come up with an idea to show the notes.
* It makes users easily notice that there is a new feature available.
* There will be a brief description of the new feature.
* It's better to have the documentation link that can lead users to know more details of the new feature.

### Itemized UX Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/1802
* https://github.com/opendatahub-io/odh-dashboard/issues/1856

### Itemized Dev Issues

TBD

**Comment by xianli123** [comment]
@kywalker-rh @andrewballantyne @yannnz I created this tracker about how to notify users when a new feature is released. It's not an urgent thing. I will take some time to research other products and make a design. Please have a look and add something I might missed.

**Comment by kywalker-rh** [comment]
@xianli123 I think this should also be linked with https://github.com/opendatahub-io/odh-dashboard/issues/1856, since the content may appear on a landing page.

**Comment by dgutride** [comment]
RFE created on jira for this - moving to closed.
