### ISSUE TITLE
[Story]: No serving platforms available view

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1994]
### Goal

Create a view to display when there are no serving platform available selected

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1913
* https://github.com/opendatahub-io/odh-dashboard/issues/1941

### Itemized goals

* Detect that neither `kserve` and `modelmesh` are available to select in the cluster
* Display a view to prevent the user to select a serving platform

### Mocks

![image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/ad93d9a0-ff0c-4d5b-aa6f-90e81e3015d4)

**Comment by lucferbux** [comment]
@vconzola I've added this to keep track of the state of not having any platform selected.

**Comment by lucferbux** [comment]
This will be covered in https://github.com/opendatahub-io/odh-dashboard/issues/2010, closing this in favor of that issue.

**Comment by vconzola** [comment]
If neither KServe nor ModelMesh is selected in the cluster settings when a new project is created, we should display this empty state in the project's Models and model servers section. https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/v/Arobq4/a/uuid/036B63EC-0D57-44CF-8A9F-63DF6B4F0BAC
