### ISSUE TITLE
[Bug] Error message on enabling TrustyAI via UI are not descriptive

### ISSUE THREAD

**Issue by nehachopra27** [opendatahub-io/odh-dashboard#1996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2

### Current Behavior

When Enabling a TrustyAI service via UI, when the Operator is not installed, The error message is 404 Page not Found.
<img width="1430" alt="Screenshot 2023-10-20 at 13 34 40" src="https://github.com/opendatahub-io/odh-dashboard/assets/11557840/a9f4dfe2-437d-4ffb-ab93-c5913c28f85a">

### Expected Behavior

Clear Error Message should be available to user so that he can do the configuration. 

### Steps To Reproduce

1. Create a Data Science Project
2. Navigate to DSP page
3. Click Settings
4. Check the Enable TrustyAI checkbox

**Comment by andrewballantyne** [comment]
Ah yeah... we had this with model serving... it had the same 404 error when the API is not there.

**Comment by alexcreasy** [comment]
@ppadti use this error message for now, we'll need QE signoff before we merge the ticket.

"The TrustyAI operator is not installed on this cluster."

**Comment by ppadti** [comment]
> @ppadti use this error message for now, we'll need QE signoff before we merge the ticket.
> 
> "The TrustyAI operator is not installed on this cluster."

sure, Thanks @alexcreasy

**Comment by alexcreasy** [comment]
@nehachopra27 we've merged the mitigation we agreed for this to our feature branch. The complete solution for this (i.e. hide the tab altogether if TrustyAI is not installed), will need this PR to merge first: https://github.com/opendatahub-io/odh-dashboard/pull/2032.
