### ISSUE TITLE
[Bug]: Option to expand storage should be disabled when the storage cannot be increased

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.22.0-2

### Current Behavior

We have 2 situations:
1. When a cluster storage (PVC) has never been connected to any workbench, its size cannot be increased, because the PVC is not bound to any volume 

Result: The UI allows users to increase the storage size from the Edit modal, however the change is not saved and next time the PVC will get connected to a workbench, it will be created with the original size.

2. When a cluster storage (PVC) was connected to a workbench and now is not connected to any, its size can be increased, because the PVC is already bound to a volume

Result: The UI allows users to increase the storage size from the Edit modal, however the change is not saved and if the user opens the Edit modal again, they will see the original size. Next time the PVC will get connected to a workbench, it will be created with the new requested size.

### Expected Behavior

field to increase the storage size is disabled if PVC is not bound

### Steps To Reproduce

1. create a PV storage in the DS Project
2. click on "Edit storage" from 3dots menu on the right
3. increase the PV size

1. create a workbench and attach a PV storage
2. delete the workbench
3. click on "Edit storage" from 3dots menu on the right
4. increase the PV size

**Comment by shalberd** [comment]
@bdattoma duplicate? feature branch ODH just not yet merged into RHOSDS?

https://github.com/opendatahub-io/odh-dashboard/issues/1876#

Also, watch out for this when resizing PVCs based on a given storage class name: https://github.com/opendatahub-io/odh-dashboard/issues/1876#issuecomment-1739093145

**Comment by andrewballantyne** [comment]
We are working to get this into `main` next sprint. I'll leave this open for now for next triage as a topic point to the team.

**Comment by bdattoma** [comment]
ok thanks! Sorry for the duplication, I think I searched among the Open Issue only that's why I didn't find the other one.

**Comment by andrewballantyne** [comment]
Ooops, this actually should be part of `main` now. RHOAI 2.5.
