### ISSUE TITLE
[Tech Debt]: Migration Scripts in Node

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2013]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

We build out the odd migration function to do something usually fairly small.

When we approach writing it, it usually is something like:
- Read for the state configmap (is it on-going, reduces multiple pod overla -- sorta)
- Write the state configmap
- do the operation
- Update the configmap
- Handle error cases if something blows up

### Why?

It's inefficient and the various migration efforts are all manual with no real shelf-life.

I propose we spend some time making a pattern that we can do flexible stuff in. Mutate k8s resources, move from one to another, upversion things... etc.

Emphasis on handling failures and reporting them consistently. Code organization would also help here. Shelf-life dates and plans might also be good to document so we know when we can remove the code.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2908
