### ISSUE TITLE
[Bug]: Manually triggered pipeline runs do not include the latest pipeline version

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/odh-dashboard#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.33.0

### Current Behavior

Please refer to the description in this task: https://github.com/opendatahub-io/data-science-pipelines/issues/164#issue-1952349023, and this comment: https://github.com/opendatahub-io/data-science-pipelines/issues/164#issuecomment-1779969741, for current behavior.

### Expected Behavior

Please refer to this comment: https://github.com/opendatahub-io/data-science-pipelines/issues/164#issuecomment-1779969741, for expected behavior.

### Steps To Reproduce

Please refer to the description in this task: https://github.com/opendatahub-io/data-science-pipelines/issues/164#issue-1952349023, and this comment: https://github.com/opendatahub-io/data-science-pipelines/issues/164#issuecomment-1779969741, for steps to reproduce this bug.

### Workaround (if any)

Please refer to this comment: https://github.com/opendatahub-io/data-science-pipelines/issues/164#issuecomment-1779969741, for a potential workaround.

**Comment by DharmitD** [comment]
cc: @gregsheremeta @mamurak

**Comment by manaswinidas** [comment]
@andrewballantyne @dgutride Review the path for this

**Comment by dgutride** [comment]
Replaced by:  https://issues.redhat.com/browse/RHOAIENG-272
