### ISSUE TITLE
[Feature Request]: Inject default configurations in Notebook CR on workbench creation

### ISSUE THREAD

**Issue by adrien-legros** [opendatahub-io/odh-dashboard#2015]
### Feature description

This comes from a feedback of a customer in a testing phase. We need a way to inject default configurations when creating a new workbench.

There are few use cases where it is needed:
- The customer injects CA bundle using 2 different labels in their Notebook, so he can connect to his internal Git.
- He would like pip to be configured by default. So adding default env var, eventually mount the pip config file from a configmap.

### Describe alternatives you've considered

- Asking ODH users to copy, customize and deploy a Notebook CR from a list of pre-configured ones. However the users are not necessarily familiar with Openshift. We also don't leverage the workbenches section of the UI.
- Using templates to normalize Notebooks. Including those in the UI with a mean to set parameters would be a great solution.
- Creating a parallel dashboard that take care of the notebook conf and creation. But we don't leverage the workbenches section of the UI and it required work on customer side.

### Anything else?

Despite not explicitly asked by the customer, we might need to set additional configurations such as tolerations. It might not be a default config for all their notebooks but at least a subset of them #633

**Comment by shalberd** [comment]
regarding own pip conf: https://github.com/opendatahub-io/notebooks/issues/127#issuecomment-1709547310

**Comment by adrien-legros** [comment]
Thank you Sven for your reply. It seems that the customer is not using the cluster wide proxy. In fact their injections is made using different labels. So I suppose they use their own operator do inject the CA, that's why they need it here. I will try to find out why.

**Comment by manaswinidas** [comment]
## UX context

How do we want to allow admins to configure a default for each notebook? This probably is for both global and projects.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-13
