### ISSUE TITLE
[Tracker]: Support e2e Mocked Tests

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2016]
### Description

We have a need to start writing on-PR end-to-end (e2e) tests that have high reliability to execute as intended. Our features need the ability to provide e2e tests that perform logical user paths to make sure the feature performs as intended.

Biggest problem we have with e2e tests using a cluster is stability. Stability in hosting the cluster, stability in executing all the test cases, stability in speed to complete the task. This leaves us with a bit of a gap being able to perform on PR tests with stability as flakes are a common problem with live cluster testing.

We have decided that we need mocked e2e tests for PRs. These should be more reliable.

### Target Branch

main

### Requirements

* Setup Cypress (chosen by QE & Dev as a middle ground)
* Tests should be able to run on all PRs (add it to the existing testing framework npm script executions)
* Tests should have stability and not need a cluster to test against (specifically when running on PRs)
* Tests should have the ability to be executed against a cluster locally if needed
    * We'll want to be able to setup nighty CI to execute the same tests against a cluster, mocker needs to be optional

### Itemized UX Issues

N/A

### Itemized Dev Issues

* https://github.com/opendatahub-io/odh-dashboard/issues/2071
* https://github.com/opendatahub-io/odh-dashboard/issues/2072
* https://github.com/opendatahub-io/odh-dashboard/issues/2246
* https://github.com/opendatahub-io/odh-dashboard/issues/2252
* https://github.com/opendatahub-io/odh-dashboard/issues/2254
* Write an e2e test against Projects or some already existing feature as an example
* Backend TSC issues do not break the CI ([example](https://github.com/opendatahub-io/odh-dashboard/actions/runs/7120035177/job/19386423074#step:9:25))
* Jest tests appear to run before TSC (so type issues can look like failed tests weirdly)

**Comment by dgutride** [comment]
Work complete - moving to closed.
