### ISSUE TITLE
[Bug]: Usage Data Collection docs are incorrect

### ISSUE THREAD

**Issue by MelissaFlinn** [opendatahub-io/odh-dashboard#2020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.34

### Current Behavior

Currently, the link goes to
https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html/managing_users_and_user_resources/usage-data-collection#usage-data-collection-notice-for-openshift-data-science

This is correct for downstream versions 1.33 and earlier

### Expected Behavior

For 1.34 and later, the link should go to:
https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html/managing_resources/usage-data-collection#usage-data-collection-notice-for-openshift-data-science

(change "managing_users_and_user_resources" to "managing_resources")

### Steps To Reproduce

1. In the RHODS dashboard, admin view, select Settings> Cluster Settings.
2. Scroll down to the *Usage data collection" section - click on the "documentation" link.
![doclink-cluster-settings](https://github.com/opendatahub-io/odh-dashboard/assets/31925014/16356224-39df-448b-8107-6d53c5536a03)

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1198
