### ISSUE TITLE
[Feature Request]: Create a migration to remove old v1alpha version from accelerator profile crd

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2021]
### Goal

Currently there are two versions inside the accelerator profile crd with v1 being the current and v1alpha being the old. They are identical other than the version name. Some user could still be have crs of version v1alpha while some and all future users are using v1 for their crs.

Create a migration script that removes the v1alpha version from the CRD and converts all the CRs to v1 version

### Dependency issue

No dependencies

### Itemized goals

- create a migration script

### Mocks

No mocks

**Comment by andrewballantyne** [comment]
@Gkrumbach07 can you associate this to your Tracker for phase 2 of Accelerator Profiles? This should be a story not a feature request

**Comment by Gkrumbach07** [comment]
@andrewballantyne does this still need migration? all this migration would be doing is removing the version, which is what the operator would do anyway. There is not a need to update the CRs right?

**Comment by andrewballantyne** [comment]
I think the goal here was to remove it from the versions in the CRD 🤔 CR versions didn't change anything and thus don't need to be modified afaik. We can float this one down the line if you want (ie separate from your tracker) -- but I would like to keep this issue open so we can remove the v1alpha version from the CRD at some point.

**Comment by Gkrumbach07** [comment]
Right, I am ok with pushing it off the tracker. 

However, I am not entirely sure the migration would do anything, becuase couldnt we just push out a new version of the crd. All migration does is a PUT request to remove v1alpha version from the crd.

**Comment by andrewballantyne** [comment]
It won't do anything to the CRs I imagine, but we need to make sure we test that. The CRD having the v1alpha API seems kinda goofy but was needed when we had to do it last min and caused a break in the flow. If we have to keep it "indefinitely" it doesn't really hurt either... since the API is the same.

**Comment by Gkrumbach07** [comment]
Here is the proposed migration [solution](https://gist.github.com/Gkrumbach07/d0b0f103ae73273f178b830612a7c35c). This works well, but I am still not sure when e will update the actual manifests to remove v1alpha
