### ISSUE TITLE
[Tech Debt]: Refactor Event Tracking in Project List View

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2039]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

The current implementation of event tracking is intermixed with core flows in the project list view, specifically in the fireNotebookTrackingEvent function. This is causing unnecessary fetching of accelerator profiles and other data not relevant to the page which could lead to performance and maintenance issues.

### Why?

Separating event tracking from core functional flows will enhance code readability and maintainability. It will also prevent unnecessary operations like pulling accelerator profiles in contexts where they are not needed, thereby improving performance.

### Anything else?

Suggested Fix: Decouple the event tracking logic from the main functional flows, possibly by abstracting it into a separate module or using a more modular approach.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2955
