### ISSUE TITLE
[Tech Debt]: rename RHODS references

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#2044]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

Wherever `Red Hat OpenShift Data Science` or `RHODS` is referenced, rename the reference to `OpenShift AI`.

First evaluate whether the reference is necessary and should otherwise be removed.

### Why?

Alignment with name change.

**Comment by andrewballantyne** [comment]
Definitely found in the docs, but most of our code won't reference a deployment. We probably half only a few references.
