### ISSUE TITLE
[Story]: OVMS OOTB Model does not support KServe

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2048]
### Goal

Decide which is the best approach for OVMS in Kserve

### Dependency issue

No dependencies

### Itemized goals

1. Right now OVMS is supporting both kserve and modelmesh
2. But it contain modelmesh exclusive spec, see https://github.com/opendatahub-io/odh-dashboard/blob/f/model-serving/manifests/modelserving/ovms-ootb.yaml#L49
3. We need to figure out with the model serving team which is the best approach to support kserve for OOTB

### Mocks

No mocks

**Comment by lucferbux** [comment]
https://github.com/opendatahub-io/odh-dashboard/issues/2059

**Comment by bdattoma** [comment]
so decision was to allow OVMS to run on Modelmesh only, no KServe. @lucferbux correct?

**Comment by lucferbux** [comment]
> so decision was to allow OVMS to run on Modelmesh only, no KServe. @lucferbux correct?

Yes, I'm sorry @bdattoma I thought i updated the description, give me a sec.
