### ISSUE TITLE
[Story]: Regression in modelmesh modal for tokens

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2049]
### Goal

In `ManageServingRuntimeModal` we have a regression when selecting `Token authorization`, it no longer automatically generates the first token

### Dependency issue

No dependencies

### Itemized goals

1. Fix a regression
2. To reproduce, create a new Model Server in modlemesh
3. Select token authorization
4. It should present a default token, but right now it's not there

### Mocks

No mocks

**Comment by DaoDaoNoCode** [comment]
I need to correct something here. When you select `token authorization`, the default service account will show up. The problem is when you select `model route`, it will automatically select token authorization, and only in this case, the default token will not be generated.
