### ISSUE TITLE
[Story]: Display lack of accelerator recommendations in column

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2056]
### Goal

Find an alternative to "disabling a label" to signify  lack of accelerator recommendations in column

### Dependency issue

- https://github.com/opendatahub-io/odh-dashboard/issues/1439

### Itemized goals

In the current [mocks](https://www.sketch.com/s/c8183f89-76f5-4a23-b885-a9e404a61414/a/P1Wp0m1) for Habana part 2, the label "Create profile" button is disabled for images that lack the recommend accelerators annotation. This is not possible in PF. 

![Screenshot 2023-11-02 at 6 17 49 PM](https://github.com/opendatahub-io/odh-dashboard/assets/12587674/df674891-3d8a-403b-944c-37dc5acfbefa)

### Mocks

No mocks

**Comment by Gkrumbach07** [comment]
@yannnz I ran into this last week. Context for the problem is in the issue description

**Comment by yannnz** [comment]
Hi Gage, is it possible to use the compact filled grey label with icon to visually fake the disabled clickable label? [PF compact filled label](https://v4-archive.patternfly.org/v4/components/label/#compact) @Gkrumbach07

**Comment by Gkrumbach07** [comment]
Here is what it looks like
<img width="411" alt="Screenshot 2023-11-07 at 1 45 14 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/79818d92-8835-473d-9f17-325867c07faa">

**Comment by yannnz** [comment]
> Here is what it looks like @yannnz <img alt="Screenshot 2023-11-07 at 1 45 14 PM" width="411" src="https://user-images.githubusercontent.com/12587674/281163365-79818d92-8835-473d-9f17-325867c07faa.png">

Hmmm, is it possible to change the color of the icon and text to grey too?

**Comment by Gkrumbach07** [comment]
@yannnz that is the patternfly grey. So the other options is to manually set the css, but we should avoid doing tha

**Comment by yannnz** [comment]
> @yannnz that is the patternfly grey. The other option is to manually set the css, but we should avoid doing that if possible

I see. I checked with the PF team today, here is the suggestion of how to disable the editable label and what are the limitation of the approach: https://patternfly.slack.com/archives/C293LQ36J/p1699429646350539

If it is not a good approach from the development perspective,  I think it is fine to just leave it as black at least the user will see the label and the tooltip to understand how to enable that function. WDYT @Gkrumbach07

**Comment by Gkrumbach07** [comment]
> I see. I checked with the PF team today, here is the suggestion of how to disable the editable label and what are the limitation of the approach: https://patternfly.slack.com/archives/C293LQ36J/p1699429646350539

This is a PF5 solution and even then it is not perfect. disabling doesnt seem to change the color at all. I think the problem is that labels are not meant to be used as buttons. They can be external links, or can be edited, but not as a button

**Comment by yannnz** [comment]
> > I see. I checked with the PF team today, here is the suggestion of how to disable the editable label and what are the limitation of the approach: https://patternfly.slack.com/archives/C293LQ36J/p1699429646350539
> 
> This is a PF5 solution and even then it is not perfect. disabling doesnt seem to change the color at all. I think the problem is that labels are not meant to be used as buttons. They can be external links, or can be edited, but not as a button
> 
> @yannnz

Eric replied and said he can help on the disabling style with PF V4.: https://patternfly.slack.com/archives/C293LQ36J/p1699464992885189?thread_ts=1699429646.350539&cid=C293LQ36J
Would it help the issue we have here?  In the PF doc, the Label can be used to trigger a modal or dropdown, though it is a different use case as we have here: https://v4-archive.patternfly.org/v4/components/label-group/react-demos#editable-labels-with-add-modal

**Comment by Gkrumbach07** [comment]
We landed on this UX

![image](https://github.com/opendatahub-io/odh-dashboard/assets/12587674/6f107eb7-5854-4ffd-bc95-e6b4c1fa78b5)
