### ISSUE TITLE
[Story]: Support Istio Values in `notebookNamespace`

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2060]
### Goal

It seems the work for OSSM is working on the dashboard namespace -- but when Juyter Tile uses the `notebookNamespace` there is a gap

### Dependency issue

No dependencies

### Itemized goals

* Manage the needed annotations on the project for `notebookNamespace` when it is enabled (optional)

### Mocks

No mocks

**Comment by andrewballantyne** [comment]
@cam-garrison @bartoszmajsak We did talk about this, let me see if I can reiterate what we last talked about.

This is intended to be a documentation flow, correct? You're not going to "manage" this namespace like you manage others (aka. application namespace & ds projects), so this just needs to be documented for "using labels and annotations" if one wants to set this up?

In RHOAI, this may need to be something we work with the Operator folks to make sure we get that auto setup, but for ODH it could be documentation. Does that sound right?

**Comment by bartoszmajsak** [comment]
I'm not sure I have enough context here. Does it mean you can point jupyter tile to any existing ns? If so, in order to be managed by service mesh it has to have the annotation.

**Comment by cam-garrison** [comment]
@andrewballantyne Your summary is accurate based on the discussions we had before -> plan was to provide documentation to have the user set the annotation.

**Comment by andrewballantyne** [comment]
> I'm not sure I have enough context here. Does it mean you can point jupyter tile to any existing ns?

@bartoszmajsak Yes, it is called the `notebook-namespace` and it's in the OdhDashboardConfig under `.spec.notebookController.notebookNamespace`. 

To be clear, ODH is "by your own path" to handle the Jupyter tile in ways you need. So documentation, if applicable, would be needed.

RHOAI on the other hand, creates a namespace for the deployments and [sets the namespace](https://github.com/red-hat-data-services/odh-manifests/blob/d72c788e8eeba638c583a8c7be2508757be1f26c/odh-dashboard/odhdashboardconfig/odhdashboardconfig.yaml#L30). This likely will need to be handled OOTB if Service Mesh is enabled... as we have both managed and self managed installations. So we need to cross this path before we can take Service Mesh to RHOAI, likely with a conversation with the Operator team.

**Comment by dgutride** [comment]
Moving to closed - unsure what needs to be done here, if you'd like me to recreate this in jira, please let me know.  My expectation is the work referred to in this epic will encompass this.  https://issues.redhat.com/browse/RHOAIENG-372
