### ISSUE TITLE
[Feature Request]: Hiding outdated workbench image version from Dashboard

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/odh-dashboard#2084]
### Feature description

Currently, Opendatahub ships with multiple OOTB workbench images. Each image has 2 version included with it (eg: Data-Science 2023.1 and 1.2). With the latest OpenDatahub 2.4 release, there is an introduction of new version tag 2023.2.
With this cadence to support 1.2 version image has come to an end from the OpenDatahub/Notebook component. 

As we prompt users to switch to newer images, we should also start disabling (i.e Hide old version tag) from Dashboard UI.
So the user can spin a new workbench with out-of-date image version. 
This would not cause hindrance to long-running notebooks. It is only a positive way of asking user to utilize newer version of these images.

Based on this IDE team has already worked: https://github.com/opendatahub-io/notebooks/issues/154
Included annotation to the out-of-date images:
` opendatahub.io/image-tag-outdated:true`

Task to perform:
- Based on the annotation set, hide the version from the workbench view.

### Describe alternatives you've considered

None

**Comment by manosnoam** [comment]
Verified in RHOAI 2.5: When notebook has an outdated image, it is showing:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/0b0008f6-cf68-4f5f-81e5-e8fb9bdab9a7)

**Comment by jstourac** [comment]
Just for completion - the situation that Noam just described is for an imagestream with just one tag (version). If there are more tags in the imagestreams available, only those tags that aren't marked as outdated are shown in the UI as expected.

Thank you, guys.
