### ISSUE TITLE
[Tech Debt]: Enforce `no-magic-numbers` lint rule

### ISSUE THREAD

**Issue by manaswinidas** [opendatahub-io/odh-dashboard#2096]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

Enforce `no-magic-numbers` eslint rule so that we don't worry about it in case we miss it while reviewing. 

https://eslint.org/docs/latest/rules/no-magic-numbers

Before we merge this, let's validate what the impact of the lint rule is.

### Why?

Magic numbers make it difficult to maintain code(https://github.com/opendatahub-io/odh-dashboard/pull/2034#discussion_r1385492214)

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-509
