### ISSUE TITLE
[Story]: Bring popovers to Kserve Modal

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2097]
### Goal

Add popovers present in the modelmesh modal to kserve

### Dependency issue

No dependencies

### Itemized goals

As a follow up of https://github.com/opendatahub-io/odh-dashboard/issues/1580, bring those popovers to kserve modal

### Mocks

No mocks

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1783
