### ISSUE TITLE
[Story]: Kserve support for performance metrics

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#2099]
### Goal

Ensure our performance metrics features for both the model server and also models themselves work with Kserve in addition to model mesh

### Dependency issue

* Backend support: https://github.com/opendatahub-io/kserve/issues/119

### Itemized goals

* Add Kserve support for model server metrics
* Add Kserve support for model inference metrics

### Mocks

No mocks

**Comment by dgutride** [comment]
Migrated to https://issues.redhat.com/browse/RHOAIENG-246 - moving to closed
