### ISSUE TITLE
define available components via openshift labels on the routes

### ISSUE THREAD

**Issue by erikerlandson** [opendatahub-io/odh-dashboard#21]
I can't tell if you are already doing this from the code:  Was thinking it might be elegant to have the dash just look for available routes by a special odh label.  That would also make it easy to customize with additional routes for a customer, if desired.

I see you have a sort of javascript database of [attributes](https://github.com/opendatahub-io/odh-dashboard/blob/master/routes/api/components/available-components.js). Conceivably it could all be stored in configmaps created by the operator, which also could be extended by adding custom configmaps.

**Comment by cfchase** [comment]
I like this as it would allow other components and projects to define their own attributes outside of the code.  Unless there are objections by @vpavlin , @nakfour or others, I can work on this

**Comment by andrewballantyne** [comment]
It would definitely be interesting to mount cards based on available routes -- but we'd need to think through the UX of this. What about the icon? The display label? The description? There is more to the cards than just a route link, but it is a promising idea to exposing more components.

**Comment by cfchase** [comment]
Looks like this issue has been going stale.  I would think we could configure components and routes on the CR once https://github.com/opendatahub-io/odh-dashboard/pull/243 is implemented?

**Comment by andrewballantyne** [comment]
Calling this issue stale... closing. We can reopen if the request is still desired.
