### ISSUE TITLE
[Bug]: "End date" picker in pipeline run creation page defaults to NaN when using Firefox

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#2100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.33

### Current Behavior

When trying to create a pipeline with a scheduled recurring run, enabling the "End Date" parameter results in NaN values for both the date and time.
Even after modifying the values to "real" ones the page remains in error state and the pipeline cannot be created. The only way to proceed is to disable both End and Start Date options.

This is only reproducible while using Firefox (confirmed at version 119.0 on Fedora) - the same issue is not reproducible using Chromium on Fedora or Chrome on Mac

![image](https://github.com/opendatahub-io/odh-dashboard/assets/82518733/a57e551a-adec-4bb4-a50d-a7c5ccb39de9)

### Expected Behavior

End Date defaults to a real date and time, values can be changed at will, and the pipeline scheduled run can be created

### Steps To Reproduce

Use firefox
Got to Data Science Pipelines page
Create a new Pipeline 
Use a "Scheduled recurring run" Run type
Enable the "end date" parameter under "Duration"

### Workaround (if any)

Use a different browser

### What browsers are you seeing the problem on?

Firefox

### Anything else

`Firefox Version 119.0` on `Fedora - 1.0`

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1197
