### ISSUE TITLE
[Feature Request]: A way to update an endpoint through the UI

### ISSUE THREAD

**Issue by RHRolun** [opendatahub-io/odh-dashboard#2104]
### Feature description

If I update a model, either by replacing the existing one or adding a new version of it (in the folder structure 0/model.onnx, 1/model.onnx, etc), there seems to be no way to make the model server update to the new version of the model without going to OpenShift and updating the InferenceService object.
The goal of this feature is to add a visual way for a user to update the model server in the above cases, while keeping the endpoint address the same.

### Describe alternatives you've considered

Some ways to do this could be:
- Adding a refresh button next to the status icon for each model
- Adding another option in the dropdown for each served model called "Update"

**Comment by andrewballantyne** [comment]
cc @lucferbux

**Comment by lucferbux** [comment]
Hi @RHRolun do you mean by that that if you replace the model location with a new model, the controller itself is not reloading unless you change something else in the spec?

UI wise we just update the spec of the `InferenceService`, but if that's so, I think we need some tweaks in the controller.

cc @Jooho @Xaenalt let's wait for the response, but if that's the case we'll need to transfer the ticket!

<img width="819" alt="Screenshot 2023-11-21 at 10 27 19" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/e7367d94-af63-4c69-95e1-4e792e58a543">

**Comment by Xaenalt** [comment]
This is specific to modelmesh correct? I recall there was some part of the modelmesh design which makes watching for storage changes difficult. That being said, the default OVMS does have this kind of watching feature, but I'm not sure that modelmesh implements it. This would be a good question for @ckadner from IBM

**Comment by RHRolun** [comment]
Hi @lucferbux ,

> do you mean by that that if you replace the model location with a new model, the controller itself is not reloading unless you change something else in the spec?

Exactly, if I overwrite the model in the S3 bucket or add a new version of that model in the S3 bucket (like in the image below), the model controller does not update unless I force it to by changing something in the spec.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/113337503/3c09b7b8-9010-4db9-8f77-d3c19e12014e)

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-10
