### ISSUE TITLE
[Feature Request]: In-application example for inference

### ISSUE THREAD

**Issue by RHRolun** [opendatahub-io/odh-dashboard#2106]
### Feature description

When a user serves a model, it's not obvious how to send inference requests to it.
This feature aims to guide the user by giving them a working code example, obtainable through the visual interface, that fits the model they have served.
For example, they could access it through an option in the deployed models list, next to the relevant models.
The code example would contain all required fields pre-filled with the correct information (such as the input layer name) and dummy data (a bunch of zeros for example). 
The user would also be able to select between the different languages, such as Python and R when R becomes supported.

**Comment by andrewballantyne** [comment]
cc @lucferbux

**Comment by lucferbux** [comment]
Hi @RHRolun we have this same thing in our roadmap for model registry, we can improve the inference list page too, that's something we can discuss. cc @vconzola @simrandhaliw

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-9
