### ISSUE TITLE
[Feature Request]: Support Disabling Workbenches Section of DS Projects

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2107]
### Feature description

When we disable Workbenches from the API, it breaks a lot of the flows in the DS Projects. We should either "not support" it right now or fully support it. Hiding the Workbenches section is all that is done in `main` today and we should look to do all the needed dependency areas.

Some ideas where we are having issues:
- DS Projects view list gets stuck at the skeleton loader trying to read the status of the workbenches (columns probably need to be removed)
- "Connected workbenches" column in PVC & Data Connection tables gets stuck in loading
- The Add PVC and Data Connection modals have sections in the form to connect them to workbenches -- these are broken flows

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2752
