### ISSUE TITLE
CNBI Phase 2

### ISSUE THREAD

**Issue by jkoehler-redhat** [opendatahub-io/odh-dashboard#212]
Problem statement
Goals
Enable RHODS users to easily get started with the packages/libraries/components they need for their data science projects.
Enable RHODS users to be confident that their notebooks will work given dependencies across specific versions for needed packages/libraries/components.
Problem
RHODS provides several out-of-the-box notebook images that automatically include packages to make it easy for users to get started with common components. However, in many/most instances, users need a specific set of packages/libraries with specific versions depending on the projects. There are so many possible variations of these packages/libraries/versions that it’s not practical to provide out-of-the-box images to anticipate the various needs. Users do not want to have to rely on pip installs for all the packages/libraries on a regular basis because it’s time consuming, and it can be difficult to keep track of all the needed components. They are looking for a quick & easy way to start a notebook session with the components they need for a project. Oftentimes, there can be repeatable patterns for the necessary components rather than starting from scratch for every project. 

Many times users need specific package/library versions for a project, and they need to ensure that the combinations of packages & versions will work together. This could be driven by the need to leverage existing code that was created using a specific package/library version. They want to avoid scenarios where the notebook won’t run successfully because of an incompatibility across different packages & versions. 

Why is it important?
This is a common/core function, and users need to be able to get started quickly and easily so they don’t waste time trying to assemble the needed components to get started. They don’t want to waste time manually installing all the needed components for each project, and they don’t want to spend time trying to resolve dependency issues across packages/versions. This is a key part of the value proposition for RHODS - make it easy for users to get started and be productive on their data science projects. RHODS needs to be flexible enough to accommodate the wide range of packages/libraries/versions needed across users. 

Requirements
P0 - ‘must have’ - would hold up release without this 
P1 - ‘should have’ - should plan to do this, but wouldn’t hold up release for it
P2 - ‘nice to have’ 

Number
Priority
Requirement
1
P0
Admins must be able to bring in/import existing notebook images for use in RHODS. The system must enable users to bring in/import notebook images via the RHODS UI (eg. users should not have to edit config files such as YAML files). After import, the images should be available for selection in the UI like out-of-the-box images. 

Use case: Organizations have existing notebook images they created for past data science projects. They want to use these images in RHODS. 

Notes:
Need the right base image; might not be able to be completely free form
Can we identify any vulnerabilities? 
Custom not supported like OOTB; they would have to reproduce problem in one of our OOTB images
Some type of validation based on base image - eg. UBI-8
2
P0
Users must be able to create new notebook images from scratch by defining the packages/libraries/components needed. 

Notes:
Users should be able to start with fundamental components - eg. Python version
Users not forced to verify & resolve dependency issues.
3
P0
Users must be able to copy an existing notebook image (either provided by Red Hat or custom), make changes by adding/removing components, and create/save the new image. 
4
P2
Users must be able to make custom images private (only accessible by the user) or public (accessible to all cluster users).

Notes:
If this requirement is not fulfilled, the default is public 
Imported images (eg. by admins) would be public
Might need to address the epic for deploying NB servers in separate user namespaces before supporting this item?
Can we prevent users from making public?
5
P1
The system must provide users some capability to check dependencies and verify any dependency issues as they are defining the components in a notebook or a new custom image.

Notes:
User adds a TensorFlow version and needs to identify dependencies (specific packages and versions needed) 
User adds a TensorFlow version and adds an incompatible version of a dependency (eg. the wrong version of scipy to work with the added TensorFlow version). The user should be able to access a tool in the UI to identify the issue and make corrections.
Can Thoth service address this?
This should be an optional tool
6
P1
Users must be able to add & remove components/packages to/from an environment from a curated library directly via the UI.

Notes:
Idea is to incorporate Guillaume’s module concept
If applicable, UI should distinguish between “community” modules and Red Hat provided modules
Red Hat doesn’t have to provide any modules
7
P0
Admins must be able to export custom images & store on a local system.

Notes:
This could be provided as part of standard OSD capabilities
The idea is to give users an option to store custom images they create in a separate location for backup purposes.
Put in a registry instead of local?

P2
If a custom image is built on top of RH-provided curated image, provide a way that the custom image can be rebuilt when the curated image is updated by RH. 

Acceptance Criteria
Verify ability to import custom NB images and have the images be available for selection in the UI in the same way as out-of-the-box NB images.
Verify ability for user/admin to export custom NB images and store on a local system.
Verify ability to create a new image from scratch by defining image components/packages and have the image be available for selection in the UI like OOTB NB images.
Verify ability to create a new image using a different Python version like Python 3.9 and have the image be available for selection in the UI like OOTB NB images. 
Verify ability to create a new NB image from an existing RHODS NB image (either custom or OTTB) and have the image be available for selection in the UI like OOTB NB images.
Verify ability to dynamically add/remove packages/components to/from an environment via the “modules” UI.
Verify ability to access a tool in the UI to identify and verify dependencies for components/packages during the process of creating a new custom NB image. 
TBD: Verify ability to create a new custom image and have the image only be available for selection for the user that created the new image.

**Comment by andrewballantyne** [comment]
This ticket should get a similar rework to match the effort @samuelvl did in https://github.com/opendatahub-io/odh-dashboard/issues/213 -- but can wait until we put our focus into it.

**Comment by samuelvl** [comment]
@andrewballantyne Regarding CNBi we are still in the architecture phase https://docs.google.com/document/d/1lESU67PFCtM5Mt05wL_ee_LY7Wc9OcGNBb5cvcOtkVU 

We can rework this issue when we finish the architecture document
