### ISSUE TITLE
[KFNBC] Requirements

### ISSUE THREAD

**Issue by jkoehler-redhat** [opendatahub-io/odh-dashboard#213]
Replace JupyterHub (JH) with Kubeflow notebook controller (KFNC). The aim is to have feature parity with existing JH functionality while utilizing the KFNC backend capabilities.  Mockups for UX/UI here: https://marvelapp.com/prototype/90ii3fd/screen/85876386

## Requirement 01 (Done)
The system must provide an access point to create NB server sessions (“spawner” page).

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/267 

## Requirement 02 (Done)
The dashboard components and any associated UI text & documentation (eg. quickstarts, how to docs, etc.) must have appropriate branding & terminology for KFNC rather than JH.

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/267

## Requirement 03 (Done)
The spawner page must implement the  the same _**Images**_ functionality with JH.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/150

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/267

## Requirement 04 (Done)
The spawner page must implement the  the same _**Sizes**_ functionality with JH.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/159
- https://github.com/opendatahub-io/odh-dashboard/issues/304

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/267
- https://github.com/opendatahub-io/odh-dashboard/pull/238

## Requirement 05 (Done)
The spawner page must implement the  the same _**GPU**_ functionality with JH. Additionally, the system must continue to support tolerations for GPU workloads as implemented in this story.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/158
- https://github.com/opendatahub-io/odh-dashboard/issues/301

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/264
- https://github.com/opendatahub-io/odh-dashboard/pull/288

## Requirement 06 (Done)
The spawner page must implement the  the same _**Environment variables and secrets**_ functionality with JH.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/282 

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/256
- https://github.com/opendatahub-io/odh-dashboard/pull/275
- https://github.com/opendatahub-io/odh-dashboard/pull/331

## Requirement 07 (Done)
Users must be able to cull idle NBs via admin setting in the same way that's supported with JH.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/283

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/298
- https://github.com/opendatahub-io/odh-dashboard/pull/269

## Requirement 08 (Done)
Users must be able to **start** NB server sessions via the UI.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/307
- https://github.com/opendatahub-io/odh-dashboard/issues/306
- https://github.com/opendatahub-io/odh-dashboard/issues/305
- https://github.com/opendatahub-io/odh-dashboard/issues/295
- https://github.com/opendatahub-io/odh-dashboard/issues/290
- https://github.com/opendatahub-io/odh-dashboard/issues/316
- https://github.com/opendatahub-io/odh-dashboard/issues/341

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/267
- https://github.com/opendatahub-io/odh-dashboard/pull/299
- https://github.com/opendatahub-io/odh-dashboard/pull/298
- https://github.com/opendatahub-io/odh-dashboard/pull/320
- https://github.com/opendatahub-io/odh-dashboard/pull/332
- https://github.com/opendatahub-io/odh-dashboard/pull/329
- https://github.com/opendatahub-io/odh-dashboard/pull/326

## Requirement 09 (Done)
Users must be able to **stop** NB server sessions via the UI.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/149
- https://github.com/opendatahub-io/odh-dashboard/issues/293
- https://github.com/opendatahub-io/odh-dashboard/issues/294
- https://github.com/opendatahub-io/odh-dashboard/issues/302

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/267
- https://github.com/opendatahub-io/odh-dashboard/pull/332

## Requirement 10 (Done)
The system must provide suitable error messages related to the inability to start NB server sessions and enable the user to recover and try again immediately.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/157
- https://github.com/opendatahub-io/kubeflow/issues/29
- https://github.com/opendatahub-io/odh-dashboard/issues/315
- https://github.com/opendatahub-io/odh-dashboard/issues/351

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/330

## Requirement 11 (Done)
Notebook server sessions are created in a default namespace. Users can only create notebook server sessions in the default namespace. 

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/297

### Pull Requests
- 

## Requirements 12 (Done)
Admins must be able to access the same functionality currently available via JH admin console.

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/273
- https://github.com/opendatahub-io/odh-dashboard/issues/309

### Pull Requests
- https://github.com/opendatahub-io/odh-dashboard/pull/333

## Requirement 13 (Done)
We need to be able to set up tolerations to match pre-configured taints. 

### Issues
- https://github.com/opendatahub-io/odh-dashboard/issues/338

### Pull Requests
-

## Remaining KFNBC Issues

See the [issue filter](https://github.com/opendatahub-io/odh-dashboard/issues?q=is%3Aopen+is%3Aissue+label%3Afeature%2Fnotebook-controller) on `feature/notebook-controller`.

**Comment by andrewballantyne** [comment]
KFNBC requirements are tied to the 2.1 release of the Dashboard.

See the RC notes here: https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.1-rc
