### ISSUE TITLE
[UX]: Designs for model list view and related empty states

### ISSUE THREAD

**Issue by simrandhaliw** [opendatahub-io/odh-dashboard#2130]
### Description

**WHAT**
 Create UX mockups for the primary model list view, including any related empty state use cases.

**HOW**
- Explore design options and create UX mockups for them.
- Review the designs with stakeholders including the UX team and CCS.

**DONE**
- Design artifact that includes information about design iterations, feedback, final or latest designs, etc.
- UX team, content, and stakeholder review and acceptance.

**Guidelines**
The following steps should be adhered to:
- The final, proposed design ideas must align with PatternFly design components.
- When sharing final design details, include links to PF components used in designs, and describe component behavior in the context of the use case. Also, include the final microcopy if needed.

**Comment by cshinn** [comment]
Recreated as https://issues.redhat.com/browse/RHOAIUX-7
