### ISSUE TITLE
[Bug]: Add spinner and change logic In Model Serving Global Page

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

main

### Current Behavior

It takes a long time to load when you switch between projects so you will probably see an empty state flickering when you do it. Especially when you switch from a specific project to "All projects".

### Expected Behavior

There should be loading state when you switch between projects

### Steps To Reproduce

1. Go to the global model serving page
2. Select a project
3. Switch back to "All projects"
4. Look carefully at how the empty state changes and re-rendering

**Comment by lucferbux** [comment]
I'm investigating the issue right now

**Comment by lucferbux** [comment]
@vconzola we can talke here about the loading indicator between project switches.
