### ISSUE TITLE
[Tech Debt]: Add PR template validator

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2138]
### Type

Dev Efficiency (eg. CI improvements, issue templates, etc)

### Description

We need to make sure all the PRs meet the template.

Here is the tool we could probably use https://github.com/marketplace/actions/template-validator. Any suggestions are welcomed if you know some better tools.

### Why?

It makes no sense if you have a PR up without filling the template because the reviewers have no idea what this PR is solving.

**Comment by andrewballantyne** [comment]
Consider `[WIP]` PRs not something to validate

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2900
