### ISSUE TITLE
Integration of KFNBC UI into backend KFNBC

### ISSUE THREAD

**Issue by jkoehler-redhat** [opendatahub-io/odh-dashboard#214]
- [x] KFNBC (Samu) is work in progress and can be used
- [x] Install KFNBC KfDef if Maro’s cluster (Samu will work with Maros on this).
- [x] Create new feature flags
- [x] Include backend APIs
- [x] Create route to new spawner and hide it

**Comment by samuelvl** [comment]
Fixed by https://github.com/opendatahub-io/odh-dashboard/pull/245
