### ISSUE TITLE
[Bug]: Packages JupyterLab and Notebook versions advertised do not match installed ones on AiKit spawned image

### ISSUE THREAD

**Issue by asanzgom** [opendatahub-io/odh-dashboard#2140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `OpenShift AI 2.4`)

### Version

RHODS 2.4 RC1 on Managed Cluster

### Current Behavior

Packages JupyterLab and Notebook versions advertised do not match installed ones on AiKit spawned image

![image](https://github.com/opendatahub-io/odh-dashboard/assets/100594859/040ba3d6-6f07-41a4-a818-86d7f7ea8265)

```
$ pip list | grep jupyterlab
jupyterlab                        3.5.3
$ pip list | grep notebook
notebook                          6.5.3
```

### Expected Behavior

Versions advertised should match those already installed on the image

**Comment by harshad16** [comment]
@asanzgom Please can you share, 
- how you come across this image?

**Comment by asanzgom** [comment]
@harshad16 I installed AI Kit Operator from OperatorHub to be able to spawn the image 
![image](https://github.com/opendatahub-io/odh-dashboard/assets/100594859/cd1cbb34-648e-4625-86b2-be0c8edaf92d)

**Comment by harshad16** [comment]
@Xaenalt Can you share where the imagestream of this image exists ?
we need to update it.

**Comment by Xaenalt** [comment]
Currently it's built on the user's cluster, there's a plan in the works to transition it to the notebooks repo

**Comment by asanzgom** [comment]
still present on RHODS 2.5 RC1

**Comment by Xaenalt** [comment]
Yeah, there aren't plans to fix it currently, Intel is instead going to transition to maintaining those notebooks in this repo so it can use the CI here to keep it up to date

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1196
