### ISSUE TITLE
[Tech Debt]: Disable `.sort` for `.toSorted`

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2141]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

We are using `.sort` sometimes without understand it mutates the source. That source could be a `useState` property and we are violating React principles by using it.

### Why?

Ideally everyone should `[...myArray].sort` but it seems hard to police. We may be able to just go with `.toSorted` which is the proper React way of managing data, since it will do the copying for you.

Docs:
- https://eslint.org/docs/latest/rules/no-restricted-properties
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted

Make sure this is supported by all the browsers we support (including any EUS versions)

**Comment by christianvogt** [comment]
`#reverse()` and `#toReversed()` falls into the same category as this issue.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2414
