### ISSUE TITLE
[Tech Debt]: Frontend - `.toString()` has odd side-effects

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2142]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

We should avoid `.toString()`. It can be used on React.ReactNode and it will present itself as `[object Object]`.

Casting to string shouldn't be something you should _ever_ need to do. Respect the data type, or accept the proper consequences of crafting your own string.

Note: We already have this linter on the backend to avoid `e.toString()`

### Why?

Understanding how data types work is very important. `.toString()` is a way to tell TypeScript "I don't care if I don't have a string, make it one" -- which just diverts all the power of TypeScript's error telling you to manage the type.

`ReactNode.toString()` || `number.toString()` || `null.toString()` there are so many ways to not properly manage our states if you just take a union type and to string it.

**Comment by manaswinidas** [comment]
Can this help? https://typescript-eslint.io/rules/no-base-to-string/

**Comment by andrewballantyne** [comment]
@manaswinidas not much different tbh... that linter rule is specific for those who want to provide `.toString` implementations. I want to stop all implementations. We don't use classes or custom objects, so maybe in the end of net difference is the same... but I'd like to just take the stance of no usage of the function.

**Comment by manaswinidas** [comment]
We can also use a `regex` , for example: https://stackoverflow.com/questions/72647371/is-there-an-eslint-rule-to-forbid-a-specific-string-of-text

**Comment by andrewballantyne** [comment]
@manaswinidas oh sorry -- you're trying to offer the solution. I thought you were offering a different solution. We already do this in the [backend](https://github.com/opendatahub-io/odh-dashboard/blob/80dde8a50982e9c32bded6e6a7bcd5e87062af1d/backend/.eslintrc#L36-L42) -- I imagine we just copy that implementation.

**Comment by manaswinidas** [comment]
Thanks for letting me know, wasn't aware of the backend implementation

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-508
