### ISSUE TITLE
[Feature Request]: Allow to change model serving mode per project

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2144]
### Feature description

Currently, users cannot change the Model Serving mode on a DS Project, but they need to create a new project. However, I think it is uncomorftable and it should be allowed to switch without the need to re-create all the resources in the project (e.g., workbenches, data connections).

**Comment by manaswinidas** [comment]
cc @lucferbux

**Comment by vconzola** [comment]
@lucferbux So this is suggesting being able to switch between KServe and MM, not have both, in the same project? I assume without impacting currently served models? I think the UX would be pretty complex to support this.

**Comment by bdattoma** [comment]
> @lucferbux So this is suggesting being able to switch between KServe and MM, not have both, in the same project? I assume without impacting currently served models? I think the UX would be pretty complex to support this.

I would not exclude the option to have both enabled in the same project, tbh. So far there are technical reasons not to allow that scenario, but once the technical issues are completely solved, why wouldn't we allow both model platforms to be used in the same project?

**Comment by vconzola** [comment]
@bdattoma I know having both platforms enabled in the same project is the long term goal and according @Xaenalt it's still some months away. What I'm trying to understand is if this request is for a stop gap solution that's allows switching between them in a project until we're able to support both?

**Comment by bdattoma** [comment]
> @bdattoma I know having both platforms enabled in the same project is the long term goal and according @Xaenalt it's still some months away. What I'm trying to understand is if this request is for a stop gap solution that's allows switching between them in a project until we're able to support both?


I'd rather try finding a way which will automaticlly be compatible with (or easily adapted to) using both the platforms when it will be possible.

**Comment by andrewballantyne** [comment]
@bdattoma The sad reality is I pitched this [2 months ago](https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1696277029960329?thread_ts=1696249696.127799&cid=C05NXTEHLGY) and the backend team didn't want to increase the scope for 2.5 and add risk that there was edge cases they couldn't button up. We will likely get this before we support both in the same project.

**Comment by lucferbux** [comment]
Yes, I agree on what andrew has said. Is it possible in a technical side, It will involve a little bit of UX work and we might be able to get it before full support of both platforms in the same project (which is targeted for next year).

**Comment by Xaenalt** [comment]
Yes, the reality is, it's possible from a technical standpoint, but it will require several rather sizeable upstream changes which were beyond the scope of 2.5, hence its next year target

**Comment by lucferbux** [comment]
> Yes, the reality is, it's possible from a technical standpoint, but it will require several rather sizeable upstream changes which were beyond the scope of 2.5, hence its next year target

Oh we are talking about removing all the resources and change the label of the project to either select `modelmesh` or `kserve` again. Is that a problem for that flow @Xaenalt or you were talking about supporting both platforms in the same project?

**Comment by Xaenalt** [comment]
From the original comment, I figured it meant a way to have both coexist in a project

**Comment by Xaenalt** [comment]
Coexistence is going to require significant eng lift upstream, switching workflow is already supported by deleting all current resources and switching

**Comment by andrewballantyne** [comment]
> > deleting all current resources
> 
> what resources you mean? Models and model servers? or others as well?

Clearing state and supporting the ability to switch the label on the project. ServingRuntimes & InferenceServices are the main ones. There are a ton of other resources the Dashboard creates to support auth and what have you -- not deleting those (via CLI / OpenShift Console) will likely cause conflicts against resources sharing the same name. 

> > switching
> 
> via UI?

Sean is a backend dev, he means the backend supports it. The UI doesn't support this explicitly because of my [thread I linked earlier](https://github.com/opendatahub-io/odh-dashboard/issues/2144#issuecomment-1823498718).

---

This is not currently planned by the Dashboard at this time. It will continue to stay in that state until we work through the need with PM (and the backend team's support of it). @jedemo (and Adam -- not sure if he has a handle) will need to make that call on desire / need before we can slot it into our development roadmap.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIRFE-28
