### ISSUE TITLE
[Feature Request]: Allow to use both model serving modes in the same project

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2145]
### Feature description

We are moving towards having ModelMesh and KServe working together in the cluster, it has still some issues, but it can work already. 

We should consider adding more flexibility in the DS Projects about using both the tools in the same DS Project.

### Describe alternatives you've considered

if there are reasons not to have this option implemented, I think we should at least work on giving the option to change the selected serving mode - https://github.com/opendatahub-io/odh-dashboard/issues/2144

**Comment by lucferbux** [comment]
Hi @bdattoma the model serving team (cc @Jooho @Xaenalt ) are working to support both ModelMesh and KServe in the same DS Project in the future, but we don't have the possibility right now to do so. We'll add that feature once it's supported by the controllers.

In the meantime, the alternative of change the selected serving mode could be feasible, we would need UX, but it's a matter of removing all the model serving resources and change lables in the project. That's something we can support in the meantime. cc @vconzola

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIRFE-27
