### ISSUE TITLE
[Bug]: Data Connection always reports AWS S3 as provider

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

nightly

### Current Behavior

The data connection form is abstracted from the cloud provider, however it shows AWS S3 as provider for any DC

![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/71ee4ddd-7107-42a8-add3-0a5136b89454)

### Expected Behavior

Remove the column -- it's not clear what details are being used so we can remove the column for now.

### Steps To Reproduce

1. create a data connection in a DS Project
2. check the `Provider` column in the DS Project details page

**Comment by manaswinidas** [comment]
cc @andrewballantyne @xianli123 Can we just drop the Provider column?

**Comment by andrewballantyne** [comment]
@xianli123 Kun, I know we talked about dropping it when we had the data connections "S3-compatible" flows... but I don't think we need to wait for this anymore. Thoughts on just dropping the column today (without that other work)?

**Comment by xianli123** [comment]
@andrewballantyne @bdattoma I agree with you. Removing this column will not influence anything at this moment. We can drop this column.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-1162
