### ISSUE TITLE
[Feature Request]: Allow to add DS permissions only for existing users and groups 

### ISSUE THREAD

**Issue by manosnoam** [opendatahub-io/odh-dashboard#2148]
### Feature description

Currently when adding a custom (editable) user or group to DS permissions, there is no verification mechanism to choose only from existing list of users and groups. This can make the troubleshooting of permissions failures that could happen if a non-existent user or group is added:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/e46d4e01-713c-4b5c-b3af-65760b01079c)

Adding a verification mechanism for selecting a user/group from that is already present in the cluster would resolve it.

### Describe alternatives you've considered

Option 1: After submitting the Permissions dialog page, there's a verification process to check that all entered users/groups exist and legitimate to be added, and if they are not - A proper warning message is displayed.
(Or even better: when pressing the "V" for a new entry, verify just that user/group, and alert if required).

Option 2 (more complicated probably): A list of users/groups will be opened when pressing the "Name" field, which lists only existing entities to select from.

**Comment by manaswinidas** [comment]
cc @andrewballantyne

**Comment by andrewballantyne** [comment]
Slack thread that lead to this ticket:

> We cannot list users as there is no way to filter users in k8s… So we’d have to build some middle-man searcher, and it was not desired cost for little gain. Clusters with 10s of thousands of users would be very hard to manage. I imagine most companies will use a deterministic username system, your email or userid or something that your colleagues could blindly type. We could look at verification but it’s awkward if you’re off by a character and don’t know it
> 
> We list groups if you have access to list groups in OpenShift. If you cannot, you’re typing blind.
> 
> The thought is you’d talk to whomever you wanted and type in the value they give you.
>
> Proper permissions for admins (which might fix the group listing for all admins) is intended to be covered by the Operator issue: https://github.com/opendatahub-io/opendatahub-operator/issues/606
> 
> Your permissions in OpenShift Console is intended to be king here in all cases. If you cannot do it via the oc client or from the OpenShift Console UI — you shouldn’t be able to do it on our side (there are exceptions to this rule today, but they need to go away)

Noam then asked if we could alert in a way to allow them if they got success. To which I replied log _this_ issue.

---

Here is the crux. If we do go down this path, it is the service account who would likely need to validate it on behalf of the user. Even when the Dashboard Admins gets proper access, it may or may not include all users & groups. If it does not, then _every_ user both basic and admin would need to go through the Service Account.

This could potentially not be great for security if someone may be able to "phish" for users or groups that they shouldn't know exist -- I'm not sure how sensitive this data is.

I'll bring this up at the Architectural Council to see what they think. If UX has an opinion now, they can chime in and I can take that recommendation to the AC as well. 

cc @kywalker-rh @xianli123

**Comment by xianli123** [comment]
It would be better to have a verification mechanism. On the one hand, selecting existing users or groups can ensure that the users or groups are safe. It will not have a security problem. On the other hand, it doesn't make sense to type an unexisting user or group. I will keep an eye on this.

**Comment by andrewballantyne** [comment]
@xianli123 If I, as a user, cannot list the users or groups from the cluster (cli, in openshift console, etc)... and I want to know if there are users or groups and I just start typing in random values, seeing a checkmark when I find one and a question mark or 'x' when I don't would absolutely let me check if others are using the cluster or have accounts. This definitely sounds like a security gap. Developer Sandbox for instance, is used by many people and you could phish for other users who use the cluster with this functionality. Which is definitely not ideal.

**Comment by manosnoam** [comment]
> seeing a checkmark when I find one and a question mark or 'x' when I don't would absolutely let me check if others are using the cluster or have accounts. This definitely sounds like a security gap. 

I think @xianli123 refers to my suggestion: 
> Option 1: A verification process to check that all entered users/groups exist and legitimate to be added.

i.e. Not using the "type and see" available users/groups from a generated list.

**Comment by xianli123** [comment]
@andrewballantyne @manosnoam Yes, I referred to the Option 1 

> when pressing the "V" for a new entry, verify just that user/group, and alert if required

I put a screenshot below to show my idea. After the user enters the user/group name and the cursor leaves the field, the validation mechanism determines whether the user/group exists. Does it make sense?
<img width="706" alt="Screenshot 2023-11-23 at 10 10 40" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/9e4813f5-e305-4f20-98be-c88e68b23030">

**Comment by manosnoam** [comment]
> I put a screenshot below to show my idea. After the user enters the user/group name and the cursor leaves the field, the validation mechanism determines whether the user/group exists. Does it make sense? 

Yes indeed. This is actually an improved mechanism than my suggestion, where an additional dialog is displayed. 

- We can either use it, or a simplified option, where pressing on the "V" (available in the original dialog, when adding new user/group) Verifies that user/group. 

- Note that "Can't find this user" is one kind of verification. It could also be an existing user that does not have permissions to be part of the desired group, so the warning should be accordingly.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-22
