### ISSUE TITLE
[Bug]: Typo in Cluster Settings subheader

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.4

### Current Behavior

This is the current header

<img width="439" alt="Screenshot 2023-11-16 at 11 29 22" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/e06e2558-dd33-4602-ae64-79bb9accfcfe">

### Expected Behavior

It should say:

`Manage global settings for all users.`

### Steps To Reproduce

1. Go to Cluster Settings
2. Check the header

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1195
