### ISSUE TITLE
[Bug]: Inconsistent empty state for kserve in global view

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.4

### Current Behavior

We currently have this empty view for a KServe Project

<img width="1695" alt="Screenshot 2023-11-16 at 12 01 12" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/a7f89f08-27fb-44a3-b718-f43325034076">

### Expected Behavior

To have the following label:

`To get started, deploy a model`

### Steps To Reproduce

1. Enable only kserve
2. Go to Model Serving view
3. Select an empty project

**Comment by manaswinidas** [comment]
cc @lucferbux
