### ISSUE TITLE
[Bug]: Hide accelerators when they are not present in the SR selection

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.4

### Current Behavior

Right now we display **Accelerator** and **Number of accelerators** even when they are not selected of even present in the cluster.
<img width="1200" alt="Screenshot 2023-11-16 at 12 34 05" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/ffa7ca48-998b-43a6-a4f3-b717928cdc82">

### Expected Behavior

We should hide those fields when they are not added to the SR spec

### Steps To Reproduce

1. Create a kserve project
2. Deploy a new model without selecting accelerators

**Comment by manaswinidas** [comment]
Triage team decided that if your cluster has no accelerator profiles, hide accelerator name and number . If it's not in use.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-547
