### ISSUE TITLE
[Bug]: Notebook image settings should be renamed

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.4

### Current Behavior

Right now the BYON section is called "Notebook image setting"

<img width="755" alt="Screenshot 2023-11-16 at 12 36 31" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/d93540ba-1a55-4aa7-9463-6513c52f890f">

### Expected Behavior

The section should be called `Custom notebook images`

### Steps To Reproduce

1. Go to Settings
2. Check that right now is called `Notebook image settings`

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1194
