### ISSUE TITLE
[Bug]: Inconsistent status handling for kserve

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

2.4

### Current Behavior

Right now, the way InferenceService spec is handling status changes in KServe is inconsistent. We need to do a research and figure out the way to proper support status for KServe.

### Expected Behavior

To display the correct status of the deployment.

### Steps To Reproduce

1. Create a new kserve model
2. Deploy a model
3. Check that the status symbol is inconsistent.

**Comment by manaswinidas** [comment]
cc @lucferbux

**Comment by lucferbux** [comment]
I'm assigning myself to this, I'll add more info about how to research the status handling here.
