### ISSUE TITLE
Upgrade fastify to the latest version

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#218]
We are currently running an older version of fastify.  We should upgrade to the latest version.

**Comment by andrewballantyne** [comment]
This is still needed, even with https://github.com/opendatahub-io/odh-dashboard/issues/259 -- fastify is still our server routing software.

**Comment by andrewballantyne** [comment]
This falls under general upgrading of dependencies. This ticket will just take up space. Closing this so we can have smoother tracking of other issues (that's not to say we don't need to keep upgrading our dependencies -- but those will be tracked via other means)
