### ISSUE TITLE
[Bug]: Creating two custom images with the same name fails with a weird error message

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/odh-dashboard#2186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `OpenShift AI 2.4`)

### Version

2.4.RC2

### Current Behavior

When I try to create two custom images with the very same name, the operation fails during the creation of the second one, which is good. Although, the error message seems to be wrong stating this text: `Unable to add notebook image: HTTP request failed`, see:

![Screenshot from 2023-11-20 12-25-03](https://github.com/opendatahub-io/odh-dashboard/assets/12250881/1260d5d2-96d6-4f9e-b0df-7a6b9799338f)

I believe that the `HTTP request failed` should be replaced by something else :slightly_smiling_face:   - notebook name and the reason why - duplicate name in this case.

When I do similar thing with the invalid image location, I get clear error message: `Invalid repository URL: random`.

### Expected Behavior

The error message is clear and complete.

### Steps To Reproduce

1. Open the RHOAI web UI
2. Go to `Settings -> Notebook image settings`
3. Click on `Import new image` button
4. Fill in the data, eg.:
   * Image location: `quay.io/opendatahub/workbench-images@sha256:f3dd0190871e35e469a8ac977ef4733bd596ba4d64da0e3bc13ece470d594dab`
   * Name: `foo` 
5. Click on the `Import` button
6. Click on `Import new image` button again
7. Fill in the data using the very same name of the image
8. Click on the `Import` button
9. See the error `Unable to add notebook image: HTTP request failed`

**Comment by shalberd** [comment]
I guess the status-section of the created imagestream or the events could be parsed for more conditions such as these.

**Comment by andrewballantyne** [comment]
Yeah, this is likely a legacy issue cropping up again. We used to just take the top-level error message out of our old K8s library caller... it always is "HTTP Request Failed" ... if we dig into the response value, it gives a more k8s error flow that you could see on OpenShift Console. I imagine that's the solution here.

Thanks for calling this out, definitely seems like something we can fix.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1192
