### ISSUE TITLE
[Tech Debt]: Refactor K8s Library calls to Pass Through

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2188]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

We currently use K8s official node-client code and it is in alpha versions. We could upgrade or we could remove.

If we upgrade, it seems Snyk still has issues with the library. 

Let us just shift this to using our pass-through API. This will allow us to manage all k8s calls the same way.

### Why?

On-going Snyk issues and the cost of refactoring vs just switching over the pass though API path.

**Comment by andrewballantyne** [comment]
Investigate the impact and benefit before acting on it.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2899
