### ISSUE TITLE
[Feature Request]: Add Model framework version metadata in the Caikit CustomServingRuntime

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#2189]
### Feature description

maybe we could add the version metadata in the Caikit custom serving runtime, otherwise user will see this in the UI:
image

![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/d0a6edaf-1736-41dd-b44f-e83909b305ea)

### Describe alternatives you've considered

I would say we could review the need of (name - version) in the UI since the metadata is not mandatory.

**Comment by bdattoma** [comment]
@Xaenalt does the runtime have a specific version?

**Comment by andrewballantyne** [comment]
cc @lucferbux

**Comment by Xaenalt** [comment]
@bdattoma Could we expose the short_sha as the ID for now? If not, we can expose something like setuptool's git tag + N commits number possibly

**Comment by lucferbux** [comment]
Yeah, this should be a freebie, if @Xaenalt provide us with a version i can quickly raise a PR with that info, I'm gonna assign myself to this ticket, since we can commit to it for this week.

**Comment by Xaenalt** [comment]
Ok, so the caikit format models aren't really versioned in the traditional sense, it's up to the internals of any caikit "module" to implement version semantics. There's a field in the config.yml `module_id` that seems like it could be used for that, but it may be a pain to keep up to date

**Comment by bdattoma** [comment]
gotcha, if it's painful then I think it's not worth it, at least for now. 
But, are there any model framework which are going to have a version? are we aware of them?

**Comment by lucferbux** [comment]
Closing this based on the latest comment, we can open a new one if we support a different runtime.

**Comment by lucferbux** [comment]
That's something we could discuss, since it's not mandatory, we can have other visual cues, maybe a label for versioning or something like that, cc @vconzola

**Comment by bdattoma** [comment]
@lucferbux okay thanks Lucas. Please keep into consideration the risk of having outdated metadata about the model framework version which would make the info displayed in the creation form unreliable

**Comment by vconzola** [comment]
@lucferbux We didn't originally have version metadata in the dropdown options, but it was added later at someone's request. Do you remember who asked for it and/or why we added it?
