### ISSUE TITLE
[DS Project UI] - Add different data sources

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#219]
The current supported data source is only PV and Object Storage, we should also add the following as the data sources (or maybe data resources):
- [ ] Starburst (P1)
- [ ] RHODA connectors (P2)
- [ ] Nooba / multi-cloud gateway (P2)

**Comment by andrewballantyne** [comment]
We do need future data sources (now called data connections) but we will add tickets as we need them.
