### ISSUE TITLE
[Story]: Create the menu for pipeline or pipeline version selection

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2192]
### Goal

Implement a menu that will be used to select the pipeline or pipeline version when uploading a pipeline version or creating the pipeline runs

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/2191

### Itemized goals

- Create a reusable and composable menu for pipeline selection or pipeline version selection, which will be used when uploading the pipeline versions and creating the pipeline runs
- If the fetched items total size is more than 10, there is a "View more" button, which will add 10 more results (or the rest of the results if the rest of the size is less than 10) when clicking it
- There is a helper text under the search input to show how many fetched items totally
- There is a badge next to the "View more" button to show how many items are in the list that users can see
- The menu should contain a search input, which allows you to search and use the search params to fetch the data
- The updated column is sortable
- Truncate the item name if it's too long
- Add the tooltip to the list of items, and show the description of the item (if any). Also, show the full name of the item if the name is truncated.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/37624318/a8188172-b643-4a8f-94fc-61e0ea316587)
<img width="845" alt="Screenshot 2023-11-20 at 1 23 33 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/63d40818-fec9-4f44-815a-9dce1265ad63">
<img width="845" alt="Screenshot 2023-11-20 at 2 20 07 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/e7e1c77b-5b2a-42a9-9b7c-fe2e28603016">

### Aspects continued elsewhere

* https://github.com/opendatahub-io/odh-dashboard/issues/2190
* https://github.com/opendatahub-io/odh-dashboard/issues/2194

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/p/52D4BC1C-F002-4775-9C69-7E82C519E931/canvas

**Comment by dgutride** [comment]
Replaced by:  https://issues.redhat.com/browse/RHOAIENG-268
