### ISSUE TITLE
[Feature Request]: Add recommended accelerators to custom serving runtimes

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2193]
### Feature description

Currently (as of habana 2 feature) a admin can set an image's recommended accelerators annotation through the byon admin panel. _This applies specific styling to aid a user in picking the correct image/accelerator combination._ They do this by selecting/creating identifiers in a text combo box that is prefilled with accelerator identifiers that are present in acceleratorProfile CRs on the cluster.

Selecting identifiers for custom serving runtimes is currently done by manually adding the `opendathub.io/reccommend-accelerators annotation to the yaml in the create/duplicate form for custom serving runtimes. A admin is not shown that this is possible and the current way of doing it is not ideal. The custom serving runtimes form needs to include a similar if not the same form element as the identifier combo box in the byon admin page

**This issue will need UX**

### Describe alternatives you've considered

add a simple help icon to explain how to add the annotation

**Comment by DaoDaoNoCode** [comment]
cc @lucferbux

**Comment by Gkrumbach07** [comment]
This is still valid, needs migration

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2582
