### ISSUE TITLE
[Story]: Add pipeline version selection when creating pipeline runs

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2194]
### Goal

Implement a selection for pipeline versions on pipeline run creating page

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/2192

### Itemized goals

* Add a dropdown for the pipeline version
* When the pipeline is not selected, the dropdown will be disabled
* Select the pipeline toggle will open the menu implemented in #2192
* Select the pipeline version toggle will open the menu implemented in #2192, too, but set the versions as the items

<img width="845" alt="Screenshot 2023-11-20 at 2 16 52 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/7775d865-4b9a-434c-84d9-b6c51354455c">
<img width="845" alt="Screenshot 2023-11-20 at 1 23 33 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/63d40818-fec9-4f44-815a-9dce1265ad63">
<img width="845" alt="Screenshot 2023-11-20 at 2 20 07 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/e7e1c77b-5b2a-42a9-9b7c-fe2e28603016">

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/p/52D4BC1C-F002-4775-9C69-7E82C519E931/canvas

**Comment by dgutride** [comment]
Replaced by:  https://issues.redhat.com/browse/RHOAIENG-266
