### ISSUE TITLE
[Feature Request]: Landing page (Welcome page) for ODH/RHOAI

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/odh-dashboard#2195]
### Feature description

When user opens the ODH/RHOAI WebUI console these days, the default page that is opened for him is the list of tiles with the enabled applications - only Jupyter by default ATM. We may want to create a separate landing/welcome/home page instead.

Adding notes from the recent UX meeting with possible content proposal by Jorge:

* Welcome to ODH/RHOAI!
* orientation of the project structure, etc
* Chris Chase Vide
* What's new (blogs,...)
* Where are the tutorials? Links to the user doc
* Communications from the admin
* Link to release notes for current version
* What version of ODH/RHOAI you are running
* Section about things you have been working on recently:
   * Open Data Science Project you were working on
   * Open last pipeline run
* ODH/RHOAI admins could (in Dashboard settings):
   * Show/hid different sections (welcome, what's new, media,...)
   * Configure a custom sections to present info to users (e.g. BU: link to a page showing relevant information for their users and/or scheduled maintenance planned on the cluster)

This relates to:

* #1797 
* #1993

---

FYI: @erwangranger, @jgarciao, @andrewballantyne

**Comment by andrewballantyne** [comment]
> the list of tiles with the enabled applications - only Jupyter by default ATM

Technically, this is only for ODH. RHODS I think has more tiles.

**Comment by andrewballantyne** [comment]
cc @xianli123 @kywalker-rh FYI

**Comment by andrewballantyne** [comment]
Added this item to https://github.com/opendatahub-io/odh-dashboard/issues/1797 -- if it needs a new home after we discuss it more, that's okay. It seems like a good spot to start.

**Comment by xianli123** [comment]
@andrewballantyne @jstourac I wonder if it's necessary to have a login/signup button or form on the Welcome page.

**Comment by andrewballantyne** [comment]
@xianli123 for what? What would the user "sign up" for? The Dashboard?

**Comment by erwangranger** [comment]
Agreed with Andrew. If you can see the (future) Welcome page in the dashboard, you've logged in already.

**Comment by xianli123** [comment]
@andrewballantyne Hah, sorry, I misunderstood. There should be no more logins/signups on the Landing or Welcome page. @erwangranger Thanks for your explanation.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-20
