### ISSUE TITLE
[Story]: Refactor pipelines table list

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2196]
### Goal

Implement the new pipelines view to change the toolbar and the table list

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/2191

### Itemized goals

- Use split dropdown, which allows you to upload a new pipeline version
- Move the deletion to the kebab toggle in the toolbar and make the pipeline table row selectable so you can delete them in batch, this is the same as requested in #1961 
- Expand the pipeline will not show runs now, it will show the versions table implemented in #2199
- Add a dropdown item "Upload new version" to the pipeline table row action, too. Which could open the modal implemented in #2190 and prefill the pipeline selection

<img width="1055" alt="Screenshot 2023-11-20 at 2 31 28 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/d6833d99-9fb5-43d9-a3f0-e1b3acea13ad">
<img width="1055" alt="Screenshot 2023-11-20 at 3 07 40 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/cacfe716-950d-4637-b1a3-f05b3ca422a7">

### Aspects continued elsewhere

* https://github.com/opendatahub-io/odh-dashboard/issues/2190
* https://github.com/opendatahub-io/odh-dashboard/issues/2199

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/lRzqa1x

**Comment by dgutride** [comment]
Replaced by https://issues.redhat.com/browse/RHOAIENG-263
