### ISSUE TITLE
[Story]: Improve the toolbar on the pipeline details page

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2197]
### Goal

Implements the new toolbar on the pipeline details page

### Dependency issue

No dependencies

### Itemized goals

- Add a new toggle that will open the dropdown menu to view the table of the versions in the pipeline
- Add a new dropdown item to support uploading pipeline versions

<img width="1076" alt="Screenshot 2023-11-20 at 3 19 57 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/7de089ae-8d5f-4a4b-baab-c81c5828b122">

### Aspects continued elsewhere

Create the pipeline versions table in the dropdown menu - Ticket TBD

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/w5xbELE

**Comment by dgutride** [comment]
Closed by https://issues.redhat.com/browse/RHOAIENG-265
