### ISSUE TITLE
[Story]: Create pipeline versions table in pipeline table expandable section on global pipelines page

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2199]
### Goal

Implement a table list to show pipeline versions when expanding the pipeline table row

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/2196

### Itemized goals

- The first pipeline version will be the default, the name is the same as the pipeline
- Only show 10 pipeline versions by default
- When clicking "View more", show 10 more items. If it's more than 10, give the row a fixed max-height instead of expanding the height
- Could be sorted by pipeline version name or created time
- Add a "Back to top" button to scroll back to the top of the pipeline versions list
- Clicking on "View runs" will take it to the triggered runs table in https://github.com/opendatahub-io/odh-dashboard/issues/2200 and preset the filter

<img width="1055" alt="Screenshot 2023-11-20 at 3 07 40 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/cacfe716-950d-4637-b1a3-f05b3ca422a7">
<img width="957" alt="Screenshot 2023-11-20 at 3 31 49 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/bea895a8-6230-49a2-804d-eea64fe0b865">

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/a/dg1grVb

**Comment by dgutride** [comment]
Replaced by https://issues.redhat.com/browse/RHOAIENG-264
