### ISSUE TITLE
[DS Project UI] - Use context to pass props

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#220]
~~Currently, we are using some hook functions to watch the resources on the cluster and use that hook function anywhere we need. This causes a lot of fetching and instability for the UI because of these network requests.~~

~~An ideal solution would be to use React-Redux, which environment is already set up in the codebase. We should just keep fetching all the data at one place and save them in the redux store, so the whole application could use the data on any page, and call the actions to refresh the data.~~

Refactor the way to fetch and get data on different pages using React Context.

Tasks:
- [ ] Using context for data science projects
- [ ] Using context for image streams
- [ ] Using context for workspaces/notebooks
- [ ] Using context for data sources
- [ ] Using context for storage
- [ ] Using context for model serving

**Comment by lucferbux** [comment]
Seems a reasonable solution, my only concern is why we would need to use React-Redux rather than using a global Context and a hook to retrieve the data in the page we need it. We accomplish the same and we don't need to use any 3rd party solution. What are your thoughts?

**Comment by DaoDaoNoCode** [comment]
Yeah, I think context also makes sense here. I remember discussing this problem with Chris but I cannot remember the details 🥲. Hi, @cfchase do you remember why we want to use Redux instead of context here?

**Comment by cfchase** [comment]
> Yeah, I think context also makes sense here. I remember discussing this problem with Chris but I cannot remember the details smiling_face_with_tear. Hi, @cfchase do you remember why we want to use Redux instead of context here?

Both of those solutions are fine, I just don't want to have 2 styles of managing global state in the dashboard.  The dashboard currently already has Redux, but I have no problem with switching if we remove Redux.  The current Redux configuration is a bit messy and if we want to continue to use Redux, we can follow https://redux.js.org/usage/usage-with-typescript and use the redux toolkit to clean things up.

**Comment by DaoDaoNoCode** [comment]
@lucferbux Yeah I am OK with that, you could set up the meeting so we can discuss more.

**Comment by lucferbux** [comment]
Perfect, I'll send an invite on Monday, thanks @DaoDaoNoCode

**Comment by lucferbux** [comment]
From my point of view, we should keep the reducers and actions just to make the state immutable, as it's a great pattern, but we can refactor our code with little effort if we want.

**Comment by DaoDaoNoCode** [comment]
@lucferbux I made some changes to the title and description of this issue and add the story tag and tasks to it. Simply convert any task to issue when you are ready to start! 😁

**Comment by lucferbux** [comment]
> @lucferbux I made some changes to the title and description of this issue and add the story tag and tasks to it. Simply convert any task to issue when you are ready to start! 😁

🎉🎉🎉

**Comment by DaoDaoNoCode** [comment]
@lucferbux I find I need to use context first for KFNBC work so I will create a context named `AppContext` to pass some props like `isNavOpen` from App.tsx to other files. If you haven't started this context work you could wait until my KFNBC PR is submitted and merged so you can work on top of it.

**Comment by christianvogt** [comment]
For k8s resources, with the support of websockets, we can switch to the SDK watch resources APIs which stores data in its own redux store. This helps to cut down on multiple network requests when multiple independent components request the same data.
