### ISSUE TITLE
[Story]: Improve pipeline runs table

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2200]
### Goal

Refactor pipeline runs table for both scheduled and triggered runs

### Dependency issue

No dependencies

### Itemized goals

- If the page is navigated from the "View run" button on the pipeline details page or pipeline version table action dropdown, then preset the filter to the pipeline version name and filter the runs
- Change the column `Pipeline` to `Pipeline version`
- Add the `Pipeline version` to the filter dropdown

<img width="957" alt="Screenshot 2023-11-20 at 3 50 14 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/dbad0020-c4e1-4958-949a-853710547775">
<img width="890" alt="Screenshot 2023-11-20 at 4 01 40 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/d9d4a4d8-aad9-4efe-a961-ccde61fe0a90">

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/p/52D4BC1C-F002-4775-9C69-7E82C519E931/canvas

**Comment by dgutride** [comment]
Replaced by: https://issues.redhat.com/browse/RHOAIENG-267
