### ISSUE TITLE
[Story]: Refactor deletion modal for pipelines and pipeline versions

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2204]
### Goal

Refactor the modal to delete a single pipeline version or a batch of pipeline/pipeline versions

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/2198
* https://github.com/opendatahub-io/odh-dashboard/issues/2196

### Itemized goals

When a single pipeline or a single pipeline version is selected, show the generic deletion modal like nowadays (But we need one for the pipeline version which we don't have now)

<img width="968" alt="Screenshot 2023-11-21 at 10 17 15 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/a38845b4-b95a-4ac4-b113-9e59bb2b38f4">

When you select multiple pipelines/pipeline versions in the table, you can delete them in a batch. This could reuse the work done in https://github.com/opendatahub-io/odh-dashboard/pull/1896

<img width="968" alt="Screenshot 2023-11-21 at 10 19 39 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/415ac623-aff1-401d-8a7e-26e29c6f5ea1">

### Mocks

https://www.sketch.com/s/6c72b6b2-2c32-45ff-b07c-381d9d8c8267/p/52D4BC1C-F002-4775-9C69-7E82C519E931/canvas

**Comment by dgutride** [comment]
Replaced by:  https://issues.redhat.com/browse/RHOAIENG-270
