### ISSUE TITLE
[Bug]: Clean up a mis-uploaded cache file

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#2205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

main

### Current Behavior

There is a cache file uploaded accidentally along with the PF5 upgrade
https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/.cache_16xe4ex

### Expected Behavior

Remove that file

**Comment by andrewballantyne** [comment]
Let us not only remove it but git ignore cache files please.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1782
