### ISSUE TITLE
[Bug]: Inconsistent Model Path

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Installing Dashboard directly (eg. `v2.12.0`, `commit xyz`, `branch name`)

### Version

main

### Current Behavior

In #1173 QE noted that there was a gap in edit where if you submitted with `/something` you'd edit into `/something` -- but the UI always prefixes with `/` so now you're seeing::

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/27b8ceac-60ad-475a-949b-209e88a5f7b9)

### Expected Behavior

Not sure if we should be trimming the `/` entirely on submit... or just on Edit for our UI rendering 🤔 

cc @lucferbux 

We need to understand what is expected by the Model Serving engines -- does it matter if it has a prefix slash or not? If not, then this is a purely a rendering issue.

### Steps To Reproduce

1. Create a Model (and a server if you're using Model Mesh)
    * Have a "Path" with prefix `/`
2. Edit the Model again

Do the same with no prefix `/` but some folder path. The two submit the same, but the visual rendering of the prefix `/` is double down.

**Comment by dgutride** [comment]
Migrated to https://issues.redhat.com/browse/RHOAIENG-542
