### ISSUE TITLE
Dashboard ODH / RHODS Consolidation

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#224]
The dashboard code in ODH is out of sync with the code in red-hat-data-services.  The code from red-hat-data-services should be backport to a new branch called main on opendatahub-io.  When doing this we should allow features to be enabled / disabled using a config map called odh-dashboard-config.  

Tasks:

- [x] #195 
- [x] #189
- [x] #43
- [x] #191
- [x] #193 
- [x] #194 
- [x] #191 
- [x] #35 
- [x] All PRs signed off / approved and merged
- [x] Perform Regression testing on new main branch.

Pull Requests: #211 Covers 189, 43, 191, 193, 194, 191, & 35

**Comment by andrewballantyne** [comment]
@LaVLaS Is this something we can work to close off? Is RHODS aligned with the effort yet?

**Comment by dlabaj** [comment]
All of the tasks have been completed for this backport.
