### ISSUE TITLE
[Tech Debt]: Inconsistency in the deployment of the DashboardConfig CR

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2240]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Source

main

### Description

We've been having a weird flow in which we didn't deploy a default `OdhDashboardConfig` resource in the upstream operator but we used a [default file](https://github.com/red-hat-data-services/odh-manifests/blob/master/odh-dashboard/odhdashboardconfig/odhdashboardconfig.yaml) for the downstream operator.

### Why?

To eliminate complexity and have a uniform way of deploying a configuration between environments.

**Comment by andrewballantyne** [comment]
We have code default states and manifest default states, this is a recipe for mismatch and an unexpected issue. We should resolve this state to a singular state... either we are going to use default manifest on new installs, or we are going to use code. Having both is not good -- especially since ODH and RHOAI will operate differently.

**Comment by lucferbux** [comment]
@zdtsw @VaishnaviHire we want to get rid of https://github.com/red-hat-data-services/odh-manifests/blob/master/odh-dashboard/odhdashboardconfig/odhdashboardconfig.yaml so we can leverage the creation of the resource from the dashboard init itself.

**Comment by zdtsw** [comment]
> @zdtsw @VaishnaviHire we want to get rid of https://github.com/red-hat-data-services/odh-manifests/blob/master/odh-dashboard/odhdashboardconfig/odhdashboardconfig.yaml so we can leverage the creation of the resource from the dashboard init itself.

anything want from our side? or just a good info :D

**Comment by andrewballantyne** [comment]
@zdtsw @VaishnaviHire what custom logic do you guys have for the Dashboard?

I know there is some for RHODS Manifests, is there anything for specific files? I'd like to look to reduce and obfuscate any information you have about our internals so we can play around with what we want without needing to consult with you guys. Lucas believed you had a reference to this specific file (or a group of files that came from the deployer).

**Comment by zdtsw** [comment]
> @zdtsw @VaishnaviHire what custom logic do you guys have for the Dashboard?
> 
> I know there is some for RHODS Manifests, is there anything for specific files? I'd like to look to reduce and obfuscate any information you have about our internals so we can play around with what we want without needing to consult with you guys. Lucas believed you had a reference to this specific file (or a group of files that came from the deployer).

all i can see from operator logic , it is replacing this file (or the folder) on line https://github.com/red-hat-data-services/odh-manifests/blob/rhods-2.5/odh-dashboard/odhdashboardconfig/odhdashboardconfig.yaml#L25 with 
```
		deploy.SelfManagedRhods: "rhods-admins",
		deploy.ManagedRhods:     "dedicated-admins",
```
depends on which platform type it is for RHODS.
then the normal run kustomize in the folder.

nothing special than that.

**Comment by lucferbux** [comment]
Closing this in favor of https://issues.redhat.com/browse/RHOAIENG-943
