### ISSUE TITLE
[Bug]: Number of model server replicas for Kserve is not applied correctly from the dashboard 

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#2243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `OpenShift AI 2.4`)

### Version

RHOAI 2.5 RC1

### Current Behavior

Setting a number of model server replicas different from the default (1, i.e. 0 or >=2) does not produce the expected result - the model (server) is always deployed with 1 replica.

The issue appears to be that, even though the dashboard makes two PUT requests for the ServingRuntime and InferenceService, the InferenceService is never updated correctly and the number of replicas is not controlled by the `spec.replicas` attribute of the ServingRuntime (which is the field that gets correctly updated) but rather by the `spec.predictor.minReplicas` field of the InferenceService (which is not present/updated).

The InferenceService CR should be updated to have a `spec.predictor.minReplicas` attribute which controls the number of replicas of the server - I have tested this by manually editing the CR and have confirmed that it works, ~~although editing the IS CR creates a new deployment resource entirely rather than increasing the number of pods in the currently existing one; I am not sure if this is an acceptable behaviour.~~ (I have confirmed this is expected functionality)

### Expected Behavior

Number of replicas varies based on the setting chosen when deploying or when editing the model

### Steps To Reproduce

Install RHOAI 2.5 RC1
Deploy Kserve model
Modify the no. of replicas (while deploying or later)
Confirm that the deployment does not change, the number of replicas is not respected, the ServingRuntime is updated to reflect the replicas setting in `spec.replicas`, and the InferenceService does *not* have the correct `spec.predictor.minReplicas` attribute.

### Workaround (if any)

Manually edit the InferenceService of the model to add the `spec.predictor.minReplicas` attribute and set it to the number of desired replicas.

**Comment by Jooho** [comment]
We need to revisit this issue in 2.6 because of the different behavior of `kserve` and `modelmesh`.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-823
