### ISSUE TITLE
ODH Dashboard Testing Updates

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#225]
This issue is used to track the updates that we are adding for testing to ODH Dashboard for the 1.3.0 release.

Tasks:

- [x] #141 
- [x] #139 
- [ ] All PRs signed off / approved and merged

**Comment by lucferbux** [comment]
Just out of curiosity, we are expecting to update our github actions flow just to trigger CI for these new tests? @dlabaj @DaoDaoNoCode

**Comment by andrewballantyne** [comment]
This appears done. I'm going to close it -- If this is still an on-going ticket @dlabaj please reopen and add more to the description.
