### ISSUE TITLE
[Feature Request]: move topology/core to a singular concept

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2251]
### Feature description

We want to separate the core topology concept from the pipelines concept becuase pipelines is strongly tied to kubflow, but core topology doesn't need to be. Some feature may want to use topology, but not be tied into the ds pipelines ecosystem.

### Describe alternatives you've considered

dont split up the concepts

### Anything else?

`usePipelineTaskTopology` is used to set up nodes and edges for the topology component inside ds pipelines. this can stay inside the pipelines concept becuase it uses kubeflow logic

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1780
