### ISSUE TITLE
[Story]: Hide metrics when project is kserve enabled

### ISSUE THREAD

**Issue by alexcreasy** [opendatahub-io/odh-dashboard#2253]
### Goal

Improve hiding of metrics features not supported by kserve when a project is kserve enabled.

### Dependency issue

No dependencies

### Itemized goals

* Hide "Install TrustyAI" widget when project is kserve enabled
* Hide "Show server metrics" kebab item on project detail page when project is kserve enabled
* Model server component on project detail page should not show links to model metrics when project is kserve enabled
* Global model serving page should not show links to model server when kserve is enabled on the project
* When project is not marked as kserve or MM, warn user that selecting kserve reduces features (TBD with UX)

### Mocks

* No mocks, discussions with UX needed around warning user kserve does not support bias or perf metrics and change is not reversible.

**Comment by dgutride** [comment]
Replaced by https://issues.redhat.com/browse/RHOAIENG-248 - moving to closed
