### ISSUE TITLE
[Tech Debt]: document cypress testing

### ISSUE THREAD

**Issue by christianvogt** [opendatahub-io/odh-dashboard#2254]
### Type

Quality (eg. tests)

### Source

main

### Description

Add documentation for cypress to the front end docs:
- Running cypress as it pertains to local dev env and ci
- Testing expectations for developers
- Test structure
- Best practices

Note that there exist some documentation for testing already in the [architecture.md doc](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/architecture.md).

### Why?

New devs should use our docs to understand how to add and maintain cypress tests.

**Comment by dgutride** [comment]
Already in jira
