### ISSUE TITLE
[UX]: User flow for Distributed workloads

### ISSUE THREAD

**Issue by yannnz** [opendatahub-io/odh-dashboard#2257]
### Description

- Based on the MVP plan, create the user flow to illustrate the steps of Admins to configure and monitor the Distribute workloads resources. Create the user flow to illustrate the steps of Data scientists to use Distributed workloads, and monitor the jobs. 
-  Review with stakeholders for agreements.

### Goals

The user flow helps the designers align with the team to understand how different personas achieve tasks. The outcome will be use as the reference to divide features and deliver comprehensive mockup designs.

### Expected Output

- User flows for both Admins and Data Scientists. 
- Info Architecture map. 
- Agreements from stakeholders.

### Completed artifacts

[Done][User flow](https://miro.com/app/board/uXjVNflcBYI=/?moveToWidget=3458764570502885117&cot=14)
[Under review][IA map](https://miro.com/app/board/uXjVNflcBYI=/?moveToWidget=3458764571278786343&cot=14)
[Under review][Design action items](https://miro.com/app/board/uXjVNflcBYI=/?moveToWidget=3458764570703196884&cot=14)

**Comment by xianli123** [comment]
The miro board recorded the analysis of the Distributed workloads. It includes the use flow iteration and the final user flow. Here is[ the user flow section ](https://miro.com/app/board/uXjVNflcBYI=/?moveToWidget=3458764570817659034&cot=14) for distributed workloads.

**Comment by cshinn** [comment]
Recreated as https://issues.redhat.com/browse/RHOAIUX-5
