### ISSUE TITLE
[UX]: [Admin] Distributed Workloads- Quota configuration and management

### ISSUE THREAD

**Issue by yannnz** [opendatahub-io/odh-dashboard#2258]
### Description

- Persona: Admin
- Task detail: 
         -Design the interactions and UI of the quota configuration for Distributed workloads, which allows the admin to 
           configure project based quotas for Data Scientists. 
        - Design the interactions and UI of quota management for Distributed workloads, which allows the admin to view and 
           manage existing quotas.

### Goals

- Research to find out parameters and any necessary input data needed for the design.  
- Deliver the design of interactions and UI of the quota configuration for Distributed workloads
- Deliver the design of the interactions and UI of quota management for Distributed workloads

### Expected Output

- Implementable Hi-fi design mockups illustrating both interactions and UI.
- Design reviewed by stakeholders for feedbacks and agreements.

**Comment by cshinn** [comment]
Recreated as https://issues.redhat.com/browse/RHOAIUX-4
