### ISSUE TITLE
[Tech Debt]: Mocks need a defined pattern

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#2264]
### Type

Quality (eg. tests)

### Source

main

### Description

Mocks in the dashboard need to have common implementation that solves the following issues:
- how params are passed into the mock function without duplicating the type
- how do we handle params that are not specified in the type (do we force it using `as ResourceKind`)
- How do we simplify mocking msw api calls that use mock functions

### Why?

Each mock acts a little differently so its hard to keep things consistent

**Comment by christianvogt** [comment]
tracked by https://issues.redhat.com/browse/RHOAIENG-2412
