### ISSUE TITLE
Remaining CNBi Phase 1 work

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#227]
The following are the remaining tasks for CNBi Phase 1 Pipelines

Tasks:

- [ ] #129
- [ ] #175
- [ ] Merged CNBi Phase 1 to main branch currently being delivered as part of Dashboard 2 work.
- [ ] Add feature flag to turn on Pipelines version of CNBi.  This will disable CNBi imagestream version if this flag is enabled.

**Comment by andrewballantyne** [comment]
This is out of date to the current process -- we'll log new issues to cover any future goals.
