### ISSUE TITLE
[Bug]: Dashboard doesn't register DataSciencePipelinesApplication (DataScience server) with different names than pipelines-definition

### ISSUE THREAD

**Issue by Frawless** [opendatahub-io/odh-dashboard#2270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

incubation (2.4.0)

### Current Behavior

When I create DataPipelines server via CR (`DataSciencePipelinesApplication`) and it doesn't have name `pipelines-definition` the dashboard doesn't show it and user still has to create new one to run DataSciencePipelines.__### ### 

### Expected Behavior

Dashboard will register every `DataSciencePipelinesApplication` or the operator will not reconcile the ones without proper naming -> proper documentation should be available.

### Steps To Reproduce

1. Deploy ODH
2. Deploy DSC - https://github.com/skodjob/deployment-hub/blob/main/open-data-hub/install/data-science-cluster.yaml
3. Create DataScienceProject and DataSciencePipelinesApplication with different name than `pipelines-definition`

**Comment by andrewballantyne** [comment]
Yeah, this is something we are aware of... there are big changes coming in v2 of Pipelines, I imagine we will address this part of that effort.

The effort has been moved to Jira: https://issues.redhat.com/browse/RHOAIENG-331

**Comment by Frawless** [comment]
Great, thanks for the info!

**Comment by lucferbux** [comment]
@andrewballantyne Can you move it to Jira please?

**Comment by andrewballantyne** [comment]
Moved to Jira under the v2 DS Pipelines effort.

https://issues.redhat.com/browse/RHOAIENG-945
