### ISSUE TITLE
[Tech Debt]: remove Stack and Stack Items from ToolbarGroup instances

### ISSUE THREAD

**Issue by jenny-s51** [opendatahub-io/odh-dashboard#2277]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Description

cc @andrewballantyne @alexcreasy as discussed in our meeting today.

To follow PF guidelines, update toolbar label instances to sit inline with toolbar items, i.e. remove Stack where it is used within <ToolbarGroup> components

### Why?

#2268

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2403
