### ISSUE TITLE
[DS Project UI] - Validate the input of all the forms

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#231]
Currently, there is no validation for the UI. However, there are many forms like creating a new project, creating a new notebook, adding a data source or storage, etc... We need to add validation to all the forms to avoid the user entering something invalid.
There are 2 kinds of validations:
1. Check all the input fields using regex and show the error hint message under the text input like the example here https://www.patternfly.org/v4/components/form#invalid.
2. Check the result of the submission and show proper error alerts if there is something error after submitting a form. For example, if the user tries to create a project that already exists (duplicated project name) after hitting the submit button, he may get a 409 conflict HTTP error code. Then the UI should show the error message as the alert. Currently, it's doing nothing.

**Comment by andrewballantyne** [comment]
Old and out of date. Closing.
