### ISSUE TITLE
[DS Project UI] - Users and data projects permissions

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#234]
Currently, the users can only see the projects created by themselves. However, they should be able to set the view and edit permissions to all the users on the cluster. If the user goes to the projects details page and clicks on the permissions tab, he should be able to give permission to other users, and other users should be able to see all the projects in the projects table based on their permission. In this way, they could collaborate on the project together.

**Comment by andrewballantyne** [comment]
Out of date -- we implemented a new Data Science Projects. It does not have permissions, but it is on the roadmap. Currently it leans on K8s permissions so if you have powers to do it in OCP -- you should have the permissions to do it in the Dashboard.
