### ISSUE TITLE
(Dashboard Backend) User authorization checks

### ISSUE THREAD

**Issue by maroroman** [opendatahub-io/odh-dashboard#237]
There should be checks of user RBACs added to the dashboard so that actions made by the users are properly verified against their permissions on the openshift cluster based on the username in the dashboard status call.

I propose using https://github.com/fastify/middie to add middleware for each call requiring it, that would contain a check which would go through the user roles and check whether the required permissions are present.

Ex. GET nb images call would contain middleware with parameters `{"get" : "images.openshift.io"}, "opendatahub"` The middleware should loop through all the user rolebindings and in the roles the should look for the given combination. If it exists in a cluster role or a "opendatahub" role it should allow the call to go through.

**Comment by maroroman** [comment]
@DaoDaoNoCode @dlabaj @cfchase @lucferbux What do you think?

**Comment by lucferbux** [comment]
I think that's a great solution! Having some util method running as middleware in selected paths is a common pattern, easy to read and follow, I would give a +1

**Comment by maroroman** [comment]
After talking with @cfchase , I will try to implement this using bearer tokens passed by the proxy and take all calls through kubernetes which should complain if a user doesn't have the correct permissions.

**Comment by andrewballantyne** [comment]
@maroroman @lucferbux What's the net goal here? To make the error more palatable to the user or to help the UI not make requests it can never fulfill from this user? 

If you do not have access to something, Kube will stop you -- so it should be a moot issue if that's all we need. Unless the error message is undesirable, in which case we can look to do something about that, probably with the library you mentioned.

If we are looking to improve the UI, ie not show actions that cannot ever work -- I recommend we start thinking more along the lines of what OpenShift Console does, and use something like `useAccessCheck`...

K8s create on:
```
    {
      apiVersion: 'authorization.k8s.io/v1',
      kind: 'SelfSubjectAccessReview',
      spec: {
        resourceAttributes: {
          group,
          resource,
          subresource,
          verb,
          name,
          namespace: reviewNamespace,
        },
      },
    };
```
[Code Reference](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx#L52-L65)

eg:
```
  const canUpdate = useAccessReview({
    group: NodeModel.apiGroup,
    resource: NodeModel.plural,
    verb: 'patch',
    name: node.metadata.name,
    namespace: node.metadata.namespace,
  });
```

**Comment by maroroman** [comment]
@andrewballantyne I think #259 will make this issue obsolete so I am willing to close it, since communication directly with k8s with a bearer token will provide all the authorization we need.

**Comment by andrewballantyne** [comment]
@maroroman Reading back on this -- I wonder if the underlying request here is still valid but the discussion on the how confused the situation.

#259 will mirror the RBAC access we have today. It uses the `kube` plugin for `fastify` and make requests as the `user` that is logged in -- server side. 

We do not have a solution (that I know of) for the logged in **UI** user to make requests as them. We can look to maybe find a way to do that but it would be undesirable in our hybrid architecture today.

**Comment by andrewballantyne** [comment]
I'm going to close this issue -- as far as I can tell, when my user routes to the Dashboard (from the link in OpenShift Console) I am the selected user that is kicked by our `GET /api/status` -- this means when I make API calls against that backend, these calls made to kube on my behalf is from my user and thus is my permissions.

We default to `kube:admin` if things go off the rails -- but it looks like this _should_ already be done by k8s... and with the pass through API we will start moving this logic to the client -- which albeit is the same user access token on the pass through API. 

Later down the road if we have a desire to show 403 pages or hide items that are permission driven (like fields, sections or pages) we can use the OpenShift Console method of `checkAccessReview` -- which will tell me before an API call, if I have authorization to make it successfully.
