### ISSUE TITLE
[Bug]: Unable to login to odh dashboard when creating/using multiple instances of kfdef in different projects(ns).

### ISSUE THREAD

**Issue by donovat** [opendatahub-io/odh-dashboard#2500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

Open Data Hub Operator 1.11 

### Current Behavior

Have installed the ODH Operator, (on multiple Openshift clusters). Have then created multiple kfdef instances in different project/namespaces. Each kfdef instance has its own instance of odh-dashboard. The first instance works, and users can login via the OpenShift login button etc. However the second and remaining odh-dashboard instances all fail with the error:
```
error	"invalid_request"
error_description:  "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."
state	"c676ffee6417296dd039067859ed14bd:/"
```
Have had discussions on the slack channel, and took a look at the oauth client setup. 
I notice that only the one `client application` is registered for ODH - with only one callback url. Even though multiple applications should be registered each with their own call back, i.e.
```
oc get oauthclient.oauth.openshift.io
NAME                           SECRET                                        WWW-CHALLENGE   TOKEN-MAX-AGE   REDIRECT URIS
console                        ssjsjjsjsjsjsjsjssjsjsjsjsj   false           default         https://console-openshift-console.xxx-xxxxx-9ca4d14d48413d18ce61b80811ba4308-0000.containers.appdomain.cloud/auth/callback
dashboard-oauth-client         Qsywywywywywywywywywwywy              false           default         https://odh-dashboard-odh.xxx-xxxxx-9ca4d14d48413d18ce61b80811ba4308-0000.containers.appdomain.cloud
openshift-browser-client       shshshshshshshshshshshshshshs              false           default         https://c1999-e.containers.cloud.ibm.com:30250/oauth/token/display
openshift-challenging-client                                                 true            default         https://c1999-e..containers.cloud.ibm.com:30250/oauth/token/implicit 
```
The suggested workaround to delete the secret `dashboard-oauth-client-generated` and bounce the dashboard pod fails, however if you delete both the `dashboard-oauth-client` and `dashboard-oauth-client-generated` secrets and bounce the pod, the `oauthclient.oauth.openshift.io` resource gets updated with the new secret value, but the original dashboard then fails to logn, and do any other dashboards. 

### Expected Behavior

multiple instances of the application oauth are created, each with a unique `oauth client id` {at the moment its seems to create just the one with a default id}.

### Steps To Reproduce

See details above.

**Comment by andrewballantyne** [comment]
Unfortunate KfDefs are no longer supported. Please upgrade to v2 of the Operator and use the DSC & DSCI resources.

@VaishnaviHire / @zdtsw -- let me know if you folks feel that statement is not accurate in anyway, but I believe we have officially as of 2.7 stopped installing the default with v1.
