### ISSUE TITLE
Add documentation for Notebook and image API endpoints

### ISSUE THREAD

**Issue by maroroman** [opendatahub-io/odh-dashboard#263]
The API endpoints for Imagestreams, BYON images and Notebooks are not documented or incorrectly documented in the docs folder, this needs to be amended.

**Comment by andrewballantyne** [comment]
We need to generate such documentation... leaving this up to the devs will make this always behind.

Maybe we use something like: https://www.npmjs.com/package/fastify-print-routes ?

https://github.com/opendatahub-io/odh-dashboard/issues/259 will seek to start to replace this effort with a singular API that directly talks to kube.

**Comment by andrewballantyne** [comment]
As I noted in https://github.com/opendatahub-io/odh-dashboard/issues/401 -- we will not be doing this. Our net goal is to move away from this. I was unsure of full direction a month ago.
