### ISSUE TITLE
[Bug]: Admin UI Idle Culler settings is enabled to 0 min when culler_timeout does not exist in the jupyterhub-cfg configMap

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `culler_timeout` does not exist in the jupyterhub-cfg ConfigMap, the `Stop idle notebooks` setting of `Cluster Settings` sets `Stop idle notebooks after` after 0 minutes.  This has no affect since the idle culler pod is not running

### Expected Behavior

The Cluster Settings should show that notebook idle culler is disabled when `culler_timeout` 
* Does not exist
* Is Null
* Equals the default value `31536000`

### Steps To Reproduce

1. Edit `jupyterhub-cfg` to remove `culler_timeout` value
2. Deploy odh-dashboard
3. Login to the odh-dashboard Cluster Settings UI and check that `Stop idle notebooks` is enabled

### OpenShift Version

OpenStack

### Openshift Version

4.10.20

### What browsers are you seeing the problem on?

Chrome

### Open Data Hub Version

```yml
Dashboard v2.0
```

**Comment by DaoDaoNoCode** [comment]
This issue will be closed when we fully remove JupyterHub dependency in #1211

**Comment by andrewballantyne** [comment]
I will move this to Jira.

**Comment by andrewballantyne** [comment]
Should be covered by https://issues.redhat.com/browse/RHOAIENG-572
