### ISSUE TITLE
[KFNBC]: UI - Create error notification for every failing API call

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#281]
### Feature description

For KFNBC UI, it's now mostly using `console.error` to show error messages when the API call fails. We hope to see a more detailed error message in the notification drawer if something went wrong.

**Comment by andrewballantyne** [comment]
All errors are more-or-less suppressed to the console; this is very confusing to the user. We should look to fix this asap.

**Comment by andrewballantyne** [comment]
We need to focus on where failures happen. It is likely in kube calls, so we want to grab `e.response.body` to get the error and return that to the client.

**Comment by andrewballantyne** [comment]
This is a technical debt issue that we won't get to. We have plans to migrate the KFNBC over to a project based system which uses k8s pass through api. If there is missing error messages, we'll catch them on a 1 on 1 basis.
