### ISSUE TITLE
[KFNBC]: UI - Update NOTEBOOK_ARGS to expose the kernels to be compatible with the culling scraping endpoint

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#283]
### Feature description

Example: https://github.com/opendatahub-io/odh-manifests/blob/7df1e6bca3f191aa1e55fb00aabb8749ebd446ab/tests/resources/notebook-controller/notebooks/thoth-generic-oauth-notebook.yaml#L16-L22 (Requirement for culling support)

### Anything else?
Screenshot of the Cluster Settings with missing `culler_timeout` ![ps_20220711153011](https://user-images.githubusercontent.com/2432396/178368184-30706a54-e7a1-4c05-ac08-4a556349cc14.png)

**Comment by maroroman** [comment]
@DaoDaoNoCode Should this be done automatically on spawning every notebook?

**Comment by DaoDaoNoCode** [comment]
I am not sure, do you have any idea? @samuelvl

**Comment by samuelvl** [comment]
All the notebooks must be exposed in that path, regardless the culling feature is enabled or not. Solution is updating the NOTEBOOK_ARGS variable with the following value:

```shell
- name: NOTEBOOK_ARGS
  value: |
    --ServerApp.port=8888
    --ServerApp.token=''
    --ServerApp.password=''
    --ServerApp.base_url=/notebook/${NB_NAMESPACE}/${NB_NAME}
```

And update the probes to use this new path:

```shell
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /notebook/${NB_NAMESPACE}/${NB_NAME}/api
              port: notebook-port
``` 

Finally, the UI will redirect the "Start server" button to this path.

**Comment by DaoDaoNoCode** [comment]
@samuelvl That makes sense, I will add this field every time when creating the notebook.

**Comment by samuelvl** [comment]
@DaoDaoNoCode Can you share the notebook object?

```shell
oc get notebook ${NOTEBOOK_NAME} -o yaml
```

**Comment by samuelvl** [comment]
The image `image-registry.openshift-image-registry.svc:5000/opendatahub/s2i-minimal-notebook:v0.0.15` is [one year old](https://quay.io/repository/thoth-station/s2i-minimal-notebook?tab=tags) and it uses the deprecated `NotebookApp` instead of `ServerApp`.

Try with the following:

```
- name: NOTEBOOK_ARGS
  value: |-
    --NotebookApp.port=8888
    --NotebookApp.token=''
    --NotebookApp.password=''
    --NotebookApp.base_url=/notebook/opendatahub/jupyter-nb-daodaonocode
```

I have opened this PR to update minimal notebook tag to be compatible with `--ServerApp` https://github.com/opendatahub-io/odh-manifests/pull/592

**Comment by DaoDaoNoCode** [comment]
@samuelvl I tried `NotebookApp` but it still gives me a 404 error when opening the notebook, while I cannot find any error event in the pod.

**Comment by samuelvl** [comment]
@DaoDaoNoCode Can you try with the `--ServerApp` flag and the image `s2i-generic-data-science-notebook:v0.0.5`? Minimal should work when updated to `v0.3.0`
