### ISSUE TITLE
[Feature Request]: Telemetry user tracking feature should default to Disabled

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#285]
### Feature description

By default we should set `disableTracking: true` so that standard build of odh-dashboard do not appear to have it enabled even when the `woopra` and `segement.io` are not enabled or configured.  Since this is an opt-in feature by Admins then the enabling that feature should be opt-in.  These error logs appear to be 

```
{"level":50,"time":1657631027586,"pid":78,"hostname":"odh-dashboard-866d6d4fd5-2vmss","msg":"Error retrieving segment key enabled: HttpError: HTTP request failed"}
{"level":50,"time":1657631027599,"pid":78,"hostname":"odh-dashboard-866d6d4fd5-2vmss","msg":"Error retrieving cluster settings: HttpError: HTTP request failed"}
```

**Comment by andrewballantyne** [comment]
This is "done"-ish. If you do not have a config, we will turn tracking on, but all deployments should have a config. 

We can update the DashboardConfig fallback to not have it enabled. 
https://github.com/opendatahub-io/odh-dashboard/blob/31aff2f5202c6afd155f2e7dc8641cb02d14dd23/backend/src/utils/constants.ts#L42
