### ISSUE TITLE
[Repo Setup]: Enable CI to build and push the latest dashboard image

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#286]
### Feature description

To allow users to deploy the latest version of odh-dashboard as part of a rolling ODH release, we need to automate the build of the dashboard image when `main` is updated.  I recommend we use OpenShift-CI as the ODH standard method since @samuelvl has already set it up for ODH default notebook image builds

- [ ] Add OWNERS file
- [ ] Enable OpenShift-CI to build and push to quay.io/opendatahub/odh-dashboard

### Describe alternatives you've considered

Using quay build triggers to build the image when `main` is updated.  Initial attempts have failed and quay doesn't not provide verbose logs to debug the issue

### Anything else?

See #268 about documenting how we make new features available to users for testing

**Comment by samuelvl** [comment]
The repository https://github.com/opendatahub-io/odh-dashboard will be added to this folder https://github.com/openshift/release/tree/master/ci-operator/config/opendatahub-io 

The images can be promoted to Quay using the `opendatahub-io-ci-image-mirror` workflow. Example at https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml

**Comment by LaVLaS** [comment]
https://github.com/openshift/release/pull/30719 was just merged.  We should have automatic builds for any commits pushed to `main` now.  

@samuelvl has an example PR that we can reference to also create images based of PRs for testing

**Comment by samuelvl** [comment]
@LaVLaS The PR to support PR images mirroring [was merged](https://github.com/openshift/release/pull/31258). All what you need in the dashboard is adding the following job to the [CI configuration](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/odh-dashboard/opendatahub-io-odh-dashboard-main.yaml#L24-L42):

```yaml
- as: odh-dashboard-pr-image-mirror
  steps:
    dependencies:
      SOURCE_IMAGE_REF: odh-dashboard-image
    env:
      IMAGE_REPO: odh-dashboard
    workflow: opendatahub-io-ci-image-mirror
```

For example, I opened this PR https://github.com/opendatahub-io/kubeflow/pull/34 and the CI mirrored the following images:

- quay.io/opendatahub/kubeflow-notebook-controller:pr-34
- quay.io/opendatahub/odh-notebook-controller:pr-34

**Comment by samuelvl** [comment]
@LaVLaS I found an small issue when merged https://github.com/opendatahub-io/kubeflow/pull/34

PR to fix it -> https://github.com/openshift/release/pull/31377

**Comment by LaVLaS** [comment]
@samuelvl @andrewballantyne openshift-ci PR https://github.com/openshift/release/pull/31258 to add support for PR image builds

**Comment by andrewballantyne** [comment]
I believe this is completed now. Closing.
