### ISSUE TITLE
[KFNBC]: Add an information panel when stopping a notebook

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you stop a notebook you're brought back to the launcher without any information/warning/confirmation.
It may confuse people, not being sure if the notebook was indeed shut down or you were brought back to the launcher by mistake. It may be further confusing if at some point we allow a user to launch multiple notebooks simultaneously, as KFNB allows.

### Expected Behavior

When stopping a notook, add a pop up window in a similar way as when you start it. The message could simply be "Now stopping your notebook...", a OK button to close the Window, and then only you're brought back to the launcher.

### Steps To Reproduce

Stop a notebook.

**Comment by DaoDaoNoCode** [comment]
<img width="560" alt="Screen Shot 2022-07-15 at 4 33 36 PM" src="https://user-images.githubusercontent.com/37624318/181516446-79e5d394-b88f-442e-8d25-aa7ed2a82c60.png">
UX design here.
