### ISSUE TITLE
[KFNBC] Add notebook destination namespace to OdhDashboardConfig

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/odh-dashboard#297]
### Feature description

Instead of getting the notebook namespace destination from an environment variable:

https://github.com/opendatahub-io/odh-dashboard/blob/fee96c0414d0deca2504ec3be230fc4f5c01b16c/frontend/src/utilities/const.ts#L14

Get this value from a new field in the `OdhDashboardConfig` custom resource:

```yaml
notebookController:
    notebooksNamespace: "odh-notebooks" # optional
```

If `.notebookController.notebooksNamespace` is not present, use the same namespace where the dashboard is deployed.

### DoD

- [ ] Backend implementation (link PR)
- [ ] Frontend implementation (link PR)

**Comment by DaoDaoNoCode** [comment]
I already implemented both the frontend and backend of this but met some permission issues and logic problems, as well as CRD. @samuelvl We can talk tomorrow morning.

**Comment by andrewballantyne** [comment]
As discussed on Slack. @DaoDaoNoCode please push your code up and create WIP/Draft PRs that link to this issue so we can keep track of on-going work and work that is waiting on other work.
