### ISSUE TITLE
[KFNBC]: File -> Log out does not work

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on File -> Log Out brings up an error message
![image (5)](https://user-images.githubusercontent.com/82518733/179182321-0eeb12f6-01bd-4209-b41d-4bda8acefbbc.png)
Clicking on `dashboard` simply reloads the JL interface.

### Expected Behavior

Logs the current user out, server keeps running

### Steps To Reproduce

Spawn server
Click on `Log Out` in the `File` menu
Click on `dashboard` in the error message

**Comment by DaoDaoNoCode** [comment]
@samuelvl Just FYI you can directly overwrite `hub_control_panel_url` instead of `hub_prefix` and `hub_host` to get rid of `/home` in the URL.

**Comment by samuelvl** [comment]
@DaoDaoNoCode I don't see that variable in the extension panel: https://github.com/jupyterlab/jupyterlab/blob/3.0.x/packages/hub-extension/src/index.ts#L79-L85
