### ISSUE TITLE
[KFNBC]: Deployment Size in the control panel is always shown as default

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After spawning a server the control panel page will show the details of the server.
`Container Size` always shows `Default` regardless of user selection (and limits/requests).

### Expected Behavior

Container size matches the size that was selected (S/M/L etc.)

### Steps To Reproduce

Spawn server
Go to nb control panel
Expand `Notebook server details`

**Comment by andrewballantyne** [comment]
@lugi0 The PR merged this morning, so it would not be part of any image build more than 5 hours ago (from this message)
