### ISSUE TITLE
[KFNBC]: os.environ in a nb server exposes IP addresses of all running nbs

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I do 
```
import os
print(os.environ)
```
in a notebook server, I will get back a list of environment variables, which include IPs for all running notebooks (along with ports for connection, which are the default 443/80, but could be more sensitive if we had custom port mapping).

### Expected Behavior

I should not be getting the IPs of everyone else's notebook servers

### Steps To Reproduce

Spawn a notebook
in a code cell, write
```
import os
print(os.environ)
```

**Comment by samuelvl** [comment]
@lugi0 I wasn't aware of this behavior, any ideas why is it happening?

**Comment by lugi0** [comment]
@samuelvl I'm not sure. Currently in RHODS what gets exposed is similar but limited to your own running nb:
```
KUBERNETES_PORT tcp://XXX.XX.X.X:443
KUBERNETES_PORT_443_TCP tcp://XXX.XX.X.X:443
KUBERNETES_PORT_443_TCP_ADDR XXX.XX.X.X
KUBERNETES_PORT_443_TCP_PORT 443
KUBERNETES_PORT_443_TCP_PROTO tcp
KUBERNETES_SERVICE_HOST XXX.XX.X.X
KUBERNETES_SERVICE_PORT 443
KUBERNETES_SERVICE_PORT_HTTPS 443
```
Now the same information (for TLS) seems to get exposed for all (running?) servers. Perhaps at spawn time something is fetching this info for all `jupyter-nb-*` pods in the namespace instead of narrowing it down by username?

**Comment by lugi0** [comment]
What I see in the logs of the pod might confirm what I said earlier:

```
+ JUPYTER_ENABLE_WEBDAV=false
+ export JUPYTER_ENABLE_WEBDAV
+ '[' -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ']'
++ echo jupyter-nb-lgiorgi-0
++ sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'
+ DEPLOYMENT=jupyter-nb
++ cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
+ NAMESPACE=opendatahub
+ WEBDAV_REALM=opendatahub/jupyter-nb
```

There's a sed on the pod name which returns `jupyter-nb`, which is then set as the `Deployment` (and as the `WEBDAV_REALM`)
```
++ echo jupyter-nb-lgiorgi-0
++ sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'
+ DEPLOYMENT=jupyter-nb
```

I'm not sure if this is then used anywhere else to fetch those environment variables

**Comment by lugi0** [comment]
My best guess at the moment is that the culpript is `/opt/app-root/etc/jupyter_server_config.py`, but I cannot find that file in the pod

**Comment by VaishnaviHire** [comment]
> What I see in the logs of the pod might confirm what I said earlier:
> 
> ```
> + JUPYTER_ENABLE_WEBDAV=false
> + export JUPYTER_ENABLE_WEBDAV
> + '[' -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ']'
> ++ echo jupyter-nb-lgiorgi-0
> ++ sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'
> + DEPLOYMENT=jupyter-nb
> ++ cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
> + NAMESPACE=opendatahub
> + WEBDAV_REALM=opendatahub/jupyter-nb
> ```
> 
> There's a sed on the pod name which returns `jupyter-nb`, which is then set as the `Deployment` (and as the `WEBDAV_REALM`)
> 
> ```
> ++ echo jupyter-nb-lgiorgi-0
> ++ sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'
> + DEPLOYMENT=jupyter-nb
> ```
> 
> I'm not sure if this is then used anywhere else to fetch those environment variables


@lugi0 This seems to be set by the minimal notebook https://github.com/thoth-station/s2i-minimal-notebook/blob/master/builder/run#L14. But I am not sure why same issue was not observed by JupyterHub.

**Comment by VaishnaviHire** [comment]
@lugi0 @samuelvl 

As given in the Kubernetes [docs](https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services),  env variables related to services are shared across pods in a namespace if the service is created after the pods are deployed.

From the Note in the docs
```
When you have a Pod that needs to access a Service, and you are using the environment variable method to publish the port and cluster IP to the client Pods, you must create the Service before the client Pods come into existence. Otherwise, those client Pods won't have their environment variables populated.

If you only use DNS to discover the cluster IP for a Service, you don't need to worry about this ordering issue.
```
