### ISSUE TITLE
[KFNBC] Store controller status in .status.notebookController stanza

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/odh-dashboard#309]
### Feature description

Following [K8s best practices](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status), the status of the controller should be in the `.status` field instead of `.spec`. 

Move the `.spec.notebookControllerState` stanza to `.status.notebookController`.

https://github.com/opendatahub-io/odh-dashboard/blob/fee96c0414d0deca2504ec3be230fc4f5c01b16c/manifests/base/odh-dashboard-crd.yaml#L84-L105

**Comment by andrewballantyne** [comment]
Updating `.spec` is bad form, so this is rated higher because we should look to be predictable with our resources so that it can be understood by all how to consume data.

**Comment by andrewballantyne** [comment]
Also switching it to a bug as this is not the intended use of K8s resources.
