### ISSUE TITLE
[KFNBC]: Add TENSORBOARD_PROXY_URL env variable

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-dashboard#314]
### Feature description

To display Tensorboard in `s2i-tensorflow-gpu-notebook` image, add TENSORBOARD_PROXY_URL if not present. The default value for this env variable should be as follows:

```
TENSORBOARD_PROXY_URL=$(NB_PREFIX)/proxy/6006
```

### Anything else?
Related Issue: https://github.com/thoth-station/s2i-tensorflow-gpu-notebook/issues/6

**Comment by andrewballantyne** [comment]
@VaishnaviHire I believe this can be closed, can you confirm?

**Comment by andrewballantyne** [comment]
Closing this issue as stale -- feel free to reopen if needed @VaishnaviHire if you feel otherwise.
