### ISSUE TITLE
[KFNBC]: Add API call to get detailed logs for notebook controller

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#315]
### Feature description

When starting the notebook server, we hope to see the detailed logs of the spawning. Based on the comment in https://github.com/opendatahub-io/kubeflow/issues/29, we should fetch the events of the Notebook Pod.

This is for the Backend implementation. See https://github.com/opendatahub-io/odh-dashboard/issues/351 for the Frontend implementation.

**Comment by samuelvl** [comment]
Increasing priority to high since this is a requirement for phase 0
