### ISSUE TITLE
[KFNBC]: Custom image that works in RHODS fails to spawn in KFNBC

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I try to create a custom image with this URL: quay.io/thoth-station/s2i-lab-elyra:v0.1.1 (which I am able to spawn in RHODS)
spawning will then fail with the following logs in the nb pod:

```
+ [[ ! -f /opt/app-root/src/.local/share/jupyter/metadata/runtimes/my_kfp.json ]]
+ elyra-metadata install runtimes --schema_name=kfp --name=my_kfp '--display_name=Default Kubeflow Pipeline Runtime' --api_endpoint=http://ml-pipeline-ui.kubeflow/pipeline --cos_endpoint=http://minio-service.kubeflow:9000 --cos_username= --cos_password= --cos_bucket=default --engine=Tekton
Parameter '--cos_username' requires a value.
Install a metadata instance into namespace 'runtimes'.
Options
-------
--replace
Replace existing instance
--schema_name=<string>
The schema_name of the metadata instance to install. Must be one of: ['airflow', 'kfp']
--name=<string>
The name of the metadata instance to install
--display_name=<string>
Display name of this Kubeflow Pipelines configuration
--description=<string>
Description of this Kubeflow Pipelines configuration
--api_endpoint=<string>
The Kubeflow Pipelines API endpoint
--user_namespace=<string>
The Kubeflow Pipelines user namespace used to create experiments
--api_username=<string>
The Kubeflow Pipelines API endpoint username
--api_password=<string>
Password for the specified username
--engine=<string>
The Kubeflow Pipelines engine in use ('Argo' or 'Tekton')
--cos_endpoint=<string>
The Cloud Object Storage endpoint
--cos_secret=<string>
Kubernetes secret that's defined in the specified user namespace, containing the Cloud Object Storage username and password.
--cos_username=<string>
The Cloud Object Storage username
--cos_password=<string>
The Cloud Object Storage password
--cos_bucket=<string>
The Cloud Object Storage bucket name
--tags=<array>
Tags for categorizing Kubeflow pipelines
+ exec /usr/libexec/s2i/run
ERROR: don't know how to run your application.
Please set either APP_MODULE, APP_FILE or APP_SCRIPT environment variables, or create a file 'app.py' to launch your application.
```

### Expected Behavior

Image is added to spawner and is spawnable

### Steps To Reproduce

Log in with a RHODS admin user
Create a custom image through the dashboard with this URL: quay.io/thoth-station/s2i-lab-elyra:v0.1.1
(if logged in with kubeadmin) switch to another user and move to KFNBC spawner
try to spawn the custom image

**Comment by samuelvl** [comment]
Tracked in https://github.com/opendatahub-io/s2i-lab-elyra/issues/44

**Comment by andrewballantyne** [comment]
This looks like an issue with the image? The 2nd last line of the log is not something the Dashboard can fix I don't think. 

> ERROR: don't know how to run your application.

We pass the image off and it failed to startup.

Would we even consider this a Dashboard issue? @samuelvl

**Comment by samuelvl** [comment]
> Would we even consider this a Dashboard issue?

No, this is a issue with the elyra image. We opened https://github.com/opendatahub-io/s2i-lab-elyra/issues/44 to track it. Closing.
