### ISSUE TITLE
[KFNBC]: Cancel button in the spawner page 

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image (6)](https://user-images.githubusercontent.com/82518733/179729055-41249d79-acc6-471f-a701-e7a34a89e144.png)
a `Cancel` button appeared at the bottom of the spawner page. If I click it, it brings me back to the `Enabled` page.

### Expected Behavior

I don't think there should be a `Cancel` button in the spawner page, since I am not currently spawning anything

**Comment by andrewballantyne** [comment]
@kywalker-rh We have cancel buttons in OpenShift Console on all our pages, it effectively just does a browser history goBack... does this make sense to bring into ODH? If we do not have a back button here, I am more strongly thinking we should have the navigation still visible like I mentioned in https://github.com/opendatahub-io/odh-dashboard/issues/318

**Comment by DaoDaoNoCode** [comment]
Should we get rid of the cancel button now since we will always show the navigation?

**Comment by andrewballantyne** [comment]
This has legit uses and I ran it by Kyle. No need to remove the cancel button. When you're an admin, it takes you back to the screen (when you're impersonating someone else) and it is okay to go back to the components page when you navigate as a regular user. As you are canceling out of the form you started by launching the KFNBC.

**Comment by jkoehler-redhat** [comment]
I was reviewing the mocks and there is indeed a cancel button.  @lugi0 see https://marvelapp.com/prototype/90ii3fd/screen/85876386.
