### ISSUE TITLE
[KFNBC]: Environment variables are not added to the spawned server 

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding environment variables in the spawner page does not result into them being available in the spawned server
![Screenshot from 2022-07-19 15-29-25](https://user-images.githubusercontent.com/82518733/179762774-15a0b5be-4b1a-495f-b1ab-42221ce623c3.png)
![Screenshot from 2022-07-19 15-31-05](https://user-images.githubusercontent.com/82518733/179762788-b7c307ae-1e99-455c-bf1a-0540c8892fdc.png)

### Expected Behavior

Environment variables available in the server

### Steps To Reproduce

In the spawner page, add one or more environment variables
Spawn the server
import os
print(os.environ['YOUR_ENV_VAR_NAME'])

**Comment by andrewballantyne** [comment]
Kinda defeats the purpose of env vars if you do not have access to read them.
