### ISSUE TITLE
[Bug]: ODH is not listed in OpenShift's Console > Applications

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/odh-dashboard#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the kubeflow pilot cluster, ODH is not listed in OpenShift's Console > Applications. I'm not sure if this is the expected behavior or it should appear (like RHODS does), but creating this bug just in case.

![image](https://user-images.githubusercontent.com/66894/179963276-4603718f-eda4-405c-9eca-eea0d3883dea.png)

### Workaround (if any)

A custom deployment can just create a ConsoleLink for this solution.

**Comment by andrewballantyne** [comment]
@LaVLaS @cfchase I believe we talked about adding the Dashboard to the ConsoleLink -- would this be something provided by the operator?

**Comment by andrewballantyne** [comment]
Started a thread on the [Open Data Hub Slack](https://odh-io.slack.com/archives/C0330L52N22/p1660675448857699) -- to be determined how we approach this. It appears there is no easy way to do this today.

**Comment by andrewballantyne** [comment]
The Operator is not powerful enough to do this. We have some plans for another controller for the Dashboard as we migrate to fully using the Pass-through API. This hopefully can be readdressed at that point.

A custom deployment can just create a ConsoleLink for this solution. So there is at least a workaround.

**Comment by lucferbux** [comment]
@zdtsw @VaishnaviHire @andrewballantyne We are closing this because it should be handled by the operator.

**Comment by andrewballantyne** [comment]
I have created https://issues.redhat.com/browse/RHOAIENG-943 -- and make it Dashboard issue instead of an Operator issue... we can just unify our manifest files and this should solve things. Some collab may be needed.
