### ISSUE TITLE
[KFNBC] Most cards under Resources tab still show JupyterHub icon

### ISSUE THREAD

**Issue by laubai** [opendatahub-io/odh-dashboard#336]
As per discussion on Slack with Guillaume, these icons should all be Jupyter icons rather than JupyterHub icons once KFNBC is implemented.

**Comment by laubai** [comment]
![Screenshot from 2022-07-21 23-47-21](https://user-images.githubusercontent.com/466662/180229994-06bd67f0-f967-4459-b7bf-b476a1f18de3.png)

One of the cards has the correct Jupyter icon, the rest have the JupyterHub icon still.

**Comment by DaoDaoNoCode** [comment]
@laubai Just want to make sure, we want to keep all of these docs, and only change the icons of them, right?

**Comment by laubai** [comment]
@DaoDaoNoCode Good question - I think so, but I haven’t actually run through them. Let me do that on Monday and get back to you.

**Comment by laubai** [comment]
@DaoDaoNoCode Yes, we can keep them all. I will log a separate issue, though - Launching Jupyter hides the QuickStart that the user is currently following steps in, which is an issue for people trying to complete the  first quickstart! :)

**Comment by DaoDaoNoCode** [comment]
@laubai Is there a getting-started doc for `jupyter` like this `jupyterhub` one? https://github.com/opendatahub-io/odh-dashboard/blob/main/data/getting-started/jupyterhub.md. If there is no, should I also hide the `jupyterhub` card on the `Explore` page when the notebook controller is enabled?

**Comment by andrewballantyne** [comment]
Bulk un-assigning things that were old -- reassigned this back to you @DaoDaoNoCode as you're working on it now. If you are actively working on it please move it into progress on the board.

**Comment by DaoDaoNoCode** [comment]
Sure, already moved. I just need some more information to get this PR submitted so I can make sure we are showing the correct docs on every page including `Explore` and `Resources`.
