### ISSUE TITLE
UI - Refactor SpawnerPage component

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#340]
### Feature description

We need to refactor the SpawnerPage component since it's too large (over 400 lines), and it's not easy for us to read and maintain it. We should split it into different functions into different files.

**Comment by andrewballantyne** [comment]
Thanks for logging this Juntao. The component is doing too many things to achieve a working UI. It should be broken out into hooks or wrapping components (if applicable). There should be no need to do it all in one component, it obfuscates the code readability.

**Comment by andrewballantyne** [comment]
I'm going to pull it from the notebook controller work as it does not impact our deliverable for that.

**Comment by andrewballantyne** [comment]
Hmm, no way to partially link a PR to this issue. Will spawn a new issue and keep this one for the on-going goal of refactoring that page to be more manageable.

**Comment by andrewballantyne** [comment]
Going to close this. We should be migrating away from the old spawner page in favour of a customizable one (likely) when we work through the notebookNamespace migration (see [Milestone](https://github.com/opendatahub-io/odh-dashboard/milestone/8) for progress)
