### ISSUE TITLE
[KFNBC]: KFNBC should follow the access policy defined in the groups ConfigMap

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems KFNBC is not using the groups configuration in `jupyterhub-default-groups-config` CM. Any user I log in can access the spawner page. Thus, it is not possible to allow only a portion of the OCP users to spawn jupyter images

### Expected Behavior

Only the users belonging to `admin_groups` and `allowed_groups` (referring to  `jupyterhub-default-groups-config` CM) are able to access spawner page. 
All the remaining users get a 403 error page (or any user-friendly message explaining why they cannot go forward)

### Steps To Reproduce

1. Open  `jupyterhub-default-groups-config` CM or Go to `ODH Dashboard > Settings > User management` 
2. Set a group as `allowed_groups` and `admin_groups` (i.e.,  `Data Science user groups` and `Data Science administrator groups` in the UI)
3. Log in the ODH Dashboard using a user which does not belong to any of the previously set groups
4. Launch `Jupyter`
5. Check if you reach the spawner page and can spawn an image

### OpenShift Version

Other

### Openshift Version

OSD

### What browsers are you seeing the problem on?

Firefox

### Open Data Hub Version

```yml
1.2.0
```

**Comment by bdattoma** [comment]
based on the logs in the dashboard pods, I see that if you log in using an admin, it recognizes it is an admin since it prints out `isAdmin: true`. 
So, the issue could be only related to prevent users to access KFNBC if they are not in the selected groups

**Comment by andrewballantyne** [comment]
Based on the conversation in gchat, this definitely is something we need to address. This is the premise for our packages to only allow users to access content they are allowed to see.

**Comment by anishasthana** [comment]
@andrewballantyne I think #383  supersedes this issue. The configmap in question is not used any more (we use rhods-groups-config). What we now want to do is to update the CRD to include a way to specify the groups that have access.

**Comment by bdattoma** [comment]
>  is not used any more (we use rhods-groups-config)


@anishasthanat this bug report mentions `jupyterhub-default-groups-config` because it's about ODH, but it is valid for RHODS too where instead of using this CM, the `rhods-groups-config` is used.
