### ISSUE TITLE
[KFNBC]: "Launch application" on Jupyter hides Quick Start

### ISSUE THREAD

**Issue by laubai** [opendatahub-io/odh-dashboard#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

New users would typically want to refer to resources as they perform tasks to ensure they're doing the right thing.

When a user has a Quick Start open and clicks "Launch application" on the Jupyter card from the Applications -> Enabled page, the quick start and the navigation both disappear.

The navigation can be expanded again, but you can't simultaneously view the launcher and a quick start.

You can get back to the quick start by returning to the Resources tab (or any other tab) but you cannot view a quick start and the launcher at the same time.

### Expected Behavior

Quick Start stays open (or can be expanded for easy reference without losing the Launcher page) when the user clicks "Launch application"

### Steps To Reproduce

1. Log in to RHODS dashboard.
2. Click Resources tab and open any quick start.
3. Click Applications -> Enabled and click "Launch application" on the Jupyter card.
4. Quick start disappears.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Open Data Hub Version

```yml
opendatahub-operator.v1.3.0
```

**Comment by laubai** [comment]
Note this seems related to https://github.com/opendatahub-io/odh-dashboard/issues/318 but is not the exact same issue, apologies if this is considered duplication.

**Comment by andrewballantyne** [comment]
Definitely related but not a duplicate -- this is a much higher priority issue as quick starts needs to remain open for them to be of use.
