### ISSUE TITLE
[KFNBC]: "Default" Container size is missing from Notebook controller page

### ISSUE THREAD

**Issue by tarukumar** [opendatahub-io/odh-dashboard#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Default" Container size is missing from Notebook controller page. We have only small,Medium and Large sizes present

Other behaviors:

1. Actual container size value has changed:
Example:
JH:
Small:
Limits: 2 CPU, 8Gi Memory Requests: 1 CPU, 8Gi Memory
Medium:
Limits: 6 CPU, 24Gi Memory Requests: 3 CPU, 24Gi Memory

KFNBC:
Small:
Limits: 2 CPU, 2Gi Memory Requests: 1 CPU, 1Gi Memory
Medium:
Limits: 4 CPU, 4Gi Memory Requests: 2 CPU, 2Gi Memory
Large:
Limits: 8 CPU, 8Gi Memory Requests: 4 CPU, 4Gi Memory
![Screenshot from 2022-07-25 18-05-49](https://user-images.githubusercontent.com/93319437/180778760-25438ce2-34f5-4e84-ac5e-1972f17fb28b.png)

![Screenshot from 2022-07-25 15-56-04](https://user-images.githubusercontent.com/93319437/180762500-533542e4-3460-4789-8286-7d75d84f8f04.png)

### Expected Behavior

"Default" Container size is should present on Notebook controller page. 

### Steps To Reproduce

Launch the KFNBC spawner page

### Open Data Hub Version

```yml
RHODS: 1.15.0-qe-nbc
```

**Comment by DaoDaoNoCode** [comment]
@samuelvl Do you know what the default should be? I didn't know how can I get the default value so I remove that temporarily. If you know where I can get the default value and set it to the Notebook Object, I can add it back.

**Comment by lugi0** [comment]
@andrewballantyne if the aim is to have parity, keep in mind that RHODS also allows for `Large` and `XLarge` sizes, but they only show up in the spawner if the user has enough resources to actually use them

**Comment by andrewballantyne** [comment]
That's a good catch @lugi0 -- @DaoDaoNoCode we do not do any of that kind of detection today right? I do not recall seeing any code detecting the possibility for `Large` and `XLarge` in the Dashboard. (cc @dlabaj)

**Comment by andrewballantyne** [comment]
Is the ODH Dashboard Config created as part of RHODS setup? Because if it is, then that will be solved by that setup -- if not, then our defaults will not cover this. @DaoDaoNoCode

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne I have no idea about this. This would be a good question for @samuelvl

**Comment by samuelvl** [comment]
@anishasthana @maroroman Could you help us identifying where the default size is defined?

**Comment by maroroman** [comment]
> @anishasthana @maroroman Could you help us identifying where the default size is defined?

Sorry for the late answer. The default was added in JSP base don the user profile: https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/blob/master/docs/sizes.md We can solve this issue by solving: https://github.com/opendatahub-io/odh-dashboard/issues/339

**Comment by andrewballantyne** [comment]
This is solvable via our current configurations using `Default` as a property of the ODH Dashboard Config -- if we want to wait until we have more configurations to allow an admin to control it, we can do that.

Unless this gets special attention, this will remain a lower priority based item.

**Comment by tarukumar** [comment]
are we going with same container size value for KFNBC as JH or it will differ ?

**Comment by anishasthana** [comment]
It depends on what has been configured so far.  https://github.com/red-hat-data-services/odh-deployer/pull/250 is migrating old values over (including the old default) over.

**Comment by lugi0** [comment]
Folks, looking to get some clarity here, will the `Default` size be implemented in KFNBC or not? Should we remove it from our testing entirely?

**Comment by andrewballantyne** [comment]
@lugi0 I believe there is some discussion around what is and isn't the way to do it. But it was not planned for 1.15. If it is going in it will be 1.16

**Comment by lugi0** [comment]
Yes, 1.16 is fine, just looking for a definitive answer, since some of our tests are failing because of the missing size and we need to know if it will be reimplemented or not

**Comment by andrewballantyne** [comment]
Fair enough. Also, apologizes for the lack of improvement in testing for KFNBC... We'll start focusing on what we need to do next week now that the bulk of features are in KFNBC we can start architecting the right solution for automation moving forward.

**Comment by lugi0** [comment]
No worries, we're all aiming for the same goal :)

**Comment by anishasthana** [comment]
If there was an existing `Default` config in Jupyterhub, it will be migrated over. As for new installs, I'm not actually sure.

**Comment by andrewballantyne** [comment]
@anishasthana migrated where though? Into the ODH Dashboard Config CR? Because that doesn't exist on install

**Comment by anishasthana** [comment]
Ah... I'm thinking of RHODS right now. We are migrating the old global profile over into the `Notebook Sizes` field in the CR and renaming it to Default.

**Comment by erwangranger** [comment]
@kywalker-rh, @vconzola , when we did the mock up for the new Notebook Sizes UI, I believe we had discussed removing the obscure "default" and instead let the customer choose which of "S/M/L/XL" should be considered the default. 

I agree this does not need to get done immediately, but I think it's more important to keep the sizes (S/M/L/XL) the same in KFNBC as what they were in JupyterHub, rather than spend too much time on the "default" size, which should go away eventually. 

I hope this helps.

**Comment by vconzola** [comment]
@erwangranger You're correct. I did remove the "default" size from the list of sizes and added a checkbox to the "create/edit size" modal that allows an admin user to select the default size. https://marvelapp.com/prototype/i9h5357/screen/87639140 My assumption was that on the spawner page the default size would be indicated by parentheses, e.g., "Small (default)" in the list of sizes, but I guess this fell through the cracks and never got mocked up.

**Comment by andrewballantyne** [comment]
Thanks for the input @erwangranger that saves us some work as it is in motion right now.

Closing this ticket out as we do not want `Default` in KFNBC as noted in the previous comments.
