### ISSUE TITLE
[KFNBC]: All ISV/RH addon tiles are missing from the Dashboard

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing the 1.15 livebuild (quay.io/modh/rhods-operator-live-catalog:1.15.0-qe-nbc), all ISV tiles and all additional RH addons tiles are missing from the dashboard.
The behaviour is present both after a fresh install and after enabling KFNBC

### Expected Behavior

Dashboard shows all resources and tiles that are currently available in RHODS

### Steps To Reproduce

Install a 1.15 live build
Visit dashboard

**Comment by andrewballantyne** [comment]
@LaVLaS @cfchase thoughts on what happened here? I'm not super familiar with the RHODS setup, so I do not know if there is additional things not packaged with. I imagine it has to do with a configuration from the KFDEF, no?

@lugi0 Do you recall the last version it worked with?

**Comment by lugi0** [comment]
It is currently working with the 1.14 RC build @andrewballantyne

**Comment by LaVLaS** [comment]
The ISV/RH addon tiles are specific to the downstream build and not included upstream build.  Since those tiles need to be built into the image, we will add an extra commit downstream to add those missing tiles for the downstream build.

There are hardcoded yaml files in the data folder that will eventually be moved to k8s resources that will be read at runtime in #243

**Comment by samuelvl** [comment]
Increasing priority since this is a blocker for RHODS 1.15 release

**Comment by jkoehler-redhat** [comment]
This issue will be fixed in ODH by https://github.com/opendatahub-io/odh-dashboard/pull/243

**Comment by jkoehler-redhat** [comment]
Misunderstanding on what would address this.

**Comment by LaVLaS** [comment]
This is not an upstream odh-dashboard blocker because these files are not relevant for the upstream release.

**Comment by andrewballantyne** [comment]
This is my fault causing this ticket to yo-yo haha... The solution is indeed downstream as Landon mentions. https://issues.redhat.com/browse/RHODS-4800 is the downstream ticket. I misunderstood how we were tracking things and normally everything is in ODH first, but this is an exception to that rule. @lugi0 please follow the Jira ticket for the solution/progress watching of this issue.
