### ISSUE TITLE
[KFNBC]: while CUDA builds are ongoing user is unable to spawn any image

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Shortly after the installation of RHODS, while the CUDA builds are still ongoing, the user is unable to spawn any image from the spawner page.
The list of images will be empty, and will be populated only after the last cuda build completes (usually tensorflow).
![image (7)](https://user-images.githubusercontent.com/82518733/180796991-9e43dce4-6a62-42c9-957b-6ce9af47bf90.png)

If the user tries to spawn a server while the list of images is not present, a pod will be created with a `undefined:undefined` image.

It seems that, shortly after the last build completes, the user will still be unable to spawn an image (i.e. clicking on the `Start server` button does nothing)
![Peek 2022-07-25 13-52](https://user-images.githubusercontent.com/82518733/180797081-555f00b6-d3f3-46d0-8370-a615a3fb0447.gif)

### Expected Behavior

User is prevented from spawning the tensorflow/pytorch/cuda images while the builds are ongoing, but should be able to spawn using any other image

### Steps To Reproduce

Start installing RHODS
Go to KFNBC spawner page
Look for the list of images and/or try spawning a server

### Workaround (if any)

Wait until all cuda builds are complete

**Comment by lugi0** [comment]
@mwaykole and @kpouget have both experienced this first hand and might have additional details

**Comment by andrewballantyne** [comment]
This seems pretty straight forward -- lock the button when it can't be created properly. It is likely the defaults are influenced by presets and we just need to accept that there is an initial state of the button not being enabled.

Might be worth looking into a UX warning or info that says things are still starting up as to why the button is disabled in this case. Whomever picks it up should talk with UX to see how they feel about that -- min is we lock down the button when things are still loading.

**Comment by kpouget** [comment]
for testing purposes, it would be great if the button could be available as soon as the basic images are available

**Comment by andrewballantyne** [comment]
There is likely an error getting swallowed server-side... we should send that back to the client and present it next to the button so we can showcase why it did not start. The build should be able to start with the default images, and if there is an issue with that due to something, that needs to be presented -- the button, if enabled, should work or tell us why it cannot.

**Comment by cfchase** [comment]
```
TypeError: Cannot read property 'length' of undefined
 at checkTagExistence (/opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:69:34)
 at /opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:93:14
 at Array.forEach (<anonymous>)
 at getTagInfo (/opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:84:10)
 at processImageInfo (/opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:59:15)
 at /opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:31:20
 at Array.map (<anonymous>)
 at /opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:30:47
 at Generator.next (<anonymous>)
 at fulfilled (/opt/app-root/src/backend/dist/routes/api/images/imageUtils.js:5:58)

```

**Comment by samuelvl** [comment]
@lugi0 Can you confirm if this is still an issue in RHODS 1.15?

I don't see it anymore on a fresh 1.15 installation:

![image](https://user-images.githubusercontent.com/27858594/185922781-344c808d-889f-437a-bbe1-2c0e4921dacb.png)

``` $ oc get builds                                                  
NAME                                        TYPE     FROM          STATUS     STARTED          DURATION
11.4.2-cuda-s2i-core-ubi8-1                 Docker   Git@ac6291a   Complete   45 minutes ago   6m55s
11.4.2-cuda-s2i-base-ubi8-1                 Docker   Git@ac6291a   Complete   39 minutes ago   6m8s
11.4.2-cuda-s2i-py38-ubi8-1                 Docker   Git@4d85c35   Complete   32 minutes ago   8m11s
11.4.2-cuda-s2i-thoth-ubi8-py38-1           Docker   Git@9c71221   Complete   24 minutes ago   6m29s
s2i-minimal-gpu-cuda-11.4.2-notebook-1      Docker   Git@68a44b9   Complete   18 minutes ago   12m17s
s2i-pytorch-gpu-cuda-11.4.2-notebook-1      Source   Git@409f91f   Running    5 minutes ago    
s2i-tensorflow-gpu-cuda-11.4.2-notebook-1   Source   Git@45e5e50   Running    5 minutes ago    
```

**Comment by kpouget** [comment]
Things look good on my side (I delete the BuildConfigs to avoid wasting resources)
![image](https://user-images.githubusercontent.com/7559202/185923764-3136c8d9-2d6d-46fc-b6d7-5ac812f97978.png)

**Comment by kpouget** [comment]
> I can pick CUDA because it was already built, minimal and Standard but can't pick pytorch and tensorflow because they are building

hum, I can pickup all the images though :#

**Comment by samuelvl** [comment]
> hum, I can pickup all the images though :#

Yeah me too, after the build finished I can pick them all :)

**Comment by andrewballantyne** [comment]
Am I following this correctly -- is this issue no longer present? We can always reopen this issue if we see something specific in the future. @samuelvl @kpouget
