### ISSUE TITLE
[BYON]: In some places in the dashboard instead of notebook images its mentioned as byon-image

### ISSUE THREAD

**Issue by mwaykole** [opendatahub-io/odh-dashboard#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In some places in the dashboard instead of notebook images its mentioned as byon-image

### Expected Behavior

The name should be consistent in all the places  either Byon-image or Notebook-image

**Comment by mwaykole** [comment]
![Screenshot from 2022-07-26 11-47-08](https://user-images.githubusercontent.com/44530572/180937006-f0b0143d-b101-443d-9adb-e0dbeec9ab70.png)
![Screenshot from 2022-07-26 11-46-58](https://user-images.githubusercontent.com/44530572/180937019-adbc0964-0a04-4bd7-b7ff-ee70e5d7fabe.png)
![Screenshot from 2022-07-26 11-46-48](https://user-images.githubusercontent.com/44530572/180937028-ee1df808-eb64-46e2-98c5-b347e98166e5.png)

**Comment by mwaykole** [comment]
![Screenshot from 2022-07-26 11-47-08](https://user-images.githubusercontent.com/44530572/180937666-de4d3b80-3694-4df4-b3b8-613d9e9fa4
![Screenshot from 2022-07-26 11-46-
![Screenshot from 2022-07-26 11-46-48](https://user-images.githubusercontent.com/44530572/180937682-b9133085-23c7-4f7b-bf20-332b718b0397.png)
58](https://user-images.githubusercontent.com/44530572/180937675-d67a14a3-ddb1-49a4-aa12-459b0a8ccaad.png)
7f.png)

**Comment by mwaykole** [comment]
![Screenshot from 2022-07-26 11-46-48](https://user-images.githubusercontent.com/44530572/180937774-c20e3fb3-4b08-4834-9142-6e81559c5fc4.png)
![Screenshot from 2022-07-26 11-47-08](https://user-images.githubusercontent.com/44530572/180937790-8a1c5af4-8050-4d6c-befb-88497d4d27b7.png)

**Comment by DaoDaoNoCode** [comment]
This looks like not a KFNBC bug. It's a naming issue for BYON feature.
