### ISSUE TITLE
[KFNBC/JH]: Usage Data Collection checkbox is in a weird state by default and cannot be "enabled"

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After install, both with JH or KFNBC, the Usage Data Collection checkbox appears to be in a weird state
![selenium-screenshot-291](https://user-images.githubusercontent.com/82518733/180947577-b8d301d1-cac3-4d67-b257-27893fcb452d.png)
The checkbox is usually either empty or has a check mark (in case data collection is enabled). Selenium thinks that in this state, the checkbox is _not_ enabled.

After trying to select the checkbox (i.e. check mark appears) and clicking on `Save Changes`, nothing happens and the settings are not saved.

Furthermore, in this default state, even though Selenium sees the checkbox as currently disabled, the JH API still exposes the Segment key, as if usage data collection was actually enabled.

### Expected Behavior

Checkbox should either be empty (disabled) or have a check mark (enabled).
By default, I _think_ it should be disabled.
The segment key should not be exposed when usage data collection is disabled.

**Comment by lugi0** [comment]
Small update:

After clicking on `Save Changes`, if you refresh the browser page these error notifications will show up for a split second before the page is reloaded. One notification for each click on the button.
![Screenshot from 2022-07-26 09-31-52](https://user-images.githubusercontent.com/82518733/180949586-5ebd7596-434e-48dd-8766-785a6308ff4c.png)

**Comment by maroroman** [comment]
@lugi0 Could you please verify if this issue is still present in the latest live build? There was a fix in the deployer that may have solved this.

**Comment by lugi0** [comment]
@maroroman the issue is still present. Now by default the checkbox has a checkmark, but if you try to change the settings nothing happens when clicking the button, and when you refresh the page you still get the list of notifications with the `e.response is undefined`

**Comment by jgarciao** [comment]
In RHODS 1.15.0, the _Allow collection of usage data_ setting is properly stored in the configmap odh-segment-key-config but, when setting it to false, if you go to another section of the dashboard and then come back to Settings -> Cluster settings, the checkbox has the unfamiliar check mark mentioned in the description of this issue

![usage-data-collection](https://user-images.githubusercontent.com/66894/185109750-bcb82379-d210-42fe-b479-7b4aca75ba4c.png)

**Comment by andrewballantyne** [comment]
@jgarciao This should be fixed by the on-going PR: https://github.com/opendatahub-io/odh-dashboard/pull/404

When it gets merged down to RHODS, you should be able to get that fix.
