### ISSUE TITLE
[KFNBC/JH]: JupyterHub tile randomly disabled

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While testing the 1.15 live build that includes both KFNBC and JH, the JupyterHub tile was seemingly randomly in `Disabled` state.
This was at least an hour after install and after having run Smoke tests on the same build/cluster, where the issue was not seen.
![selenium-screenshot-4](https://user-images.githubusercontent.com/82518733/180952834-ffd7b46c-5b1e-407a-acbb-54d03dffce50.png)

I don't think I've ever seen this behaviour in RHODS, so this might be caused by some of the changes being made for KFNBC.

### Expected Behavior

JH tile does not become `Disabled`

### Steps To Reproduce

No known reproducer at the moment, this seems to have happened randomly

**Comment by andrewballantyne** [comment]
Yeah, I've seen this too... happens when things are being loaded. I've never seen it get stuck like this (you said for 1h) -- Did you navigate the screen @lugi0 ?

@DaoDaoNoCode I believe our loading code is doing something weird when the tile is added, likely a React state or something because I find it goes away when I navigate away and come back (ie the component reloads)

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne Yeah it's weird sometimes that I don't know how it loads but looks like it's not loading in a correct order, I will do some research on how this issue happens.

**Comment by andrewballantyne** [comment]
@DaoDaoNoCode if you do not know off the top of your head, we can leave the investigate to the bug. No worries 🙂

**Comment by lugi0** [comment]
@andrewballantyne I don't think it was in this state for 1h, but it just happened to be in this state while a test was being run. 
What's weird is that a bunch of tests ran before that and passed, and other tests ran after and passed, so it seems quite random.
I have not manually encountered this, the screenshot is from an automated test run (which failed because of the Disabled state).

**Comment by andrewballantyne** [comment]
Interesting... I see this almost like clockwork when I change the state of the ODH Dashboard Config to be JH or KFNBC... the card shows up always in a disabled state first.

**Comment by andrewballantyne** [comment]
JH doesn't exist anymore for the Dashboard. Closing this issue. I have also not seen this in sometime -- which is probably because of the OdhApplication existing now.
