### ISSUE TITLE
[KFNBC]: Access Jupyter notebook server requires another login action

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Current process to access a Jupyter notebook server**
1. Log in RHODS Dashboard using credentials of UserX
2. Spawn the desired notebook image from the spawner
3. click "Access server" button after the notebook server spawning process is done
4. Log in Jupyter once again using credentials of UserX

**Issue with the current behavior**
User is already logged into the dashboard. Users will perform login in Jupyter everytime they stop and start a new notebook image (UX affecting)

### Expected Behavior

If a user spawns a notebook image and they are already logged in, then the log in should not be requested once again when trying to access the server

### Steps To Reproduce

1. Log in RHODS Dashboard using credentials of UserX
2. Spawn the desired notebook image from the spawner
3. click "Access server" button after the notebook server spawning process is done
4. Log in Jupyter once again using credentials of UserX

### OpenShift Version

Other

### Openshift Version

OSD 4.10

### What browsers are you seeing the problem on?

Firefox

**Comment by samuelvl** [comment]
This is the expected behavior by design in Openshift, OAuth proxy does not provide SSO capabilities. 

We are exploring alternatives to provide a SSO experience for ODH components, tracked in [RHODS-2130](https://issues.redhat.com/browse/RHODS-2130)
