### ISSUE TITLE
[Feature Request]: Add sharing options for a notebook server

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#357]
### Feature description

As of now, a userX can access the notebook server started from a userY by using  userX's credentials and without informing/warning userY. 
I think it would be good to have for a user to be able to configure the access policy to their own servers. For example, userX wants to be the only one accessing their servers until they decide to share with others. (I may understand if ODH Admins can still have access to the private servers).

**Comment by samuelvl** [comment]
This will be default behavior after we merge this PR https://github.com/opendatahub-io/odh-dashboard/pull/358

- User X will only have access to server X
- User X will only have access to server Y
- ODH Admins will have access to server X and Y

**Comment by bdattoma** [comment]
@samuelvl what about the ability of sharing access? Would it make sense?

**Comment by andrewballantyne** [comment]
I do not believe Lucas' work will solve this @samuelvl -- I think @bdattoma is asking for something related to the "Project" work found in Kyle's mocks here: https://marvelapp.com/prototype/afa716d/screen/87997400

**Comment by andrewballantyne** [comment]
I do not believe this is part of KFNBC

**Comment by samuelvl** [comment]
@andrewballantyne @bdattoma Correct, sharing notebooks between users is part of the future Project initiative but it's not in KFNBC scope

**Comment by andrewballantyne** [comment]
I've removed it from the project then... this is something we need to address, but not part of the KFNBC work.

**Comment by bdattoma** [comment]
cool, thanks for the clarifications @andrewballantyne @samuelvl

**Comment by andrewballantyne** [comment]
We leaned on k8s permissions -- if you have access to the project, you'll likely have access to the workbench. No other feature level of permissions is expected here. Closing this issue as I think we achieved what we were after. If not, we can readdress this with fresh eyes.

**Comment by bdattoma** [comment]
@andrewballantyne Okay thanks.

> No other feature level of permissions is expected here


What about this Epic https://issues.redhat.com/browse/RHODS-1142? Wouldn't it require the same implementation of this Feature Request?

**Comment by andrewballantyne** [comment]
@bdattoma we should probably close that Jira ticket. Our priorities have shifted a lot in the last year and ODH will be driven by the latest desires. I highly doubt RHODS-1142 will be reused.

**Comment by bdattoma** [comment]
> @bdattoma we should probably close that Jira ticket. Our priorities have shifted a lot in the last year and ODH will be driven by the latest desires. I highly doubt [RHODS-1142](https://issues.redhat.com//browse/RHODS-1142) will be reused.

got it. I will post a comment in Jira to ask Jeff to review that Jira and close it if needed

**Comment by bdattoma** [comment]
@andrewballantyne according to Jeff this is still in plan

**Comment by andrewballantyne** [comment]
Understood. This ticket will not track that effort -- when it becomes a priority we will log something new to meet the new standards / tracking we use now.
