### ISSUE TITLE
[KFNBC]: Readiness and Liveness probe failing in the notebook pods (intermittent)

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Notebook pod is sometimes getting failures on Liveness and Readiness probe (events). Last time it happened to me it was when using Intel AiKit jupyter image. The notebook server is working, though.

![image](https://user-images.githubusercontent.com/88311595/181038749-d5ccbddf-c71d-4f72-bc7a-8541a3ba4b6e.png)

### Expected Behavior

no failures among the events

### Steps To Reproduce

Spawn a notebook image (e.g., Intel Aikit)

### OpenShift Version

4.10.2

### Openshift Version

OSD

**Comment by samuelvl** [comment]
@bdattoma Can you provide notebook pod logs?

**Comment by bdattoma** [comment]
> @bdattoma Can you provide notebook pod logs?

I will next time I hit the problem

**Comment by andrewballantyne** [comment]
This issue is 20days old with no update. I'm going to close this issue for now. If you see it again @bdattoma, please post the logs and reopen the issue (or log a new one if you prefer).

There is nothing we can do currently with this issue.
