### ISSUE TITLE
[Bug]: Default user fallback to "kube:admin"

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now, when fetching the user, if both **oauth proxy's header** and **openshift user username** are empty the dashboard will fallback the username to `kube:admin`.

### Expected Behavior

Maybe if we cannot find the User we need to raise an exception and raise an error in the frontend.

**Comment by andrewballantyne** [comment]
RBAC is not going to work if we default to kube admin, so we need to make sure the calls to kube are made under the logged in (frontend) user, and not whomever is tied to the kube middleware. (they are the same when running locally, but not the same when on a hosted server)

**Comment by andrewballantyne** [comment]
If we fail to get the auth for the user -- we now have a failed to properly load the dashboard state. If we can get it out as a `userError` we can just not show the Dashboard.

Something like (from https://github.com/opendatahub-io/odh-dashboard/pull/447)
![Screen Shot 2022-08-26 at 6 29 13 AM](https://user-images.githubusercontent.com/8126518/187742561-fec347f2-cb27-4778-a92c-9686410cb08e.png)
