### ISSUE TITLE
[Feature Request]: Improve our Merge Checks in PRs

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#361]
### Feature description

Currently when we go to merge a PR, it does not prevent a merge when it finds an invalid TS reference. Which kinda defeats the purpose behind having TS.

I'm not sure what part of our configuration is having issues, but we did suppress it ([this was fixed](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/config/webpack.common.js#L38) for development). It is possible we just need to remove this line and that'll cause the builds to break during a PR and thus cause the CI step to fail.

### Anything else?

It should be fairly easy to test. Remove the line in one commit. In another commit cause a type issue and push that up to your PR. If the PR flags it and stops the merge, then that's our solution. Removing the commit that caused the type issue should allow the PR to merge.

**Comment by lucferbux** [comment]
It's even easier, the `test:type-check` is missing from the test command. Adding it.
