### ISSUE TITLE
[KFNBC]: User1 can spawn a notebook and then access it as User2

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when spawning a notebook from the KFNBC spawner, the nb is "assigned" to the user logged into the RHODS dashboard, e.g. if logged in as `ldap-admin1` the notebook pod / route will refer to `jupyter-nb-ldap-2dadmin1`.
However, after the spawn is complete and the user clicks on `Access server`, the user will be asked to log in with an OCP user again, and the user is able to login as a different user (e.g. `ldap-user1`).
This can be repeated multiple times, by e.g. opening an Incognito window and pasting the URL to the running notebook server.

This means that all users have the ability to log into and use another user's server. Problems arise when two users work in the same server / same notebook at the same time, as there will be conflicting changes, and the autosave feature of Jupyter will start showing popups mentioning changes having been saved already.

### Expected Behavior

Only the user who spawned the server should be able to access it, unless we are able to provide a seamless way for multiple users to collaborate on the same server/files

### Steps To Reproduce

Install RHODS 1.15 build with KFNBC
Enable KFNBC
Login to RHODS dashboard as User1
Spawn a server
Click on `Access server` after spawn is complete
In the new tab, log in as User2
(optional) copy/paste the URL in a different browser / incognito window and login as User3, User4, etc.

**Comment by samuelvl** [comment]
This will be fixed by https://github.com/opendatahub-io/odh-dashboard/pull/358
