### ISSUE TITLE
[KFNBC]: Notebook URL does not include the counter in the pod name

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When spawning a server, a pod will be created with a name such as `jupyter-nb-username-0`.
I believe this is being done to support the ability for a user to spawn multiple notebooks in the future.

However, currently the URL for a running notebook will strip the final counter from the pod name (more likely, it's using the container name inside the pod, which also strips away the counter). This will become an issue, I think, once we want to implement the multiple notebooks ability.

Example:
```
                          No counter
                              v
https://jupyter-nb-ldap-2dadmin4-redhat-ods-applications.apps.CLUSTER.e52g.s1.devshift.org/notebook/redhat-ods-applications/jupyter-nb-ldap-2dadmin4/lab
                                                                                                                                                ^
                                                                                                                                           No counter
```

### Expected Behavior

I think the URL should also include the counter in the pod name

### Steps To Reproduce

Install RHODS 1.15 build with KFNBC
Enable KFNBC
Spawn a server
look at the URL

**Comment by samuelvl** [comment]
Hey @lugi0 The reason behind the counter is because the notebook controller creates and `StatefulSet` rather tan a single pod (JH) and it identifies each replica with a different number, for example:

``` $ oc get notebook                                                     
NAME                                 AGE
jupyter-nb-user-40redhat-2ecom   14m

$ oc get statefulset                                                  
NAME                                 READY   AGE
jupyter-nb-user-40redhat-2ecom   1/1     12m

$ oc get pods       
NAME                                               READY   STATUS    RESTARTS   AGE
jupyter-nb-user-40redhat-2ecom-0               2/2     Running   0          13m
``` 

When we allow users to create more than 1 notebook we'll add some kind of ID to differentiate each notebook.

Let me know if it answers your question and I can close the issue.

**Comment by lugi0** [comment]
@samuelvl it does, thank you. I'll go ahead and close this one
