### ISSUE TITLE
[Feature Request]: Preview BYON Display When Creating Instance

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#375]
### Feature description

When Importing an image for BYON it would be great to be able to preview what the notebook will look like in the Jupyter Launcher page.

The preview could appear at the top or bottom of the modal and refresh as the user inputs data.

This would help users to see how the fields they are inputting impact what the user will see when they are completing the form.

**Comment by andrewballantyne** [comment]
@kywalker-rh This is a request to UX

**Comment by andrewballantyne** [comment]
This was brought up at the UX meeting on Aug 4th -- UX will look into what we can do to show the details when importing.

**Comment by vconzola** [comment]
@strangiato We're in the process of redesigning the Launcher page and changing how images are selected as well as how package attributes and contents are displayed. Can we run these designs by you and get your feedback?

**Comment by strangiato** [comment]
That would be great!  I sent you a message on gChat with with another person from my team that would be great to include.

**Comment by vconzola** [comment]
Yep. Got it. We need to make some tweaks to the mockups. Look for an invite late next week or early the following week.

**Comment by lucferbux** [comment]
@andrewballantyne Please move to Jira

**Comment by andrewballantyne** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAISTRAT-42
