### ISSUE TITLE
[Bug]: Missing x-forwarded-access-token header error is flooding logs

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/odh-dashboard#376]
### Current Behavior

Deploy dashboard and check out logs:

```shell
$ oc logs -l app=odh-dashboard -c odh-dashboard --tail=-1
```

The following error is constantly printed:

```
{"level":50,"time":1659113788116,"pid":68,"hostname":"odh-dashboard-5fbdbb88f7-h5n5j","msg":"Error: Error getting Oauth Info for user, Error: missing x-forwarded-access-token header. Getting the cluster info."}
```

### Expected Behavior

Do not print this error message.

**Comment by andrewballantyne** [comment]
How are we expecting this to be added? I noticed the line of code that had issues with it when I was writing in my current PR... it's expecting a bearer token to come from the client dashboard?

**Comment by samuelvl** [comment]
@andrewballantyne The bearer token is passed from the oauth proxy to the dashboard in the `x-forwarded-access-token` header

**Comment by maroroman** [comment]
@lucferbux I think you worked with this area of code

**Comment by accorvin** [comment]
I'm pretty sure that this is being generated from our blackbox probes of the dashboard. When the probe sends a request to the dashboard, it's not currently sending any authentication information. I'm working on addressing this.

**Comment by accorvin** [comment]
I see from this line: https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/userUtils.ts#L7 that we're looking for a header `x-forwarded-access-token`.

Looking at the OAuth proxy code, https://github.com/openshift/oauth-proxy/blob/master/README.md?plain=1#L128 it appears that the proxy will send the header (when configured to do so, which I think we currently aren't) in the format `X-Forwarded-Access-Token` (note the case differences).

When I configure the OAuth proxy to send this header in dev, I'm still seeing this error message in the dashboard pod logs, which makes me think the case difference might be an issue. I'm not sure how to test a change to the dashboard to confirm this hypothesis. Anyone want to help me out?

**Comment by samuelvl** [comment]
> It appears that the proxy will send the header (when configured to do so, which I think we currently aren't)

We [retrieve the username](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/userUtils.ts#L23-L45) by using the `X-Forwarded-Access-Token` so [we are already sending it](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/overlays/authentication/deployment.yaml#L13).

> I'm not sure how to test a change to the dashboard to confirm this hypothesis.

You can try making the change in the code and [build an image with the changes](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/CONTRIBUTING.md#build).

**Comment by lucferbux** [comment]
We've find the problem, both **liveness** and **readiness** probes are hitting the `/status` endpoint. I would suggest creating a new path only for the probes. something like `/probes`. What do you guys think? @samuelvl @accorvin @andrewballantyne

**Comment by accorvin** [comment]
@lucferbux why wouldn't we just change the existing `/status` endpoint to not require auth? Is it used for other existing purposes that do require auth?

**Comment by lucferbux** [comment]
@accorvin  yeah, it's used to retrieve the status of the application, and there are several features (such as getting the username) that need the auth

**Comment by lucferbux** [comment]
@accorvin my main point is that we shouldn't use an endpoint with logic as a probe, it's a waste of resources, I would either move the logic away from the `/utils` endpoint to another one or just create a new path for the probes.

**Comment by accorvin** [comment]
@lucferbux I think I agree with that statement for the readiness and liveness probes, but for the sake of discussion I want to raise a possible counterpoint (that is probably best illustrated using the notebook spawner page as an example):

The notebook spawner page does a lot when the user hits it (e.g. lots of queries to the cluster to get the list of images, available cluster resources, etc.) If something with this functionality broke, the user would have a bad experience, so we want our monitoring to catch it. That means that either the liveness, readiness, or blackbox exporter probes need to detect this failure scenario.

We could:
1. Have all three probe types query the same endpoint, where that endpoint exercises a lot of the backend functionality of the page. To your point, this would consume a lot of resources, but this option does have the benefit of potentially self-healing when issues occur that could be resolved by a simple pod restart.
2. Have the readiness and liveness probes query an endpoint that does not exercise backend functionality, but have the blackbox exporter probe the application endpoints that _do_ require backend code execution. This is less resource intensive, but would trigger an alert that SRE would need to manually action upon.

**Comment by andrewballantyne** [comment]
Just to add here -- the `GET /status` endpoint does not do anything useful for checking if we have things configured probably for UI functionality. The best it can give is if the user is not properly configured to have access to the dashboard.

```
{
  currentContext,
  currentUser,
  namespace,
  userName,
  clusterID,
  clusterBranding,
  isAdmin,
  isAllowed,
}
```
The data is pretty rudimentary. The `getUser` logic behind finding out if they are an `isAdmin` / `isAllowed` access based on group configurations is what causes the `x-forwarded...` header check. 

---

To the point at hand... I discourage (slightly today, stronger as we get closer to the end of the year) making a new endpoint that serves a singular purpose to be for probes with or without logic that is backend resource intensive. We have long term goals to be a Plugin in the HAC world and we need a pure k8s interface for that (at least today). #259 serves to bring that into the app -- but needs to wait for the Data Science Grouping work because the user has weird namespace access today and that needs to be cleaned up before we can move to a pass through API.

If we need to setup something for probes for the next 6-ish months (theoretically) as we move to the SDK/pass-through API -- I'm okay with it. I would not recommend it being a heavy coded endpoint if we can avoid it.

**Comment by andrewballantyne** [comment]
That works for me -- the config is a good fetching point for a quick status. Better than a custom one that serves no Dashboard UI related effort.

Should be noted, that endpoint will also be moved to the client as part of the on-going pass through API work. But for now that seems good to me.

**Comment by accorvin** [comment]
If I follow correctly, I think we're saying we should change the blackbox probe to query the /api/config endpoint of the dashboard. Is that right?

cc @atheo89
