### ISSUE TITLE
[KFNBC]: Launcher can only launch Jupyter-based images

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The logic for the launcher is at the moment purely focused on Jupyter Notebooks. It introduces many things in the Notebook definition (and then the Pods) that may not be relevant for every custom images, like some env vars, or make them simply unusable like readiness and liveness probes (because of course there is nothing to answer at the specified address).
As a concrete example, a perfectly legit image for the Notebook Controller may not work because the readiness/liveness probes injected by our launcher/dashboard check for a non-existent API, therefore preventing the Pod to reach running state. At the moment, the probes are hard-coded there: https://github.com/opendatahub-io/odh-dashboard/blob/14a2e2f33e2439c9fe143be3dfaf878b8a39e586/frontend/src/services/notebookService.ts#L112

### Expected Behavior

In a more general way, here are the items that should be customizable per type of image if we want to enable the full power of custom images (or simply let users work with their own material, as the Notebook Controller was designed for):
- Readiness and Liveness probes: using different services or mechanisms.
- User PVC mount point (could be different than `/opt/app-root/src` which is the current norm only because of the S2I support in our general images). Some images may even want to disable this user PVC.
- Supplementary mounts: other volumes and mount points should be allowed. It was the case previously with the single-user profile mechanism that allowed to do this through a simple ConfigMap.
- Environment variables: different of supplementaty ones should be configurable.
As there may be too many parameters to take into account, including fool-proofing future ones, a simple method could be to allow a ConfigMap with the same name as the ImageStream to keep all of these configurations. Then instead of hard-coding the Notebook configuration [here](https://github.com/opendatahub-io/odh-dashboard/blob/14a2e2f33e2439c9fe143be3dfaf878b8a39e586/frontend/src/services/notebookService.ts#L62) , it could be retrieved on a per-case bases. The existing value could be the default, replaced by the content of the relevant ConfigMap if indicated as such in the ImageStream (maybe an annotation with the name of the CM to use for Notebook stub).

Using different types of images (RStudio, VSCode,...) also has impact on the UX. Currently, the launcher has only one tile "Jupyter", leadind to the selection of the image to launch. Which may not be Jupyter at all... We have different choices here:
- have different tiles for the different tools. Drawback is that it forces to duplicate/customize the Start page for each of those images (that we may not know in advance).
- change the launcher entry name for "Notebooks" or "Servers" (original KF naming), and keep the Start page identical, putting all the "notebooks" images accessible from there. Drawback: change of tile Icon, name, and description to include the fact that it may be more than Jupyter images.

**Comment by samuelvl** [comment]
Moved to `kind/enhancement ` since this is a new feature that wasn't initially planned in https://github.com/opendatahub-io/odh-dashboard/issues/213

**Comment by guimou** [comment]
Compatible images can be created without modifications, as done here: https://github.com/opendatahub-io-contrib/workbench-images/releases/tag/2023b_2023-02-01
Some points are still valid (custom mountpoints, dedicated launch tiles,...), but they are already followed in other issues.
