### ISSUE TITLE
[Bug]: GPU will crash the whole app

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After #288 got merged, the app will crash if you go to the spawner page.
You will see the error message like
```
Error: getaddrinfo ENOTFOUND thanos-querier.openshift-monitoring.svc.cluster.local
[dev:backend ]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[dev:backend ] [nodemon] app crashed - waiting for file changes before starting...
[dev:frontend] [HPM] Error occurred while trying to proxy request /api/gpu from localhost:4010 to http://localhost:4000/ (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
And the page will be soon unavailable:
<img width="1904" alt="Screen Shot 2022-08-04 at 1 45 06 PM" src="https://user-images.githubusercontent.com/37624318/182917326-826487a5-4a76-4911-b420-9c9de0339549.png">

### Steps To Reproduce

1. Fetch the latest code
2. Go to the notebook controller
3. Wait for ~20 seconds

### Workaround (if any)

No

**Comment by andrewballantyne** [comment]
I have tested my cluster with this issue and it does not crash. Although still of high importance to fix, I'm not sure if it's a blocker -- it seems to be dependant on cluster setup
