### ISSUE TITLE
[Feature Request]: Remove Python 2 dependency

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/odh-dashboard#399]
### Feature description

In order to improve our building process we should find a way to not require installing python 2:

https://github.com/opendatahub-io/odh-dashboard/blob/aaebc79eb2b24d7024e4e97e9b95b75e70eb764c/Dockerfile#L27

Python 2 is needed because it is a dependency of [node-gyp](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/package-lock.json#L11757-L11783) which is required by [node-sass](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/package-lock.json#L11862-L11884).

[Node-sass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated), finding an alternative library may not require Python 2.

**Comment by maroroman** [comment]
We can try using dart sass instead: https://sass-lang.com/dart-sass

**Comment by andrewballantyne** [comment]
I believe we solved this via the `sass` library.
