### ISSUE TITLE
[Bug]: JupyterHub tile in Explore section of dashboard

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Explore section of the dashboard, the Jupyter tile is still called `JupyterHub`

### Expected Behavior

Should be called Jupyter

**Comment by samuelvl** [comment]
Increasing priority to high since this is a requirement for https://github.com/opendatahub-io/odh-dashboard/issues/213
