### ISSUE TITLE
[Bug]: No alternative to JupyterHub API present

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is currently no replacement for the JupyterHub API page/endpoints for KFNBC

### Expected Behavior

There should be an equivalent API page/endpoints

**Comment by andrewballantyne** [comment]
This is unlikely to be something we will do. We are talking to Kube, so there isn't an API for us to share with you. Currently we are using a note server to do this (so today we can do this) but in the near future (#259) the server will just be a pass through API and thus we will not have any API visible to external users.

**Comment by andrewballantyne** [comment]
If this is a need @lugi0 we can discuss this further -- but as it stands this won't be done.

**Comment by lugi0** [comment]
I guess I only opened this bug because our aim is `to have feature parity with existing JH functionality while utilizing the KFNC backend capabilities.`, as per #213.
As long as @jedemo @jkoehler-redhat and others are ok with dropping this functionality I don't personally see a need to reimplement something equivalent
