### ISSUE TITLE
[BYON]: Impossible to update custom notebook image source

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once an image has been imported, there is no way to update its source.

When a custom image is updated in its source repo (eg quay.io), like with a new tag, there is no way to update its definition in the UI to use this new tag. Using a "latest" tag and update it in the source repo is not an option as:
- You may not want to use the tag "latest", which has some impact on not always exactly knowing what you're running.
- Even if you move the tag "latest" in the source repo, it is not picked up automatically by the ImageStream. Once the sha signature of the source image has been imported in the ImageStream, it is never updated until you force it.

### Expected Behavior

Ability to modify the image source for a custom image in the UI.

### Steps To Reproduce

- Import a custom image
- Want to modify the image source, like pointing to a new tag
- No way to do that in the UI

### Workaround (if any)

Modify the image source (tag) directly in the image stream.

Btw, I understand the need for unicity in the byon Image Streams, but could we simply append a uuid to the name of the image when naming the Image Stream instead of totally obfuscating the name? When someone will have tens of custom images, or even two, and want to check the ImageStream, good luck finding which is which...

**Comment by samuelvl** [comment]
Moved to `feature/byon` project

**Comment by lucferbux** [comment]
@andrewballantyne Could you move this to jira please?

**Comment by andrewballantyne** [comment]
Moved to Jira: https://issues.redhat.com/browse/RHOAISTRAT-43
