### ISSUE TITLE
[Feature Request]: GPUs for Auto Scaling

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#407]
### Feature description

We need to support a GPU dropdown that detects availability of auto-scaling and present that option to the user.

Jeff noted some of his thoughts on how the GPU dropdown will work in #301 ([comment](https://github.com/opendatahub-io/odh-dashboard/issues/301#issuecomment-1192576547)).

When the user cannot get the GPU count or in fact there are zero usage on the given server, we need to show the disabled state still. Otherwise we'll need to allow them to scale up to whatever the max GPU allowed is (but making it clear that some are available - if any - and others are unavailable and doing so will cause a wait for availability).

### Describe alternatives you've considered

We may need UX to look at what the items in the dropdown say -- maybe something like:
```
0
1
2 (unavailable - can auto-scale)
```
May be a bit winded, perhaps a dropdown or something also.

### Anything else?

RHODS ticket: https://issues.redhat.com/browse/RHODS-4617

**Comment by andrewballantyne** [comment]
This work was never started. Removing @maroroman from assignee.

**Comment by maroroman** [comment]
Forgot to provide status updates, sorry about that. Reassigning this back to myself and focusing on this issue.
