### ISSUE TITLE
[Feature Request]: Break Client Routing Into Accessible Chunks

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#408]
### Feature description

As I noted in a [comment here](https://github.com/opendatahub-io/odh-dashboard/pull/385/files#r939056083), I think we should look to break up our routing into three sections.

1. ~~Authed but not "allowed" users -- this can be used to be landing pages and resources to help people see what we do but they can't do any create/manipulation/deletion of resources~~ We have since disabled this feature -- you're either allowed or not.
2. Allowed users -- once they are authorized by OAuth, we allow them access to everything they have access to create Notebooks or projects or what have you -- we can also narrow as a secondary filter, by using `useAccessReview` (from [OpenShift Console](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/rbac.tsx#L107)) to hide UI elements when the user does not possess the ability to do those actions (as the k8s call will fail anyways)
3. Admin users -- everything green under the sun, no restrictions

In our Routing, we can use component composition to just mount portions of the router in different spots -- globally disabling it at one level thus preventing any of those routes mounting -- any bookmark or direct navigation will end up in 404 (we can maybe look at auth checks & 403 wrapper pages if they have Dashboard access but do not have k8s access)

I think this will help us stay clean as more UI elements get added moving forward.

**Comment by andrewballantyne** [comment]
When we do this work, we should take the loading logic in https://github.com/opendatahub-io/odh-dashboard/pull/447 and move it into its own component (with the fetching logic for user).

App structure can be something like:

```
<App>
  <LoadUser> // << new, put the `detectUser` logic in here and handle the loading state and error state within
    <AppContext.Provider>
      <Page ...>
         ...
      </Page>
    </AppContext.Provider>
  </LoadUser>
</App>
```

**Comment by andrewballantyne** [comment]
We should also consider mounting our own custom `<Route`  -- where we implement an Error Boundary component (see [React docs](https://reactjs.org/docs/error-boundaries.html)) along with permission checking. Make it nice to add new routes.

**Comment by lucferbux** [comment]
@andrewballantyne Please move to jira

**Comment by andrewballantyne** [comment]
Moved to Jira: https://issues.redhat.com/browse/RHOAIENG-944
