### ISSUE TITLE
[Bug]: Update OCP username scrubbing to support any special character that may break DNS domain names

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When OCP usernames have special characters we will need to translate those characters to a valid character code that adheres to the Kubernetes Object name standards that require object names to meet the DNS name format.

The current [code](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/utilities/notebookControllerUtils.ts#L33) only translates `-@.:` and we should be handling all possible special characters for the default encoding

See https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

NOTE: Original issue was discovered in JupyterHub UI but we should be accounting for this in the dashboard UI

### Expected Behavior

Any username are converted to a valid string that meets DNS naming formatting

Mozilla JavaScript [uriEncode()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

### Steps To Reproduce

1. Create openshift user with special characters.
     Example: iam#foo+bar@odh.io
2. As the user, login to ODH Dashboard and attempt to spawn a notebook
3. Check that any k8s objects the odh-dashboard creates with the username is not created correctly

### Openshift Version

4.10

### Open Data Hub Version

```yml
ODH 1.3
```

**Comment by andrewballantyne** [comment]
I think we may need to go further than this @LaVLaS.

Encoding URI Components gets you to `A-Z a-z 0-9 - _ . ! ~ * ' ( )` -- k8s names only allow `contain only lowercase alphanumeric characters, '-' or '.'` and have a name limit -- which could be problematic for our generating files if somehow a user has 200 character length name (likely not a problem though lol).

- JS Encoding characters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description
- K8s name characters: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
