### ISSUE TITLE
[Feature Request]: Strengthen our OdhDashboardConfig CRD

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#420]
### Feature description

Our CRD is weak in forcing structure (almost no properties are required, including `spec` -- some nested ones are). To that extent we have to write code that assumes you can make invalid structures inside the CRD by omitting required parts and what if they chose not to add "ALL" of the options. It's a bit erroneous. 

Properties I'd like to see enforced (any part of the tree not mentioned is optional):

- `.spec`
- `.spec.groupConfig.adminGroups`
- `.spec.groupConfig.allowedGroups`
- `.spec.notebookController.enabled` true or false if you're including this block seems logical

Up to debate if we want these -- personally I find it odd if they are omitted, seems lackluster of a Notebook Size to not have a Size. Maybe limits are optional? I guess if you only wanted to limit CPU or Memory, and not both -- then this is probably accurate as-is. It's odd `resources` and its shared sibling property `name` are required (they are the only ones in the config that are) -- seems odd that `resources` would be empty though.
- `.spec.notebookSizes.[].resources.requests`
- `.spec.notebookSizes.[].resources.requests.memory`
- `.spec.notebookSizes.[].resources.requests.cpu`
- `.spec.notebookSizes.[].resources.limits`
- `.spec.notebookSizes.[].resources.limits.memory`
- `.spec.notebookSizes.[].resources.limits.cpu`

These are unused -- probably could be removed instead of making them required. the `gpuConfig` and `envVarConfig` are not used in the codebase.
- `.spec.notebookController.gpuConfig.enabled`
- `.spec.notebookController.envVarConfig.enabled`

We'd have to update our backend & frontend types to match the structure we provide so we are aligned both on-server and in-code. 

`.status` can be ignored as it is intended to be migrated as part of #416 

### Anything else?

Eg:
```
     schema:
        openAPIV3Schema:
          description: // some description of the CR
          type: object
          required:
            - spec
          properties:
              // etc
```

**Comment by samuelvl** [comment]
I'm fine with #&#x2060;1  (enforce spec) and #&#x2060;3 (remove unused).

Regarding #&#x2060;3 I think we should follow kubernetes schema -> https://pkg.go.dev/golang.org/x/build/kubernetes/api#ResourceRequirements This is, any requests/limits combination is allowed (including empty limits or requests). But I agree on if `.name` is defined, `.resources` should be required too, at least with an empty value `{}`. 

- `.spec.notebookSizes.[].name` required.
- `.spec.notebookSizes.[].resources` required.
