### ISSUE TITLE
[Feature Request]: Add support for cusomization of notebook pod nodeAffinity in the config

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#425]
### Feature description

In #406, we added the default application of `nvidia.com/gpu` for any non-gpu nodes.  The current implementation is hardcoded for a specific deployment scenario with no support for disabling it or providing user customization.

I think a Dashboard/notebook admin should be able to to manage:
1. If/when`nodeAffinity` is applied to a pod
2. What `nodeAffinity` expression is applied

If the Dashboard designated two states for the application of  `nodeAffinity` and `toleration` to `gpu-notebook` and `non-gpu-noteook` then you can apply the proper values/expression based on admin input.  Affinity/toleration would be applied if any value was found in the DashboardConfig

### Describe alternatives you've considered

No alternatives since the dashboard does not currently support user input of notebook configuration beyond Image, Size and ENV var

### Anything else?

N/A

**Comment by andrewballantyne** [comment]
Converting this to a bug -- we shouldn't have added a feature that does not always apply. We need to be able to sub-configure this item.

cc @LaVLaS do we think this should be a UI toggle-able thing? Or can an entry in the ODH Dashbaord Config work?

I assume this is critical for 1.16? cc @jkoehler-redhat

**Comment by jkoehler-redhat** [comment]
@cfchase thoughts on priority?

**Comment by cfchase** [comment]
It looks like non-gpu pods prefer non-gpu nodes, which seems like a reasonable default for 1.16 and I don't think there's a risk leaving it this way.  I would like to see the feature of adding affinity along with tolerations, but I don't think it's required for 1.16 and would require changes to the OdhDashboardConfig CRD and it's late for that.

**Comment by samuelvl** [comment]
I don't think this is a bug, it is fully compatible with an environment with no GPUs:

1. GPU environment ->  Normal notebooks are scheduled on non-GPU nodes.
2. Non-GPU environment -> Normal notebooks are scheduled on any node (except masters).

I like the idea of making affinity configurable but to me this is not a bug, I understand this is similar to https://github.com/opendatahub-io/odh-dashboard/issues/338 but with affinities.

**Comment by dgutride** [comment]
Moving to closed based on all of the accelerator work done at the end of 2023 - if this is still an issue, please reopen in jira (or tag me and I'll move it).
