### ISSUE TITLE
[Feature Request]: About Page -- Version of ODH/RHODS/Etc

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#427]
### Feature description

Currently today our UI does not say anything about what version it is. Should this be something we add?

OpenShift Console has an about modal with versions:
![Screen Shot 2022-08-19 at 4 00 18 PM](https://user-images.githubusercontent.com/8126518/185698043-c2c6b42f-e330-4841-a223-5134a658eccf.png)
![Screen Shot 2022-08-19 at 4 00 23 PM](https://user-images.githubusercontent.com/8126518/185698047-bb33aed6-860a-4147-8df2-e3312753cc59.png)

Did we want something similar for ODH (configurable of course).

### Anything else?

The how we do it will be up to debate. We could use the `OdhDashboardConfig` to store the value... we could try to derive it from some other value? If we don't get it we can omit the about modal?

Did we want to add anything else to the about modal?

Technically speaking, we'd just use the [PF About Modal](https://www.patternfly.org/v4/components/about-modal). The content is the only question.

**Comment by andrewballantyne** [comment]
cc @cfchase @LaVLaS @jkoehler-redhat @jedemo @kywalker-rh

**Comment by jkoehler-redhat** [comment]
I believe there are discussions on this with move to on prem.  Will keep this in mind.

**Comment by andrewballantyne** [comment]
Going to bring this back up to the UX meeting on Thursday -- this feels more important these days; especially with upstream adoption and how we only expose the Operator version and not the Dashboard one. ODH 1.4.0 has what version of the Dashboard? Now we are on 1.4.1 -- what does it have?

I think we need something like this soon-ish to help guide things forward when it comes to the Dashboard features.

**Comment by andrewballantyne** [comment]
@kywalker-rh after the UX meeting it sounds like this is a go -- we'll just need to know what items you'd like to add to the modal.

**Comment by lucferbux** [comment]
This has been stale for a while? It's still a `field-priority` task so it would be nice to plan ahead for this sooner than later.
We talked about this in a UX Meeting at the beginning of this year, any thoughts on the outcome @kywalker-rh @vconzola ?

**Comment by jstourac** [comment]
This is something that would be really nice to have IMHO.

At least fields for ODH/RHODS version, Update channel, License information in case of RHODS, optionally also the OpenShift and Kubernetes versions may also be useful.

**Comment by dgutride** [comment]
Moving to closed - if UX would like this, please recreate on UX board.

**Comment by dgutride** [comment]
Create RFE - this is critical for developer debugging (even if the field doesn't need it).

**Comment by ralombar** [comment]
Moved to Jira: https://issues.redhat.com/browse/RHOAIUX-26

**Comment by ralombar** [comment]
@dgutride Shall I close this issue? It has been moved to Jira

**Comment by dgutride** [comment]
Yes - we can close it.
