### ISSUE TITLE
converge red-hat-data-services fork

### ISSUE THREAD

**Issue by durandom** [opendatahub-io/odh-dashboard#43]
Most of the active development seems to be happening in https://github.com/red-hat-data-services/odh-dashboard which is as of now 39 commits ahead of this upstream version.
The red-hat-data-services fork can expose additional content like tutorials via the [data](https://github.com/red-hat-data-services/odh-dashboard/tree/63e63ef511e50188da45288c2aa109e9f83d7b02/data) directory.
This is useful for other installations of ODH, like https://www.operate-first.cloud/

Unfortunately, the configuration of the widgets in the data directory is maintained right in the repository, which makes it hard to install a version with a different set of widgets

**Comment by andrewballantyne** [comment]
The gap is larger now. @LaVLaS do you have information here? What's the effort behind aligning RHODS... I thought our branching strategy from a week or so ago would have aligned the two repos.

**Comment by andrewballantyne** [comment]
@LaVLaS I think with 1.15 this is no longer the case, right?

**Comment by andrewballantyne** [comment]
Comparing against the `main` branch of RHODS, we are not behind by that much (likely the last weeks worth of effort). I do not believe this is still an issue as we have moved away from a custom cherry pick to a standard fast forward the upstream repo.

If I am wrong on this front, feel free to reopen the ticket.
