### ISSUE TITLE
DSG Requirements

### ISSUE THREAD

**Issue by jkoehler-redhat** [opendatahub-io/odh-dashboard#433]
General Mocks -- https://marvelapp.com/prototype/afa716d/screen/88098906
Workspace Creation Options -- https://marvelapp.com/prototype/e0d1f41/screen/88329650

## Requirement 1

P0: Ability to view and create multiple projects from the dashboard.

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/449
- https://github.com/opendatahub-io/odh-dashboard/issues/450
- https://github.com/opendatahub-io/odh-dashboard/issues/451

## Requirement 2

P0: Ability to view and create one or more "workspaces" (NB server sessions) from within a single project. Notes:

- workspaces may be active (running) or idle.
- system must support multiple active workspaces at the same time
- workspaces UI should provide at least the same options available when starting a Jupyter NB session via the tile on Enabled tab ("spawner UI"). This includes out-of-the-box and custom NB images, container sizes (utilize any ConfigMap/settings options), GPUs (if applicable), environment variables. 

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/483
- https://github.com/opendatahub-io/odh-dashboard/issues/485
- https://github.com/opendatahub-io/odh-dashboard/issues/674
- https://github.com/opendatahub-io/odh-dashboard/issues/661
- https://github.com/opendatahub-io/odh-dashboard/issues/662

## Requirement 3

P0: Ability to view and create one or more data sources for a project.

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/490
- https://github.com/opendatahub-io/odh-dashboard/issues/486

## Requirement 4

Ability to connect to the following data sources:

- P0: PV
- P0: Object storage / S3
- P1: Starburst
- P2: RHODA connectors
- P2: Nooba / multi-cloud gateway

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/492
- https://github.com/opendatahub-io/odh-dashboard/issues/491

## Requirement 5 

P0: Ability to delete projects

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/493

## Requirement 6

P0: Ability to delete workspaces

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/494

## Requirement 7

P0: Ability to delete data sources associated with a project

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/495

## Requirement 8

P0: Users must be able to access Jupyter notebook sessions via tile on Enabled tab (existing functionality).

- The intent is that the projects option is an alternate method for access Jupyter NB sessions. But users must be able to continue to access via Jupyter tile. 

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/484
    - Likely not to be done, this was to upgrade the old Spawner but there are complications with current infra and it will not be an easy undertaking -- the older notebook design will remain and satisfy this requirement

## Requirement 9

P0: Ability to connect workspaces to a new PV or existing PV.

Issues:

- https://github.com/opendatahub-io/odh-dashboard/issues/496

## Tech Work

- https://github.com/opendatahub-io/odh-dashboard/issues/259
- https://github.com/opendatahub-io/odh-dashboard/issues/668

**Comment by andrewballantyne** [comment]
Forgot to close this. Merged as part of https://github.com/opendatahub-io/odh-dashboard/pull/689
