### ISSUE TITLE
Admin UI Requirements

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#436]
# Admin UI for RHODS configuration and settings

## Issues

- Admin UI for admins to configure NB container sizes
    - https://github.com/opendatahub-io/odh-dashboard/issues/1799
    - https://github.com/opendatahub-io/odh-dashboard/issues/1832
- Admin UI for mapping RHODS groups

## Description

As a RHODS admin, I need to be able to configure RHODS for use with the settings that match my organization's needs.

Note: The settings items would apply across the cluster.

## Requirement 1
P0: Setting for culling idle notebooks (# of minutes to keep pod up after user stops NB server). Default is 0 or no culling of idle notebooks.

## Requirement 2
P0: Ability to map RHODS allowed/user group and admin group to defined groups
(without having to edit config map).

## Requirement 3
P0: Ability to configure custom NB sizes (aside from OOTB sizes).
P1: Ability to configure which NB sizes are available for selection.
P2: Ability to configure default PVC size for users. Ability to restore system default.

## Requirement 4
P0: Ability to edit opt in/out for specific notifications and user emails that should receive notifications.

## Requirement 5
P0: Ability to edit opt in/out for sending user interaction data.

## Requirement 6
P0: If Red Hat modifies default values (eg. default PVC size) in a future release, the defaults should only be updated if an admin hasn't changed the default. For example, if the system default for PVC size is 20 GB and an admin changes to 40 GB, then Red Hat updates the default to 30 GB, the change should only apply to clusters that still have the original default value.

## Requirement 7
P2: Ability to export config settings and import to another environment. Use cases: organization with multiple clusters.
TBD: Ability to configure log out period for users. For example, we will set a default, but admins should be able to modify the default. Ability to restore default. Note: this capability exists in OSD today.

## Notes

* In the future, we could include additional groups/permissions capabilities: 1) define access rights for groups (eg. ability to access specific OOTB images or create specific sizes); 2) define custom groups and define access rights (eg. group that can access Seldon).
* We expect some of the custom notebooks functionality to be limited to admins. That will be addressed in the custom notebooks epic.
* Admins should be able to configure tolerations for Jupyter notebooks. That will be addressed in a separate linked story.

**Comment by andrewballantyne** [comment]
This will be properly tracked when it's on the roadmap again -- requirements slip, it's been a while since this was looked at and we have changed the way we track items now -- seems more headache to keep this floating than to just redo it when the time comes.

**Comment by dgutride** [comment]
Migrated to jira:  https://issues.redhat.com/browse/RHOAIENG-333
