### ISSUE TITLE
[Bug]: Communication with segment.io is blocked by Mozilla Firefox

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the web browser Mozilla Firefox, the communication between Dashboard and segment.io is blocked in downstream, probably because of [Enhanced Tracking Protection mechanism](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop).
It may not a issue in ODH bits, but it affects the  monitoring and usage data collection. 
Filing this issue to understand if we want/need to take an action. If so, then investigate if there's a workaround we can provide to customers or a permanent solution

### Expected Behavior

Segment’s `analytics.js` to be enabled and not blocked by any browser.

### Steps To Reproduce

1. Enable Usage data collection from Dashboard
2. Connect to segment.io (ensure you correctly configured the rhods-segment-key secret)
3. check if events are tracked

### What browsers are you seeing the problem on?

Firefox, Safari

**Comment by DaoDaoNoCode** [comment]
This is interesting, I am wondering whether we should do a version bump to use `analytics-next` package instead of the current one because the current one is outdated and the new version has better support for React. Maybe after bumping the version and refactoring the tracking functions the problem could be solved, we will see.

**Comment by DaoDaoNoCode** [comment]
Found some explanations here https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/supported-browsers/#tracking-protection-itp-etp

**Comment by dgutride** [comment]
This is still a potential issue - moving to: https://issues.redhat.com/browse/RHOAIENG-3984
