### ISSUE TITLE
[Feature Request]: As an Admin on KFNBC -- I want to view a users notebook settings

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#441]
### Feature description

When I am logged into the Dashboard as an Admin and I navigate my way to the Administration Tab of the KFNBC -- I can see notebooks running. I can even stop it if I want. But I don't get to see what the settings are behind that notebook.

Let me describe the current view of what we have in KFNBC.

This is what I get to see about MY Notebook (as an admin or not):
![Screen Shot 2022-08-25 at 4 18 36 PM](https://user-images.githubusercontent.com/8126518/186760774-d6c00f59-612f-4694-88ad-632a94c97cf4.png)

As an admin, I can also see what notebooks are running:
![Screen Shot 2022-08-25 at 4 18 46 PM](https://user-images.githubusercontent.com/8126518/186760778-56081b11-c224-4f54-83fa-e4094ed3ddec.png)

I can even start notebooks for those who do not already have them running:
![Screen Shot 2022-08-25 at 4 18 58 PM](https://user-images.githubusercontent.com/8126518/186760779-6ac076d1-e119-4d61-93c5-e9fe46e3856b.png)

I however, cannot view the notebook details of one that is already running (that is not me).

I believe this is an easy feature to give the user -- the code should just work, we just need a UI element to make that happen.

### Describe alternatives you've considered

The data is all in the Notebook -- which we technically have access to since we are showing the running status. I think it would be great to allow them to navigate to the view page -- as if it was their Notebook

### Anything else?

This should be approved by UX (and not disagreed with by PM -- it should be so low of an effort from Dev that it just needs to be signed off on).

**Comment by andrewballantyne** [comment]
@kywalker-rh @vconzola @jedemo

**Comment by jedemo** [comment]
This makes sense to me. I can see the utility of this. Thanks for the suggestion.

**Comment by andrewballantyne** [comment]
Thanks Jeff. Just need some input from UX, do we show "view" by default & hide stop under a kebab? Vice versa? Or both under a kebab? Or... crazily, both back to back in the same table column?

So many options 🙂

**Comment by kywalker-rh** [comment]
Let's go with @andrewballantyne's first option to change "Start" to "View" when running and put Stop under a kebab. This matches typical RH UX by putting the destructive action under a kebab to prevent accidental clicks.

For the record, I have also asked Katie for thoughts on the column label. "Server status" doesn't quite fit the column at this point, so I'm proposing "Actions" instead (but that doesn't necessarily fit this issue either, so we can make that change separately if needed).

![Screen Shot 2022-08-30 at 4 24 04 PM](https://user-images.githubusercontent.com/53235442/187536812-bdb57804-505b-4882-bcfe-91139c7e1c6d.png)

**Comment by andrewballantyne** [comment]
That works for me, if Katie feels otherwise, we can make the call to change the name. But we can go with this for now.
