### ISSUE TITLE
[Bug]: Error shows when changing default PVC Size

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

> We observed that while changing the PVC size from RHODS dashboard. Error msg is observed. This only occur when your 'Stop idle notebooks' set to 'Do not stop idle notebooks'.Even with the error when we try to spawn a new notebook it create PVC size which was set. From what we understand it's an UI issue.

Discovered during testing of 2.1 ([origin](https://github.com/red-hat-data-services/odh-deployer/pull/257#issuecomment-1227294871))

### Expected Behavior

No errors should happen, partial saving of the page should be possible.

### Steps To Reproduce

> This only occur when your 'Stop idle notebooks' set to 'Do not stop idle notebooks'

### Workaround (if any)

The workaround:
> 1) Toggle the tolerations checkbox on/off
> 2) Save nothing else

You should be safe to get around this issue now. It’s a failed default for the tolerations “card” data… so when it tries to operate on the server it fails to interact with this missing data

### Open Data Hub Version

```yml
2.1
```

**Comment by andrewballantyne** [comment]
The issue appears to be an initial state problem with the tolerations UI. There is no default when you first reach this page. So the data sent to the server is an omission to the `notebookTolerationSettings` property -- and then it tries to do a `.enabled` on it and it throws an `undefined` error.

**Comment by jgarciao** [comment]
This bug is important for us because it prevents users to properly set their dashboard settings. More info at RHODS-3624
