### ISSUE TITLE
[DSG]: Allow adding projects (multi support)

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#450]
### Feature description

#449 will get us routes to the page, once we are here we need to allow for multiple projects to be created. 

- Support the ability to add a project ([Mocks](https://marvelapp.com/prototype/afa716d/screen/88098876))
    - And the two field modal ([Mocks](https://marvelapp.com/prototype/afa716d/screen/88098875))
    - If #449 is not completely merged by this time, simply handle the modal -- mount the open action however you like and we can clean it up later
- Render the project in a multi-list view ([Mocks](https://marvelapp.com/prototype/afa716d/screen/88098883))
    - "Data science workspaces" is just Notebooks today, render a status with a toggle
    - Don't worry about the right side of the table (Serving Status + the Kebab), just omit those from your work
    - Should support pagination

**Comment by maroroman** [comment]
@andrewballantyne Do we want to divide this into backend and frontend PRs, or should it be covered by a single PR?

**Comment by andrewballantyne** [comment]
I suspect not -- https://github.com/opendatahub-io/odh-dashboard/issues/259 should look to eliminate the need for backend work to manage this.
