### ISSUE TITLE
[Bug]: Dashboard pod logs do not report some expected errors when they happen

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are 3 conditions where the dashboard pods used to report errors:

1. Admin group does not exist (i.e., failed to retrieve group .. , might not exist)
2. Admin group set to "system:authenticated" (i.e., it is not allowed to set system:authenticated as admin group")
2. Dashboard Config CRD got deleted (i.e., failed to retrieve Dashboard CR groups configuration")

Now the error reporting for those 3 cases is not triggered anymore. 

Even 1 and 2 are not use cases anymore (since User Mgmt UI has replaced config maps), the errors should be triggered in case someone manually change the CRD (for any reasons..)

Besides, it seems like the code for reporting those error messages is still present: https://github.com/opendatahub-io/odh-dashboard/pull/270/files 

### Expected Behavior

All these errors should be logged.

### Steps To Reproduce

1. set adminGroups specification in odh-dashboard-config CRD to an inexistent group 
2. check the logs in dashboard pods
3. set adminGroups specification in odh-dashboard-config CRD to "system:authenticated"
4. check the logs in dashboard pods
5. delete the odh-dashboard-config CRD 
6. check the logs in dashboard pods

**Comment by lucferbux** [comment]
> I can reproduce the first issue, but cannot reproduce the second and third one. The dashboard config is overwritten and patched automatically. For example, if I set the admin group to `system:authenticated`, it will be automatically removed and there will be only a group with an empty string, and the error log will go back to the first one. It's the same with the third issue, if I remove the whole group config section in the dashboard config, it will be automatically added back. Can you verify this? @lucferbux

Yes, I think I didn't detail the issue quite well back then, the main problem here is that in 2 and 3, we override `DashboardConfig` but we throw the same generic error, and if I can recall correctly, wasn't ideal.
The logic is detailed here: https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/routes/api/groups-config/groupsConfigUtil.ts#L53-L81 and as you can see we try/catch all these flows in the same place so we throw the same error, we might want to add more granularity to the logs.

**Comment by manosnoam** [comment]
Tried the scenario on RHODS 2.4, but the dashboard logs did not alert on changing to non existing adminGroups:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/dd189f36-f9a6-46a4-9b47-d913cae028b0)

Checking these pods logs showed no error/warning about the missing group "no-rhods-admins":
![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/fcf596c8-d83b-4fe2-82d3-3ec0ae737fee)

**Comment by andrewballantyne** [comment]
No errors what so ever? You followed the steps in the description? Did you ever launch the Dashboard or was this all passive just "doing the action" and "looking in logs". The 2min cache rule would apply to some of the auto-behind the scenes stuff. But you can trigger some of this by visiting the Dashboard UI (especially the User Management admin page)

**Comment by andrewballantyne** [comment]
@manosnoam forgot to tag you 🙂
