### ISSUE TITLE
[Conversation]: Improve Linter Settings

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#469]
We should look at improving our linter to maybe get prettier to format things to our preference.

Topics I think we can talk about (feel free to add more)

---

### Unnecessary braces `{` in a directly returned function
```
const foo = () => {
  return 'bar';
};
// vs
const foo = () => 'bar';
```

--- 

### Braces around straight returns

```
const foo = (bar: string | null) => {
  if (!bar) return null;
  // vs
  if (!bar) {
    return null;
  }

  return 'baz';
};
```

---

### Auto sort imports

Get them so all our 3rd party libs are at the top

`..` sorting so that the items further away go under 3rd party imports, working down to local files `./some-file`

---

### Support more tsconfig paths

Have it so alias paths can snap us back to the root to grab types/constants/utils/services/etc

```
import { } from '../../../utilities/useSomeHook';
// vs
import { } from '~/utilities/useSomeHook';
```

Note: When it's 1 file -- it can get confusing. `import { } from 'k8sTypes'` looks weird. We need a leading character to signify it's a special import.

---

### Reassigning variables passed to you

https://github.com/opendatahub-io/odh-dashboard/pull/693#discussion_r1024165385

---

### Stop console logs of any kind

We can ignore the ones we need for stability/error reporting -- but we should stop all logs from accidentally allowing debug code from slipping in.

---

### No else return

Prevent `if () { return } else { return }` so that the code structure is more malleable in the future. 

https://eslint.org/docs/latest/rules/no-else-return

---

### Always type argumentless variables

```
let icon;
```
What is icon? Is icon the string? the JSX? We should force typing here so it has more contextual usage.

```
let icon: React.ReactNode;
```

**Comment by lucferbux** [comment]
I'm inclined to use the styles used by other RedHatters (i.e. Patternfly or OpenShift core teams). I guess @andrewballantyne is well versed in that matter, so if all these changes are inclined to reach that I'm on board.

**Comment by dlabaj** [comment]
I know where those are setup in other projects i can pull them over.

**Comment by lucferbux** [comment]
> I know where those are setup in other projects i can pull them over.

Perfect! Sounds great.

**Comment by andrewballantyne** [comment]
@DaoDaoNoCode was there more you wanted to do with this issue or can we assume it was covered by #969 ?

I know we only touched the frontend, and tbh, overly rewriting the backend for a bunch of linter changes seems a bit excessive. Thoughts? The goal is to get rid of it, and styling on the backend isn't super important imo -- none of these are really going to impact us a lot as we don't do a lot of node development anymore.

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne I think we can close this one. Most of the backend code will be gone one day anyway so I guess it doesn't worth the effort to do a large refactor to the backend. Thanks!
