### ISSUE TITLE
[Bug]: Pods that request a GPU have the `nvidia.com/gpu.present` affinity set

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ported from downstream: https://issues.redhat.com/browse/RHODS-5072

Pods that request a GPU (and are scheduled on a gpu node) still have the nvidia.com/gpu.present affinity set even though they shouldn't.

```
[lgiorgi@fedora ods-ci]$ oc exec jupyter-nb-ldap-2dadmin4-0 -n rhods-notebooks  -- nvidia-smi
Defaulted container "jupyter-nb-ldap-2dadmin4" out of: jupyter-nb-ldap-2dadmin4, oauth-proxy
Tue Aug 30 09:08:06 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   34C    P8    15W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[lgiorgi@fedora ods-ci]$ oc get sts jupyter-nb-ldap-2dadmin4 -o yaml -n rhods-notebooks | yq -y .spec.template.spec.affinity
nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values:
              - 'true'
      weight: 1
```

On a pod without GPUs:
```
[lgiorgi@fedora ods-ci]$ oc exec jupyter-nb-ldap-2dadmin4-0 -n rhods-notebooks  -- nvidia-smi
Defaulted container "jupyter-nb-ldap-2dadmin4" out of: jupyter-nb-ldap-2dadmin4, oauth-proxy
time="2022-08-30T09:11:06Z" level=error msg="exec failed: unable to start container process: exec: \"nvidia-smi\": executable file not found in $PATH"
command terminated with exit code 255
[lgiorgi@fedora ods-ci]$ oc get sts jupyter-nb-ldap-2dadmin4 -o yaml -n rhods-notebooks | yq -y .spec.template.spec.affinity
nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values:
              - 'true'
      weight: 1
```

The scheduling appears to work correctly either way (the non-gpu pod is schedule on a cpu node, the gpu pod on a gpu node), I guess because the affinity is a `preference` and the request for a GPU overrides it.

### Expected Behavior

Affinity should only be set on the non-gpu pod

### Steps To Reproduce

1. Install ODH
1. Install GPU operator / provision GPU node(s)
1. Spawn a server with GPU and one without GPU
1. Check their definition for the nvidia.com/gpu.present affinity

### Workaround (if any)

Not really needed - it has no impact since it's a preference

> the affinity is a `preference` and the request for a GPU overrides it

### Open Data Hub Version

```yml
2.1
```

**Comment by andrewballantyne** [comment]
@maroroman I decided against automatically assigning this to you. Please grab it at your earliest convenience -- but someone else can work on it in the meantime if needed.

**Comment by maroroman** [comment]
Okay after some help from Samu we have found out that the issue lies in the fact that we are patching the notebook. With the current patch strategy if there is an affinity present after requesting a non-gpu notebook and we request a gpu notebook the empty object does not replace the affinity and it is left in the notebook (but the toleration is added). I think the best course of action will be to replace the PATCH call with a REPLACE call. I will create a PR for this. cc @andrewballantyne @lugi0

**Comment by andrewballantyne** [comment]
Ah, thanks. I figured I might shoot myself in the foot when I wrote the patch logic -- I was just piggybacking on existing threads of code. Shows me for not just doing the right thing and trying to save some effort. Apologizes for this.

**Comment by andrewballantyne** [comment]
https://github.com/opendatahub-io/odh-dashboard/issues/581 should handle this by simply not trusting the client with assembling the CR.
