### ISSUE TITLE
[DSG]: Convert Old Spawner Into Project Based Spawner

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#484]
### Feature description

The Jupyter tile is not going anywhere right now, so we need to bring it inline with projects.

- Needs be able to create a NEW namespace
    - create one under the hood; something like `${username}-jupyter-${random6Digits}` -- it should never have conflicts this way
        - We'll discuss with UX in a future ticket about perhaps using an existing one

There is still a pending question about upgrading this page to have similar options or a subset of #483 -- but that will be another ticket.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2757
