### ISSUE TITLE
[DSG]: Support Notebook List

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#485]
### Feature description

Create a table to hold onto notebooks (using an existing Notebook from the Jupyter Tile for data should be enough to get test data while you wait on #483)

- Must support
    - collapsible rows
    - sortable columns
    - external links
    - kebab items

### Anything else?

Mocks - https://marvelapp.com/prototype/afa716d/screen/88397428

Consider [existing](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/utilities/useTableColumnSort.ts) `useTableColumnSort` utility -- probably should be moved to a more generic spot.

**Comment by lucferbux** [comment]
I'm taking this, will test first with only one notebook as suggested.

**Comment by andrewballantyne** [comment]
@lucferbux we may be able to improve this with the work done in my work. I played around with getting more flexibility out of consistent table structures. Lets talk on Monday about what we can do to improve things

**Comment by DaoDaoNoCode** [comment]
@lucferbux Since #451 is done, this one could probably be implemented based on that. That only contains the empty state.
