### ISSUE TITLE
[Bug]: Notebook "Server Starting" popup not visible 15s after click on Start Server

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From https://issues.redhat.com/browse/RHODS-5150
In our automation, when the `Start Server` button is clicked on the Notebook Spawner page, the `Starting server` modal page doesn't show up within 15s, and the UI remains on this view:
![selenium-screenshot-6](https://user-images.githubusercontent.com/37624318/188649969-e0f4aef2-4e87-4493-811b-2722b73319b1.png)
See a sample [test log here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/495/pull-ci-openshift-psap-ci-artifacts-master-ods-nb-ux-on-single/1566785914682740736/artifacts/nb-ux-on-single/test/artifacts/011__driver_rhods__notebook_ux_e2e_scale_test/ods-ci/ods-ci-0/log.html).

The [browser console log entries](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/495/pull-ci-openshift-psap-ci-artifacts-master-ods-nb-ux-on-single/1566785914682740736/artifacts/nb-ux-on-single/test/artifacts/011__driver_rhods__notebook_ux_e2e_scale_test/ods-ci/ods-ci-0/browser_log_entries.yaml) don't show anything interesting.

**Comment by andrewballantyne** [comment]
I logged this duplicate https://github.com/opendatahub-io/odh-dashboard/issues/508 -- going to favour it due to more content in that issue.
