### ISSUE TITLE
[Bug]: Failed to get Route -- Didn't Apply The Annotation `opendatahub.io/link`

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During testing with 100 concurrent users, QE found that requesting the creation of a Notebook can sometimes lead to not properly annotating the redirect link to the notebook.

This is likely due to the server being under load and the trail of resources that are being created for us take a bit longer than desired. We have a hardcoded 500ms wait and we need to do better than one-shot-and-done. 

Based on the screenshot on the RHODS issue (https://issues.redhat.com/browse/RHODS-5128), it looks like a standard 404 on the route -- which is likely because of the 500ms timeout we do before trying to fetch it. A solution in that are may be our best blind test of the situation.

### Expected Behavior

When waiting for the Route to be created, we need to be more patient and allow the server to be slow. 

Solution could be something like: We should try every 1 second to get it, and timeout after 10 seconds. If we failed to get the Route in time for the Notebook to start spinning up, we should make the Start Modal re-request the route before trying to redirect when the status of the Notebook goes live.

I would assume we are just too fast and if we waited 1 or 2 more seconds this wouldn't happen - even under load.

### Steps To Reproduce

If possible test with multiple concurrent users -- 100 were used to test, 63 failed. 

If not possible, it may be difficult to reproduce this issue. One could try to test this with a bash script making curl requests at the post notebook end point.

### Open Data Hub Version

```yml
2.1
```

**Comment by kpouget** [comment]
> This is likely due to the server being under load and the trail of resources that are being created for us take a bit longer than desired. We have a hardcoded 500ms wait and we need to do better than one-shot-and-done.

> Based on the screenshot on the RHODS issue (https://issues.redhat.com/browse/RHODS-5128), it looks like a standard 404 on the route -- which is likely because of the 500ms timeout we do before trying to fetch it. A solution in that are may be our best blind test of the situation.

could you point me to the 500ms timeout?

and also to the call that you suspect ends up with a `404`? 
for the API-level testing I tried to catch all the frontend->backend API calls, but I didn't see anything related to the `route`.

with this:
```
curl --silent https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/476/pull-ci-openshift-psap-ci-artifacts-master-ods-nb-ux-on-ocp/1565426347851911168/artifacts/nb-ux-on-ocp/test/artifacts/011__driver_rhods__notebook_ux_e2e_scale_test/ods-ci/ods-ci-15/browser_log_entries.yaml | yq
```
you'll see the frontend end calls that ended up in 404.

**Comment by kpouget** [comment]
[here is the confirmation of the route fetch failure](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/476/pull-ci-openshift-psap-ci-artifacts-master-ods-nb-ux-on-ocp/1565426347851911168/artifacts/nb-ux-on-ocp/test/artifacts/012__sutest_rhods__capture_state/redhat-ods-applications/rhods-dashboard-88f5f964c-75s4f.log):
```
[pod/rhods-dashboard-88f5f964c-75s4f/rhods-dashboard] 
  {"level":50,"time":1662066799432,"pid":108,"hostname":"rhods-dashboard-88f5f964c-75s4f",
    "message":"routes.route.openshift.io \"jupyter-nb-psapuser15\" not found","explicitInternalServerError":false,
    "error":"Error fetching Notebook Route","stack":"NotFoundError: routes.route.openshift.io \"jupyter-nb-psapuser15\" not found\n    at createCustomError (/opt/app-root/src/backend/dist/utils/requestUtils.js:9:45)\n    at /opt/app-root/src/backend/dist/routes/api/notebooks/notebookUtils.js:90:60\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "type":"Error","msg":"routes.route.openshift.io \"jupyter-nb-psapuser15\" not found"}
```
