### ISSUE TITLE
[Investigation]: Review message priority for some error messages

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#509]
### Feature description

Currently, if a notebook triggers an autoscale, it shows up as a scary error.  We should probably show this as an info so that we don't scare users.  There might be other specific messages that we might want to capture and downgrade in the same way.

![Screenshot from 2022-09-07 23-40-53](https://user-images.githubusercontent.com/1448375/189029431-874043ed-41ec-4bf9-ad72-d45bc20d1424.png)

**Comment by andrewballantyne** [comment]
Overlaps with the direct request to handle the auto scale -- see #525

**Comment by andrewballantyne** [comment]
If we can discover other ones we want, we can either roll them into #525 if it had not been started, or log another issue.

**Comment by andrewballantyne** [comment]
Closing as I think we know of more situations. 

See https://github.com/opendatahub-io/odh-dashboard/issues/559 for an issue around scaling.
