### ISSUE TITLE
Remove JH References

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have moved to supporting Jupyter (KFNBC) fully in 2.1.1, we should have cleaned up any references left.

Right now the `manifests` folder still references JH being enabled. [File ref](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/overlays/odhdashboardconfig/odh-enabled-applications-config.configmap.yaml#L8).

We also have a lot of references that are not needed anymore.

### Expected Behavior

We should remove any references to JupyterHub in all aspects of our repo.

### Open Data Hub Version

```yml
2.1.1
```

**Comment by andrewballantyne** [comment]
We should remove all references to JupyterHub -- ODH Manifests said they would be aiming at v1.5 to remove it, but I see no reason for us to wait. It's extra resources we are owning for an obsolete flow.

Resetting this back to neutral as it has not made motion since last Sept.

**Comment by LaVLaS** [comment]
It can be removed completely.  JupyterHub deprecation was announced fir ODH 1.4 and finalized in ODH 1.5 (https://github.com/opendatahub-io/odh-manifests/pull/751)
