### ISSUE TITLE
[Bug]: Patternfly CSS is being overridden 

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rigth now several style's components are being overridden from the original Patternfly version.
We **should not** have this behavior in the dashboard.

### Expected Behavior

All the components in the dashboard should use the default style of Patternfly.

**Comment by andrewballantyne** [comment]
This is a pretty bad infrastructure problem. Overriding css from PF is a VERY bad idea.

cc @DaoDaoNoCode when we get a moment, I'd like you to work to undo this damage to our CSS classes so we can stay in sync with PF updates without constant problems.

**Comment by andrewballantyne** [comment]
To clarify the intent behind this ticket, let us think on what is happening, how to fix it, and more importantly, how to prevent it going forward.

1. `.pf-...` class references exist heavily in a lot of our CSS -- these are usually nested under a custom class name, so it is usually limited to a given usage. This serves to modify the PF library which can hurt us when upstream changes implementations on us and our styles are no longer compatible... also it can prevent us from seamlessly adopting feature fixes and new implementations -- this will be annoying to track down.
2. The goal should be to ONLY use PF components and very very rarely use custom styles to achieve a custom implementation around PF (never within' PF classes unless we are hotfixing a bug) -- but more ideally, this should be conversations with UX to change our design to meet PF components and just avoid custom styles
3. To prevent this we probably should look at adding a css linter rule to prevent any usage of `.pf-` -- how to do this will require some googling, but I suspect this isn't the first needed implementation of this usecase and something in npm will already be set to do this for us

**Comment by andrewballantyne** [comment]
This is an ongoing effort with each PF Upgrade that @DaoDaoNoCode goes through.

From a quick look, the current offenders are:
- App.scss
- OdhCard.scss
- OdhListItem.scss
- EnableModal.scss
- LearningCenter.scss
- LearningCenterToolbar.scss

There are two use-cases that are waiting on https://github.com/patternfly/patternfly-react/issues/8028 -- needs a followup. @DaoDaoNoCode can you review their response and see if you have an action that is their React components or if we got it for free? If not, I'll need to carve out time to follow up with it.

There is also one more use-case -- `NotebookController.scss` -- this is deprecated. Let us not worry about this. This all should go away when we do the Notebook Namespace decommission ([Milestone](https://github.com/opendatahub-io/odh-dashboard/milestone/8))

**Comment by dgutride** [comment]
Moved to story in Jira:  https://issues.redhat.com/browse/RHOAIENG-2408
