### ISSUE TITLE
[Bug] Failed to create the notebook message, but notebook up and running

### ISSUE THREAD

**Issue by kpouget** [opendatahub-io/odh-dashboard#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When launching a notebook from my dev cluster, I observed the following state:
- notebook successfully created
- but `Failed to create the notebook` displayed in the background

![image](https://user-images.githubusercontent.com/7559202/189725318-d5e937d9-16a8-4351-aeff-25f07717230c.png)

Image that was running is [quay.io/opendatahub/odh-dashboard:main-f3db801](http://quay.io/opendatahub/odh-dashboard@sha256:272cc8d9e052767b6089f038ce3dbd0117198e288c4b1723f54c292afdb5aae7)

**Comment by andrewballantyne** [comment]
Should be fixed by the spawner speed improvements
