### ISSUE TITLE
[Feature Request]: Label all the ressources created by the dashboard

### ISSUE THREAD

**Issue by kpouget** [opendatahub-io/odh-dashboard#545]
### Feature description

For proper tracking and cleanup, it would be convenient to have labels in the resources created by the Dashboard

```
$ oc get notebooks --show-labels 
jupyter-nb-psapuser1   2m35s   app=jupyter-nb-psapuser1,opendatahub.io/odh-managed=true,opendatahub.io/user=psapuser1
```
almost good, except that `app` (or something else) could have the value `odh-dashboard`, so that we can list all the Notebook created by the Dashboard

```
$ oc get role,rolebindings --show-labels | grep psap
role.rbac.authorization.k8s.io/jupyter-nb-psapuser1-notebook-view   2022-09-13T12:30:39Z   <none>
rolebinding.rbac.authorization.k8s.io/jupyter-nb-psapuser1-notebook-view   Role/jupyter-nb-psapuser1-notebook-view   5m7s    <none>
```
--> no label at the moment

**Comment by kpouget** [comment]
same for PVC, Secrets, ConfigMaps

**Comment by kpouget** [comment]
```
oc get notebooks,cm,secrets,roles,rolebindings,pvc -oname | egrep 'kpouget'  | xargs --no-run-if-empty oc delete
notebook.kubeflow.org "jupyter-nb-kpouget" deleted
configmap "jupyterhub-singleuser-profile-kpouget-envs" deleted
secret "jupyterhub-singleuser-profile-kpouget-envs" deleted
Error from server (NotFound): secrets "jupyter-nb-kpouget-dockercfg-lhfcw" not found
Error from server (NotFound): secrets "jupyter-nb-kpouget-oauth-config" not found
Error from server (NotFound): secrets "jupyter-nb-kpouget-tls" not found
Error from server (NotFound): secrets "jupyter-nb-kpouget-token-npzxq" not found
Error from server (NotFound): secrets "jupyter-nb-kpouget-token-p8786" not found
```
would be useful to be able to distinguish the resources created by the `dashboard` from the ones created by the notebook controller(s) (the ones that couldn't be found above, following the notebook deletion)

**Comment by kpouget** [comment]
any update on this?
would be useful for improving the automation

**Comment by andrewballantyne** [comment]
@kpouget Can you log something in RHODS?

**Comment by andrewballantyne** [comment]
We can try to get this done by 1.19

**Comment by andrewballantyne** [comment]
Juntao did this as part of the DSG work when we labeled those resources as well.

`'opendatahub.io/dashboard': 'true',` is the label for the solution to this.
