### ISSUE TITLE
[Bug]: feature.json has been removed from the main branch.

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently there no way to disable ISV since  feature.json is missing.  Instead of adding it back it's recommended to use the dashboard config instead to disable and enable ISVs

### Expected Behavior

Should have the ability to disable ISVs

### Steps To Reproduce

N/A

### Workaround (if any)

Currently you can remove the CRs related to  the  ISV.

### What browsers are you seeing the problem on?

Chrome

### Open Data Hub Version

```yml
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by andrewballantyne** [comment]
To clarify -- you can still use `data/features.json` if you add the path back. The default is just missing -- which had nothing in it.

**Comment by dlabaj** [comment]
@andrewballantyne I'm just going to add back feature.json.  We can remove it later if we want.
