### ISSUE TITLE
[Bug]: Refine filter events logic for auto-scale nodes

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a follow up issue after we merge #563.

I noticed there could be a false positive `NotTriggeredScaleUp` after the `TriggeredScaleUp` event, while the node is actually scaled up. Check the log in the image below for more details:
<img width="760" alt="Screen Shot 2022-09-12 at 1 19 16 PM" src="https://user-images.githubusercontent.com/37624318/190702239-246ab240-cf78-413b-b73e-acb7d900850e.png">
But the logs after the `NotTriggeredScaleUp` event indicate that the node is scaled up and the notebook is being created.

In current logic, if this happens, we will always show an error `NotTriggeredScaleUp` all the time and filter all the events after that. We need to think of a better way to filter the event and find out this false positive situation.

### Steps To Reproduce

Hard to reproduce, sometimes happens sometimes not, very randomly.

**Comment by andrewballantyne** [comment]
This didn't appear in the testing I did for #563 -- But if we can figure out how this happens, we should definitely improve this experience.

Perhaps it is a conflict if two people start scaling at the same time?

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2749
