### ISSUE TITLE
[Bug]: Sometimes Events Don't Show

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In an unknown set of events, the start modal doesn't appear to be showing status updates.

Theories:
- ~Bad start time? Maybe use the metadata creation date if we don't have notebook last activity?~ Nope, PSAP showed the Notebook CR, it has the annotation

Definitely looks to be a filtering issue as there is no node scaling on this cluster and the logs go from fail to schedule to scheduled.
```
NAMESPACE                                          LAST SEEN   TYPE      REASON                                             OBJECT                                                                          MESSAGE
rhods-notebooks                                    47m         Warning   FailedScheduling                                   pod/jupyter-nb-psapuser94-0                                                     0/14 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 9 Insufficient cpu.
rhods-notebooks                                    36m         Warning   FailedScheduling                                   pod/jupyter-nb-psapuser94-0                                                     0/14 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 9 Insufficient cpu.
rhods-notebooks                                    36m         Normal    Scheduled                                          pod/jupyter-nb-psapuser94-0                                                     Successfully assigned rhods-notebooks/jupyter-nb-psapuser94-0 to ip.us-west-2.compute.internal
rhods-notebooks                                    35m         Normal    SuccessfulAttachVolume                             pod/jupyter-nb-psapuser94-0                                                     AttachVolume.Attach succeeded for volume "pvc-23079708-2c6f-4a03-a166-fe0992db7744"
```

### Expected Behavior

Always to show events related to the current notebook we are spinning up.

Investigate alternative ways to sync events to a given Notebook start -- can we use a uid? Is there a particular revision number? Something we can filter on that is not date related.

### Steps To Reproduce

Hard to say how to make this happen. We should investigate places where this can happen and try to fix it blind.

### Open Data Hub Version

```yml
v2.1-hotfix branch (~2.1.0 + some fixes for 2.1.1 & 2.2.0)
```

**Comment by andrewballantyne** [comment]
See the RHODS ticket for any findings we find during investigation. https://issues.redhat.com/browse/RHODS-5327

**Comment by dgutride** [comment]
This was already migrated!  https://issues.redhat.com/browse/RHOAIENG-428  Closing
