### ISSUE TITLE
[Bug]: Regex validation for env variables in spawner page.

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding an environment variable with only digits in the name, the build status freezes, and the notebook controller outputs this error:

`1.663845121362662e+09 DEBUG events Warning {"object": {"kind":"Notebook","namespace":"opendatahub","name":"jupyter-nb-lferrnan","uid":"49ea52f2-fabd-457c-94bd-988549fe3817","apiVersion":"kubeflow.org/v1beta1","resourceVersion":"618045"}, "reason": "FailedCreate", "message": "Reissued from statefulset/jupyter-nb-lferrnan: create Pod jupyter-nb-lferrnan-0 in StatefulSet jupyter-nb-lferrnan failed error: Pod \"jupyter-nb-lferrnan-0\" is invalid: spec.containers[0].env[2].name: Invalid value: \"1341\": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')"}`

We should have validation in the frontend to comply with this value.

### Expected Behavior

When writing an env variable that starts with a number, have form validation.

### Steps To Reproduce

1. Go to the spawner page
2. Create a new env variable
3. Fill it with digits, i.e. `1234`
4. Start the notebook, it will freeze and it won't output any error.

### Workaround (if any)

Not using env variables that start with digits.

**Comment by andrewballantyne** [comment]
Ah yeah, field validations are lacking in our space -- good issue to log, not sure if QE has a test case for this in their automation -- I'll reach out and let them know.
