### ISSUE TITLE
[Feature Request]: Disable Application Tile until required Dependencies are installed

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/odh-dashboard#596]
### Feature description

To avoid unexpected issues while using an Application shown on the ODH Dashboard, the tile should be disabled until prerequisite dependencies are installed, with a warning message showing the user the reasoning the Application is in the disabled state.

In particular, Operator dependency checking should be implemented (ie. This Application cannot be used until operator xyz is also installed), although this functionality can likely be later extended to check other resources as well.

### Describe alternatives you've considered

Disabling the application by default and providing instructions in documentation on installing dependencies and manually enabling the Application.  This is not a great alternative as it is cumbersome and unintuituve to the user.

**Comment by andrewballantyne** [comment]
This is a feature we have planned to do, but we have not had the chance to properly prioritize it. I'll marked it as low for now. We'll need to discuss with PM and Management to determine when we can get this in.

**Comment by andrewballantyne** [comment]
cc @jkoehler-redhat

**Comment by lucferbux** [comment]
@andrewballantyne I think the ML-Ops team needs this feature for the pipelines, it might be great to add more priority to this, as they are targeting this sprint to have the beta. Is that right @gmfrasca @anishasthana ?

**Comment by anishasthana** [comment]
Yep that's correct, we'd need it in the (downstream) 1.18 release.

**Comment by jkoehler-redhat** [comment]
All, this will need to get some UX done too.  Asking Jeff if we can tell first customers that are trying this feature out to install the requirement.  A few of us are gonna meet and figure out what is needed, but plan a bit out.

**Comment by dgutride** [comment]
Given age, moving this to closed - will wait for PM to prioritize work on resources page and tiles to cover any issues related to dependencies in the future.
