### ISSUE TITLE
Refactor frontend Redux Implementation

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#60]
**Is your feature request related to a problem? Please describe.**
Instead of using `createStore`, `combineReducers` and apply `redux-thunk` middleware manually, I think it would be helpful to import `@reduxjs/toolkit`. It contains `configureStore` function which will do all the things above and it contains other functions like `createAsyncThunk` to help better create async redux functions. Maybe it would be easier to develop and maintain the redux store of the project in the future?

**Describe the solution you'd like**
Refactor store, actions, reducers of redux with `@reduxjs/toolkit`.

**Comment by andrewballantyne** [comment]
We should evaluate this... everything is merged together in a single reducer but we should look to separate the data into different contexts. This needs a design before we approach it otherwise we may just need to refactor again.

**Comment by andrewballantyne** [comment]
I think I'm going to close this -- we'll want to migrate away from Redux rather than leaning on improving it. React Contexts can take this -- we don't have a lot of data to manage at the app level.
