### ISSUE TITLE
[Investigation]: Moving a PVC to a Different Namespace

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#603]
### Feature description

We currently create our Notebook PVCs in the `notebookNamespace`. This works for our current setup, but is part of a lot of problematic security and maintenance points. Due to this "one namespace" problem, we use a ServiceAccount to manage creating & managing it. This is not idea for a pure K8s design. 

What we need to do is move each users `notebookNamespace` PVC to another namespace -- one they will own and have proper K8s permissions within.

Problem is, PVCs have an underlying PV -- this PV isn't namespaced and if you delete the associated PVC, the PV is auto cleaned up by K8s.

---

1. Have (or spin up) a Notebook as a user in the Dashboard -- this will create a secret, configmap, notebook and most importantly a PVC in the `notebookNamespace` (if configured, if not configured it is in the dashboard namespace)
2. Create a new namespace manually through an OpenShift Console client
3. Find a way to write a bit of node code using the k8s library we have on the Dashboard that can move the PVC from the `notebookNamespace` to your newly created namespace -- make sure the data can still be accessed

We are not entirely sure how to go about this -- but try to create a PVC in your new namespace that can reference the other PVCs PV. Then delete the old PVC and hopefully the PV stays around connected to the new PVC in your new namespace.

It's a bit unclear how this will work, we may need to read up more on K8s PVCs. 

### Anything else?

In the end we will want to have a migration script built into the Dashboard for some number of releases. Each time a user goes to spin up a new Notebook from the Jupyter Tile, we'll auto migrate them to a new namespace. We'll need to work with UX and PM to fully figure that out -- but that's for another ticket.

**Comment by andrewballantyne** [comment]
@maroroman found this slack overflow thread: https://stackoverflow.com/questions/66078689/move-or-change-a-volume-namespace

Might be a good solution. Some investigation is needed to see what we can do.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2969
