### ISSUE TITLE
[Feature Request]: Create a Migration Script INSIDE Dashboard -- Moving away from `notebookNamespace`

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#604]
### Feature description

In #603 we will investigate how we will move a PVC from one namespace to another. Once we have that figured out we will want to create a script that we can invoke in the Dashboard Node code to run when needed as part of a on-going migration effort.

---

- We'll need a new method (probably not a new endpoint) on the backend that can move all the related resources we create
    - PVC -- See #603 
    - Purely spec resources (which should be as simple as copy & paste the effort to a new namespace)
        - ConfigMap
        - Secret
        - Notebook
- We'll need a target namespace where to move them to -- this can get interesting
    - There are some limitations about creating a namespace on some hostings -- so we will need to be able to smart detect which namespaces are available to the user doing the effort to see if we can move them to a specific existing namespace
    - We may want the client to provide which namespace the user wants -- if they have permissions to self provision, that may also mean creating a new namespace

### Anything else?

Once this is in place we'll need to look at never creating in the `notebookNamespace` again. But that can be done in a cleanup ticket.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2745
