### ISSUE TITLE
[Bug]: Cluster admin does not get Admin access if it's the only user in the cluster

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It looks like when the cluster admin is the only user present in the cluster, it doesn't get the Admin access automatically. 
The dashboard pod reports these lines of error about rolebindings:

```
{"level":50,"time":1664785629417,"pid":108,"hostname":"rhods-dashboard-59bb5c9d89-6kb2f","msg":"Failed
 to list rolebindings for user, Failed to list groups filtered by 
username."}{"level":50,"time":1664785629436,"pid":108,"hostname":"rhods-dashboard-59bb5c9d89-6kb2f","msg":"Failed
 to list rolebindings for user, Failed to list groups filtered by 
username."}
```
...
As soon as we created more users, it got the permissions and the logs stopped to show those errors about role binding.
 

### Expected Behavior

Having admin access regardless the number of users

### Steps To Reproduce

1. Create a cluster (reproduced on OSD)
2. Create only one user with cluster admin permissions (no other users in the cluster)
3. Log in the Dashboard using the cluster admin
4. Check if the user can access the "Settings" section
5. create new users
6. Check point 4) once again

### Workaround (if any)

* Add more than one users

**Comment by andrewballantyne** [comment]
@lucferbux do you understand how this can happen? Also, isn't `kube:admin` always there? Do OSD clusters disable `kube:admin`?

**Comment by lucferbux** [comment]
No, i have no idea why this is happening. And kube:admin is not a real user, so when you list all the users, kube:admin does not count. (just running oc get users does not retrieve kube:admin at least)
