### ISSUE TITLE
[Feature Request]: Move the user tracking config to the dashboard configuration.

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#617]
### Feature description

Right now, user tracking config is enabled/disabled by an attribute in the `odh-segment-key-config` ConfigMap.

We didn’t move this attribute to the `odhdashboardconfig` before cause it was used by JupyterHub, but right now it can be added there since we have deprecated the service.

The steps would be:

1. Change the logic of retrieving/seting the user interation tracking to the dashboard config.
2. Delete the configmap creation in [odh deployer](https://github.com/red-hat-data-services/odh-deployer/blob/main/monitoring/segment-key-config.yaml)

### Describe alternatives you've considered

We can leave it as it is, but I think it would be nice to just add it as it’s part of the dashboard configuration.

**Comment by DaoDaoNoCode** [comment]
Maybe we could consider fixing this together with #1767
