### ISSUE TITLE
[Bug]: Clean Up Pods On Critical Startup Failure

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we are spinning up a Notebook on the Spawner Page, we can get into a state where it has critically fallen over. When this happens the user is pretty much blocked from anything.

If they chose to leave the application at this point, we leave the pods spun up in an error state, perhaps taking resources from the cluster. In JH we apparently cleaned up the pods at this point. We should look to do the same here, so we can free up resources for other users.

See downstream ticket for more details: https://issues.redhat.com/browse/RHODS-5110

### Expected Behavior

Our default case is warnings now. When we hit an error case, perhaps we just stop the notebook? Maybe we should wait 20s or something to buffer for unexpected bad events that are transient. If after the 20s we still have the identified bad state (error status) then we can stop the pods.

Keep the "if they close" stopping the notebook, as we'll want to still give them an access to back out.

### Steps To Reproduce

See downstream ticket for scenarios: https://issues.redhat.com/browse/RHODS-5110

### Open Data Hub Version

```yml
2.3.0
```

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2748
