### ISSUE TITLE
[Performance]: Investigate Start Notebook => Access JL Speed

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are a bit slower than what it was for JH to spin up a Notebook on the Spawner page. We should look into what we can do with this. Collecting the data into backend calls (such as in #587) might get us into a state where we can be faster just with less passes through the OAuth Proxy container.

### Expected Behavior

Less than 40s to spin up and access JL. We may need help from QE to get a good benchmark going. Downstream issue: https://issues.redhat.com/browse/RHODS-5190

### Steps To Reproduce

Spawn a Notebook via KFNBC Spawner Page.

### Open Data Hub Version

```yml
2.1.0 -- RHODS 1.16
```

**Comment by lucferbux** [comment]
I've run some benchmarks in my dev cluster, after 10 runs I got:

* Less than 40 secs in notebooks with images already selected (pulled previously from the cluster).
* Less than 50 secs in notebooks with images that haven't been selected before (the cluster needs to pull those images).

Might be worth revisiting this with QE in case we've improved it,

**Comment by kpouget** [comment]
@lucferbux what do you include in this timing? from "create server" to JL, or with the dashboard steps?

**Comment by lucferbux** [comment]
@kpouget The moment i click "Start server" to the moment the notebook is available. It's a manual step and hence is not very "scientific".

**Comment by lucferbux** [comment]
This issue was closed downstream, I think it's fine to close this in upstream @andrewballantyne @kpouget
