### ISSUE TITLE
[Pipelines]: Add ability to make getting started link optional

### ISSUE THREAD

**Issue by dlabaj** [opendatahub-io/odh-dashboard#630]
### Feature description

Currently we don't support the ability to have the getting started link as optional when creating and ODHApplication CR.   This feature is needed since some ISVs may not have a getting started link (e.g. ML pipelines).  We should update the CRD, and  the ODHApplication type in the dashboard code to make this field optional.  If this field isn't provide we should hide the getting started button [here](https://github.com/opendatahub-io/odh-dashboard/blob/51c19590c3a88d86345080f2f917f390207d6c2a/frontend/src/pages/exploreApplication/GetStartedPanel.tsx#L87).

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by dgutride** [comment]
Moving to closed - we will revisit if necessary.
