### ISSUE TITLE
[Bug]: GPUs cannot be used with Tainted Nodes

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

> The difference is that I usually add a Taint to my nodes called "notebooksonly". I did add it to the GPU node, because:
> A) that node has no taint by default
> B) I had noticed random pods landing on it and hogging it for nothing
> However, as soon as I add the taint, a few minutes later, the drop down disappears. 
> When I remove the taint, the drop-down re-appears. 

From the downstream issue https://issues.redhat.com/browse/RHODS-4769

### Expected Behavior

GPUs should work for both using tolerations & not using tolerations.

### Steps To Reproduce

See the current behaviour / downstream ticket.

This is likely related to the Prometheus query omitting results -- but that is just a guess. Might be impacted by #573 and supporting of scaling (which could change the "show the dropdown" logic -- may not work with unscalable nodes that have tolerations)

### Open Data Hub Version

```yml
2.3.0
```

**Comment by guimou** [comment]
As it is, tolerations added manually to a Notebook definition are "erased" when you start the Notebook through the UI. This is incompatible with multiple pools of GPUs that you have to taint to properly schedule specific workloads, or just with standard management of workloads placement through taints.
We should either:
- Leave the tolerations in the Notebook CR alone, or only reconcile the ones we provide access to trough the UI, like GPU request  = nvidia.com/gpu toleration.
- Or provide a mechanism in the UI to fully managed tolerations on Notebooks.

**Comment by andrewballantyne** [comment]
So today we have a toleration for `nvidia.com/gpu` ([code link](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/utilities/tolerations.ts#L17-L21)) -- this should be covered if you taint your node with the same. We also have the "NotebooksOnly" (configurable) default toleration for Notebooks if you check out the cluster settings as an admin -- but that's not tied to (Nvidia) GPU, that's additional.

I would imagine this is handled already to some degree 🤔 

In the work for accelerators, I imagine this will be more flexible and seamless for what is being tainted/tolerated... effectively this should be done, no?

- See https://github.com/opendatahub-io/odh-dashboard/issues/1450
    - More specifically the CR we will create to allow customization for accelerators (https://github.com/opendatahub-io/odh-dashboard/issues/1371)

**Comment by dgutride** [comment]
This is no longer valid due to Habana work - moving to closed after talking to Gage.  Please reopen with questions if there are any misunderstandings.
