### ISSUE TITLE
[Feature Request]: Re-enable KFNBC Administration Tab

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#675]
### Feature description

Follow up of #566 

After the work made on #587 we can re-enable the KFNBC Administrator Tab adapting it to the new endpoint.

There was a feature missing that we opened downstream that could be added:

"An admin can start and stop server for other users, but cannot access the server once is running."

**Comment by andrewballantyne** [comment]
#564 will handle this issue -- we should not do them separate.

Closing this issue.
