### ISSUE TITLE
[Bug]: We show a link to OpenShift Cluster Manager when OCM didn't get used

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We need to get better detection involved in what action links we show. 

Self-managed clusters do not use OCM and we shouldn't have a link for that in those cases.

See https://issues.redhat.com/browse/RHODS-5216 for more information.

### Expected Behavior

Not to show the OCM link when it is not relevant 

### Steps To Reproduce

See ticket https://issues.redhat.com/browse/RHODS-5216

### Workaround (if any)

Disable it in OdhDashboardConfig.

> As a workaround we can modify `OdhDashboardConfigs` CR and set the disableClusterManager: true under .spac.dashboardConfig.

### Open Data Hub Version

```yml
2.3.1
```

**Comment by dgutride** [comment]
Already migrated:  https://issues.redhat.com/browse/RHOAIENG-1149
