### ISSUE TITLE
[Deps]: Bump PatternFly to release 2022.13

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#685]
### Feature description

Changes:
"@patternfly/patternfly": "4.215.1" -> "4.217.1",
"@patternfly/react-catalog-view-extension": "4.90.0" -> "4.92.26",
"@patternfly/react-core": "4.239.0" -> "4.250.1",
"@patternfly/react-icons": "4.90.0" -> "4.92.6",
"@patternfly/react-styles": "4.89.0" -> "4.91.6",
"@patternfly/react-table": "4.108.0" -> "4.111.4",

**Comment by andrewballantyne** [comment]
If you could also solve any tooltip/popover issues with our strict mode & findDomNode errors, that'd be great. I suspect we won't get rid of them all -- looks like Select has it internally and I don't know if we can fix that (might be worth looking at the PF code to see if it is solvable)
