### ISSUE TITLE
[KFNBC]: Notebook control panel - wrong title for requests

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once a notebook is launched, the control panel displays this information:
---
Deployment size

Container size
Small

Limits
2 CPU, 8Gi Memory

Memory Requests
1 CPU, 8Gi Memory

Number of GPUs
0
---
The requests title should read "Requests" instead of "Memory requests" as it also shows CPU info.

### Expected Behavior

Title for requests reads "Requests"

### OpenShift Infrastructure Version

AWS

### Open Data Hub Version

```yml
RHODS 1.17.1-1
```

**Comment by andrewballantyne** [comment]
Hah, I noticed this in the new features as well -- must be a reoccurring typo. Thanks for catching that @guimou !
