### ISSUE TITLE
[Model Serving]: Enable GPU in Model Server configuration

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#703]
### Feature description

We need to enable GPU support for model server, **still waiting for proper implementation for the backend**

* Users can enable GPU support in the Model Server configuration [Mocks](https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/wLGd1Aw)

**Comment by andrewballantyne** [comment]
Waiting on the backend to provide the usage for this.

**Comment by Xaenalt** [comment]
Yes, current roadmap is to look into Triton, but OpenVINO Model Server will also support GPUs in a future release. I'll update here when there is more information

**Comment by Xaenalt** [comment]
Additionally, if users require GPU serving, they can use upstream Triton

**Comment by dgutride** [comment]
This is very old - I'm going to close it and if we are missing anything with our current accelerator implementation, we can work with PM to add it to jira.
