### ISSUE TITLE
[Feature Request]: Stop using JupyterHub translation

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#712]
### Feature description

It still seems like we're using JupyterHub's custom encoding in places.  
```
$(echo ${TRANSLATED_USERNAME} | sed 's/-2d/-/g' | sed 's/-40/@/g' | sed 's/-2e/\./g'| sed 's/-3a/:/g')
```
Last I saw it was used in the project label `opendatahub.io/user`.  I think whenever possible, we should move to something more standard such as base64 encoding

**Comment by lucferbux** [comment]
@DaoDaoNoCode we've spotted this one for jupyterhub removal too

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-573
