### ISSUE TITLE
[Bug]: Staging/Production Styling Issue

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we are in development we get a clean view of expected PF styles:
![image](https://user-images.githubusercontent.com/8126518/199098989-cae384bd-fc23-4081-9584-94a3bf91488d.png)

When we are in a hosted environment the PF styles seem to leave in some cases:
![image](https://user-images.githubusercontent.com/8126518/199098926-b89e215a-91e0-4d60-b4df-b7f8a708171a.png)

### Expected Behavior

For the Select/Dropdown components to have a border.

### Steps To Reproduce

Reproduce this by looking at any hosted environment and comparing it to the local environment run through webpack.

There is something wrong with our PF packaging or something.

### Workaround (if any)

None

### Open Data Hub Version

```yml
2.4.0
```

**Comment by DaoDaoNoCode** [comment]
Compared to the [dev](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/config/webpack.dev.js) and [prod](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/config/webpack.prod.js) Webpack configs, I found some differences.
1. The prod Webpack config uses `MiniCssExtractPlugin` while the dev one doesn't use
2. The prod Webpack config includes [node_modules/@patternfly/react-styles/css](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/config/webpack.prod.js#L54) while the dev one doesn't

Not sure which one caused this difference between the two environments but I believe this is the reason.

**Comment by andrewballantyne** [comment]
cc @DaoDaoNoCode I'd like to see this improved in the near future.
