### ISSUE TITLE
[Bug]: Misconfigured Group Permissions shouldn't throw 500 errors

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we fetch for the group that is defined in the OdhDashboardConfig and we can't find it, we will throw a 500 server error.

### Expected Behavior

We should send 404 errors as they are not found and don't (necessarily) impact the operation of the Dashboard as a whole.

### Steps To Reproduce

1. Have a config reference a group that does not exist.
2. Load up the console. 

### Workaround (if any)

Fix your config by specifying groups that are actually available on cluster

### Open Data Hub Version

```yml
2.4.0
```

### Anything else

Eg logs:

```
{"level":50,"time":12345,"pid":1,"hostname":"rhods-dashboard-","msg":"Error: Failed to retrieve Group rhods-admins, might not exist."}
{"level":50,"time":12345,"pid":1,"hostname":"rhods-dashboard-","msg":"Error: Failed to retrieve Group rhods-admins, might not exist."}
{"level":50,"time":12345,"pid":1,"hostname":"rhods-dashboard-","msg":"Error: Failed to retrieve Group rhods-admins, might not exist."}
```

**Comment by DaoDaoNoCode** [comment]
I think this bug is fixed by https://github.com/opendatahub-io/odh-dashboard/pull/725. I don't see any 500 errors now in the logs.

**Comment by andrewballantyne** [comment]
Okay, closing up -- if it comes up again, we can get more information on the state. This is an old issue.
