### ISSUE TITLE
[Bug]: NotebookUtils assembleNotebook image: dependent on ImageStream dockerImageRepo / internal Docker Repo

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-dashboard#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

more generally: https://github.com/opendatahub-io/odh-dashboard/issues/813

Currently, odh-dashboard is evaluating imagestreams defined at 

https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/additional

when building a Notebook CRD from imagestreams.

Imagestreams do not necessarily have to copy images to the internal docker registry. When using 

spec.tags.referencePolicy.type: Source, the following holds true:

The Source policy instructs clients to pull directly from the source registry of the image. The integrated registry is not involved unless the image is managed by the cluster. (It is not an external image.) This is the default policy.

In contrast, the Local policy instructs clients to always pull from the integrated registry of Openshift. This is useful if you want to pull from external insecure registries without modifying Docker daemon settings.

If we have an ImageStream with the default of the default spec.tags.referencePolicy.type: Source, then the tag of the imagestream references the remote location in status.tags[x].items.dockerImageReference.

Jupyter Imagestreams are applied, the object is present, and its status field has a
`  dockerImageRepository: ''` empty value.

```
status:
  dockerImageRepository: ''
  tags:
    - tag: v0.0.5
      items:
        - created: '2022-11-21T13:14:31Z'
          dockerImageReference: >-
            [quay.io/thoth-station/s2i-generic-data-science-notebook@sha256:3f619c61501218f03d39d97541336dee024f446e64f3a47e2bc7e62cddeb2e58](http://quay.io/thoth-station/s2i-generic-data-science-notebook@sha256:3f619c61501218f03d39d97541336dee024f446e64f3a47e2bc7e62cddeb2e58)
          image: >-
            sha256:3f619c61501218f03d39d97541336dee024f446e64f3a47e2bc7e62cddeb2e58
          generation: 2
```

Currently, the spawner evaluates the image name from dockerImageRepository. 

Hint from @samuelvl:
https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/notebookUtils.ts#L171

It puts the combination of image name and image tag into a variable imageUrl.

that variable is then correctly used at

https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/notebookUtils.ts#L280

Also, it is unclear to me what the difference between assembleNotebook in backend notebookUtils and frontend api is:

https://github.com/opendatahub-io/odh-dashboard/blob/729cb6200d7d1ba7d6756288fd9bb4d54970c806/frontend/src/api/network/notebooks.ts#L91

Looks very much similar ...

Instead, it should either get the entire imageUrl in its entirety from Imagepolicy's spec.tags[x].from.name
or even better so, 
with local reference type imagestreams also in mind, just reference the ImageStream name and tag
`<imagestream name>:<(imagestream-tag>` as the basis for Notebook.spec.containers[x].image.

This would work because the imagestream is in the same namespace and because spec.lookupPolicy.local is set to true, both in the jupyter imagestreams as well as in the odh-manifests test imagestreams.

possibly using ImageStreamTag type to get to that information or ImageStream.metadata.name and ImageStreamTag.name 

See External image and External image with pullthrough explanations at https://itnext.io/variations-on-imagestreams-in-openshift-4-f8ee5e8be633

> Can this ImageStream be used in a Pod (or other vanilla Kubernetes resource)?
Yes, but not by default. You need lookupPolicy: {local: true} [set](https://docs.openshift.com/container-platform/3.9/dev_guide/managing_images.html#using-is-with-k8s) and it only works within the same namespace.

As mentioned, that lookup policy local is already set to true in our imagestreams. Docs at https://docs.openshift.com/container-platform/4.10/openshift_images/using-imagestreams-with-kube-resources.html

when spawning and creating a new Notebook object.

As it it now, only the tag is evaluated correctly. There is no reason to split tag and name evaluation in a way that is dependent on dockerImageRepository / the internal openshift docker registry.

![Bildschirmfoto 2022-11-21 um 17 09 20](https://user-images.githubusercontent.com/21118431/203154164-f6e82716-1dad-40f4-bc33-8b65c789169e.png)

![Bildschirmfoto 2022-11-21 um 17 15 10](https://user-images.githubusercontent.com/21118431/203154198-87c2f670-caeb-442b-beeb-e9dbfe190c37.png)

Regarding possible future airgapped support: What is good that in that case, Imagepolicy's spec.tags[x].from.name can be done in digest format, making that approach for defining a notebook container image-value future-proof.

### Expected Behavior

The NotebookUtils in odh-dashboard should not assume the presence of an internal registry. There are many clients that do not use the internal registry. In fact, those clients sometimes even use ImageContentSourcePolicy and sha type digests instead of tags with a target repository in internal environments, but not within openshift.

I realize you are doing your odh-dashboard tests with imagestreams that use the internal registry of Openshift, that is,
spec.tags.referencePolicy.type: Local.

https://github.com/opendatahub-io/odh-manifests/commit/d3f189d7db9ca68a57bbef414fc90190a1ca88d2#diff-43a0688d7e25e4bdbb92d04c9fc8a3c1abd342323f0b347870feecfe826bd034

However, that cannot be assumed to always hold true. I propose using

`<imagestream name>:<(imagestream-tag>` as the basis for Notebook.spec.containers[x].image.

This would work because the imagestream is in the same namespace and because spec.lookupPolicy.local is set to true, both in the jupyter imagestreams as well as in the odh-manifests test imagestreams.

As @guimou put it:

That's a really good find. The internal repo is totally optional. And in many environments it's even a best practice to have your own properly managed repo...

### Open Data Hub Version

ODH 1.4.0 operator and manifests plus odh-core KfDef with Notebook Controller, Dashboard, and Jupyter overlay additional base images/imagestreams from
odh-manifests/jupyterhub/notebook-images/overlays/additional/

### Anything else

KfDef https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/odh-core.yaml#L50

_No response_

**Comment by lucferbux** [comment]
Hi, following up the conversation we had, I'm gonna just reply one of the questions here:

> Also, it is unclear to me what the difference between assembleNotebook in backend notebookUtils and frontend api is:
> [odh-dashboard/frontend/src/api/network/notebooks.ts](https://github.com/opendatahub-io/odh-dashboard/blob/729cb6200d7d1ba7d6756288fd9bb4d54970c806/frontend/src/api/network/notebooks.ts#L91)
> Line 91 in [729cb62](https://github.com/opendatahub-io/odh-dashboard/commit/729cb6200d7d1ba7d6756288fd9bb4d54970c806)
>  const imageUrl = `${image.imageStream?.status?.dockerImageRepository}:${image.imageVersion?.name}`; 
> Looks very much similar ...

Yes, indeed, we need to change that in both places, these are targeted to two different features. In the backend we are enabling Jupyter notebooks (spawning notebooks in a shared namespace) and in the frontend we have the logic to enable DSG (Create projects in which you can deploy notebooks, pvcs, data connections and model serving).

**Comment by shalberd** [comment]
@harshad16 @jiridanek @jstourac @atheo89 @lucferbux 

closed in favor odh odh notebook controller doing the notebook image field lookup in all cases (no openshift internal registry, openshift internal registry): https://github.com/opendatahub-io/kubeflow/pull/336 and https://github.com/opendatahub-io/kubeflow/pull/329

as well as dashboard changes https://github.com/opendatahub-io/odh-dashboard/pull/2867/

Thank you all very much, neat work

minor remaining: changing notebook container imagePullPolicy: IfNotPresent from old imagePullPolicy: Always 

as a nice-to-have feature for external registry and large images with a unique hash. Needs to be validated if that works with internal openshift registry, too. Saves times on workbench startup.
