### ISSUE TITLE
[Feature Request]: Check cluster resource limits/quotas to predict if notebook sizes will actually spawn

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#794]
### Feature description

Currently users will get no notification if any of the provided notebook size options can spawn in the current cluster unless they attempt a spawn and it fails due to scheduling.   Since we already query the cluster for worker nodes to detect GPUs, we should query available 1) worker nodes resource limit and 2) notebook namespace [resourceQuotas](https://docs.openshift.com/container-platform/4.10/applications/quotas/quotas-setting-per-project.html) to predict if the given notebookSize is viable from a scheduling perspective

Examples:

- If the largest worker node only has 8CPUs then we should add a note to the SpawnerUI to show that the Large notebook size (limit of 14cpu) is not schedulable
- If the target namespace for the user notebooks has a resourceQuota of 4GB of memory then the Small, Medium and Large notebooks are not schedulable

There should be a toggle in the ODHDashboardConfig to disable this check in the event that the cluster admin allows for autoscaling of large resource nodes and wants to disable this restriction

### Describe alternatives you've considered

This is a quality of life feature for users since the notebook sizes are completely controlled by the Dashboard admin.  They would have the responsiblity to modify the global settings when ODH is installed

### Anything else?

JupyterHub SingleUserProfiles PR https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/pull/187 that added this feature to the JH Spawner UI

**Comment by dgutride** [comment]
Moving to closed - it has been marked stale for the last 2 months with no further updates.  We will handle this if it is comes up from a customer ask in the future.
