### ISSUE TITLE
[Bug]: Incorrect ConsoleLinkKind type

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have an incorrect type for ConsoleLink. And thus when someone uses a ConsoleLink in a non-standard fashion for our use-cases, but a legit fashion for the kind itself, we will get a NPE.

![image](https://user-images.githubusercontent.com/8126518/203349764-fb977ecd-24b5-42e7-b02f-f8bda6195d90.png)

### Expected Behavior

<img width="638" alt="Screen Shot 2022-11-22 at 10 09 11 AM" src="https://user-images.githubusercontent.com/8126518/203349882-0ac4b657-b238-476d-9495-1705efa92b0d.png">

We need to set our `ConsoleLinkKind` types (both frontend and backend) to have an optional `applicationMenu` and adjust use-cases accordingly.

### Steps To Reproduce

Best guess to setting this up would be just create a ConsoleLink without the property set and load up the Dashboard.

### Open Data Hub Version

```yml
2.5.0
```

**Comment by hvpareja** [comment]
To add some info:

The **workaround** could be to update the links to always have the `applicationMenu` property

**Comment by andrewballantyne** [comment]
FWIW, I believe the `applicationMenu` being added to your ConsoleLink will lead you to probably having the link appear in additional places than what you may already want. Depends on your use-cases. Dashboard had a specific one and failed to have proper types to back that up.

**Comment by shalberd** [comment]
see https://github.com/opendatahub-io/odh-manifests/issues/705#issuecomment-1324630908 for context

**Comment by FlorianLiebhart** [comment]
Hello!
I just wanted to let you know that this issue has happened for me as well. 
As a workaround, I could add 
```
  applicationMenu:
    section: Documentation
```
to the definition of the ConsoleLink.
However, this is a bug and should be solved. :-)

Best, thanks,
Florian

**Comment by andrewballantyne** [comment]
Thanks for reporting your issue as well, this should be low hanging fruit that we can address.

**Comment by manosnoam** [comment]
Here's a ConsoleLink instance in RHODS 1.31 RC4:

![image](https://github.com/opendatahub-io/odh-dashboard/assets/9913945/dcbf587d-d196-49f7-9f9f-3a37adff4ab0)
