### ISSUE TITLE
[Model Serving]: UI Enhancements 

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#802]
### List of tasks

- [x] Inferenceservice loading status icon should be spinner rather than an hourglass.

<img width="1010" alt="Screenshot 2022-11-24 at 12 05 48" src="https://user-images.githubusercontent.com/16117276/203769687-4cb19d4f-d78a-4aee-9440-a39f093ffa71.png">

- [x] Display a tooltip message when the model fails.

<img width="1216" alt="Screenshot 2022-11-23 at 16 28 37" src="https://user-images.githubusercontent.com/16117276/203769714-71b9bdc2-4b98-468e-909f-6bff2918e7f9.png">

- [x] Adding headers to tokens row
- [x] Token sometimes retrieve "Unknown" if secret not properly fetched

<img width="1342" alt="Screenshot 2022-11-23 at 16 28 24" src="https://user-images.githubusercontent.com/16117276/203769935-bab42e27-9351-499d-87da-78a6820b1885.png">

- [x] In the "Deploy model" modal, change "Configure" button text to "Deploy" 

<img width="564" alt="Screenshot 2022-11-23 at 16 35 32" src="https://user-images.githubusercontent.com/16117276/203770185-0f5f8481-1e0a-4cd9-b882-e1405eb73070.png">

- [x] Calculate witdh based on the ? icon -> EDIT, not doing it.

<img width="782" alt="Screenshot 2022-11-23 at 16 53 10" src="https://user-images.githubusercontent.com/16117276/203770383-cfe1b245-57cf-4b3c-adf1-7ed99915ea1e.png">

- [x] Route itself doen’t refresh with changes automatically

<img width="1314" alt="Screenshot 2022-11-23 at 17 01 29" src="https://user-images.githubusercontent.com/16117276/203770424-d04d1734-5fde-4ad7-8687-b125e5ea799a.png">

- [x] HIde the link from the Model names until metrics are enabled

<img width="295" alt="Screenshot 2022-11-24 at 12 13 13" src="https://user-images.githubusercontent.com/16117276/203770558-1130b70a-88a4-4e50-9bf6-fd12e79e8378.png">

- [x] When inference service is disabled, just change the text to "Internal Service" rather than displaying a route

<img width="1151" alt="Screenshot 2022-11-24 at 12 07 41" src="https://user-images.githubusercontent.com/16117276/203770625-2ac6218d-1aef-4512-8f43-22f39e2b0027.png">

- [X] Add validation for number inputs
- [X] Change label of "Token Secret" in Model Server modal

**Comment by andrewballantyne** [comment]
>  Inferenceservice loading status icon should be spinner rather than an hourglass.

PF spinner component on small probably is enough (check the size of the icon to the spinner -- we shouldn't decrease the height of the row when it flips)

> Display a tooltip message when the model fails.

I'd like to see a tooltip for each one. Checkmark should say "deployed" or whatever. No need to make users guess at state of things. But definitely this is needed for the error flow to show the error that it is informing us about.

> Calculate witdh based on the ? icon

If you absolutely need to make them align no matter what... don't calculate, set the layout. Your options are two fold:

1. Use something like `Split` from PF, it's a block element and will manage truncating cells things if it runs out of space (might want to use the `Truncate` component on the name in that case)
2. Use `white-space: nowrap` CSS ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)) on the cell that has everything in it. If this is in a table cell, the table will adjust the column to fit the whole content (if it can). Best check with stupid long names (edit the HTML or debug code it)
