### ISSUE TITLE
[Feature Request]: Optional role to spawn pods from notebooks, used with Spark workloads

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#824]
### Feature description

The ServiceAccount used to run the notebooks does not have right to spawn Pods. This feature would be useful to directly launch Spark workloads from a notebook, which some teams are used to do in their current environments.

Details:
- Spark supports kubernetes to directly launch workloads. You can target your spark-submit command to a kubernetes cluster, which will schedule executor pods, do the computation, and remove the pods when finished. The Spark instance running in the notebook acts as the driver for the workload.
- This functionality requires rights to create/delete Pods and Services. However, the ServiceAccount under which the Notebook container is running does not have those rights.
- The requested feature would add another Role to the notebook ServiceAccount, enabling those capabilities.
- The drawback is that any notebook user would be able to create Pods in the namespace by invoking the kubernetes API, so this must be an admin-selectable feature.

Proposed implementation:
- Create a Role with needed capabilities. This can be used as a base as it's exactly what the Spark operator is doing: https://github.com/opendatahub-io-contrib/spark-on-openshift/blob/main/spark-operator/spark-rbac.yaml
- Create a toggle in admin to enable this role or not. As the drawback of the method is that people would be able to schedule Pods, admins must be able to allow this or not. The toggle would create/delete the associated RoleBinding. For DSP, this could be a per-project toggle.

### Anything else?

This would bring back some of the features we previously had in ODH with Spark notebooks, that customers are now lacking. Instead of spawning a pseudo-permanent Spark attached to a notebook, this would be more dynamic, with the Spark cluster being spawned when the command is submitted.

**Comment by lucferbux** [comment]
Hi @guimou is the *service account* you are mentioning `notebook-controller-service-account`?
If so, this would be an issue for either the kubeflow or odh-manifest repository, we don't control how the logic behind the notebook controller works and this repository should only hold issues related to the dashboard logic.

I would defer to @andrewballantyne either we keep this ticket or not.

**Comment by andrewballantyne** [comment]
I agree to some extent with @lucferbux -- The power of the Notebook Controller and any service account it has is not really within' the purview of our set of configurations. The closest we get to the Notebook Controller is by creating their custom `Notebook` CRs... which have a lifecycle we "sorta" know but don't interrupt or influence in anyway directly.

@VaishnaviHire / @LaVLaS I think this is still ODH related, but not Dashboard per se. Shall we move this issue over to another repo? If so, is that just odh-manifests or is there a better one? I suppose this could be a core kubeflow thing -- but I think this is a desire from our deployments and the permissions we grant to the service account that controls the pod logic. Open to suggestions where to move this to -- just don't think it's Dashboard.

**Comment by LaVLaS** [comment]
I don't think our default functionality should allow any ODH user the ability to create a Pod in the notebook namespace, i think this request is to allow the notebook ServiceAccount the ability to create pods in the same way that we create the `jupyter-nb-<USERNAME>-notebook-view` rolebinding in [notebookUtils](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/notebookUtils.ts#L96)

**Comment by andrewballantyne** [comment]
Discussed a bit with Landon and Vaishnavi on slack -- it's still my opinion this is outside the responsibilit of the Dashboard, but they have informed me the alternative is not great. Putting this on the backlog for now.

**Comment by guimou** [comment]
You can simply close this issue to clean up the list if you prefer. People have the recipe on how to do that by themselves should they wish to do so, it will do for the moment.

**Comment by andrewballantyne** [comment]
Sounds good, thanks @guimou
