### ISSUE TITLE
[Model Serving]: Add navigation for metric page 

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#829]
### Feature description

Enable navigation for model serving metrics ([Mocks Server](https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/agOKG1D) [Mock Inference](https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/AxlyJ2R)):
* Display metrics in DSG project
* Display metrics in Global Model Serving view
* Model links to navigate to the metric page for the inference/model

**Comment by andrewballantyne** [comment]
@DaoDaoNoCode / @lucferbux can you two sync and make sure this isn't covered by the work in existing PRs?
