### ISSUE TITLE
[Feature Request]: Remove `opendatahub.io/link` cases

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#844]
### Feature description

In the KFNBC flows we need to reply completely on the route object and no longer on the annotation we add.

**Comment by DaoDaoNoCode** [comment]
Should we also remove `opendatahub.io/link` for the workbenches in the DS projects?

**Comment by DaoDaoNoCode** [comment]
Sorry, checked the code and found the workbenches are not relying on that annotation. Please omit the comment above.
