### ISSUE TITLE
[Feature Request]: Warn users of pod restart when editing workbench

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-dashboard#847]
### Feature description

When editing a workbench most changes require the pod to be restarted if it is currently running.  Before saving the changes a warning should appear stating that the pod will need to be restarted and users should save any notebook data before proceeding.

Restarting the pod without warning could result in loss of user data that has not been saved or pushed to git.

### Describe alternatives you've considered

Instead of automatically restarting the pod or giving a warning, you could add an extra step after the changes have been saved.   A message could be displayed on the workbench item indicating that the changes will be applied once the pod has been restarted with a button to "Restart Now".

**Comment by andrewballantyne** [comment]
We're going to need to work with UX to make sure we cover these scenarios in a way that is consistent. 

cc @kywalker-rh we should talk to make sure we make a sane one-effort solution to this problem from all the angles that a user can cause this to happen.

The restart is done by the notebook-controller (and outside of our control as far as I know -- I'll investigate to see if there is an annotation or something we can use to avoid auto restarts), so we need to prompt them before making changes that what we are about to do will potentially cause a loss of data.

**Comment by andrewballantyne** [comment]
Talked with Kyle, we will go with a Blue (info) Alert at the bottom of modals/pages as needed to any operation that will restart the Workbench.
