### ISSUE TITLE
[Bug]: Harmonize workbenches naming across UI

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Depending on where you are in the UI, Workbenches are sometimes named Notebooks.
As we will soon introduce other types or images, like RStudio or VSCode, the "notebook" denomination won't be accurate anymore. As we settled to name those "environments" workbenches, it should be done consistently accross the UI.

### Expected Behavior

Workbench should be the only name used for any interactive environment launched through the UI.

**Comment by andrewballantyne** [comment]
cc @kywalker-rh @jedemo 

This would rename the Jupyter Tile and the link to it from DS Projects (project list page). Thoughts? I know we explicitly went this way for first release of DS Projects, but we'll need to migrate over at some point.

**Comment by kywalker-rh** [comment]
@jedemo I agree, I've added it to the agenda

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1099
