### ISSUE TITLE
[Bug]: Model serving image must be in sha format for disconnected installation

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For disconnected installation, all the images to pull must be addressed in sha index format, having a tagged image will result in a deployment failure.

### Expected Behavior

Having the image for model serving with an sha image.

**Comment by shalberd** [comment]
Extremely valuable change and a great step toward making ODH airgapped-compatible
