### ISSUE TITLE
[Bug]: Respect `annotations` as optional for ImageStreams

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you create an image stream without any annotations, our backend code does not handle this. 

Code in question: https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/routes/api/images/imageUtils.ts#L95

### Expected Behavior

Should be able to handle an image stream without annotations and take reasonable defaults that we already have in place.

### Steps To Reproduce

1. Have image stream without any annotations
2. View the Jupyter tile spawner page ~(should also cause problems on the DS Projects workbench creation page)~

### Workaround (if any)

Add any annotation to get past the issue. Eg. `opendatahub.io/test: 'test'`

### Open Data Hub Version

```yml
2.5.2
```

**Comment by DaoDaoNoCode** [comment]
This will break the notebook controller spawner page but will not break the DSG workbench creation page because they are using different ways to process the image streams (backend API vs pass-through API)

**Comment by andrewballantyne** [comment]
Good to note Juntao, thanks!
