### ISSUE TITLE
Improve User Interaction Tracking (DS Projects / Model Serving / etc)

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#866]
Right now we are covering user interaction tracking with segment.io for several flows, but we lack support for DS Projects and Model Serving. We might wanna expand the user interaction tracking to those sections.

# Requirements

Waiting to hear exactly what PM would like.

> Initial thoughts
> 
> * Would like to track # of projects created in a cluster
> * Would like to track # of model servers created and # of models deployed in a cluster

This is beyond the UI today -- we'll need to consider more "user interaction" based tracking for this to be viable effort on our end.

**Comment by andrewballantyne** [comment]
@jedemo @kywalker-rh We should talk about what coverage you guys want and align in 1.22. We have some in 1.21 of RHODS and we should look to see what we can do to trigger it more uniformly on all the needed spots.

**Comment by andrewballantyne** [comment]
Related effort was done in #807

**Comment by jedemo** [comment]
Added Jira for this: https://issues.redhat.com/browse/RHODS-6280

**Comment by dgutride** [comment]
Will be covered by PM feature board when necessary.
