### ISSUE TITLE
[Bug]: Incomplete address for internal model serving endpoint

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the model-server is configured to be presented through an external Route, you get all the info to connect to it:
![image](https://user-images.githubusercontent.com/3944034/210831538-f01c990b-38fb-47fb-bbf2-bcb71d1eccd9.png)

When you create a model-server that is only available internally to the cluster, the popup giving the address of the endpoint is missing the full information. The `/v2/models/model_name/infer` is not there, making the URL unusable unless you know the format KServer is using.
![image](https://user-images.githubusercontent.com/3944034/210831285-cbf13add-4505-4973-bec8-69371e6ed3d7.png)

Also, url is redundant with grpcUrl, it's the same. We should only keep Rest URL and gRPC URL.

### Expected Behavior

Internal address information should give the same full information on how to reach the model API internally.
Optionally, offering the same copy/paste functionality as for the external config would be good.
Optionally, a gRPC Route when creating an external access would be useful, as it's a preferred endpoint type for model APIs.

### Workaround (if any)

Read the KServe doc and figure out what the API endpoint path is...

**Comment by lucferbux** [comment]
We might wanna talk with @anishasthana @DharmitD or @HumairAK. We are currently pulling this from the `InferenceService` spec, inside `status?.components?.predictor`.
We don't build the external route, we get that from the controller, not sure if the controller should update that spec to have the hole route, what do you think?

**Comment by lucferbux** [comment]
I've created [this bug](https://github.com/opendatahub-io/modelmesh-serving/issues/56) in the model serving component just to further discuss how to approach this issue.

**Comment by dpanshug** [comment]
@lucferbux, is the solution coming from the `modelmesh-serving` end, and can we close this issue from here?

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-1102
