### ISSUE TITLE
[Bug]: Editing Workbench Does Not Respect Zero GPUs

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we are in edit mode of an existing workbench within a DS Project -- setting zero GPUs is actually considered not doing anything with GPUs... whereas if the workbench ever had GPUs enabled, it would then never be able to remove the GPU setting from the value it was last set to zero.

### Expected Behavior

We should look to clear the GPU setting when GPUs are set to zero if they are already on a workbench.

### Steps To Reproduce

1. Have a Workbench with a configured GPU setting
2. Edit the Workbench in the DS Project UI
3. Set the GPU value to 0
4. Save the Workbench with no other changes

-- we should have zero configured at this point on this workbench --

### Open Data Hub Version

```yml
2.5.2
```

### Anything else

For development clusters without GPUs, you could possibly use the `gpuSetting` value in the DashboardConfig to fake GPUs -- your pod likely won't start, but it should be an effective test (which we will need to verify on cluster at some point).

**Comment by bdattoma** [comment]
where gpuSetting must be set? I tried setting it in odh-dashboard-config under spec.dashboardConfig or under spec but it gets automatically deleted (operator was scaled down to 0 before doing that).

Plus, would the syntax be: gpuSetting: <number_of_gpus>?
