### ISSUE TITLE
[Feature Request]: Drop the `base_url` env var from the Notebook

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#891]
### Feature description

The net of this problem is:
> Fails to launch notebook from OCP route instead of Dashboard UI

OpenShift Console's Route object for a Notebook is confusing as it does not work but it works in the Dashboard fine. The Notebook is configured with a `base_url`, a holdover from the JH days. We need to try and see if we can remove it so the link can work in both cases without any issue.

There will be a few spots this needs to be updated including the route link itself as well as any pulling of the Route object. We should do this for both Jupyter tile and the DS Projects view.

### Anything else?

This needs to be properly tested, there is an assumption this will work, but it's not 100% known.

**Comment by andrewballantyne** [comment]
If we do this -- it looks like it might impact the culler. It assumes `notebook` in the path. https://github.com/opendatahub-io/kubeflow/blob/9cb4b57cc1473131a9da3c73c56e00c7b1b5798e/components/notebook-controller/pkg/culler/culler.go#L154

Pausing this effort until we know more.

**Comment by andrewballantyne** [comment]
cc @harshad16

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2746
