### ISSUE TITLE
[Bug]: Model server modal error handling with dynamic spec

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now, when entering a misconfiguration in the `servingruntime` spec for a Model Server creation, will only log an error in the console and fallback to the default configuration.

### Expected Behavior

The dashboard should have a proper error handling, considering all the outcomes of the configuration.

### Steps To Reproduce

1. Modify the `servingruntimes-config` configmap with wrong configuration
2. Create a new model server
3. Check that the modal will submit the action and a error is logged.

**Comment by andrewballantyne** [comment]
This should be done for our next release. This is not a state it should stay in. The solution is probably just handle errors in the modal and not fall back on the default. They chose something different, we shouldn't force them into the default -- to which they have to delete and recreate to test again -- it's not a good flow.
