### ISSUE TITLE
S3 Browser

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#9]
Manipulating object storage data from a notebook is not intuitive and requires code for basic operations (upload, copy, delete,...). Several solutions can be implemented at Jupyter level:
- https://github.com/IBM/jupyterlab-s3-browser
- https://github.com/danielfrg/s3contents

An S3 browser could also be implemented at the ODH UI level.

That's open for discussion (other solutions, pros, cons, comments,...)

**Comment by guimou** [comment]
@LaVLaS Hue is a solution, but tbh I'm not sure that from a UX perspective it's really practical. That would mean they would have to connect to Hue (so first an account must have been created for them), configure their S3 access with their own credentials, and then do their stuff. If they don't use Hue at all apart from that, it's kind of cumbersome imho. That's why an integrated solutions (whether in Jupyter or in the dashboard, where there are already authenticated, meaning we can retrieve keys from their profiles) would enhance it somewhat.
To your second question, yes, I have already implemented both solutions (I even demonstrated the S3content one in the presentation we did for OpenShift Commons of ODH on OCS). Changes are to be made on the notebook container though (not in the jupyterhub_config.py), so that's another special image.

**Comment by andrewballantyne** [comment]
We did discuss a little bit about having a browser for the S3 storage during the Data Science Projects feature. It was not placed as a high priority among the other items we needed to do.

cc @kywalker-rh is there any plan to return to that topic?

**Comment by guimou** [comment]
I just published an Rclone custom workbench that brings some S3 browsing capabilities among other features: https://ai-on-openshift.io/tools-and-applications/rclone/rclone/
This could do for the moment.

**Comment by andrewballantyne** [comment]
@guimou sounds like we can close this until it shows back up on the radar for a more direct dashboard feature?

**Comment by lucferbux** [comment]
Closing this cause we haven't had motion in it over a year, please log in https://issues.redhat.com/projects/RHOAIENG/summary if this is still desired.
