### ISSUE TITLE
[Feature Request]: Add developer testsuite to verify dashboard updates are working as intended

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#900]
### Feature description

To verify that updates to the dashboard code and each release is working as intended, we should add a test framework that can be run against each PR to verify that the change works as intended and does not break existing functionality.  Ideally, each developer would contribute a new unit and/or functional test that could verify basic functionality of every feature.

### Describe alternatives you've considered

Currently, we are reliant on https://github.com/red-hat-data-services/ods-ci for automated integration testing in  but this framework is focused on downstream product and is focused purely on end-user testing

### Anything else?

[cypress](https://cypress.io) has been mentioned as a test framework for NodeJS projects

**Comment by lucferbux** [comment]
I think this is a really great place to start a discussion about the current testing state of the application. We previously had [this issue](https://github.com/opendatahub-io/odh-dashboard/issues/225) in which we worked in the scaffolding of the testing framework.

There are a few open threads for testing here:

## e2e testing
As you mentioned, a framework like **cypress** might be the best option for an e2e test in which we can add some general testsuit for a user mocked flow. The main challenge would be **create an environment with the odh operator installed for this prs**

## Integration testing

**Backend**
We are currently trying to deprecate the backend, there's even an effort to remove the default notebook spawning in favor of workbenches. This will reduce **even more** the functionality of the backend.
Despite that, there are still a few key features that rely on the backend, we can consider adding integration testing with **tap** as the [official documentation](https://www.fastify.io/docs/latest/Guides/Testing/) suggest here.

**Frontend**
We currently have react testing library to test the integration of components, was implemented in #141 and we need to start using this in most of our main components.

## Unit testing

For both **backend** and **frontend** I would use **Jest**, it's a great tool to add unit testing for specific functions.

---

The main challenge we have with both **unit testing** and **integration testing** is that we rely so much in openshift calls, so to feed the data to test most of our codebase we need either a lot of mock data or something to mimic openshift calls.

We might wanna further expand this ticket and have a discussion for this year to come.

**Comment by lucferbux** [comment]
What do you think about this? @andrewballantyne @DaoDaoNoCode @LaVLaS

**Comment by andrewballantyne** [comment]
I'd like to see us take the core of RHODS testing upstream. They have been coding a lot of tests for functionality and I'd really appreciate that effort showing up on ODH to help us catch things early.

You're definitely right on the mark, @lucferbux, with the needing of a proper hosted infra for testing with the ODH Operator and that's not something we have today. We are supposed to be getting more build resources, and I think we might be able to use some of that to leverage more CI/CD support upstream too.

We also need accessibility support on a CI/CD basis -- so that'll need to be added into the framework we setup. The AXE tool I think needs a UI to be running as well, so it plugs into cypress or some other framework as I understand it.

**Comment by andrewballantyne** [comment]
This is being addressed by our current plan. See our [architectural documentation](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/architecture.md#testing-structure) for more info.
