### ISSUE TITLE
[Feature Request]: Allow overriding default custom runtime

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#904]
### Feature description

As a short term measure until we fully support multiple customized serving runtimes, we would like the ability to change the default servingruntime in some scenarios.  In this case a user could default to any number of open source runtimes.  If the default is currently begin used/overwritten, adding and using an override field in the servingruntimes-config configmap should allow us to do this with low risk.

### Describe alternatives you've considered

Fully implementing supporting multiple serving runtimes.

**Comment by lucferbux** [comment]
I think is a good idea to have a `default-config` and an `override-config`, this way users can have both the default configuration with an image that's being updated every version and then their own version. Current setup will force the user to either select one or another.

**Comment by andrewballantyne** [comment]
Needed for future exploration with other aspects of model serving -- upping priority and adding it to the release.
