### ISSUE TITLE
[Feature Request]: Update Node.js version to 18

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/odh-dashboard#915]
### Feature description

Looks like Node.js 14 is losing maintenance in April, so updating is becoming a concern.  
https://github.com/nodejs/release#release-schedule

There are UBI 8/9 base images for Node.js 18 available.
https://catalog.redhat.com/software/containers/search?product_listings_names=Node.js&p=1&q=nodejs-18

**Comment by andrewballantyne** [comment]
Good catch Chris -- we should look into updating.

**Comment by andrewballantyne** [comment]
This will need to get iterations on it before we can merge it -- won't make this release, should be able to take Lucas' work and merge it at the start of the next sprint (March 13th)
