### ISSUE TITLE
[Feature Request]: Improve the Quality of PVC Expanding

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#933]
### Feature description

There are K8s Events triggered on the PVC when there are issues upgrading -- we do not show them in the UI as they are not part of the K8s request.

An example:

> VolumeModificationRateExceeded: You've reached the maximum modification 
rate per volume limit. Wait at least 6 hours between modifications per 
EBS volume

Seems we do not support it well when the PVCs have issues upgrading, limits to upgrading, or how long it takes.

We should look to find ways to report the status of the PVC in various states. Reading events and populating them on the project details page might be a performance concern.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2756

**Comment by shalberd** [comment]
@dgutride @andrewballantyne not only what is already written in the jira ticket, but also:

depending on the storageClass, a volume might not even be expandable.

So before the GUI checks or even enables volume or PVC expansion at cluster storage ... it should check for allowVolumeExpansion (incubation, upstream ODH): https://github.com/opendatahub-io/odh-dashboard/issues/2011#issuecomment-1779583221

You could and would need to look up by name the current PVC storageClass details by metadata.name of StorageClassKind.
