### ISSUE TITLE
[Bug]: Continued Progress on Stop/Start Spawner Success

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Continuation of #899

Under certain circumstances it seems there can still be a warning message from k8s events that cause the container not to come up properly.

Here are the thoughts from our Quality team:

> I have verified that when stopping/starting the server after the "oauth proxy container started" message appears, the second spawn attempt does not get stuck anymore. In most cases it will progress smoothly until the server is ready, while sometimes it will flash the "Killing" warning message briefly in the modal. On one occasion I've been able to make the "Killing" message stick around for a few seconds, but I haven't found a reproducer and it resolved itself in ~5 seconds anyway.
>
> However, I have noticed that now, if clicking on "Cancel" when the modal shows either "Pod assigned" or "PVC attached" the process will become stuck for about 1-2 minutes; the pod is shown in Terminating status, but no logs or events are added during this period. At the ~2 minute mark a new event will be shown (attaching screenshot), which will also be replicated in the spawner page as a Warning message.
After this event appears, the pod appears to be restarted or anyhow refreshed, and in my testing the spawn progress will resume and complete.
>
> In my opinion this is a bad experience for the user, since stopping/starting the server during this ~2 minute window will always lead to the same stalled progress bar (related to the same pod in the backend) but without any indication that the user is supposed to wait a bit longer for the process to continue.
Ideally, as is the case for the oauth proxy container, stopping and restarting the server should also restart the pod and sidestep the ~2 minute timeout window in which any progress is stalled, as the end result would be the same (requested server gets served) but the experience would be more in line with user expectation.

It should be noted this seems to be more of a problem for RHODS setups than ODH -- I have not been able to reproduce this in an ODH instance.

### Expected Behavior

It's hard to say if we can intelligently figure out when this is happening -- but if we can test it under RHODS setups or perhaps find a way to produce this in ODH.

A possible solution may be to just prevent starting up of the server for some arbitrary amount of time to prevent collisions with other k8s resources in flight.

### Steps To Reproduce

See the description for the scenario details.

Launch Jupyter and stop/start the Notebook.

### Workaround (if any)

Wait 2-5mins for K8s to release all the data before trying to spawn another notebook.

### Open Data Hub Version

```yml
Dashboard 2.6.0
```

**Comment by adnankhan666** [comment]
Not migrating ~ labelled "stale"

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2742
