### ISSUE TITLE
[Feature Request]: support for accelerators via OdhDashboardConfig

### ISSUE THREAD

**Issue by dtrawins** [opendatahub-io/odh-dashboard#956]
### Feature description

In RHODS dashboard the notebook profiles can be defined in `OdhDashboardConfig` resource. The gap is however it is not possible to assign cluster resources via the device plugin. Only CPU and Memory resources can be defined in the profile.

Accelerators requirements can not be specified as they are not included in the CRD spec. https://github.com/opendatahub-io/odh-dashboard/blob/c652c186b5674666f3132613f9090fdf6bba7e32/manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml#L68

The notebook controller does support extra resources like AI accelerators so a workaround it to manually update the notebooks.kubeflow.org resource after it is created by the dashboard.

The request is to extent the `OdhDashboardConfig` CRD and allow passing the accelerator spec to the notebook resource while spawning the notebook container 

### Describe alternatives you've considered

Containers can be spawned via the notebook resource but that requires administrative access to the cluster and can not be done from RHODS dashboard.

### Anything else?

An example use case is with Intel ARC GPU card

**Comment by andrewballantyne** [comment]
Hi @dtrawins, thanks for the issue! Glad to hear you'd like additional functionality. 

We don't store our GPU values in with the resources as part of the DashboardConfig CR, as the goal was for us to have more flexibility connecting GPUs with resource requests/limits. However, we currently only have support for the `nvidia.com/gpu` property and that's done via another field on the form.

Is your request for any accelerator or specifically the `Intel ARC GPU`?

**Comment by ryanloney** [comment]
The exact name is Intel Data Center GPU Flex. https://www.intel.com/content/www/us/en/products/docs/discrete-gpus/data-center-gpu/flex-series/overview.html

Intel Arc is a similar product, but for laptops and desktops. Not as likely for Arc to appear in OpenShift clusters.

**Comment by uMartinXu** [comment]
With the new RHODS Dashboard Accelerator Profile, this issue can be fixed. see https://github.com/intel/intel-technology-enabling-for-openshift/tree/main/e2e/inference#work-with-interactive-mode

**Comment by dgutride** [comment]
Based on comment above - moving to resolved.  Thank you!
