### ISSUE TITLE
[Bug]: Show Less / 2 More Issues on ODHDocCards in the Resource Section

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is only one label -- it's got a hardcoded 3 items in it.

![Screenshot 2023-02-23 at 11 44 52 AM](https://user-images.githubusercontent.com/8126518/220973484-36722df9-cf8c-4a7f-84da-05cbbc1152b2.png)
![Screenshot 2023-02-23 at 11 44 58 AM](https://user-images.githubusercontent.com/8126518/220973488-13224261-b607-4d79-85da-6cdc66aca73e.png)

### Expected Behavior

For it to perform normally based on the number of items.

### Steps To Reproduce

1. Install the ODH Dashboard & the accompanying resources from ODH Manifests & ODH Dashboard manifests folder
2. Navigate to the Resources section and view card mode
3. Find the Jupyter docs one (should be generated from the OdhApp and not be an actual OdhDocument object)

### Open Data Hub Version

```yml
Dashboard: v2.6.0
```

**Comment by DaoDaoNoCode** [comment]
This is an issue I noticed and submitted a fix in PF https://github.com/patternfly/patternfly-react/pull/8505. It's already merged and bumping the PF version could simply fix this issue I think.

**Comment by andrewballantyne** [comment]
> This is an issue I noticed and submitted a fix in PF [patternfly/patternfly-react#8505](https://github.com/patternfly/patternfly-react/pull/8505). It's already merged and bumping the PF version could simply fix this issue I think.

@DaoDaoNoCode can you verify this is fixed in your PF bump PR?
