### ISSUE TITLE
Revisit UI for OOTB images n & n-1 support

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#990]
### Feature description

The intent is to give users the ability to select the latest, n,  and the previous version, n-1, for each OOTB image for notebooks.

<img width="1460" alt="Screenshot 2023-03-03 at 13 39 20" src="https://user-images.githubusercontent.com/16117276/222722524-17308a1c-0d4f-464c-bc24-4b73c7b7874f.png">
<img width="1469" alt="Screenshot 2023-03-03 at 13 39 15" src="https://user-images.githubusercontent.com/16117276/222722549-2a727a90-186e-4c10-af7d-2f53bdfc9cf1.png">

**Comment by andrewballantyne** [comment]
`opendatahub.io/workbench-image-recommended: 'true'` annotation will appear on the tags of a given ImageStream. This should render a simple UI element to denote it is "Recommended" (as noted in the issue's screenshots). Also, we should sort it to the top as well.

**Comment by andrewballantyne** [comment]
Will be bumped to next release to sync up more with the image effort.
