### ISSUE TITLE
[Feature Request]: Provide more feedback on notebook starting status

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-dashboard#997]
### Feature description

When worker nodes are on Autoscaler and resources are not available immediately to start a notebook, it can take a long time for a new node to be provisioned and ready. This is especially true with a GPU-enabled node because NVidia drivers and special containers have to be deployed before the Pod requesting a GPU can be spawned. This can take up to 10mn, and meanwhile no info or feedback is given to the user, except error messages that "there are not enough resources".

This feature would add specific feedback when an Autoscaler action is going on, like "please wait, additional resources are being provisioned to launch your environment".
It will prevent people opening support tickets because after 5mn their environment has not started. Without feedback they can't know if it's normal or if there is a problem, leading them to stop/start again and again until it works because meanwhile the new node would have finished provisioning.

### Describe alternatives you've considered

- Pop up/note that would describe what "can" be going on if we cannot detect that autoscaling is in progress.
- Documentation somewhere describing the process (although I'm pretty sure no end-user will ever read it).

**Comment by andrewballantyne** [comment]
This probably needs to be talked about in the UX meeting Thursdays to see how it will be best utilized. I'll add it to the agenda for next week.

**Comment by andrewballantyne** [comment]
From the UX meeting -- @guimou will think on how we can improve this and look to see if he can gleam any more information we can use. We currently have a 30s wait before showing errors, but the events are not clean and deterministic. We might want to look at alternative changes to help avoid scary red messages when auto-scaling is happening behind the scenes.

@guimou happy to talk whenever, ping me on slack when you want to talk or respond here if you have some additional information.

**Comment by andrewballantyne** [comment]
cc @harshad16

**Comment by dgutride** [comment]
Moving to closed after discussion with @guimou .
